== Chapter I

I have believed it right to leave to you, my children,
the account of some occurrences I have passed through in life, for your improvement;
and such counsel and remarks,
as shall open on my mind in the clearness of gospel love and parental affection;
and also a short account of our forefathers from the first family;
for when I was in New England,
I became acquainted with one branch of the family that informed
me they had been in the practice of keeping the spread of the name;
and that their branch of fore-parents,
had preserved some remarkable occurrences that took place in the order of Providence,
in the family.
A woman, some in years, of bright abilities, who appeared sound in her memory,
said she could well remember all the children of the first family that stayed in America,
and that lived to be old; and she had heard all three of the brothers,
(when she was young), and the old man,
relate the account of the occurrences that took place.

I was born the 22nd of the 4th month, 1762, being the son of Elijah and Phebe Hoag,
and of the fifth generation from the first family, which came over from England,
and settled not far from Hampton, and bound out their son John,
an apprentice to a leather dresser and glove maker.
Shortly after this, there came an advertisement from England,
that there was a great estate fell to them, so they all returned but this boy,
whose master would not give him up; so John remained an apprentice under a hard master,
without a friend to interfere or plead his cause, until he was of age,
after which he married an only child whose maiden name was Emery,
and with her he had an estate that placed him in good circumstance.
It was remarked that he was a man of that calmness of mind and steadiness of deportment,
that it was a rare thing to see him discomposed by crossing occurrences.

He was a man of fine natural abilities,
and filled the place of side Judge in the County Court,
until the taking up people for witchcraft,
which he opposed with such steadiness and resolution, that he lost his seat,
and his influence with the people.
He and his wife being zealous Presbyterians,
were well agreed in the education of their children.
Their son, Joseph, while a young man, had it on his mind to go to a Friends`' meeting;
he did so; it proved a silent one; there he became convinced,
and soon joined the Society, became an acceptable minister, and lived to old age.
It was believed that he was faithful in his day, and died in good unity with his Friends.
His becoming a Friend, caused great uneasiness and alarm in the family,
so that they used all their endeavors by persuasion and argument to turn him from it,
but to no purpose,
although he was a man the smallest in capacity of the males in the family,
yet none of them could hold way with him in argument, in matters of religion.

This so roused his brother Jonathan, that he went to the Priest with the pitiful story,
that Joseph had become possessed with the Quaker spirit,
and so bewitched with it that they could not talk him out of it,
nor do anything with him.
He therefore wished the Priest to come and talk to him, and pray with him,
or else they should lose him.
This the Priest utterly declined to do, telling him it would do no good to talk to him,
for he would not be talked out of it;
the best way would be to laugh and jeer him out of it.
If that did not do, take him to frolics and make him dance;
if he did not get rid of it then, give him drams until he was merry,
and that would wear it off.
This counsel so displeased Jonathan, that he went home, out of patience with his Priest,
and concluded he would go to meeting with Joseph,
and see what he could find among the Quakers.

When he went, Lydia Norton was at the meeting;
she so thoroughly unravelled all the Presbyterian creeds,
that he became decidedly convinced.
This increased the agony in the family.
Then Benjamin, their youngest brother, a man of great wit and readiness of speech,
with much anxiety, exerted all his abilities for their preservation;
but finding himself unequal to the task,
and not being able to get his Priest to his assistance, gave it up with sorrow,
for awhile; but observing the steady conduct of his brothers,
concluded he would go and see what it was they got among the Quakers,
that made such an alteration in their conduct, (which he related afterwards);
and at the meeting he attended, a woman Friend came,
who was so enabled to overturn Benjamin`'s bulwarks,
that it finished the business with him.
He told his brothers that he came there to see what they were after,
and he had found out, and did not blame them, and never more followed the Priest,
but became a Friend.

This, to their religious parents,
was such a heavy stroke that their mourning seemed to be without consolation,
believing that unavoidable destruction was the certain doom of all their sons--so
that for a while it seemed as if it would take their natural lives;
but after a while they seemed to comfort themselves, having done their duty,
and God would be glorified in them that were lost, as well as in them that were saved;
so gave it up,
endeavoring to keep their three daughters as much from exposure as they could,
and from talking with their brothers on religious subjects.
But they being young people together, it was out of their power.
At length there came a Friend from England, and Mary, their favorite daughter,
went to the meeting, and the testimony of the Friend so thoroughly convinced her,
that in a short time she became a member, and soon came forward in the ministry,
and in a few years became an able minister.

Shortly after, one of the younger sisters was convinced and became a member;
the other gradually broke off from the Presbyterians,
and though she never became a member, the greater,
and all the latter part of her days she attended Friends`' meetings.
Their parents continued a number of years in their way;
at length the priest got to pitying them; stating,
what a hard fortune it was to lose all their children, body and soul,
after raising so likely a family, to which the aged father replied,
"`I do not know about my children being lost; I brought them up as well as I knew how,
and I thought they behaved well, while they kept to their education.
I have observed them a number of years, since they have turned Quakers,
and I think their conduct is much more like the pattern of mankind,
than it ever was before.`"
To which the priest exclaimed, "`I see you are gone;`" got up, left him,
and never visited him afterwards.
After this, the father became a member, and died in the principles of Friends.

This so affected his wife, that she seemed afflicted to his dying day.
She often said she could not give up, as he had been so upright a man,
but that he would come out of that Quaker spirit, and die a good man at last.
A short time before his death, he told her,
that in a few weeks he should die and go to rest;
that he had obtained an assurance of happiness; to which she exclaimed;
"`oh! my dear husband, will you die in that delusion,
and go to destruction;`" and wept very bitterly.
A little before he died, he told his wife he was not deceived, and she would have a sign;
that when he died the cords of one of his thighs should be shrunk, as Jacob`'s was,
and that should be a proof to her that he was not deceived.
This but increased her agony,
for she viewed him still plunging into the dark cloud of delusion, so that when he died,
her mourning was without bounds, thinking he was gone into misery.

When they came to lay him out,
the cords of one his thighs was so drawn that the leg stood as though he sat in a chair.
Several men tried to straighten it, but could not.
After the man had taken the measure of the corpse,
he bethought himself that it might be had not got the bend of the limb exact,
he would go back and be certain;
when he came back he put his hand under the heel and found it gave way,
he straightened the limb without any difficulty.
When the widow saw this I was told she sat down suddenly
and sat in a profound silence for some length of time,
and then exclaimed, "`all my trouble is gone;
my husband is gone happy;`" after which she gave the relation of these testimonies--as
given by her husband while living--in the presence of her children and neighbors,
but added, "`I could not believe until my own eyes see,
and now I am satisfied;`" She went with the Presbyterians no more,
but attended Friends`' meetings to the end of her days.
Her husband was upwards of eighty years of age when he died.
Their son Jonathan left six sons and several daughters; the sons, except one,
all moved to the Oblong, in New York State.
My grandfather on my mother`'s side,
was Jonathan--the son of Jonathan--who was one of those who removed to the Oblong, was,
I think, about 84 years of age when he died.

I shall now turn my attention to my own life, and subjects connected with it.
Very early in life I was favored with Divine visitations and well remember when
the few friends that lived over the Creek were allowed to hold a meeting;
this being the first I have any remembrance of attending.
I often felt my mind tendered in these little meetings, and my understanding enlightened,
and I often covenanted that I would live a good life, and be a good man;
but being of a fretful disposition, I often fell short,
and brought sorrow and keen conviction on my mind;
and I often went into the woods alone and wept bitterly,
and promised myself to do better.
So I passed along several years,
sometimes doing pretty well and sometimes bemoaning myself in solitary places.

But to return to the early day of this little meeting--which
consisted of five men and four women,
who were heads of families, where I was steadily taken,
and soon loved to go--I had not passed my tenth year,
when I was led into the following night-vision.
I fancied in my sleep that I went to meeting with my little brothers on 4th day,
it being our meeting day;
and I beheld that my father and the few friends of that meeting,
came in and sat down together as usual.
Shortly I saw three or four coming from the southeast, riding very fast;
their garb and appearance were like Friends, and I thought they were Friends.
They came into the house with a quick motion, fierce look,
and seated themselves with my father.
Shortly I saw my father rise, and deliver a short testimony;
soon one of this company rose up and condemned father`'s testimony,
and him as a false preacher, adding,
that there was a false ministry coming forth among them,
and if they were not well guarded, it would do much hurt;
at the same time pointing at my father, and with harsh censure sat down.
One of his company arose and united with the last testimony.
The meeting then soon closed, and all went out together.
My father and his company turned to the right, with a moderate, steady pace;
the others turned to the left, with a quick hasty movement.

I thought I went the next meeting day, as usual,
and saw father and his little company sit down together.
Shortly I beheld the other company come, in their former appearance and motion;
but said they would not sit with Elijah; he should sit on the bench,
and they would sit in the gallery.
They fixed a seat over his head and placed themselves there.
Soon after the meeting was quiet, my father delivered a short testimony,
then one of this company arose, spoke hasty and quick; a second followed,
and looking down on my father, called him a deceiver, a false teacher,
a cunning deviser of fables, working in the craft of the serpent,
and warned those who sat with him to make their escape before it was too late.
The third arose and united with him.
I noticed father sat very still, looked solid, but never replied.
The meeting closed; they parted much as before, father looked very sober.

My prospect continued on to the third meeting,
where I saw father and his little band take their seats as usual;
the others came in with their former appearance and motion, but at later period,
being more in number; and went to their gallery, as they called it.
In my view, father appeared in this meeting,
and was soon followed by one of that company; a second, and a third.
Before they had done I discovered they had gained
the attention of two of father`'s little company;
an own brother and brother-in-law.
They repeated their former censures and warning,
and said the Lord sent them to warn this people.
This time they broke their meeting first, went out, and turned to the left hand;
father broke his meeting as he went out and turned to the right hand;
these two uncles turned from him and followed the other company.
He looked solid and sorrowful, but never replied nor showed resentment,
through all these appearances.

As I came out of the meetinghouse, I looked up and saw a beautiful oval cloud,
and a very comely man standing upon it, who spoke to me, saying,
"`Do you know what these things mean?`"
I answered, "`no;`" he replied, "`I am sent to tell you.`"
I then mused in my mind who he should be; he replied,
"`I am an angel of the Lord;`" then pointing to the company which my uncles followed,
he said, "`that company are schemers, and have a ranter spirit,
and shall come to nothing; but that man of dark appearance, in the honesty of his heart,
shall be saved.
You shall see your uncles come to nothing.`"
Then looking towards father, said, "`Your father is a true minister;
he will have abundance to undergo from these schemers,
but if he keeps his place they never will overthrow
him for the Lord will keep him from falling.`"
All this was showed me, before my father had appeared in public,
neither had I seen any of these men before I had this view, except my uncles,
but have seen all of them since.

Not long after this father appeared in public,
and a few months after this I saw all three of the men come in that appeared to me before,
where I heard the communications, and saw the conduct,
I think exact as it had appeared to me.
After meeting I learned their names, and who the dark appearing man was;
he was a very dark, swarthy countenanced man, of small natural abilities,
and seemed to be influenced by others.
In a few months they came to our little meeting again in a company as before,
where I heard and saw acted out, what had appeared to me before, except fixing a gallery;
but about a year after, I think it was, I was at the old Nine Partners,
at monthly meeting, I believe, for the first time.
Here was the first I ever saw a gallery, and here, by this band,
my father was ordered off the front seat, and bid to sit down among the people.
He had before this been taken by his friends at home, on the front seat,
in his own meeting, and had been invited on to that seat,
by an old minister belonging to the same monthly meeting.
They not only ordered father down,
but I heard the censorious communications delivered at large,
and I noticed that father sat very still, through all these different times,
looked very solid, but never replied a word;
so that I saw in the course of two years all acted out by
these three men that appeared in my night vision.

My uncles, about this time, appeared very thoughtful and religiously inclined;
but after this last meeting, they turned against my father,
and would censure him to his face,
and say that these were all true recommended ministers, and other Friends believed so;
and so it was that they manifested a bitter, censorious spirit against him through life.
They were all young recommended ministers, when they began opposition to my father.
One of them being a subtle, smooth-tongued man,
used all the influence he was capable of to bear him down, and so far succeeded,
during fifteen years, as to get the greater part of the elders,
and some of the ministers belonging to our quarterly
meeting in the same spirit of opposition with themselves.
Yet some aged ministers, and a few elders countenanced my father, and plead for him.

My uncle by marriage, in a few years appeared to lose all his religion; took to drink,
ran through his estate, and was disowned from society.
His family, all went out of society except my aunt.
My own uncle departed from all religious appearance and became a hard drinker,
involving his estate, leaving his family nearly destitute.
Two of his children became hard drinkers; several went out of the society,
and have not returned to this day, which is upwards of twenty years;
only one of the family is a religious character.
So they seemed to be scattered in Israel, and divided in Jacob.

Now, to return to those pursuers of my father:
two of them carried a high hand for several years,
till they got mostly the rule of the monthly meeting,
and during this time the meeting disowned a great many youth for trifling misses;
and older friends, who did not tune after their pipes,
if they could get a hitch upon them.
At length these two leaders fell out between themselves, about interest matters,
and carried the quarrel so high as to charge each other with lies,
so that the monthly meeting had to disown them both.
They ran through their estates, and became insolvent;
the leading one never returned to society; the other, after many years came back,
but never has been of much use or account.
The dark appearing man being of small abilities, and naturally of a quiet make,
contented himself with his own gift, for the most part,
so that he kept his credit good in society and among his neighbors,
and died in unity with his Friends.
The family of the leading one pretty much ran out; one daughter became a nice Friend,
and recommended minister; so that we see that those who consider their ways,
and turn to the Lord, do not have to answer for the sins of their fathers

This rent, made a great break in the strength of that class; and about this time,
I think it was, some others, who were leading members, were detected in scandalous deeds,
and were disowned.
So it continued along, and in a few years,
I think there was not less than fifteen leading members
of this class disowned from society.
This made a great change in the times.

And now, dear children, in my silent musings,
in looking over the just dealings of the Almighty, and remembering my night-vision,
and having lived to see it come to pass,
and to see the end of many of these fiery builders and ruin of their great castle,
and that, after all this,
I have lived to see your grandfather in his old age a recommended minister,
who traveled in the ministry, with the unity of his brethren,
in different and distant parts of this country,
greatly to the satisfaction of his friends, and the peace of his own mind,
I believe it my duty to leave the account of these occurrences for you to look at,
and think upon, when I am laid in the silent grave,
where you may see how the Shepherd of Israel preserves,
and carries through all tribulation, those who trust in Him;
and that He never fails to plead the cause of the innocent,
and give them the new song on the banks of deliverance.
While on the other hand, you may as clearly see how the Lord destroys Babel,
with all her builders,
and that nothing will stand or endure but what His own spirit creates and directs,
in all our religious movements.

I now return to my getting along, from nine to twelve years of age.
I had many clear openings.
I remember that in the course of this time, I went one day to the meeting early,
and got to the house before any others came.
I felt an inclination to sit on the front seat, and I did so; sat there awhile;
there it was made known to me as clear as ever it was afterwards,
that in that part of the house I should have to sit in time to come,
and should have to preach, and I must conduct well,
for if I did not I should not be fit to preach; and that I must mind and do right.
My mind was made sensible of the solemnity of the subject,
which continued with me through the meeting,
and it was revived on my mind at times for years.

Being early visited with good, I was often observed to be in a muse,
and was often asked what I was studying about, but being of a bashful make,
was not willing my thoughts should be known to any mortal, and to escape being noticed,
I often went into the woods and other secret places to prevent exposure.
On account of my quickness of temper when crossed,
and aptness of disposition to be caught and diverted with merriment,
I took this way in order to cry to my Maker, without any person knowing it;
but I invited a cousin about my age, to go along with me,
telling him my thoughts and feelings.
He went with me a little while;
at length he told me he could not bear to be laughed
at and despised by his brother and playmates,
as he was, for being sober and going with me, and he must leave me.
I reasoned with him, and endeavored to persuade and encourage him to keep along steady.
He acknowledged he was well satisfied with my company,
and that he never felt better than when he was sitting alone with me, in silence;
he believed it was right, but could not bear what he met with, and must leave me,
which he did, to sorrow alone.

He took his career in merriment, and afterwards told me at times,
that by and by he would be good; but sorrowful to relate,
he has never become a religious man to this day, though now over fifty years of age.
But I have heard of his telling of the good meetings he and I had in the woods;
that he believed, if he had kept with me, he would have been a good man.
His departure, with other circumstances, appearing to combine to depress my mind,
led me into great discouragements, being of a weakly make,
and having had a number of gatherings in my head, which affected my hearing,
and oftentimes being in a muse when spoken to, did not always understand,
and of course did not attend, which was often followed with a rebuke.

This, with the censure of being careless,
(although I had no disposition to be disobedient,) almost broke my heart at times.
At other times it would aggravate and discompose me,
and I think these discouraging circumstances continued for two years.
Yet, all along, my mind was impressed with a sense that it was my duty to be obedient,
for the Lord required it of me.
Under these impressions, my intentions were to try to do right, and many times,
when I had got out of the right way, and was favored to see it,
I went alone and bemoaned my condition,
and begged for the pardoning mercies of my Redeemer, and found Him a tender Father,
who pitied my weaknesses and compassionated my griefs.

In the year 1777, being fifteen years old, I thought I would learn to swim,
and often being in the water,
I perceived that when the water got into my ears and ran out,
it brought a wax-like matter, which cooled the heat in my ears, and gave ease.
This induced me to practice, so I commenced going to a clear, cold spring,
nearly every day, and filling my ears with the water.
It continued to bring away that gluey matter until
I began to hear with one ear pretty well.
This seemed to put new life in me, for this enabled me to hear, and answer quick,
and pay attention.
I continued the practice, and after a while,
there was a sharp snap in my head that seemed to make it jar, and soon after it,
there came out of the other ear, a twist in the form of a screw, that looked like glue,
which I judge was the eighth of an inch long.
This coming away gave vent to thinner matter, which so cleared my head,
that it relieved me of a roaring, which had been almost perpetual,
and enabled me to distinguish sounds, an enjoyment that I never had before.
This enlivened my spirits, and I soon manifested activity,
and abilities that were not discovered before,
which drew the attention of those about me,
and served to enliven my ambition to embrace every opportunity to gain esteem.

This summer, about the beginning of rye harvest, in the time of the revolutionary war,
a band of rangers, so-called, came, and commanded my father to go with them, under arms,
to look up some drafted men, who had absconded.
Father refused; their captain demanded the reason; he replied,
it is against my conscience to go with men under arms to distress my peaceable neighbors;
the captain replied, "`+++_______+++ your conscience, you shall go,`" drew his sword,
and presented to father`'s breast bidding him walk on,
or he would run him through immediately.
Father being unwell, was lying on the bed; he looked the captain calmly in the face,
and replied,
"`I shall not go with you one step as a pilot;`"
the captain stepped forward with these expressions:
"`+++_______+++ you, then I will run you through immediately;`" father replied,
"`that you may do, for I shall not put my life against my conscience;
but I would have you consider, that you have but one life to live,
and must die as well as myself; to shed innocent blood is a heavy thing;
you may bring a load on yourself, that you may be sorry to carry through life,
and will be a heavy thing to answer for, before the judge of all men,
to whom you must give an account.`"

The captain turned pale, his hand fell with a tremor; he turned to his men,
and bid them take him; they were not hasty to obey;
he raised his sword with a harsh expression, bidding them take him by the shoulders;
they did so, dragged him out of that room, and across another, down a flight of stairs,
and through the kitchen, into the door-yard, very quick.
The captain then said,
"`I make a prisoner of you for your stubbornness;`" father replied,
"`as a prisoner I will go where I am ordered, but as a pilot I will not go one step.`"
They put him under guard that night; the next day he was sent to jail,
but the jailor not being there to take the delivery of him, he returned home for a week,
was then taken back and put into a miry, stinking room, adjoining a slaughter yard,
and no place to get air, except the window fronting the slaughter yard,
and a little hole where they passed in food.
Here they were kept a number of days, and were not even allowed straw to lie upon.
My father being taken with the camp-fever, and in danger of dying, they became alarmed,
and removed him, (and another man confined with him,) into a clean room,
where they could have fresh air, allowing his friends to come and bring him necessaries.

In about two weeks he recovered, and was then removed to Esopas,
(since called Kingston,) and put on board the Fleetprison,
where he was kept till after the fall sowing.
When father was taken away we had just begun to cut our rye, of which we had five acres;
eleven bushels sowing of wheat, three acres of flax, and three of oats.
Owing to the extreme difficulty of procuring help at this time,
we were under the necessity of accepting the kindly offered
assistance of a young woman who lived in the family,
and who proposed that if we three eldest boys would take our sickles and reap,
she would bind after us, and help set up.
I went forward with all the resolution my constitution would bear, and we succeeded,
with the help of a man for a few days, in securing our grain crops in good season.

I was prompted with the idea, that it should be seen the crops should not be lost,
if it were possible to save them; yet all this fell short of consoling my mind, so that,
many hours when at work, the tears would run down my face plentifully,
and weeping frequently occupied the watches of the night.
I often exclaimed, "`O, Lord, what shall we do?
Have mercy on us;`" and so he did, for my mind was often favored to feel that peace,
and that foretaste of joy, which I have not language to express;
more particularly so in meetings.
Our father advised us to keep to meetings,
and not to neglect those of the middle of the week.
We kept strictly to his charge, and I believe to this day it was a blessing to us;
and I feel myself bound,
in humble gratitude thankfully to adore the goodness
and tender mercies of the Shepherd of Israel,
who graciously sustained in the needful time.

When we went at our hay, I found that I was so worn, I could mow but to little purpose;
my strength so gone, and my brother less able than I was, that under this depression,
I wept aloud as I mowed, and my father`'s youngest brother passing at the time, stopped,
and looked upon us with astonishment; (he was a fore-handed man, and had plenty of help);
at length he said, "`Joseph, what is the matter with you, that you cry so?`"
Finding that my feelings were discovered, surprised me;
at length I told him that we had almost worked ourselves to death already,
and had not strength to mow; must lose all our grass,
and have no fodder for our stock in the winter, for we could hire no help.
My uncle, with a smile, bid me not be discouraged, or work too hard,
and he would see if he could get some help,
and signified that our fodder would not be lost.
He went home and told his men it would not do;
Elijah`'s boys would kill themselves trying to save their hay;
seeing how the little fellows worked in the meadow alone,
gave him such a feeling as he never had before, and they must go and help them.
In a few days, with his assistance, we were enabled to secure nearly all our hay.
This so put us forward, and renewed my courage, that with diligence,
I succeeded in putting in eleven acres of winter grain, in good season,
and had commenced spreading the flax, when father returned home.
Our success in business during my father`'s absence,
raised the admiration of the neighbors.
But, alas! as my former situation served to depress, and cast me down,
this change sorrowfully produced the contrary effect,
as is common for one extreme to produce another.

Before leaving the subject of my father`'s imprisonment,
I shall remark that those in authority often endeavored
to prevail on him to take the oath of allegiance,
or sign the association, stating that he should then have his liberty; he,
refusing to comply, informing them he had done nothing to forfeit it;
that he was a free-born American and should not acknowledge
their right to make such demands,
for he suffered for conscience sake,
in obedience to a King who was above all the powers of the earth,
to whom they must answer as well as he.
After a while they offered him that if he would be bound to stay on his own farm,
he might go home.
He told them he should enter into no such engagement; that he suffered in a good cause,
and that if he was set on his own farm, he should go where he thought right.
After this they informed him that he was to be banished to the British, at New York,
and then he might fight for his King, to which he replied, if they sent him there,
he should return; that he did not suffer for King George,
that he did not like his conduct better than theirs;
that his sufferings were for the cause of another King,
to whom King George and they would have to give an account for their wretched conduct,
and the shedding of human blood; to which it was replied,
"`then you shall lay where you are until you die, and the flesh rot off your bones.`"

But shortly after, father was set at liberty,
with orders to go home and behave himself well.
There were several other Friends made prisoners, for going to the Yearly Meeting; which,
at this time, was held on Long Island;
among these were two of his most absolute opposers, who showed their feelings,
even in this time of affliction, which added to his sufferings.
They often held meetings on the vessel on first days,
but their standing so opposed to him,
there seemed but little or no room for him to relieve his mind;
this caused an additional weight to his sufferings.

I shall now proceed to relate some of the most trying part of my life.
Having now gained the attention of my father, the praise of my neighbors,
and the esteem of my relations, I now thought I should be happy.
This seemed to prepare my mind to be taken captive at once; but notwithstanding,
the Lord favored me often with renewed visitations,
so that I often renewed my promises to do right,
yet often being persuaded to go into company, which I had a strong taste for;
and promised myself I would take care and do no harm,
and about as often returned home wounded to the heart for deviation from my promises.
Finding myself much noticed by my comrades, I was reluctant to lose their friendship,
which was an enjoyment I never had before.
I was also unwilling to lose the favour of my Maker,
and strove for a time to please both;
but being much in love with the praise of the world, it made the struggle hard.
For while I strove in this way, to my sorrow, I found I displeased both.
My company was not agreeable to my associates, nor my course acceptable to my Maker.
In this way I got much into a bewildered state of mind, yet was favoured at times,
to feel the renewed evidence of the testimony of the Eternal Truth,
that the time was drawing nigh, when I should have to appear in the ministry,
and it was sometimes in that clearness, which removed all doubts and scruples.

Before I proceed farther with the above subject,
I think it right to relate two remarkable favors which the Most High showed me,
between the ages of nine and fifteen, which were as follows.

Feeling solitary, I laid me down in the twilight of the evening, in a ponderous muse,
and whether I went to sleep or not I never knew.
But so it was, I was conducted with great quickness, an immense distance down,
or from all that was light or cheering,
until I was brought into full view of the regions inhabited by infernal spirits.
There I heard the cries and doleful lamentations of the miserable,
exclaiming against conduct that brought them there.
And I saw that every tongue had to confess to the truth,
and to acknowledge that it was their own evil conduct which brought them there.
Their agonies, and cries, were beyond description,
and their habitation a sea to which I could see neither bottom nor shore,
and all appeared far below where I stood.
And although it did not appear to be elementary fire,
yet there appeared a dark cloud of smoke perpetually rising, that spread over the earth.
I turned to look, and beheld, as it spread over the earth, that darkness increased,
and where the thick columns were, it almost eclipsed the light of the sun;
then looking I beheld that there was a few who seemed pleased with the light of the sun,
and took pains to keep in it.

The countenances of these appeared bright and active;
but the greater part of the people appeared disposed
to choose the darkened air to breathe in,
and where they got under the thick columns of smoke, which were so dark,
as almost to take off the light of the sun, and quite its warming beams.
These I saw in motion, (and they perceived it not), hastening down a gradual descent;
they soon moved more rapidly.
As they verged towards the burning sea,
the columns of smoke became so thick that little was to be seen; yet they appeared merry,
and would make one another so.
They seemed to have neither fear nor concern, till they dropped into the burning sea,
when their surprise appeared indescribable, and their anguish, no pen can paint.
As I beheld, I noticed in the burning sea and in the dark smoke,
there appeared great motion, as though the sea boiled.
The sight seemed amazing, but more, when I beheld the old dragon in his terrific hue,
whose appearance, and all the motions of his tail,
seemed wonderfully to promote horror and agony through the dark regions, at which sight,
it seemed as if I had no strength left.

Then I heard a voice from on high, saying to my guide,
"`see and take him back;`" he touched me, and conducted me back.
When I came to myself, my face and body were much covered with large drops of sweat,
much resembling spring-water for coldness.
I soon raised up and saw that daylight appeared.
After this, I had no relief of mind until I told two,
whom I saw on the brink of eternal ruin.
It took hold of the woman; she melted down in tears; she was one the libertine sort.
I have never seen her since.
About twenty years after,
I fell in with her husband who told me from that time and after she lived a religious,
sober life.
The man seemed to struggle under it, so I left him.
About fifteen years afterwards, I fell in with him at a Friend`'s house.
The man of his own accord, related my visit in the presence of several Friends,
and confessed that he could never get the weight of it off his mind, until he gave up,
to be what he ought to be.
The above, made some weighty impressions on my mind, for a while,
and caused me to refrain from some wrong habits I had been in,
yet often was made sensible of falling short of being
what I ought to be--the sense thereof,
frequently filled my mind with sorrow.

In this situation, I one day towards evening laid down,
and whether I dropped into a sleep or not, I cannot tell,
but thought I was standing on a beautiful eminence,
where I had a view of the heavenly host.
There I saw the King of Kings on His throne, and the Redeemer at the right hand of Power,
and the angels standing around the throne.
My sins were shown me as plain as a printed book.
I stood trembling, looking for my final sentence; and heard one of the angels say,
"`shall I slay him?`"
The great King said, "`no, we will warn him.`"
The angel said, "`shall I warn him?`"
The Savior of man replied,
"`I will warn him`" and arose from his throne and looked down upon me, and cried,
"`depart, depart, from sin;
your life is not your own;`" and as He retired to His seat the
appearance of a gate closed before me and shut all out of my sight.
When I came to myself I found my body in much the same condition
it was in when I had the night-vision before,
and had lain about two hours.
This so impressed my mind that I endeavored, for a while, to live as I ought to.

When I arrived at the age of about fifteen and a half years,
I thought it my duty to speak to a difficult subject, then before the Monthly Meeting;
but from a fear of opposition, I forbore.
This brought great distress upon me for a while.
In about three months it was laid on me to bear a
public testimony in our meetings for worship,
which I suppressed and reasoned away, for about six months, when it all left me,
and with it all comfort and peace.
My light became darkness, and truly great was that darkness.
I groped about seeking rest but found none--bitterly
bemoaning my condition in solitary places.
At length I concluded all was lost, and there was no place of repentance for me;
that I might as well be merry and take all the comfort I could.
In this state of mind I again joined my young companions,
and ran into mirth at a rapid rate, carrying the anguish of my soul with me,
wherever I went, and was often met with by renewed convictions,
which caused me to tremble.
Yet, concluding there was no return for me, I might as well go on,
so I dragged along for several months, sometimes down in the extreme,
at other times as much in the air.

About this time, hearing a discourse on Infidel principles,
where it was held up that the Scriptures were uncertain records,
and that the idea of the Divinity of Christ was a foolish one,
and that there was no future punishment; this pleased me; I wished to have it so,
and I laid hold of it willingly, endeavoring to soothe all my feelings,
in hopes it was so.
But it was a length of time before I could make myself believe this doctrine.
Still the inexpressible anguish of my soul went along with me,
nor could I reconcile my mind to the idea,
until I concluded that all the openings and impressions I had felt, and what I had seen,
were the effect of dubious stories, which my parents had told me.
When fixed in this idea, it seemed as though all light left me,
and I had little or no power, to govern my temper, or tongue.

Of all states that I had ever witnessed for hardness of heart,
and of being void of any comfortable feeling, this exceeded them.
My distress for a while was indescribable; yet I went on to vindicate the doctrine,
until I believed it.
Gross darkness, indeed! where neither sun, moon, nor starlight, are seen.
In this state I took my career in merriment and mirth--and
in this way soothed my feelings as well as I could,
concluding all was well; and,
though my mind was considerably lulled into a state of imagined security,
yet anguish kept along with me, and oftentimes my days were wearisome,
and my nights tedious.
Yet, through all this bewildered state I was favored with
a view of honor which kept me from gross evils,
or from injuring my fellow creatures, either in interest or character.

When about thirteen years of age, (I think it was), I was sent to mill,
and while the grain was grinding, the miller, who was an old man, and two others,
(aged men), fell into discourse about a travelling Minister, who had been among them,
of the Methodist belief.
They all agreed that he was an able Minister,
and had preached several good sermons in that part of the country.
They believed the Lord sent him to preach,
but that in their neighborhood he said but little,
and informed the people that he could not preach any more, and dismissed them,
which disappointed them very much.
They thought it was not right, and that he ought to be talked to.
They agreed among themselves which of the three should talk to him.

As I sat listening, in a deep muse, a solemn feeling came over my mind,
and I felt a forcible motion to go and speak to them,
and I believe the Lord required it of me.
I hesitated a little, but fearing to delay, I walked up to them,
and I think nearly in these words, addressed them: "`You are old men,
and I have been hearing you talk about the Minister,
who you believe the Lord sent among you.`"
They answered, "`they did believe so.`"
I replied, "`then I have something on my mind to say to you,`" and proceeded,
"`If the Lord sent him, He knew best where He wanted him to preach;
and it was certain that the Lord knew the states of all the people,
and knew what to give him to preach that would be suitable for the people, and how much;
and if he preached any more it would only be man-preaching,
and might not be suitable to the state of anyone in the meeting.

"`They ought to be careful how they meddle with the man,
seeing it was his duty to mind the Lord who sent him out; and if by their talking to him,
he should preach more than the Lord gave him to preach,
then he would turn from pleasing the Lord, to please man, and this might offend the Lord;
that He might take his gift in the Ministry from him,
and what an evil that would be to the man, and an injury to the cause of God.
But if they saw anything in the Minister`'s conduct that was not right,
then it was their duty to talk to him and show him his error,
and in that way they might be a help to keep him right.
I thought they had better leave him to the Lord, who they believed had sent him out,
than to meddle with him in any other way.`"

I then stopped and turned from them, feeling my mind relieved and filled with peace.
Not long after this, two of those men came to my father`'s;
one of them related to him the occurrence with this remark--that in all his life,
he never met with such a stroke;
to think that such a child of my age and looks should be able to teach him,
and it was the truth which he had not seen into before;
and he had not dared to say to the Minister what he intended.
I may remark that I went up to these men with no other view
than to say to them what came into my mind,
and I found no lack of words or matter; thus witnessing, that though a child,
when I was obedient to the Lord,
he was strength in a weak child--wisdom and utterance
in the needful time--blessed be His holy name.

Another occurrence took place (I think),
when I was between seventeen and eighteen years of age.
I went to see an aunt of mine, whose eldest child, (a daughter),
had wanted to go for some time to see a great uncle of ours.
My aunt concluded if I would wait on her, and see her safe home, she might go.
Accordingly, the next day we set out.
It was a time of life when at times I indulged myself
in such conversation as promoted merriment in company.
In this way I entertained my cousin most of the way going;
but on our return we had not travelled far, before we were overtaken by a man,
who soon fell upon me,
censuring the Quakers in strong terms because they would not fight.
It was during the revolutionary war, and critical times in that part of the country.
I heard him pretty much through,
by which time I felt my mind closely arrested with an uneasy feeling,
that the principles of Truth,
and the people that I believed were faithful to them should be so censured,
though I felt conscious that I was not one of the faithful,
which at that time I forcibly felt.

Yet, notwithstanding my embarrassed state of mind, the Lord, I believed,
for the sake of His own name, and the tender regard he had for his faithful ones,
so touched my mind, (though I was hardly sensible what it was),
that I felt as if I could not hold my tongue any longer,
let the consequence be what it would.
As I commenced, all fear was taken away, words flowed readily,
and I was enabled to show the difference between the law and the Gospel;
to open to him our principles, give him our reasons for them,
and prove them by many scripture texts,
and finally to show him that it was impossible for a true Quaker to be either Whig,
or Tory, for that implied opposite parties, and both believed in war,
and Friends did not.

By this time, the man became so tender, that with tears running down his cheeks,
he acknowledged our reasons were good, and that our principles were right,
and wished Friends would keep to them; if they did,
they would be a blessing to the world.
This remark came home to my feelings.
He added, that he was fifty-five years of age, and never saw these things before;
that it was marvellous to him,
and he believed there must be great wisdom among the Quakers,
for so young a man to know so much.
He urged me to go home with him; I informed him I could not.
When we parted with him he gave me his hand, wished me well,
desired me to remember him and pray for him.
This thought went through me like a sword, "`how can I pray for you,
when I neglect to pray for myself?`"

As I turned from this man I discovered a man who had been riding behind us several miles,
unperceived by me.
He suddenly rode alongside, and exclaimed,
"`I am glad to hear you bang off that old Whig so, for he is an old rebel,
an enemy to his King, and it is good enough for him.`"
I turned, and looked him full in the face.
It came forcibly into my mind, "`You are a tavern hunter, and one of the vilest men.`"
I soon replied, "`I believe you are mistaken in me,
for I can no more be a Tory than a Whig.`"
He said, "`why?`"
I replied, that, "`before the war,
our country got much filled up with a sort of men that hung about the taverns,
and practised card playing, cock-fighting, horse-racing, and getting drunk;
and then would go home and abuse their families;
they were equally met and agreed in the service of the devil,
and of course were his children.
The Lord had allowed an evil spirit to divide them, for they corrupted the land; and now,
one part had taken side for the King, and the other for the country;
both parties were still in the same practices,
standing on the beasts`' head before the war, they stand on the beasts`' head now,
only they have become divided into two horns, that push one another.
And I believed that in this way the Lord was purging our land,
and the two horns would have to go down into hell, with the beast:
for these reasons I could not be a Tory nor Whig.`"

He rode off whistling, and left us.
My cousin then came up, and with a serious look, said to me in substance, "`Joseph,
almost all the way going to uncle`'s, you kept me laughing with your nonsense,
and now you can talk like an angel, set the first man crying, and the last one,
you have pictured out as correctly as I could, who have lived by him all my days;
he is a neighbor to father, and is called a lighter, card-player, horse-racer,
and is a great drunkard, and follows other wicked practices.
You have been talking to him like a Minister; what can I think of you?`"
These simple remarks, went through me like the arrow that was thrown at a venture;
it cut me so close that I had to sink down, reasoning with myself, sure enough,
what am I? and as I sank down in my mind, I felt the weight of my folly.

After a while it was opened to me in the Light, and with such clearness,
that I had no power to disbelieve,
that the Lord put a word in Balaam`'s mouth to deliver to the Midianites and Moabites,
though his heart was not right before the Lord; notwithstanding he was highly favored,
yet he did not give up to cleave unto the Lord with all his heart,
and keep to the word he had spoken to the people; therefore the Lord cut him off.
And now the Lord had put a word in my mouth for those men for the
upholding of the Truth in the earth and the honour of his own name;
though my heart was not right before Him;
and if I did not cleave to the Lord with my whole heart, and keep to the word spoken,
the time was coming when I should be cut off as Balaam was.

The force of this solemn subject turned my jovialness into seriousness,
and my merriment into heaviness of heart; yet while I mourned over my own folly,
I marvelled at the wisdom, goodness, and tender mercy of the Almighty towards me,
in awakening me, and instructing me in such a wonderful manner.
Adored and praised forever, be His holy name!

In this way, I struggled along, till near eighteen years of age,
when it pleased the Lord to send his faithful servant, Abel Thomas, into our parts, who,
in a large meeting, addressed a single state,
and was enabled to speak to my condition so clearly that I could not deny a word,
commencing with the first of my religious life, to the condition I was then in,
more correctly than I could have done, and clearly informed me what I had departed from,
showing, that that was the cause of the distress I had undergone.
Then he took hold of my infidel principles, fixed his eyes in my face, and to me,
in a wonderful manner, unfolded my reasonings, laid waste all my arguments,
then warned me in a solemn manner, to return to the Truth from which I had departed,
and closed his testimony with these words: "`That Jesus, whom you have denied,
has revealed to me your state and condition.`"

Finding, after meeting, that he had traveled a number of miles to reach it,
and had lodged far from the meeting place;
he had no chance to get any outward knowledge of any state among
us--this increased the weight of his testimony on my mind,
and so convinced me, that it overthrew all my castle,
and I dared not trust in it any longer.
I went into the woods, and wept until I could weep no longer.
Now, the potent enemy of all happiness, poured in upon my mind,
a mighty flood of reasoning, thus--that this Friend was not sent for my salvation,
but only to stop me from holding up blasphemous principles,
so that I should not deceive others; it was for their sakes and not mine,
that he was sent, and that I had blasphemed the Father, Son, and Holy Spirit;
for the spirit I had felt striving in me, reproving for sin, was the Holy Spirit,
and there was no mercy for me; for the justice and holiness of God,
would never be reconciled to such a monster as I was.

These thoughts sunk me below all hope.
I became so disordered, that I was watched day and night, and was tempted to hang myself.
Sleep went from me, my stomach refused food, I pined away like one in a decline,
for my distress and horror were beyond the scope of language to set forth.
I fancied I saw the regions of endless torment ready to receive me,
so that many times I started,
fearing that I heard the devil coming to carry me away bodily.
In this situation I remained a number of weeks.

Now, dear children, stop and reflect;
behold what I passed through for departing from the truth, and letting in unbelief.
Let it be a warning to you.
My cravings are that another may never experience the like distress.
The above named Friends, Abel and James Thomas,
passing to the southward went through our Yearly
Meeting expecting to go home from Long Island.
Instead of finding themselves at liberty to return,
they felt their minds forcibly arrested to come back more than a hundred miles,
to attend our Quarterly Meeting to be held at Oblong, where father had taken me,
fearing to leave me at home.
When they came into the meeting I was exceedingly shocked,
concluding they had now come to denounce my final doom.

After sitting awhile,
Abel arose and brought into view the state he had
been led to feel for when in our land before,
and in a feeling manner,
declared that he perceived the enemy had taken advantage of the poor penitent,
and had made him believe the Lord had no mercy for him,
and that his damnation was sealed.
He continued, the enemy is a liar and was so from the beginning;
for whom God cast off he no longer strove with; therefore,
while the strivings of His Spirit are felt to caution against evil,
it is an evidence that the day of mercy is yet continued;
that if the manifestations of the Spirit of Christ within are faithfully obeyed,
a submission of self to the Lord`'s disposal, in life, or in death,
patiently enduring the needful baptisms,
submitting to the chastening of the rod that is lifted up,
and acknowledging the justice of the hand that shakes it,
the days shall come when the individual will have to go forth and
tell what great things the Lord has done for his soul.

When this was spoken, I said to myself, it is enough, I now believe.
He stopped as though he had heard me speak, and turned to another subject,
not afterwards resuming the former one.
These two sermons occasioned much reasoning in the minds of Friends,
it being thought there was no such state present;
but he being a stranger they let him pass without intimating their doubts.
May this remark be a caution to all to whom these lines may come,
to let that alone which they know nothing about; for the Lord had a witness,
and the arrow was directed to the right place.

I returned home, feeling much more composed in mind,
but it was not long before trouble poured down upon me like a mighty torrent.
Finding the company of my former associates a grief and a snare, I relinquished it,
upon which they raised many false reports and insinuations,
which prejudiced the minds of many elderly and some worthy Friends,
so that I had to bear the ridicule of the young and the censure of the older ones.
One woman who sat upon the high seat, came forward and declared to my face,
that she saw me do what I had never done or thought of doing,
yet she testified to it with such assurance that she was believed,
and I was judged to be a liar.
This seemed as though it would take my life.
I thought for a while she had effected that which she had said she would;
which was that she would destroy my credit,
and more so when I met with cool countenance and shy carriage
from those to whom I looked for sympathy and counsel.

This so unsettled my mind, that when I thought of her, the saintish appearance she made,
where she sat, and how she had deceived Friends,
I was almost induced to think the Lord would not have anything
to do with such a people but to condemn them,
under which feelings I mostly refrained from attending their meetings,
except when urged by my parents,
wandering about in solitary places to make my moan before the Lord,
and frequently attending the meetings of all other societies in my vicinity,
in order to find a comfortable home among some of them.
While in this search, I attended the Baptist worship several times,
and my mind was much caught by water baptism; which exercised me much,
and I was thoughtful of being plunged;
and while waiting to feel an impression in my mind thereto,
I felt unusually drawn to attend Friends`' meetings again.
Soon after I took my seat, these words came into my mind,
"`He shall baptize you with the Holy Spirit and with fire, whose fan is in his hand,
and he will thoroughly purge his floor, and gather his wheat into the garner;
but he will burn up the chaff with unquenchable fire.`"
This continued with me through the meeting.
When I went out, the subject left me,
and I thought no more of it until I took my seat in the next meeting,
when it again revived, and continued through this as in the former meeting,
when it left me as before.

At the next meeting, the same passage was again presented to my view, and I queried,
what does this mean that this text should continue with me during three successive meetings?
It then opened as clear to my mind, as the bright beams of the sun,
that the Holy Spirit was nothing more or less than the Holy Spirit, for ghost is spirit,
and God is Spirit, and all spirit,
and that the soul of man was the spirit which derived
its being from the creative breath of the Almighty,
and was designed, if obedient to the will of its Maker,
to become an inhabitant of heaven, and enjoy His glory.
That God, who was all spirit, self-existing, uncreated, was the Creator of all elements;
composed them with matter far beneath Himself, and placed them far below,
yet it was He who sustained them.

It appeared clear to me, that as all matter, all elements,
were dependant on Spirit for the continuation of their being,
it was not in the power of the lesser to comprehend or penetrate the greater;
and of course, the soul having derived its being from God, it was a created spirit,
and therefore, superior to all elements, being created for eternal being,
and designed to become an inhabitant of heaven, which the elements never were; therefore,
the produce of the earth, could feed the body, but it could not feed the soul:
Waters could wash and purify the flesh, but could not reach the soul, the spirit in man,
to which the Almighty gives understanding.
It appeared clear that John, being under a divine mission,
and under the influence of God`'s Spirit, saw through this mystery,
which had been hid for many ages of the world, and felt himself authorized to cry,
"`He that comes after me shall baptize you with the Holy Spirit,`" etc.,
which is the Holy Spirit.
Here it appears clear that the spirit which brought the soul into being,
which the elements had no concern in doing,
was the only power which could restore a sick soul to health,
or a wounded one to a healed state.
These views brought my mind into solemn thoughtfulness,
and this language ran through it--the Holy Spirit is also the Grace of God,
and the Spirit of God in creation acted independently of any other source,
so the Spirit of God acts independent of all elements, in the regeneration of men.

For anyone who had been regenerated, born again, or formed anew in Christ,
to be baptized with water, would be like some formerly, who began in the spirit,
and turned to the weak and beggarly elements,
thinking to perfect their happiness thereby,
which an apostle under the influence and direction
of the Spirit of God reproved them for.
Being much relieved from the entanglements of ceremonies,
I felt an increasing concern to attend the meetings of Friends;
and I was soon forcibly impressed with the necessity
of appearing in public testimony from time to time,
but fearing it was a transformation of the evil one, I felt if I did so appear,
it would be rejected by Friends, and I should be censured by them,
I put it off until my life became a burden, and was tempted to put an end to it.
At length, I gave up, and spoke a few words,
and found my mind much relieved and comforted.

My public appearance so disturbed my old associates in folly,
that an own cousin spread a falsehood about me,
of such a nature as to cause my being visited by the overseers.
This laid me under the necessity of proving the falsity of his story;
yet he was not dealt with, and I was barely discharged.
This so discouraged me,
that I did not dare to open my mouth in that way again during twelve months.
When my cousin saw the effect it had, he boasted that he had stopped me from preaching,
which was what he intended; but oh, the anguish of my soul,
I have no language to describe.
Yet I was favored with the resolution to go no more with such company,
whatever my sufferings might be, even if it took my natural life;
which at times I thought it would.
But I was favored to stand my ground, so that this storm seemed a little to pass over,
and I began to hope,
although it soon appeared that my cup of suffering was not yet full.

Sometime after Abel Thomas returned from his visit to our parts,
it was presented to my mind, that if I would curse God, my father and mother,
and the Bible, I should be happy as long as I lived;
if I would not do this I should never be happy in this world,
and as for future happiness it was out of all question, for I should never obtain it,
it was not for me; and I had better be happy while I lived, than never to be so.
These thoughts surprised me; I endeavored to put them out of my mind, but all in vain;
they continued to roll in upon me with such a weight of
darkness that I was so confused as to be very near deranged.
It was then presented to me that God never allowed
any of His to feel the torment that I did,
and I should never feel any better unless I cursed Him; that would relieve me.
I strove to put these and the like thoughts out of my mind; but in vain.

I called to remembrance all I could think of to strengthen my mind against the temptation,
and reasoned thus: if I curse God I shall surely be miserable;
it is in His power to make me miserable in time and eternity;
and no power could hinder Him from doing what He would.
I had sinned enough and had enough to answer for without adding to the dreadful account;
therefore I could not do this dreadful evil and sin against God.
And I reasoned, where can any comfort come but from God?
It then rushed into my mind like a flash of lightning,
and I thought with the terror of thunder, that if I would curse God, he would leave me,
and I could then join with those who had familiar spirits.
These,
and the like thoughts were so perpetual that it seemed as
though I could not obtain a moment`'s relief from them,
and thought I should go into endless misery.
This took away my appetite, and I dared not sleep more than nature compelled me to.
I walked the house nights, and kept my feelings to myself as much as I could daytimes;
thinking if I must go in that condition I would keep it secret from my parents,
lest it should add to their affliction through life.
My distress was dreadful; I grew weak and unable for business;
my face became pale and my eyes had a strange appearance;
when the neighbors saw me they would ask, what ailed me?
and remark, that I looked as though I was going to die, and that my eyes looked ghastly;
which but heightened my misery and confirmed my thoughts.
My parents often asked, what the matter was with me; but I kept all to myself.

This temptation continued fourteen days and nights,
when finding my strength so far gone that I thought
I could not keep on my feet any longer,
I laid down thinking it was likely one hour would close the scene with me;
when I should find myself among the miserable.
Soon after lying down I felt such a weight come upon me that I could not stir,
and thought I heard as plain and intelligible a whisper
as ever I heard from a human being,
to this effect: "`surrender, or you shall die in a minute,
and go to the place of endless torment.`"
I replied, "`I cannot do that, I never will curse God, if I lose my life.
I have enough to answer for without that terrible
sin;`" for it struck me with horror at first,
and so continued through the whole trial.
When it appeared as though my breath was going from me,
and I looked for every breath to be the last, I felt this language as the last tribute,
I should ever have the opportunity to offer, "`Our Father who are in Heaven,
hallowed be your name, your Kingdom come, Your will be done on earth as it is in Heaven;
give us this day our daily bread, and forgive us our trespasses,
as we forgive them that trespass against us; and leave us not in temptation,
but deliver from the evil thereof; for yours is the kingdom, the power, and the glory,
forevermore.
Amen.`"
I gladly embraced it, and as it passed through my mind, the weight went off me,
and the cloud of darkness with it.
My mind was at once composed and seemed filled with the joys of Paradise.
I found it best to keep still,
for I saw there was danger of being carried away with the rapture.

Great was my peace for several days, and I had many clear,
heavenly openings in the vision of light, in which there is no deception.
This strengthened my mind, for it was showed me that the Redeemer gave His life for me,
and my love to Him was not proved until I had given up my life rather than deny Him;
that the Lord`'s prayer was prepared for me at that time and His Power was with it.
This was the only offering that could possibly find acceptance with the Father from me,
and all who ever entered the Kingdom must go through great tribulations,
and have their faith and love thoroughly tried, that they might come forth like gold,
seven times tried in the furnace, weighty and pure, fit for the Kingdom;
and they that endured not the furnace were not accounted worthy
to be entrusted with the mysteries of the kingdom of Heaven,
or to enjoy the felicity of its glory.

It was not a great while, before my father sent me to a neighbours house,
(who were members, and sat on the high seats, and made a grave appearance),
just before sunset, to borrow a tool.
They were going to tea; they pressingly urged me to partake with them,
which I consented to.
After supping, I made a move to go home; but the young people persuaded me to stay,
and talk with them a little, which I yielded to, against my feelings,
thinking I might offend if I did not.
But O! how dangerous is our reasoning, as the following will show.
I had not sat long with them,
before I was invited to an out-house about five rods distant.
When I rose to go with them, it came to my mind to turn and go home;
but not heeding the motion, I went with them.
As I came to the door,
this language ran through my mind--there is an All-seeing Eye that
will bring to an account for all this--yet I stepped in,
and this language followed--how would your father feel if he knew of this,
whose prayers have been for you, when your eyes have been closed in sleep.
This shocked me, almost to trembling, but it was too late, the door was shut and guarded,
and I had no way to escape; so I walked across the room and sat down,
and did not rise until they broke up.

They soon began, and went on with their dance, which continued till near break of day.
Here I found I ought to bear testimony against their conduct, but forbore,
much to the wounding of the little peace I now and then enjoyed; but went home,
concluding to keep all this to myself; thinking, if I told of it,
as they were all children of Friends, except one,
and several of their parents were ministers, and I think elders, and overseers,
that they would deny it and throw the scandal of a falsehood upon me.
And I was not mistaken, for the girl that did not belong among Friends, told of it.
It soon got among Friends, and the overseers took it up.
This made an alarm; my father examined me several times, but I kept all to myself.

But to find the truth of the business, he sent me home with the borrowed tool,
and followed so close after, that I had not time to get out of the house,
before he came in, and ordered me to sit down.
I obeyed, dreading what was coming.
He soon opened the subject, and informed the family who his author was;
they all denied the fact, and called upon me to do so, which I could not do.
The mother of the family asserted that she sat where
she saw and heard all that was said and done;
and added, that there was neither singing nor dancing, nor any unbecoming behavior.
This pierced me to the heart; she being a woman in years,
and sat on the rising seat in the front of the meeting,
often making the appearance of great tenderness.
But I was more shocked when she said,
"`God knew there was no such conduct there;`" that she was not afraid
to appeal to the Almighty before whom she expected to appear in judgment,
and it would be a dreadful thing for her to say so if it were not true; When this came,
my head fell, yet she pressed me to confirm what she had said, but I kept silent.
When we got away father remarked, that though I said nothing, I had satisfied him;
for when she called on God, my head and countenance fell,
by which he perceived I had not lost all my feelings, and wished me to keep to them.

After this, the overseers being in pursuit of the business, came on me,
for the young people (as I was told by one of the company), had all agreed to deny it,
which they did, or that they had ever told such a thing, and that it must be me,
and what I did it for they could not tell,
for the family had never given me any occasion of offense that they knew of.
This so filled the overseers, that I was severely treated by them.
They then demanded me to tell the truth.
That I dared not do, believing if I did, I must be disowned as a liar; but being pressed,
I answered them, they would never hear me say there was no dancing at that place,
and I did not think they would ever hear me say there was.
This they called equivocation,
and concluded to carry a complaint against me to the meeting.
I then informed them I must have my right, and see my accuser face to face,
and if they could,
bring any person who would say they had ever heard
me say either good or hurt of the family,
I would be accountable for either, and until that was done,
they must not carry a complaint against me.
This so started one of the overseers that he reflected on me severely;
the other was more moderate.
They proceeded not much further in the business, but gave it as their judgment,
that I had made, and spread that false report about that family.
This was generally believed through the Monthly Meeting,
insomuch that some of the elderly Friends who sat facing
the meeting refused to give me their hand.

Meanwhile these wicked young people would laugh and jeer me, to see it;
and had not the Lord helped me,
I believe to this day that my natural life must have gone,
for my flesh wasted away as though I had had a fit of sickness.
Here I think right to remark that every young member who was at the dance,
was disowned from society within five years,
and within seven years the aged woman was disowned for bearing false witness,
and her husband for abuse to another man.
When all this took place, I could be believed.
In these occurrences, a discerning eye may easily see the goodness of Divine justice;
for though my back-sliding merited the rod,
and the Lord permitted these objects of pity to pour out their fury upon me,
and at the same time marvelously to preserve me from utter ruin, and in His own time,
after humbling me enough, turned my captivity;
and inasmuch as my accusers regarded neither truth, justice nor mercy,
the Lord turned on them the reproach of their own conduct,
and they that dug the pit were buried therein.

Now, dear children, let these things be as way-marks to you,
and remember whatever is wrong cannot be right, for the Lord is against it;
and those who knowingly do wrong, are beaten with many stripes.
It is very unwise to buy trouble at so dear a rate;
while those who do right have the Lord for their counsellor
and safeguard in all the vicissitudes of time,
for while these are faithful to their Maker`'s will, none can overthrow them.
The deepest afflictions that can be endured or come on an innocent mind,
are not to be compared with the distress of a wounded
and guilty conscience before the Lord.

Having passed through the above described combat, and finding myself in the situation,
that I could not be acceptable company with the respectable and serious,
I was determined not to be company for the wicked, and the mean grades of mankind;
so I lived almost without society for more than two years,
and I do not remember of going for a visit to more than three houses in that time,
one of which I visited on account of a young woman, who afterwards became my wife;
and though my visits were not often, but regular,
I think I kept her company over a year before I broached the subject of my difficulty,
thinking she must have heard of it;
so I left that for her to do until I thought she would not; then I mentioned it.
She readily told me she heard of it all in good time,
and was pressingly advised to dismiss me, but whenever she sat down still,
and thought of it, it seemed always clear to her that the reports were false;
and the reason she had never mentioned it to me, was,
that she thought I had trouble enough without it.

My society continued to be mostly at my father`'s house.
I kept steady to meetings, often walking to and from them alone;
so I often had opportunity for serious thought.
One thing I may mention.
My father entertained many traveling Friends and others, and being much at home,
I was ready to wait on them; my conduct was strictly watched.
In the course of one year,
several of our leading members expressed their doubts of the reports concerning me.
I was not seen going in rude company to or from meetings,
and appeared to wait on Friends readily and with pleasure, and to love their company.
In this may be seen, when good conduct is pursued, with an honest mind,
that a blessing attends; it pleads its own cause.
Yet, I carried much anguish with me, night and day, asleep and awake.
Notwithstanding all these commotions, I often felt the Spirit of the Lord upon me,
and a necessity laid on me to come forward in the ministry,
but reasoned that it could not be a right call; for, if it was,
there would be a way open for it, and now there was not;
so I endeavored to appease my feelings as well as I could,
but the woe was on me wherever I went.

At length I covenanted,
that if the Lord would send a servant (who knew nothing
of me) to come and tell me that it was a right call,
I would give up to it.
I rested upon this awhile, until I began to conclude I should get clear of preaching,
and what a happy thing it would be,
for there was nothing in the line of religion that
I viewed with so much horror as a false ministry.
Thus, I rested about three months, when, to my great surprise,
David Sands came to our house,
and almost as soon as he entered the door he singled me out,
and not only told me that the call was right,
but took hold of the reasonings and difficulties I had passed through for years,
more correctly than I could myself.
Then, in this moving language, said, "`as sure as you know all this to be true,
so sure your exercise, your concern, and your call is right;
and if you will give up and be faithful, the Lord will be your strength, and your reward,
and will surely carry you through all your straits;
the path of the righteous ever was a tribulated one,
and you have many trials to pass through, but the Lord will be your leader,
and your rearward; and though the mountains surround you, they shall be removed;
the hills shall be laid low,
and the deep waters shall be divided for the soles of your feet;
for the mouth of the Lord has spoken it.`"
Here he closed.

My mind was much broken, my reasonings were all swallowed up;
I had no power to disbelieve.
My heart exclaimed, marvellous! marvellous! wonderful are Your dealings,
O Lord! with the children of men; and Your ways past finding out.
I then concluded, this is enough, I will give up and be faithful;
yet when the exercise came upon me in meetings, to appear in public testimony,
being exceedingly fearful that I should not move exactly right,
I sat waiting to be certain, until meeting broke, and then I was shocked in mind.
In this way I drooped along some time,
until I verily thought I could not speak a word if I tried,
and begged the Lord from day to day to take my life,
and let that be an acceptable sacrifice in room of the service.
At length the Lord showed me, in a clearness I have thought,
that was equal to Paul`'s vision, that He would take from me my life in Christ,
and all His mercies, and they should never return to me any more, and that, shortly,
if I did not give up and be faithful.

He had granted the request, and sign which I had asked,
and I had not kept covenant on my part, and now He would wait no longer upon me,
for my natural life was not an offering that was acceptable to Him.
It was brought to my remembrance what Samuel said to Saul;
and the Lord further showed me that it was not owing to His being a hard Master,
that I had so often come short, but to my reasoning with flesh and blood,
and that gave the enemy the advantage to deceive me;
and all this was the effect of not trusting in His word,
for He gave strength for the weak, and wisdom to the simple,
to all those who trusted in Him, and called on His name.
And now said the Lord by his Spirit; "`take your choice decidedly,
for you shall have no longer time to be waited upon; and if you refuse My word,
I will leave you to become a drunkard and a vagabond upon the earth;
and from My presence shall you go forth, and not live out half your days.`"

This clear manifestation so shocked the whole man, that my limbs not only shook,
but my knees, like Belteshazzar`'s were ready to smite together.
For three days and nights,
my exercise was such that sleep and appetite for food departed from me.
Now I had no confidence in myself,
and I dared not so readily promise or covenant as I formerly had done,
fearing I should fail as before.
When I looked over the past I trembled;
and when I looked forward to the woe that was pronounced against me,
it appeared dreadful.
But after passing through these alarming sensations,
my mind was favored with something of a calm,
and the language of my soul was to this effect; You know, O Lord, all things;
You know that I am nothing; I have neither strength nor confidence to do Your will,
for I have come short hitherto, and dared not promise; but if You, O Lord,
will give me strength, then will I try to serve You faithfully.
If You grant not this request, I must perish.
Soon after this petition it seemed as intelligible
to me as though I heard a vocal voice say,
I, the Lord, have heard your prayer, and grant your request; but keep your eye on Me,
and let your confidence be in Me alone; obey My words and it shall be well with you.
At this, my mind became quiet, everything appeared pleasant about me.
I now thought the worst was over.
This may show how apt poor man is to lay hold of the prospect of ease.
But what soon follows, will show how liable to be disappointed.
After this, I dared not admit reasoning thoughts into my mind,
but endeavored to keep it as quiet as possible.

When meeting day came, I attended.
In the early part, a few words came into my mind with such weight as caused me to tremble.
I soon felt the necessity to rise on my feet and deliver them.
I attended to the motion,
felt my mind relieved and the sweet returns of peace
in greater fullness than I had for a long time before.
Now, my children,
please to notice that as soon as I besought the Lord to enable me to do His will,
strength was given to overcome the apparent insurmountable difficulties; whereas,
all my promises in my own strength ever failed me.
He not only gives strength, but richly rewards every act of obedience.
But my coming forward in the ministry, again raised another storm,
and much pains were taken by my kindred to render me odious,
so that the Select members would stop me from preaching.
But they chose to be deliberate and take time for judgment,
though my opposers brought over three or four Elders to their purpose,
which made hard work, and much suffering for me during several years.

These continued to persecute me, as long as they could.
But my relatives failing in the first point, fell on me themselves.
Awhile after this, a traveling Friend was at our meeting.
Although this stranger was present, I felt constrained to deliver a sentence or two.
The stranger soon arose, took the same for his text, and kept it along through his sermon.
After meeting, he went to my grandfather`'s. I called in to see him,
and sat down behind the door, not having confidence to go forward and give him my hand.
Soon after this, one of my relatives came in and addressed me thus; "`well, +++_______+++,
if you think you can make as good a hand at preaching as you have done at blackguarding,
I would have you follow the business;`" and with a mock laugh, turned and went out.
I soon followed, and after getting out of sight, vented my grief in bitter weeping,
until I could weep no more.
Awhile after this I saw another of these relatives commit an unlawful act,
and advised him to refrain from such conduct, reasoning with him upon the consequences,
if pursued.
This not being kindly taken, he went home and told his father (my uncle) such a story,
that when I met with him, he broke upon me with great rage,
and ordered me to preach no more.

I met with many more similar occurrences, in the course of five years,
and mostly from my relatives, all of which are not necessary to mention.
My motive is to give you the opportunity of serious reflection,
and of beholding the difference between the effects of good and evil conduct;
for this relative`'s family (which consisted of ten
children) are all gone from society except two.
Some of them became hard drinkers,
and most of the family are now company for the lowest grades of people.
If this is the reward in this world, how ought people to shun every appearance of evil,
when that of the world to come is woeful, and without end.
May these truths be lasting warnings to you, my children, for on the other hand,
your grandfather`'s offspring (rising of seventy souls) are all members of society,
and a number of them truly religious, useful in society,
and respectable in the community; so that well doing has its reward in time,
enough to induce thereto, if there was no hereafter.
But when we think of the latter, what pleasure is there in this world,
that is worth hazarding eternal felicity for.
O! my dear children, seek true Wisdom,
and let the God of your fathers be the chosen lot of your inheritance;
so that it may be well with you in time, and happy with you in eternity.
