== Chapter II

Having visited Huldah Case occasionally, on account of marriage,
for the space of two years or more, she, during this period,
had an opportunity of hearing many unfavorable reports concerning me,
and much advice from those in the first ranks in society,
to refrain from keeping my company.
This, however, did not change her mind, until a ministering Friend,
belonging to a neighboring meeting came along, with whom she traveled several weeks,
who so pressingly advised her not to marry, that her mind became shaken.
She proposed dropping the subject.
I accepted the proposal, and we concluded it should be final.
I retired to my father`'s house, and kept as much from company as I could;
not visiting my former intended for about three months.
But, through it all, I felt desirous that she might do well.
During this last interval many rejoiced, thinking she had escaped me.
But afterward, meeting with her, she proposed some conversation on the subject,
and when opportunity offered,
informed me that she did not feel satisfied in dismissing the subject,
on the principle she did, and chose to remove all she had put in the way,
leaving me to act according to my own choice.
It was remarked, that in these three months, she had not opened her mouth in public,
in any meeting, until the day I met with her; though frequently appearing before,
acceptably, to all classes of Friends.
I was again brought under exercise,
for by this time I had appeared several times in public, which made a stir among many;
and viewing how acceptable she was with Friends,
I could not marvel at her being a little jostled by having so much said to her,
especially when she had seen me very much jostled several times.

But, after expressing my feelings to her, and leaving her free to consider all,
and act according to her own feelings,
we both believed that we felt a clear evidence that it was right for us to join in marriage,
and soon proceeded therein, in the fear of the Lord, whose counsel we had sought,
and whose directions we believed we had.
And when we came to solemnize our marriage, the meeting was large and solemn,
and we were enabled to go through our marriage ceremony,
in a deliberate and audible manner.
We each had a little testimony to bear in the meeting,
so that we were much confirmed that the Lord owned our proceedings,
which remains as a seal with us to this day,
and also as a staff to lean upon through many trying seasons.
Our marriage occasioned additional suffering for my wife.
Many judged she was undone, and were not content with neglecting her,
but used their endeavors to discourage and bear her down for several years.
I was indeed fearful they would effect their wishes,
yet through the tender mercy of Infinite Goodness, she was so graciously preserved,
that in the course of a number of years she became established,
and an acceptable minister.

However singular the penning of these circumstances may seem,
I believe it right to leave a record of these facts.
Having had almost forty years of experimental proof
in regard to the rightfulness of our marriage,
I am to this day confirmed that the Lord owned our proceedings,
notwithstanding we had to suffer much from the censure
and opposition of some who with an apparent zeal,
professed it was their duty.
Here I would leave a caution not to meddle with that which does not belong to us; for,
in the order of Divine Justice,
that which we administer to others will surely be turned on our own heads.
Bear in mind that the seat of judgment is filled with One in Heaven,
before whose throne angels and archangels bow,
and submissively wait for direction how to execute judgment.

Were the children of men careful so to do,
the innocent would not suffer oppression from their fellow creatures,
nor the devil be exalted in the seat of judgment above all that is called God,
for all false judgment glorifies him, and builds up his kingdom.
I feel the more concerned for you, my dear children, believing the Lord has shown me,
if you keep your ranks in righteousness,
that the most of you will have to stand in the front of the Lord`'s assemblies,
to turn the battle to the gate,
and may be often tried with a spirit that loves to get together and form bands,
and work one another up into a zeal; the sparks thereof is a fire the Lord abhors,
and will surely blast.
But as you keep your eye single to the Lord,
he will favor you to see through all such works of darkness,
and so to stand in your lots as to escape the snares which are many,
and fill up your measures in your generation, as shining lights in his hand.

We were married when I was about twenty years and six months old,
and the spring following commenced housekeeping,
being poorly provided with things necessary for farming,
which rendered my situation embarrassing.
I often felt my mind drawn to visit neighboring meetings,
and sometimes those more distant.
This gave some Friends who were desirous of my welfare, considerable uneasiness,
who reasoned on this wise:
that in my limited circumstances it could hardly be required of me,
to be so frequently from home, and neglect my temporal concerns;
and those who lightly esteemed me would take advantage of it,
and raise a prejudice against me as being a forward person,
and this might injure my services, and close my way among Friends.

These reasonings brought a great exercise of mind, and bore me down exceedingly,
until the Lord helped me, and enabled me to see with clearness,
that there was no room to scruple the manifestations with which He had favored me;
speaking thus intelligibly to my understanding: "`I, the Lord,
hold all the treasures of the creation in My hand, and I can blast all the endeavors,
contrivances and wisdom of man, and give bread to the hungry, and water to the needy.
When did you ever see the righteous forsaken or his seed begging bread?
Obey My voice, and not that of man, and your bread and your water shall be sure;
your family shall be fed of My bounty,
and taken better care of than you are able to take of them.`"
It was also shown me that as I was faithful in my gift,
Friends would be dipped into sympathy for me, and be brought into unity with me,
and be moved in their spirits to plead my cause; and that in this way,
the opposition against me would be overruled.

These openings in the light revived me,
and encouraged me to press forward with renewed confidence in the Lord.
And here I think right to acknowledge, with humble gratitude and thankful praises,
the tender mercies of the adorable Shepherd of Israel;
for in a few years it all came to pass which had been shown me.
Inquiry was made abroad why my ministry was not owned, and David Sands, a wise man,
an able minister, and truly a nursing father in the church,
took up the subject of my public appearances,
and laid it so home to my opposers that they gave up to my recommendation as a minister.
But as my poor wife gave up to stay much at home,
it was several years before her liberation was accomplished.
I have cause to acknowledge that the counsel of the
Lord is better than all the wisdom of man,
for in the former there is no disappointment, while man`'s wisdom fails.

There is an occurrence which I am not free to omit, which is this:
Nearly a year after I went to house-keeping,
I went on temporal business about twelve miles from home,
where I had no knowledge of the people.
As I came in sight of a house, I felt my mind arrested to stop and go in.
The impression increased with such weight that I was afraid to pass by.
So I alighted and went in.
As I entered the door, this portion of Scripture, powerfully ran through my mind:
"`Set your house in order, for you shall surely die and not live.`"
I was exceedingly struck with the language, and instead of uttering it, as I ought,
I sat down and reasoned, until a cloud came over my mind,
and concluded that I was too young and had not arrived to
experience enough to deliver such a solemn and awful message.
And how did I know but that it was all the work of the wicked one.
So I got up and left without delivering the message, but went away with a heavy heart.

Yet I pursued my business, and when returning the next day,
the same impression came over me, but I rode by and went home,
but lost my peace and testimony, which did not return, I think, for months.
In about a year after, passing the same road, when I came in sight of the house,
my former exercise came fresh before me, but I had no impression to stop.
Yet it took my thoughts so that I called at another house near by,
and enquired after the family,
when I was told that a great change had taken place within three months;
that the family had always been healthy, and there had been no death,
nor serious sickness among them before;
they had twelve children under the same roof and that within three
months the mother and seven of the children had died with a fever,
within a few weeks of each other.
I then asked if they were religious people; the answer was no, not at all.

By this time I had got a load, and was in a fit condition for Satan to buffet.
Notwithstanding I had passed through deep sufferings and sore chastenings,
for an omission of duty, I often thought if I could be favored with the return of peace,
I should be willing to perform any duty that might be required, if I had a sure evidence.
I greatly feared being deceived, or running without right authority,
and desired to know with certainty whether I had done wrong, in withholding as I did.
At length this language was presented to my mind:
As you did it not through willful disobedience, but through fear of being deceived,
there is forgiveness for you.
Soon after this my peace in good measure returned,
and I had appeared a number of times in public, to my own comfort,
and felt pretty well settled, until I heard the account of the deaths in that family.
And then the enemy poured in his floods upon me, in this way,
that now I knew for certainty, that I had disobeyed the word of the Lord,
that I had not warned the wicked, and they had died in their sins,
and their blood was required at my hands; that the idea I had of finding forgiveness,
was all imagination, so that I was almost driven to despair,
and had not the Lord in mercy rebuked the old serpent,
I should have sunk and given up the ghost.
Adored be the Lord`'s holy name, forevermore!

Here I can but remark that had I,
instead of entering into reasonings set down in the quiet, and shut the door of my mind,
and turned to the Lord with humble prayer, that He would preserve me from all delusion,
and give strength to do His will; no doubt I should have been enabled to do my duty,
enjoyed a tranquil and peaceful mind, and escaped the buffetings of Satan.
I should have saved loss of time, escaped abundance of sorrow and woe,
and have been abundance better able to fill up my duty,
both in a temporal and a religious line.
I have suffered almost every way on account of my remissness herein,
for when my mind was so much perplexed,
I was not able to manage my temporal affairs to good account.
May these portions of sorrowful experience be lessons of lasting instruction to my posterity.

I now return to the time of our commencing business,
which was the spring after our marriage.
My father persuaded me to take part of a farm, which I consented to,
though I proceeded against my own feelings;
for my mind was often turned towards a small meeting in the Little Nine Partners;
and this impression always appeared pleasant, and continued with me several years.
But when I mentioned the subject in my father`'s hearing he would speak discouragingly;
and having confidence in his judgment, I submitted, to the wounding of my feelings,
until the prospect left me.
But so it turned that when brought into great straits in my affairs,
that I had a chance to sell my farm well, and did so.
Then I wanted to take a look into the Little Nine Partners to see what I could do there,
but father endeavored to prevent it.
So after taking half of another farm I went on with fresh courage,
thinking I could now live.

But soon after it would come into my mind, now you must go into the new country to live.
And this followed me from month to month for years,
though I strove to put it out of my mind.
When I mentioned it, my wife appeared opposed and her connections firm against it;
likewise my parents spoke discouragingly, and I gave up the prospect,
thinking I could get a living there.
But things continued to work against me from time to time.
In the course of two years I lost much of my stock so that
I had to buy my meat instead of having some to sell.
This brought me into a great strait and much reasoning,
so that I called all in question in regard to my settling in a married state,
instead of seeking to the Lord to know why it was.
In this I missed the mark,
and got so far bewildered as to cause unnecessary
exercise in regard to my getting along.

In the spring of the year, after sustaining the aforementioned losses,
my house took fire and burned up.
Now we were stripped in a manner naked, including all that my wife brought,
with the exception of two beds and their covering; that is of things about the house,
which fire would consume, and my wife had a good setting out,
she being an able farmer`'s daughter.
After this father took us home for awhile.
Then after getting my business a little arranged,
and having but little property left to depend upon, finding myself some in debt,
my father and father-in-law seeing how I was situated joined and paid half of my debts.
From that time I had to manage for myself without any material help from any other quarter,
moving once or twice a year for several years, until I paid my debts,
and got something to help myself with.

The following circumstance, I think right to record,
for notwithstanding all my exercises and losses of property,
I was so far favored in the ministry,
that in about five years from my first appearance therein, I was recommended.
I think about this time I was reduced to my greatest
straits by losses except what went with my house.
And being anxious to live above board,
as I heard of some lands owned by a Friend in New York,
lying not far from a settlement of Friends, and that the owner wanted to sell them,
I went to see if I could get a chance to help myself; but I did not succeed.
I got into New York on first day, in time to attend the morning meeting.
I had a favored testimony to bear, and was more enlarged than at any previous time,
and was affectionately noticed by Friends after meeting.

Next day I left the city, to meet my father as I had agreed,
who was on business at West Chester.
But before I got off of York-Island it came upon me with great
weight to turn back into the city and attend their next meeting,
for the Lord was going to visit the city with a sore mortality,
and it was required of me to warn them thereof; and proclaim repentance in the city.
Under the weight of this exercise I struggled much, and reasoned for several hours;
not that I scrupled so much its being the word of the Lord, as I did, Jonah like,
for I feared that if it did not come speedily to pass,
I should be censured as a deceived man.
But after setting by the way side a long time,
it was opened to my mind as plain as though it had been printed,
"`it shall not come speedily, and they will receive your message coolly,
and you will be censured for it; but when it comes to pass,
they shall remember your warning,
and have to acknowledge that the Lord was your director,
and His word was truth in your mouth, for it shall surely come.
But if you disobey Me, I, the Lord,
will bring trouble on you that shall be much worse to bear.`"
When this appeared I concluded to go and see my father and return,
as there was plenty of time for it I thought.
It then came to me not to go to him, but return back;
but I thought father would think strange of it, as there was time enough to go and come.
Then it came into my mind thus: write to your father,
and that will be better than for you to go to him.
Yet I went to father;
I informed him of my prospect to return into the city to attend the Quarterly Meeting.

He strongly opposed it and invited me to go with him.
I complied with the invitation, though against my feelings,
and it proved an entire prevention of my getting to the Quarterly Meeting.
This threw me into great confusion.
I was in great distress nearly all the time I was in that part of the country;
and I never had an opportunity afterwards to relieve
my mind of the before-mentioned subject.
Another stepped in and took the crown.
They were warned, and death came.
This step of mine opened the door for the heaviest
sufferings I ever experienced from without.^
footnote:[It appears from his memoranda, that these sufferings continued several months,
in consequence of misconceptions and unfounded reports in regard to his movements,
and although his accusers did not succeed in carrying through their designs,
yet he was discouraged from exercising his gift in the ministry for a time.]

At length I was taken sick with vomiting which continued
without much intermission until I thought I was dying.
Under this apprehension I turned my attention to reflect how I was going;
it looked all dark, and I felt I was sinking into utter darkness,
which so alarmed me that the bed shook under me, and caused me to cry, Lord,
have mercy on me! what have I done that this must be my doom?
The query was quickly answered; "`you have obeyed man and not Me;
you have given up the testimony which I, the Lord, gave you to bear,
because man has commanded you to be silent when I did not;
neither did I command man to do such a thing.
Now, go to man and let him save you.`"
When this word came, I felt as if my breath was going from me, and I gave up;
but a calm came over my mind, and a clear, gentle voice, in this language,
saluted the ear of my soul: "`will you obey Me, if I spare you this once?`"
I quickly answered, "`yes, I will, O Lord,
if You command me to go through the fire or water.`"

My sickness ceased almost instantly.
I soon asked for food; after eating a little I soon got up and walked the house.
Next day, the seventh of the week, I did a pretty good day`'s work in the field,
which was a wonder to the neighbors who saw me the day before.
The day following I went to meeting,
in the early part of which I felt an opening in gospel authority,
and arose on my feet with these words:
"`The word preached does not profit unless it be mixed with
faith in the hearer,`" and bore a lengthy testimony,
much to the relief and sweet peace of my mind.
This caused an alarm, and the elders got together to consult what to do.
Two or three of them were for laying an absolute command upon me to keep silent,
but I was informed that a young elder asked the others
if they believed I had a gift in the ministry.
They answered, "`Yes;`" he replied, "`and we have owned it, We have recommended him; now,
I want you to answer one question.
Did you ever hear Joseph more in the clearness of gospel power than he was today?`"
they answered, "`no.`" Then he replied, "`it is a proof the Lord has not forsaken him,
and I shall have no hand in silencing him, for I am afraid to fight against God.`"
They replied, "`what shall we do?`"
he answered, "`set him at liberty;`" which was in a measure, soon done.
Still I had much to pass through for several years on account of jealousies and surmisings,
but the Lord preserved me through it all, blessed be His goodness and holy power.
During this time a minister from Long Island,
came to our Monthly Meeting and harshly censured it for
allowing me to visit meetings out of its limits.
This man in a few years so lost his standing as to get under dealings,
thereby losing his influence.
There were two others who followed me privately and publicly,
one of whom died in a few years,
having had his share of trouble on account of a difficulty
between himself and an elder of his own meeting,
which so shut up his way that he could never afterward get a certificate to travel.

The other got into a way of preaching, so much as to become burdensome to his friends,
whereby he lost much of their esteem.
It comes close to my feelings, dear children, to write these truths,
for I would prefer like Noah`'s sons,
to throw a garment over the nakedness of these ministers,
if I could have felt easy so to do.
But such is the evil that has been done in our Society in my day, by private whispering,
private influence, and these, under the appearance of great concern and zeal,
so as to deceive the simple, and set the sincere-hearted one against another,
and to make wounds that are not easily healed;
seeing that what we administer to others will be administered to us again.
I desire you may be so warned and instructed that
you may take care and never be drawn away,
or prejudiced against anyone, without first knowing both sides;
then let truth and justice be your standard, lest you fare like those poor men,
who were all three favored ministers, while they kept to the Master`'s leadings,
and only judged as He gave them judgment.

A criminal is entitled to just judgment, and it is enough to bear his own sins.
When the mind of one who means to be just,
is drawn away to give unjust judgement with zeal,
in this he glorifies the devil and builds up his kingdom.
This grieves the spirit of Christ and wounds the feelings of the sufferer,
and Christ will not reward with his blessing for such services.
When the superficial,
designing and evil-minded succeed and get the better class to be tools for them,
it strengthens and encourages them to repeat their conduct.
In this way, abundance of discord is promoted, the innocent, many of them,
deeply wounded, and the evil-minded encouraged to rush headlong,
until destruction opens her mouth and swallows them up.

Again, if angels have to wait until God gives them judgment,
and then for directions how to minister and administer it,
how careful ought poor finite creatures to be how
they execute judgment without divine direction.
After living through many and varied trials with an almost constant
scene of conflict and being permitted to get my mind into the quiet,
I entered into deep searching of heart to know the
cause of trouble so continually coming upon me.
The Lord in His own time gave me to see that if I had sought to Him for direction,
instead of listening to human contrivings,
I might have been settled in Little Nine Partners
for many years and been in my right place,
where the Lord`'s blessing would have been upon me;
but as I had neglected His pointings therein, He had withheld it.
Notwithstanding,
I had striven so long in this way that I had neither money or friends to help me,
it now appeared clear that if I would give up and
go into the new country I should be blessed.
It so settled on my mind that I told it to my wife,
and opened my prospect to my own and to her relations.
My keeping steadily to the prospect brought my wife under deep concern.
However,
it was not long before she told me that she saw so clearly there
was a good farm for us in the country (where we now live),
that she was willing to go with me, ever after remaining steady in the prospect,
and thinks we are on the very spot which was presented to her view.

When I opened the prospect to my friends for their consent,
they utterly denied me any liberty to move.
In this situation they kept me for more than two years, which did not jostle me,
feeling easy in having done all on my part without feeling hard towards them,
fully believing they would have to give it up.
The Lord had shown me that I had much to suffer for my own neglect,
so that I dared not murmur.
I saw that I had suffered the loss of property for not attending
to the pointings of true wisdom in settling;
also, that my neglecting to turn back when I was coming out of New York,
as the Lord required of me, was another great cause of my falling into trials.
It grieved me much to find so many of the honest-hearted among
us so unfavorably impressed that they were shy of my company,
and I went mourning on this account many days.

It also grieved me that I had given any occasion for the superficial to
triumph and to have advantage to deceive the better ranks among us,
but the adorable Shepherd of Israel was pleased to show
me that for my revolting it was just for me to suffer,
and that when I had suffered enough he would plead my cause,
and that the works of the ungodly who had spread
discord among brethren should turn on their own heads.
And whereas they had pretended a godly concern to hide their deceit,
those should be blasted in my day.
This I have seen come to pass very fully,
and the Lord showed me also that those of the better class
who judged by the sight of the eye and hearing of the ear,
and these, only on hearing one side, judged wrong;
that they should suffer for their own wrong,
while those who looked to him for counsel would be
sensible of the truth in the life of it,
for that salutes its own.
All this have I experienced and seen come to pass.
Let these remarks, my children, be way-marks,
and let other`'s harms be lessons of improvement to you.
This opening much relieved my mind and raised my drooping spirits,
and I took renewed courage to try to do as well as I could.

I mentioned previously of Friends holding me back from moving.
It was, I think, a year before I got leave to purchase lands in the new country,
and two years before I got leave to move,
and yet another year before we got certificates,
although I had settled all my outward affairs.
The year we were detained from moving proved well for my wife,
as she went to reside at her father`'s in the verge of Little Nine Partners meeting,
where she grew in the ministry and in the life, as well as in largeness of testimony,
so that soon after moving into this country she was
approved as a minister and continues in good esteem.

After we settled in this country, things turned otherwise with us;
we prospered remarkably and soon got into a comfortable way of living,
having a good possession, which we yet enjoy,
having the pleasure of entertaining many friends.
I do not speak of our friends discouraging us from moving as censuring them,
for the misfortunes I had met with,
caused them to think I should never be able to provide for my family.
But the God of all tender mercies helped to bear up our minds,
and carried us through all the trials He permitted to come upon us,
and we have lived to see to our great comfort, seven Preparative Meetings,
three Monthly Meetings, and a Quarterly Meeting settled in this country.
Whereas, when I first came here, there were but three families of Friends,
they being settled wide apart.

After a number of Friends had moved into these parts I felt much
concerned that Friends should keep together in the Truth,
and live up to their principles; on which account I labored much.
Many of them came with little thought, further than to obtain property,
and it seemed hard to turn their attention to any other concern; so much so,
that when some of us met together they opposed us,
and when we wanted to request for a meeting, they kept us back for some time,
pleading that we lived too much scattered--that when
the country was cleared up and the roads made good,
and Friends got fore-handed then it was time enough,
for then we could attend meetings comfortably and entertain our friends.
But not thinking these reasons sufficient, we determined, after awhile,
to forward a request,
and when they saw they could not keep us back any longer they put their hands to it.
We soon obtained a meeting, and in a few years we had an established Preparative Meeting.

During this interval I had to make several visits to the meetings
and neighborhoods in the compass of which I was now settled.
This, I have since seen, was ordered in the wisdom of Providence, in a two fold sense.
Firstly, that now my labors were mostly to be in this and the adjoining country,
and this could not be without the unity of my Friends,
and generally so of the Monthly Meeting.
Secondly, as some from other parts,
took pains to send the reports that had been spread about me,
into all these northern parts, especially among the select members,
with this charge--if I came there, to take good care of me, for I was a strong-headed,
forward man, and they feared I would do much hurt.
This so affected many, that they appeared cool towards me,
which made hard work for some time.

The first of those visits was pretty soon after I got my family settled in this country.
I felt my mind weightily arrested to attend Easton Monthly Meeting,
with such clearness that I fully believed it my duty.
Accordingly I went.
I arrived there when nearly dark in the evening.
Next day I attended the Monthly Meeting, which was composed of Easton, Saratoga,
Queensbury, and White Creek Preparative Meetings; consequently it was large,
most of the principal members being in attendance.
As I entered the meetinghouse these thoughts came into my mind "`How ought those
who sit in the front of the meeting so to conduct as to adorn the seat of Moses,
as judges and lights in Israel?`"
It rested on me until I was made sensible it was my duty to leave it among them,
and feeling the lively authority of Truth, I arose with these words: "`Friends,
it is often the case when I come into the meetinghouse
and cast my eyes towards the gallery,
that the thought comes over me,
how ought those who sit there in Moses`' seat to adorn the place,
as pillars in the church, to be shining examples to the people?
Friends! our neighbors have a right to look for it--our
children have a right to call for it.
The consideration of this subject many times causes
my heart to tremble when I look towards the gallery.
O,
Friends! were this class what they ought to be how they
would hold up the standard of light and life to the people,
and the language of encouragement to the assemblies of the Lord.
Then would He bless His heritage, and his standard-bearers with wisdom and sound judgment.
But, Friends,
it appears to me that there are among you those who have mounted Moses`' seat,
who sit in your galleries,
whom the Lord has never placed there--whose conduct has been a reproach.`"

Then I was led to show how they injured the cause of Truth,
and grieved their honest brethren,
to whose hearts the testimony of Truth was more dear than their natural lives,
and how they caused the seeking enquirer after the ways of Zion to stumble,
and give an advantage for gain-sayers to reproach
and the daughters of the uncircumcised to triumph.
Then I was led to call upon the Joshuas to arise,
and cleanse the camp and remove the accursed thing out of the host,
that Israel might journey forward.
Then I felt my mind turned to other subjects.

After meeting, my aged aunt, Anna Hoag, came to me, with tears running down her cheeks,
took me by the hand with these words, "`Dear Joseph, keep to your Master,
and He will keep you, and you will not be destroyed.`"
Friends then generally looked upon and spoke to me pleasantly.
I went to my uncle`'s and my aunt took a seat by me, and said, "`Joseph, I must tell you,
for we know you could not have had any outward knowledge,
as you have not been among us since the occurrence took place, (which was true),
there is a Friend in White Creek meeting, who sits on the high seat, at the right hand,
and has quarrelled with his neighbors about their land lines,
and carried it to such a length, that he has got the neighborhood,
both in Society and out, in an uproar;
and that Friends were then laboring with him to get the business settled;`" then said,
"`Joseph, if you keep your place, this day`'s labor will make your way among us,
let them say what they will.`"

Before I left the place, (I think it was),
I was told there was another Friend living at Queensbury,
who was a man in a good deal of business, and sat on the front seat, at the right hand.
He had so much jangling in doing business,
that Friends had been laboring for some time to get his affairs settled,
and one of his neighbors told him in their presence,
that it "`would have been much for the credit of the Quakers,
and the peace of the neighborhood, if he had been put under ground years ago.`"
Both these Friends sat on the second rising seat, and nearly before me,
at the Monthly Meeting.
I soon returned home, taking one meeting in my way, having great peace of mind.
I had abundantly to marvel in deep humiliation,
at the wonderful goodness of the Lord in thus making a way for me,
where I believe blind zeal had endeavored to close it.

Sometime after this, I went again to Monthly Meeting at Easton,
and having it on my mind to appoint some meetings on my return home,
I informed the Meeting of my prospect, and had its approbation, expecting after meeting,
to pursue it.
But as soon as I came out of meeting, it seemed to shut down over my mind, for some hours.
An old experienced Minister remarked to me, after meeting,
(who had approved of my prospect), that while the subject was before the Meeting,
the remark of John Churchman came into his mind, when,
in England a large prospect opened towards other people, and a language followed,
that there was need of his labors in our Society; or nearly to this amount.
He said, he had not mentioned this, with the intention to discourage me;
but I could not see anything in it for several hours.
At length I dismissed part of my company, and my mind was turned towards White Creek,
entirely another way.
My aged uncle and aunt went with me, and we lay by during seventh day,
with my mind much depressed and under a cloud, and thick darkness;
so that I was not capable of being sociable with my friends.

We attended the first-day meeting there,
in the course of which I was favored with a pretty lively opening;
but as soon as I came out of the house, distress came over me.
I felt almost amazed, so that I could not tell where to go, or what to think of myself.
My aunt came to me, and invited me to go and see a woman who had been long sick.
I went with her, but had not been long in the house before it was opened to my mind,
that the sick woman was in despair, wearing out in a decline,
under the affliction of all the terrifying ideas
that the human mind was capable of realizing.
I was led to state her condition to her, and how she came into it;
and that if she labored to get into the quiet, and then turned her attention to the Lord,
and pour forth to Him her prayers,
they would be heard and she would experience reconciliation with her God,
and her peace to be made, witnessing the seals of redeeming love,
before she went from here, to be seen of men no more.
Before we left, she called my aunt to her,
and told her I had described her thoughts and feelings, better than she could herself,
and that was an evidence to her, that I was right, and now she had hope.
I was informed afterwards, by her sister who nursed her, that she soon became very quiet,
and sometime before she died, she expressed, that she had become reconciled to her Maker,
and was willing to die; feeling that peace and love, which was an evidence to her,
that her sins were forgiven, and she should be happy.
She departed easy, and quiet.

We returned to our lodgings; I felt easy and quiet,
and thought I saw why I had been plunged into such
extreme sufferings the afternoon before;
but still could see no way to move, or what step to take next,
until near nine o`'clock next morning, when, sitting down with the family,
it opened clearly to me I must go to East Hoosick next,
a place I most dreaded of any I knew of in those parts.
Now, the time had come, that I must go.
I released the company, except my aged uncle and aunt who went with me.
It was a good day`'s ride, so that we got in late.
My mind was depressed with a heavy-hearted feeling all day.
Next morning, aunt proposed to go to Isaac Kelley`'s, which I felt free to do;
but soon after I mounted my horse, it came into my mind,
"`whatsoever house or city you enter, stay there till you go out.`"
I told it to my aunt, she advised me to keep to my own feelings.
As soon as we entered Isaac`'s house, and I had taken him by the hand,
I asked him if he was willing to let me have a room, where I might be,
and no one know that I was there.
He led me into another room; it was well furnished for my accommodation.
There I stayed until near sunset, then walked out on a hill, viewed the place and returned.

I slept but little that night, for my distress kept with me, and rather increased,
so that in the morning I walked the house pretty much, until one hour before meeting.
I then laid down and dropped into a sweet sleep.
When I awoke, rising up, I saw the people gathering into the meetinghouse.
While looking at them I felt as though I should faint, and said to myself,
"`I cannot go into that house, for I have not strength to get there;`" and I sat down.
I had not sat long, before a language ran through me, "`go! and I will go with you,
and be your strength.`"
I rose on my feet, and went to meeting feeling pretty well composed.
I soon found I had been mistaken with regard to them as I had for years viewed them,
very much refined indeed, for they were the most reserved in conduct,
of any Friends I ever saw; strictly uniform in their dress, and plain to a nicety.
Their select members were so particular,
that many of our little preachers hardly dared to speak before them.
But when I came to sit with them, I was almost amazed for one hour; for,
instead of finding all things in perfection, I could think of but little else,
than when the sons of God met together, Satan came also among them.
I had to take this subject up,
and show them that it was reasonable to believe that Job was one of those Sons of God,
and that Satan meeting with them, was with an intent to make an inroad among them;
and when he got liberty to fall upon the best man among them,
he soon effected it by raising a false zeal in Job`'s friends,
which set them accusing Job of that of which he knew he was not guilty;
he therefore knew their zeal was false, and did not come from God.

This made Job turn their charges upon their own heads, until the controversy ran so high,
that they charged each other with falsehood, violence,
hypocrisy and speaking wickedly for God;
and while they strove to mend each other`'s faults and neglected their own,
they made a bad matter worse.
I continued, "`now, Friends,
look and see what an example these peculiar friends of Job set; these great, wise,
and religious men, all believing in the one principle, and the true God.`"
I was led to open all parts of the subject and apply them;
feeling Gospel authority to arise in my mind, all fear of man was taken away,
and Divine Power raised into dominion.
I was led to press it on each of them, to mend their own faults,
as they were the only ones who could do it,
and then there would be nothing to differ about,
for that ended the controversy between Job and his friends.
When this was done, they could meet together in unity, as before.
Then I addressed them thus; "`Friends, look to these things, why are my feelings thus?
is there not a cause?
And why should those who have been anointed with royal oil,
and have borne the shield of God in the day of battle,
whose sword returned not empty from the slaughter--why should it
be said of you they have vilely fallen on the mountains of Gilboa,
as though the shield had not been anointed with oil?
Publish it not in Gath, tell it not in the streets of Askelon,
lest the Philistines rejoice, and the daughters of the uncircumcised triumph.`"

With these words, I think I sat down, finding my mind well relieved,
and feeling as if I was in a new world.
After meeting,
several Friends came to the house where I stopped and showed a disposition for conversation,
but I felt cautious, believing it was best for me to keep pretty quiet,
though I felt a freedom to go to some of their houses.
But all kept still, except asking me a few questions, which I briefly answered.
Next morning, as soon as I awoke, it came into my mind, "`Get out as you came in.`"
I mused a little upon it, and a second language ran through my mind,
"`you came in here knowing nothing of what is among them; now,
get out knowing nothing; this is best for you.`"
I got directly up, put on my clothes, got some food as soon as I could,
took leave of my Friends, mounted my horse, and went direct home,
leaving my uncle and aunt there, and heard no more from them for several months.
Here ended my prospect, that the Monthly Meeting had approbated;
it has never returned to me since.
I have had to remember the old Friend`'s remark,
having found more need of my labors at that time, among Friends than other people.

Several months after this, I fell in company with aunt again.
She asked me if I had heard from Hoosick since I was there.
I let her know I had not.
She remarked, she would now let me know how it was, as she thought I now could bear it,
and that she believed it was well I came away when I did; for, had I stayed,
and heard matters talked up as she did,
she thought likely it would have been too much for me to bear.
It was wonderful how I was led,
and that the parties on all hands were exceedingly broken down under it,
and that she and uncle stayed and labored with them until they brought them to a settlement,
and an agreement to drop all matters past, and be at peace one with another.
She informed, that the contention began among the Select members,
and had divided the whole Monthly Meeting, and spread far among other people.
She then observed, "`so you may see your sufferings were not for nothing,
and now your way is clear with Friends there.`"

I made a number of little visits in the compass of my own quarter,
in the course of a year or two, generally to the satisfaction of Friends and others,
and much to the satisfaction of my own mind.
I was often brought to admire the wonderful goodness of God, in supporting my mind,
and carrying me through, where there seemed to be no way.
Blessed be His adorable goodness.
After a few years, I felt my mind drawn to perform a religious visit to my native place,
and parts adjacent.
I laid this prospect before the Monthly Meeting,
and had its full unity, but having lost my minutes of that journey,
I can leave no more than occurs clearly to my memory.

I set out in the beginning of winter, with Reuben Peckham for my companion.
After taking a few meetings about Easton, we rode to Coeyman`'s Patent.
On our way, we fell in with a little preacher by the name of Rowland Robinson,
who kept our company for several weeks.
Before we got to our quarters at night at Coeyman`'s, we passed a house,
and saw a plain man at the door.
The sight of him struck my mind with a disagreeable feeling, and Rowland`'s as much so.
I concluded he was not what he appeared to be, for he appeared to be a plain Friend.
We passed on nearly a mile, and put up at Jonathan Souls.
Not feeling easy about the man we had passed, we enquired after him,
and were informed that he was a solid Friend,
who had been received a member not a great while since.
This increased our exercise, so next morning we walked back, and made the family a visit,
not feeling easy to omit it.

Pretty soon Rowland addressed the widow and fatherless,
and for awhile I could not see what he was at,
though there was an aged widow in the family and we knew it not.
But he did not apply his communication there;
which caused a serious exercise to come over my mind how we should come out;
and while thus musing, it came upon me with weight, and an awful feeling,
in this language: "`When a man neglects his wife, withdraws his affections from her,
and does not provide for her and her children,
then his wife becomes a widow and the children fatherless, while he is yet in the body;
and when this is done with the view of religion, believing it to be duty,
it was the temptation of Satan, and the works of darkness,
which God would blast in the end.`"
As soon as Rowland stopped speaking, I was ready and the words went through me,
I thought, like a flaming sword, and caused the man to tremble.

Then I was led to show how people got into such darkness,
and what they had to take heed to, to come out of it;
as also what would be their reasonings to uphold such wrong principles,
and with what confidence,
and hardness of heart it would oppose all that was right or of the Lord.
I closed my service to the forsaken and afflicted, directing to keep in the patience,
with the mind resigned to the Providence of God; casting all care,
and placing all confidence in Him; then every tribulation would be sanctified to us,
and every bitter cup would be sweetened in the end, with the reward of peace.
When we concluded the visit, the woman and wife took me by the hand,
with tears on her face, and exclaimed, "`I am a widow, and no widow neither.`"
I turned and took the man by the hand, he looked me in the face,
with a fiery countenance, and said "`I am dead, and burnt up,
there is none of the old corrupt nature in me, it is all consumed;
I have no power to gratify the flesh.`"
I let him know that the spirit that separated man and wife, was the devil,
and under the curse, and so parted.
We told Friends, how we found them, and they went forward, searched into the matter,
and found things every way as they appeared to us,
and that the man had been in full communion with the ranting Shakers, secretly,
for several months, for which he was disowned.
From here, we passed to Hudson, and then down the west side of the river,
taking all the meetings down, as far as Friends then lived,
besides having a number of meetings among other people, in all of which,
the merciful Shepherd of Israel was pleased to open and direct our way,
and favor with His life-giving presence,
so that our visit was much more acceptable among Friends, than I expected,
and abundantly so among other people.

There was one occurrence in this part of my journey I do not feel easy to omit.
When at Cokeat, a meeting consisting mostly of Friends,
who joined Society by convincement; after I had, as I thought,
cleared my mind in a pretty large mixed gathering and had sat down,
it soon opened in my mind in such clearness that there was no room to doubt,
that I must communicate what was shown me.
I stood up with these words, "`I sat down expecting I had cleared my mind,
but since taking my seat it has appeared to me that there are those in this meeting,
who in days past were convinced of the Truth and
covenanted with the Lord that they would be His,
and serve Him;
and when this was the case they walked together in the unity of the Spirit,
and were each other`'s joy in the Lord;
but now they had got settled down in the love of the world,
and were at variance about Interest matters,
so as to censure each other with fraud and falsehoods, and this publicly,
before neighbors, so as to be a stumbling block and a proverb in their mouths.
Friends,
this will not do--if you do not stop and return to your first love
the Lord will take the crown from your heads and put it on the
heads of them who will be more righteous than you are.`"
I delivered considerable more that I do not remember.

After meeting we stopped near by to take dinner, and while there,
I was called into another room.
There lay a man on the bed weeping, who confessed that he and his cousin,
who were both at meeting, were guilty,
for they had been at variance sometime about Interest;
and only the day before they were invited with a number more to help a neighbor,
and there they got to talking on the subject,
got into a quarrel and gave each other the lie, and threatened to complain of,
and turn each other out of the meeting;
and that their neighbors who heard them quarrel were at meeting today,
and he could not live so, but must have it settled, and wanted me to assist.
I referred it to other Friends, they were called in,
and the business was settled on the spot; but I was told his cousin was very obstinate.
At length the penitent told the other he would give up all his demands,
though he suffered loss;
the other concluded if he would settle so he would settle with him,
and so the matter ended with them.
I was at that meeting a number of years after,
and found the penitent man a substantial Friend,
and one of the main pillars of that meeting; the stubborn one had gone out, was disowned,
and had become a poor creature,
doubtless reaping the blast of his departing from his first-love.
I was informed these two were very intimate when they came among Friends.

After getting through these parts, we crossed the river and visited Oswego, Apoquage,
and all the Oblong meetings, and having cleared my mind in these parts,
witnessing the arm of Israel`'s Shepherd to strengthen and
carry me through many deep wadings and painful exercises,
and to give strength to clear my mind so as to feel peace and solid satisfaction.
We then proceeded to Nine Partners, my native place.
Here a field of labor opened, not only among Friends, but others;
and the Lord favored me from day to day with life and gospel authority in my labors.
This gladdened the heart of many of my friends who feared
how it would turn with me when I moved from them;
it was a time of comfort to us all.
From here we went to Hudson, crossed the river,
and had a number of meetings among other people,
and had extensive labor being much enlarged while there.
When I had cleared my mind in these parts, I felt at liberty to return home,
after being absent, (I think,) more than three months,
and found my family and friends well and glad to see me return.

The next visit of any considerable length of time that I find any
account of was pretty much through the old part of our Yearly Meeting;
but the date is lost.
I remember this was a very exercising prospect to me,
for I should have to visit all the meetings where I had
my former difficulties and had suffered so much,
that I thought I was willing to undergo anything that could be endured for peace sake.
I laid my concern before Friends, had their unity,
and proceeded on my journey in the early part of the winter, having Stephen Rogers,
of Danby, an elderly Friend, for companion.
He had large acquaintance through the Yearly Meeting, was in good standing,
and was of good use to me in this journey.
We visited, I think,
nearly all the meetings on the east side of the Hudson river as we went,
till we arrived at New York, where we made a stop for several days.
Here, I may remark,
that we passed along pretty smoothly until we got
into the compass of Purchase Monthly Meeting,
and though no outward opposition appeared,
yet from meeting to meeting it seemed like standing in front of castle walls and bulwarks.
But it was marvellous to me that the Holy Shepherd of Israel so harnessed my mind with
strength and fortitude that all the castles could not stop the current of Gospel life;
my mind being led into the states of meetings so clearly
that it was acknowledged by Friends to my companion,
from place to place, that they did not expect it from me;
and they believed it was right I was there in this manner.
The adorable goodness of the Almighty, sustained and carried me through;
blessed be His name.

I now return to where I digressed from.
After staying several days at New York, and having some close service there,
our minds feeling clear, we proceeded to Flushing, and had a pretty full meeting there;
and the day following we were at Cow Neck.
Here my companion had to come to plain work,
as he sometimes had a little testimony to bear.
I had to follow on and bear a testimony against covetousness,
and neighbors injuring each other in interest or credit;
showing that it promoted hardness between families, spread discord in Society,
and did abundance of hurt.
I showed them how different this spirit was from
that disposition which endured all things,
with meekness and patience, for the testimony of Jesus, and a good conscience.
Here we met with our worthy Friend, Gideon Seaman, who took us home with him.
The next day we were at Matinicock Meeting, and the day following,
had an appointed meeting at Westbury, where I had to warn them against a worldly spirit.
Next we went to a place called Half Hollow Hills,
a little meeting that had much run down by disunity among themselves.
This was a laborious, suffering time with us.
The next was Bethpage, where we had a pretty good meeting; which ended to satisfaction.

From there we went to Jericho; notice having been given, there was a large gathering.
I expected a fine meeting, where there were so many good folks,
but was sadly disappointed,
for my mind was dipped into a sense that many in
that place had attained to the knowledge of the Truth,
so as to know it, when they felt it,
but were not enough concerned to live in the life and spirit of it.
They had settled on their beds of ease,
and were disposed to stretch on their couches of ivory.
I had to come to plain work, and sound an alarm among them.
I was told after meeting, by a Minister, who was there, that a little before,
he had to deliver the same testimony, almost word for word, at that place.
So I found I was not alone.

We returned to Gideon Seaman`'s to lodge, in company with Fry and Anna Willis,
who had been with us for several days.
In the evening, several Friends came in to see us, we being about to depart next day.
While together, one Friend remarked, they were all glad of my visit,
and believed it was right; that I might return not only with peace of mind,
but with the satisfaction that I was well accepted by Friends.
This gave great relief to my mind,
for it gave reason to hope that the old prejudices were now removed.
The next day (I think) we set forward for New York,
in order to reach their Monthly Meeting, and got in timely.
Here my companion received a letter, informing that his son,
with whom he left his business, was taken deranged,
yet he kept with me until we reached Amawalk; he then went home,
and I crossed the Hudson river, where I spent the remaining part of the winter,
travelling without any steady companion.
I continued diligent and seldom missed attending a meeting a day, and sometimes two,
until I got to Coeyman`'s, where I was taken sick with a severe cold,
occasioned by hard traveling and much exposure, which stopped me for several days.
After my recovery, I went pretty direct home, found my family well,
to my great comfort and their joy, after being absent, I think, over five months.

I had thought to omit the following event, but an uneasy feeling pervading my mind,
therefore I record it.
Near the close of the above stated visit while at Smith`'s Clove meeting,
the last I expected to attend in this vicinity, except one in course next day,
near the close of the meeting, it came over my mind with weight,
to appoint three more meetings before I left.
I exclaimed in my mind, "`I cannot for I have been five months from home,
spring`'s work is coming on, and I am in low circumstances, and must go home.`"
So I broke up the meeting;
a Friend came to me at the door and expressed that his feelings
were such that he wanted me to have three more meetings,
and named the places.
I replied short, I have set my face homeward,
I do not intend to turn to the right or left feeling determined that home I would go.
I had not rode far before my horse on a brisk trot, fell through the frost;
he threw me over his head with force; I dropped on my head.
A Friend riding behind said, he heard my neck snap like a dry stick,
and that I arose on my feet with a smile, but fell back on the ground.

I knew nothing until I found myself stayed up, sitting on the ground,
feeling as though I had awoke out of sleep;
but soon felt such sharp pain in my neck and head that it seemed almost insupportable.
I was taken by short stages to the Friend`'s house,
where the meeting was held that I expected to attend, which I think was the next day.
I kept my bed mostly, until meeting time next day, my neck being much swollen,
with a hard ring round it, which felt more like a bone than flesh,
and looked nearly black, so that my case was thought dangerous.
But through Divine mercy,
I had a number of hours for reflection in which my feelings were solemn.
When meeting time came, I was placed on a bed in the room where the meeting was held,
it being my desire.
In the early part of the meeting a voice spoke to
me as intelligibly as ever I heard a vocal sound,
saying; "`if you will go back and have the three meetings, I, the Lord,
who have wounded you, and stopped you in your career,
will enable to perform all I require of you.
And this shall be an evidence to you that I, the Lord, speak to you;
you shall be enabled to bear a testimony for me in this meeting.`"
Under the impressions of this voice my mind was brought into a calm,
and it appeared to my view how it was and why it was that I was brought into this situation;
and also that it was offensive to the Almighty and dangerous for man,
who knew the Lord`'s will, stubbornly to disobey.
My mind was seriously humbled, my spirit contrite before the Lord,
and I was glad to feel the smile of forgiving mercy once more,
being made willing to give up all to his disposal.
Towards the close of the meeting, with the help of my companion,
unexpected to my friends, I rose on my feet, and was enabled, I believe,
to bear an acceptable testimony to my Friends,
and felt great peace of mind for the obedience, my pains also were much mitigated.

At the close of the meeting I called a Friend to me,
agreeably to the opening of Light on my mind, and desired him to go to the nearest place,
and give notice of a meeting for the next day,
and see that word was sent to the other two places,
one in the day and the other in the evening.
He answered me; "`I have not faith to believe you can possibly do it.`"
I answered "`I have faith enough for both of us; the meetings must be appointed.`"
He went, and did accordingly.
Next day I rode (I think), twelve miles, reached the place in good season,
and had a satisfactory meeting.
Next day and evening, attended the other two, much to the relief of my mind;
but had to endure considerable pain, all which I bore with cheerfulness,
seeing I brought it on myself I much desire that when my children read these
lines they may pause a little and behold the tender mercies of Jehovah,
when under the chastening rod, to spare life even when in the jaws of death;
and when rightly sought unto, equally tender to forgive, heal,
and give ability to do all He requires of us;
richly rewarding the obedient with heavenly peace for doing their duty,
which they could not do without this holy help.
Adored forever be His holy name! for He is worthy thereof.
Dear children,
let the first be a warning and the latter an encouragement to faithfulness of duty,
through your generation.
