== Chapter IV

After getting recruited, and my spirits revived, we appointed a meeting in the evening,
at Friends`' meetinghouse, in Dartmouth.
It was small, but it seemed pleasant to be with Friends again, after a long absence.
The evening following, we had a meeting in Halifax, which proved a good entry into harbor.
At the close of this meeting,
it sprang into my mind to express my satisfaction
with their solid deportment and good attention,
and that it was encouraging to me, as it showed regard for religion,
and that I did not feel clear of the place, and if it were agreeable to them,
I wanted to meet with them again, on such a day, at the fourth hour in the afternoon.
They answered, it would be agreeable.
I then requested them respectfully to inform their neighbors,
that their company would be grateful to me.
After we came away, Friends told me they thought I would be disappointed,
for there had been several Friends from England, and the States, who had made trial,
and could never get a much larger meeting than we had.
I felt easy in what I had done.

We returned to Dartmouth; from +++_______+++ to +++_______+++ of 10th month,
we stayed with Friends there, and had no meeting.
The +++_______+++ we attended our appointed meeting at Halifax,
to which it was thought that more than two hundred people came,
whose deportment was becoming Christians.
It was a favored time.
The people were much tendered.
On my sitting down, soon after delivering a testimony,
it came weightily on my mind to appoint another meeting in the city.
I said to myself; it cannot be, for this house is crowded full,
and there is nowhere to meet.
While I was musing, a genteel appearing man stood up and said,
"`Do you want another meeting in the city?
My mind is impressed that you do; If you do, you can have the Methodist meetinghouse.
It is the largest in the city, and best seated; I own two-thirds of it,
and you are welcome to it.
Appoint your meeting at 5 o`'clock in the afternoon,
when the laboring class will be at liberty, and you will have a great meeting.`"

I turned to my companion, and asked him what he thought of it.
He answered, "`It was on my mind with weight, to have another meeting,
but I could not see how or where.
It is best to accept the offer.`"
I stood up and let the people know, we should be at the house at the hour,
to a minute if we could,
and that I wished them respectfully to inform their
neighbors that it would be cordial to my feelings,
to have the company of all that were willing to meet with us.
The meeting then closed, and we went to the Friend`'s house who lived near.
I soon asked the Friend if there was not a man living in the north part of the city,
who would let us have a meeting at his house.
He answered, "`Yes,`" we sent a messenger with orders, if the way was clear,
to make the appointment and go forward and notify the people.
We attended and had a comfortable meeting;
the people`'s minds appeared open to receive the doctrines of Truth.
At the close we informed them of the other appointment, and returned to Dartmouth.
Not feeling clear, I proposed another meeting there; and general notice being given,
it was large;
here way opened and utterance was given to clear my mind so as to feel fully relieved.

The +++_______+++, according to appointment, we attended at the Methodist house in Halifax.
When we came to the place, we found a large house; and after we entered the door,
we had to stop often, for the people to make way for us to get to our seats.
When we came there, there was no place but the pulpit for us.
We walked up; I looked around and saw the house crowded from one end to the other,
with people, and a great body standing outside; I, there in a lofty pulpit,
seated on a satin cushion, a thought came into my mind,
if my friends at home knew where I was, their hearts would tremble for me.
I sank down and wished I had not made the appointment,
and concluded I could not open my mouth.
There I sat under such depression of spirit and distress of mind
that I could hardly keep from trembling for some time.
My companion kept his faith well, which was a strength to me; but at length,
through the mercy of a gracious Redeemer, all this was taken off;
they appeared to me to be no more than children, and all about me no more than dust.

Feeling the Word of Life to arise in my mind, with strength and Gospel authority,
I was preparing to rise, when a language saluted me, "`see that you keep calm,
and speak deliberately.`"
Under the impression, I rose on my feet, and though there was considerable whispering,
over the meeting, the first sentence spoken stilled them so that my companion remarked,
the like he never saw;
he took notice and did not remember that he saw a
hand lifted or a foot moved for an hour and a half;
the power of the Lord came mightily over the meeting.
Truth reigned beyond what I had ever experienced before;
Gospel Truths flowed as the gentle waters, dropped as the rain,
and distilled as the latter rain upon the people.
The service closed with thanksgiving to the Most High God, for favors past,
and humble prayer for the continuation of them, and a blessing on the favor of the day.
In going out of the house,
I felt a caution to take care not to be drawn away by the affections of the people.
I was favored to take the hint,
and got away as quick as I could to the Friend`'s house near by, away from all noise,
and felt joy and peace in so doing.
Next morning, after having a sweet refreshing night`'s sleep,
I awoke feeling clear of those parts.
I told my companion we would now leave; while all was well we would leave it well.

We took stage, and in three days we crossed over the country, to the bay side,
and came to Samuel Moore`'s, at whose house a Friends`' meeting was held, on first days,
once in two weeks.
The +++_______+++ and +++_______+++ we lay by and wrote home.
11th and 1st of the week, we had a large, favored meeting at Samuel Moore`'s;
the minds of the people were broken into tenderness,
several of them to the shedding of tears plentifully.
In the afternoon we had a meeting on the mountain,
among a poor people who seemed glad of the visit,
and much tendered under the testimony I had to bear among them,
yet there did not appear to be much religious concern with any of them.
I felt peace in discharging my duty.
12th, we rode to Granville, and put up with Thomas Green, a public Friend,
and the only one in this country.
13th, we had a full and satisfactory meeting there,
where Friends`' meeting is held half of the time.

On the 14th, we had another meeting at Granville, in a Baptist meetinghouse.
This was a large meeting.
I was told that four priests came to that meeting--all
of different sentiments--and their bearers with them,
strongly armed with a coat of mail; the materials, superstition.
They did not mean to be touched on any side, nor have their castle defaced anywhere;
a sense of the state of the people very much depressed my mind with painful exercise.
I said in my heart, in vain will it be for me to open my mouth.
I felt much stripped in spirit, and was resigned to pass the meeting in silence,
believing the Lord knew what was best for me and the people.
My mind became calm and composed;
after a long silence I felt the Word of Life to arise with powerful authority,
with these words: "`Saul, Saul, why do you persecute me?
it is hard for you to kick against the pricks.`"
I was led to open and apply the subject in all its bearings;
the priests`' heads soon fell; the Lord`'s power came over the meeting,
and the mighty power of the Most High shook their castle to the foundation;
though they struggled for awhile, their armor failed them; their Goliath fell,
and the spirit of opposition, Philistine-like, fled and left the field;
Gospel Truths flowed in a clear and easy manner, and dropped as the early dew;
may it rest long on the people, many of whom were broken to tenderness of heart,
and some to tears.
Oh! may my soul forever bow before the Lord in humble gratitude,
thanks and praise to His eternal, holy name!

15th, we had a meeting at Annapolis, in a Methodist meetinghouse; many inquiring,
tender people came to it, and the Lord favored us with a good refreshing meeting.
16th, we had a meeting at Clemmens, twelve miles from Annapolis, among the Dutch,
a poor people.
We had a solemn, tendering time.
They seemed much rejoiced with the visit.
From this we rode ten miles to Digby village, and on the 18th,
and first of the week we had a meeting in the Church meetinghouse;
the minister gave up the afternoon to us.
He attended himself, and showed no disgust, though plain truths were told them.
It was a satisfactory opportunity to us, and generally so to the people.
19th, we went to Trout Cove, and had a meeting there on the 20th,
and found kind reception by the people.
We also had a meeting at Little Gulver`'s Hole.
22nd, we had another at Sanchy Cove.
In all these places we met with kind reception, and good attention was paid to us.
23rd, we made round Stormy Bay, ten miles, and lodged with a man by the name of Jones,
and had a meeting there on first day, 25th,
where a great many people were gathered together.
The power of Truth broke in upon them in a wonderful manner; they seemed melted like wax,
and some wept aloud.
The Lord was pleased to exalt the standard of Truth and righteousness,
and magnify His power in the eyes of the people.
Blessed be His holy name forevermore!

26th, we started for Wilmit, where Samuel Moore lived; but hearing of Obadiah Griffin,
an old neighbor of my father`'s when a boy, we went there,
by whom we were joyfully received.
My companion having informed me before that he thought he must return home in the fall,
now let me know he thought the time had come.
Not feeling clear of the country, it was a trial to me to think of parting,
after traveling several months together without the least discordance;
but after some struggle of mind I was favored to give him up,
and we parted with composure.
He went to Digby to seek a passage, and I went to Wilmit, where I made some stay.

The next meeting I have an account of was on St. Mary`'s road, three miles from Digby.
After it we rode to Digby, and I found my companion there; he had not yet got a passage.
We were one night together, and had to part again.
We went on to Annapolis, and made but little stop there.
I now had Samuel Moore for company.
The morning following we rode about five miles and came to a thickly settled neighborhood;
we stopped and had a meeting with a careless, easy people,
who concerned themselves very little about religion.
After meeting we went to Robert Fitz-Randolph`'s, the 30th of the month,
and lay by until first day, when we attended meeting at Wilmit,
and had an appointment on the mountain in the afternoon;
the meeting was pretty full and favored.
Truth gave strength and utterance to clear my mind, so that I felt fully relieved.
I lay by a short time, to recruit, if I could, as I was much worn down;
but my rest was not long.
Being strongly impressed to go to Cornwallis and Hoveton,
I informed Friends of my prospect, and they approved of it.
Samuel Moore and Thomas Green accompanied me.

4th of the week and month, we set out and rode forty miles,
but got in so late that there was not time to have a meeting that evening.
We gave the next day to look for a place and inform the people, and on 6th day,
we had a meeting in the Baptist meetinghouse.
The gathering was not large, the inhabitants mostly Baptists, and fixed in their belief,
so that it seemed heavy getting along among them, but I was favored to relieve my mind.
On the 7th, of the week and month, we rode to Hoveton; the 8th,
of the month and first of the week,
we had a large meeting in the Baptist meetinghouse of that place;
many of other societies coming in, there was an open door for labor.
My mind was much enlarged, the doctrines of Truth went forth clearly,
and appeared to be well received by the people.

We then returned to Samuel Moore`'s. 11th,
I made a little visit to the inhabitants of the Mountain,
and took my final leave of them.
12th, we went to visit the few Friends at Granville, and made our home with Thomas Green;
13th, met with the few Friends there, and some of their neighbors sat with them;
where we experienced the Lord`'s promise fulfilled--that
where two or three are gathered in His name,
there He would be in the midst of them,
whose presence gives joy and gladness of heart and raises the drooping head.
14th, I appointed a meeting at Annapolis; but not feeling clear,
I appointed another on first day, the 15th. The collection of people was large,
which gave opportunity to relieve my mind in a solid, feeling manner,
and to part with them affectionately.

The day following, we rode to Digby, 40 miles; 17th,
we went up the River about nine miles, and had a meeting on the north side of the basin.
I went to this meeting poor, empty, and bowed in spirit.
In this depressed condition I mourned awhile,
but my Redeemer was pleased in His own time, to arise with healing in His wings,
and to anoint the shield.
I went forth under the banner of His love; my bow abode in strength,
and the battle was turned to the gate this day,
I hope to the everlasting honor of the true and living God.
The +++_______+++we returned to Digby, and the next day, at evening,
had a meeting in a private house.

In the course of my communication I was led to address the mother of a family,
who mourned with heart-rending grief for a drunken husband,
who was spending his property at taverns in drunkenness;
so that she greatly feared her children would come to poverty and need.
I had to address her in this language;
"`hold up your head in hope for you shall soon be relieved of your burden;
your husband shall be taken away and laid under the cold turf and
not allowed to deprive you of a living nor your children of a home.
When this takes place see that you are a mother to your children,
bringing them up in the fear of the Lord, that He may be a Husband to you,
and a Father to your children, and may bless you.`"
After meeting there came in several where I was.
One man looked on me and said,
"`According to your preaching such a man is going to die soon,
and you pictured him out exactly.`"
I said, "`was he at meeting?`"
He answered, "`Yes, and his wife too.`"
Before I got away from the place, there came a man into the house where I was, and said,
such a man is dead,
just as the Minister said--he died drunk--and now we want
to get the Minister to stay and preach the funeral sermon.
I thought it best to pass away as quietly as I could.

Not feeling clear of the inhabitants up the River St. John`'s, I made the second visit,
with Samuel Moore for company; he made an agreeable companion.
21st, we set sail for New Brunswick and arrived there about twelve at night.
The next, being first day, at evening we had a large, solid,
comfortable meeting in the Methodist meetinghouse; in it my spirit was revived,
and courage renewed in the Lord to go forward in hope.
Accordingly we sailed up the River about forty miles to Archelaus Carpenter`'s,
and got there the 25th of the month.
26th, we had a large meeting at Robert Smith`'s in the neighborhood;
here the way for communication was made easy,
the doctrines of Truth were clearly opened and the people gave good attention.
Near the close, a comely woman stood up and acknowledged,
"`This is the everlasting truth we have heard today;
and there is no other way to be saved;`" and she wished the audience to prize the favor,
and in all diligence to make their peace with God.

Feeling clear of this place, we took the boat to go up the River, the wind being ahead,
we stopped after getting about four miles.
The next day, 27th, the wind being ahead, we traveled on foot six miles,
to Benjamin Birdsall`'s. Here we stopped and had a meeting with a careless people;
yet such were the mercies of the Lord that the Truth came over all,
and the minds of many were tendered.
29th, and first of the week, we had a meeting in Waterbury with the Baptists.
Though the Lord gave strength and utterance among them,
they were so settled in their belief that it was like pouring water on a rock,
yet I felt peace in doing my duty.
After meeting we traveled twelve miles to Hugh Copperthwait`'s, in Sheffield.
30th, had a meeting there at evening among a loose, hard people, mostly refugees.
It required sharp, heavy strokes to enter old dozy blocks; this made the labor hard,
but good was the Lord, who helped me to clear my mind, so that I felt easy to leave them,
and glad to escape.

1st of the 12th month,
we traveled twelve miles to Nicholas Rideout`'s and lodged with him.
2nd of the month,
we sat with a tender few who were concerned to meet together in the manner of Friends,
and were comforted.
I had to encourage them to abide faithful,
and the Lord would be with them and keep them in safety.
3rd, we were detained by a snow storm.
Early in the morning of the 4th we started for Frederickton,
finding the river not passable,
we returned to our Friend Rideout`'s. We had a little
meeting in the neighborhood on the 5th of the month,
and next day the first of the week, we met with the few friendly people at Rideout`'s,
where they commonly met.
Notice being given of our being there, a pretty large company came in.
Here I was favored with a lively, clear testimony.
In the afternoon we met with the few friendly people who chose to meet by themselves,
as usual; the life of Gospel love was sweetly felt among them.
Feeling much sympathy with them I was led to encourage
them to abide in and keep the word of patience;
it was these the Lord would keep in the hour of temptation.

7th of the month, the roads not being fit to travel, we lay by.
8th, we made trial, and got across the river on the ice, and went to Frederickton,
made our home with Robert Smith, and were kindly used.
9th, at evening, we had a large, crowded meeting,
at Cornelius Ackerman`'s. Here I was led to show that the devil was the first
that ever preached the doctrine that a man might sin and should not die;
and to show that God had always said the soul that sins shall surely die;
that God had Ministers and the devil had Ministers,
and when we heard Ministers preach such doctrine as the devil first
preached we might know they were not the Lord`'s Ministers.
I was led largely into the subject; the people gave good attention, and appeared solid.
I was told after meeting that there was a great dispute between the New Lights and Methodists,
each claiming the right of likeness to the Quakers.
The man remarked, "`You have decided the dispute.`"
I asked him, how it turned?
He said, "`The New Lights believe, '`once in grace, always in grace,`' in the extreme;
and you have laid all that waste, and the Methodists exult.`"

I was told there was a number of both sorts at meeting.
After another meeting I was attacked by a New Light preacher, and about twenty with him;
he accosted me thus: "`Well, friend, I can fellowship you, I have seen Quakers before,
and if I am ever so happy as to get to heaven I expect to have Quaker`'s company;
but how you get along without baptism and the sacrament, or Lord`'s Supper,
I cannot see.`"
Being fatigued and seeing such a sharp-looking man, and a large company with him,
I was afraid, for I thought they came for argument, which I was not fond of.
I sat a little to think when it came into my mind to ask a few questions, which would,
perhaps, bring the matter to a close.
I proceeded: "`Did I understand you that you believe there are Quakers in Heaven?`"
Answer, "`Yes.`"
Question--"`Is there any way to get into heaven, but by Christ, the door?`"
Answer, "`No.`" Question--"`Are they ever turned out when once admitted.`"
Answer, "`No.`" I then remarked,
"`Then I think the Quakers have the better of the Baptists, and make a saving.`"
He said, "`Why so?`"
I remarked, "`We save the labor of going down into the water, and coming out again,
and drying our clothes, and get to Heaven as safe as you.`"
He sat a little, then arose and took me by the hand, with these words;
"`I can bid you Godspeed, farewell;`" and went on with his company; and glad was I.

10th, we traveled up the river seven miles.
A storm coming on, we stopped with General Isaac Allen,
who kindly invited us to stay with him through the storm.
12th, we moved on up the river about four miles,
and stopped to have a meeting in the evening.
We met with painful trials, as I had now got on the ground,
where the people held their meetings somewhat in the form of Friends for several years,
and had rejected the common ceremonies.
There came in a New Light preacher who stayed round several months,
and persuaded a number of them to go into the water, and forbid women`'s preaching;
he had crazed one woman but the other two somewhat stood their ground.
He forbade the people to meet in the Quaker-way, as he called it.
There were a number who would not go into the water nor receive his doctrine;
and after he had got the people all in confusion and contention,
he went off and left them in a pitiful situation.
I found it my business to go among the remnant, that had not been drawn away,
encouraging them to meet together as before.
They had found the effects of admitting Ministers to preach
in their meetings before they knew their principles.
I thought it a sufficient warning in future, but,
poor things! they seemed so broken and heart rent, that I could but mourn for them.
O! may the Lord be a wall about them!
I believed it right to encourage the women to stand their ground.

13th and first of the week, we had a meeting in Cove village, in King`'s Clear.
It was large, both sorts being present.
My mind was led in a clear, discriminating line of doctrine,
between the precious and the vile, the letter and the Spirit,
ceremony and Gospel substance; in that the letter kills,
but the quickening of the Spirit makes alive unto love and good works.
This rejoiced the poor broken ones, the others were silenced, and Truth had the victory.
Blessed be the name of the Most High, who is strength in weakness, riches in poverty,
and a ready helper in every needful time, to all those who look to,
and put their trust entirely in Him.

14th, (I think) we had a meeting, to which a number of black people come;
it was a tendering time.
They seemed more open and ready to believe the Truth than many who had more information,
for they acknowledged they felt the Truth.
15th, we had a meeting at Archelaus Hammond`'s in the evening--not large,
but satisfactory, excepting some lightness among the young people,
but they became sober before meeting ended.
Not feeling clear of the place,
we appointed another meeting in the neighborhood
for the evening of the 16th. It was large.
Truth came over all and arose in dominion.
The people were tendered and fully acknowledged to
the truth of what was delivered among them.

17th, we had a meeting at John Barker`'s,
to good satisfaction to ourselves and the people.
19th, had a meeting in the evening at the house of John Lawrence, a favored, solemn time.
20th, first day, had another meeting in the neighborhood, to which a large number came.
I found my mind drawn to take up the subject of man`'s sinning during life;
that those who believed in and taught that doctrine were not the followers of Christ,
for he came to put an end to sin, and finish transgression,
and in the room thereof to bring in everlasting righteousness,
(a new doctrine in this part of the country), which made the people stare for awhile.

Through the mercies of the Most High, I felt my mind harnessed for the day,
and enabled to show them from many Scripture texts,
that God through Christ had amply provided means,
in the pouring forth of the spirit of His grace upon all flesh;
a measure of which was given to every man to profit withal, which, if they believed in,
and obeyed in all things, it would become that strength in them,
which would enable them to walk in newness of life--after the Spirit and
not after the flesh--and to worship the Father in spirit and in truth,
which was the only worship accepted of Him;
and I was led to show them that what was not of God, was sin, as well in worship,
as in all other conduct.
I was much helped--the word went forth clear and in good authority.
The meeting was quiet and closed solidly, for which I felt renewed cause to give thanks,
and praise to the Lord Most High, for the favors of the day.

21st, not being well, I lay by, except riding about five miles to Bear Island,
where we had a large meeting the 22nd, in the evening.
The people were attentive and quiet, and I think it was to the satisfaction of all.
After this meeting I felt at liberty to turn about.
I left some of them weeping; it was a humbling parting.
23rd, traveled ten miles, mostly on foot, and put up at Benjamin Stewart`'s,
formerly from Fishkill, New York State, who kindly entertained us.
24th and 25th, we continued our travel on foot through the snow,
which was very fatiguing, until we got to Jonathan Sisson`'s, at Lizaway Creek;
he was from my native country, and very glad to see me.
Here we had a good home, where we rested the 26th.

First-day, the 27th, we had a meeting at Jonathan Sisson`'s,
where we found a few serious, enquiring people,
and the way opened to minister Gospel truths, which were gladly received.
29th, we had a meeting on +++_______+++ Island.
In this meeting it was shown me in the clear light of the Lord,
that the people had been visited with the day-spring from on high, and much awakened;
and that the Priests,
(as in some other places) had taken this opportunity
to make them believe that this was their day of grace,
and seal of their election; that they never could be lost;
and had turned the minds of the people from that
which began the work of reformation in them,
to believe that if they were baptized in water, partook of the sacrament,
as they call it, kept the Sabbath-day, and paid the Priests well, all was well,
even while sin had dominion over them; and the last state of such was worse than first.

I was constrained to take up the subject at large,
and go into all its branches and show the corruptness of such principles,
and the weakness and hardness of heart it would leave them in; that it was delusion,
and delusion always brought forth sin, and sometimes,
conduct transacted and cloaked under religion, that was strange.
After going through these subjects I was helped in a marvellous manner
to call the attention of the people to that which first awakened them,
showing them from many Scripture texts what it was and what it would do for them;
and if they would believe in it they would have the everlasting
Gospel preached to them without money and without price.
After this meeting, feeling so relieved and clothed with peace,
I could but admire and marvel in thinking of the
goodness of the Lord in giving a sense of,
and strength to speak to the state of the people; they acknowledged it was so,
and that many had run into strange things; so much so,
that an unlawful intimacy had been urged with one of their Ministers, as the will of God.

After meeting, we went to Cornel Allen`'s; 30th, we came to Frederickton,
and having a heavy cold on my lungs, we lay by till the 2nd of 1st month, 1802.
In the evening we had a meeting in the town; many came and apparently well satisfied.
On 3rd, first day, we moved down the river; my being much unwell, we traveled slowly;
4th, we got to Hugh Copperthwaite`'s; 6th, we rode about twelve miles,
but growing more unwell, I gave up proceeding, only as I could bear it,
but soon had to stop.
This gave chance to recruit a little,
but feeling my mind drawn towards a village at the head of Grand Lake,
I persuaded Benjamin Birdsall to take us there, a distance of thirty miles;
he took us to Marmaduke Hutchinson`'s. We found them Friends and rejoiced to see us come;
we had a meeting at his house next day, and they being much beloved by their neighbors,
and living near the village, the meeting was full--a precious, tendering time.

The first Deacon of the church, with his wife,
was convinced of the Truth at that meeting;
both have since become members of our Society,
and nearly all their large family of children.
Next day we parted with them affectionately,
and returned to Benjamin Birdsall`'s on the 11th. But my weakness on the
lungs rather increasing I lay by several days until I was a little recruited,
and then went down the river to Wickham, to Samuel Underhill`'s,
where we stopped and had a large meeting on first day, the 17th, which was truly favored,
and the people were generally tendered, acknowledging the truth of what they had heard.

When I came into this place and informed what my prospect was,
and when they said a Baptist Minister had appointed a meeting the same day and hour,
and notice was spread.
I thought of it a little and then told them I felt best to attend to my own prospect,
and as we lived in a free country, the people might go the way they liked.
My proposal was complied with, and when the time came,
the Priest seeing how the minds of the people stood,
proposed to them to drop his appointment and come with them to my meeting.
This was readily agreed to; the Priest acknowledged he was glad he was there,
being well paid for coming; the presence of the Lord was among us,
and he wished the people to take heed to what they had heard, for it was the truth.
I note this for encouragement to you, my children,
to stand faithful to the pure openings of light and life,
resting assured that the Lord will make way for the right thing.

18th, we went down to New Brunswick, and my lungs becoming more affected,
we stayed until we could get a passage in a good vessel to Digby.
We sailed at two in the afternoon,
and in a few hours there came on a tremendous storm from the south-east and brought
the fog so thick that we could not see from bow to stern of the vessel.
They had soon to light lamps, and the tide going out we had a dreadful sea.
Night came on, dark beyond description, so that for twelve hours it seemed awful.
In the morning we narrowly escaped being dashed upon the rocks;
but our lives were all spared,
and we had to look back and reflect upon the marvelous providence
and tender mercies of Him who controls the great deep.

We stayed at Digby one night, and then went up the river to Wilmet,
home with my companion, who, to his joy, found his family all well.
By this time I was not able to travel.
I kept my room mostly, for several weeks, except to attend meetings as they came in,
course.
They were held half the time at Samuel Moore`'s, at whose house I was then staying.
While here I heard of three families of Friends, (the men were all brothers),
that lived back in the country,
and had not been visited by Friends since they came there.
I felt any mind impressed night and day to go and see them.
When I was recruited so that I could ride I set out
with Samuel Moore and Thomas Green for company,
and found them; one of the brothers was dead.

They told us they agreed for their passage to Pennsylvania, but before they sailed,
(unknown to them), the Captain was ordered to land them in Nova Scotia,
just about the time war was declared with America,
and it continued so long that they became discouraged and bought land there,
and had lived in the country twenty-eight years,
without having any interaction with our Society.
The old people appeared to retain the likeness of Friends, in language,
deportment and dress.
The children were much gone, except those of the youngest brother,
who had settled a number of miles back.
The parents were in the practice of sitting down with their children on first days,
which the others had omitted.
The difference in the families was easily seen.
We had a meeting in each neighborhood, but this last was a solid,
tendering and joyful time to this dear family.
When we parted with them, tears fell from their cheeks like drops of rain,
and my heart ached for them.
We returned to the other settlement where I was taken sick and confined a week.
When recruited, we had another meeting with them and parted,
and I returned to Samuel Moore`'s.

After parting with these Friends and looking over the great number I had fallen in with,
who told me their parents or grand-parents were Friends, and some that they were members,
appearing as sheep without a Shepherd,
all within me capable of feeling was awakened to sympathy,
so that I could but pour forth my prayer to the Lord that
He would pity this land and be a Shepherd to the people.
In many places I was entreated with tears to come and live among them;
that they would be Friends and enjoy Society;
for they could be nothing else and they would not go to hear the Priests;
therefore they were nothing.
Many affecting scene I passed through in this land,
feeling this language pass through my mind;
Oh! that Friends did but enough consider what our fore-fathers
passed through for the principles we profess,
and the blood of the righteous that was shed for the liberty we enjoy,
they would not wander from the sacred enclosure of Israel`'s King as they do,
seeing the Lord does not withhold anything that is for the good of those who love him.

Returning to Samuel Moore`'s, I found myself unable to keep up,
and in a few days was confined to the bed with an inflammation of the lungs.
Here I was confined for nearly three months, and was brought near the grave;
the pain and agony I underwent, I cannot describe; affecting my head,
so that I was often flighty in my talk.
When more settled, the thought of being deranged, and also of dying in a strange land,
away from my family and friends, was very afflicting.
The old enemy was permitted to throw his fiery darts,
which tried my faith to a hair`'s breadth,
in presenting to me that this was the reward of all my toil and anxiety;
that I had preached repentance, which was false doctrine, for God never sinned;
and I had told the people that God had sent His Son, Jesus Christ, into the world,
who had laid down his life as an offering, acceptable to God, His Father,
that sinners might be converted; all this was horrid blasphemy,
for it was inconsistent with the nature of God, reason, or good sense,
to believe that He would take the life of a good man, (for he was a good man),
to satisfy His revenge on the wicked, was horrid to believe; that I had preached it up,
and that if I would renounce this false doctrine, I should feel better,
for I was going to die, and if I did not do it, hell would be my doom.
This put me in such agony that I requested no one
should be admitted into the room without my consent.

I kept my room, in this condition, for two weeks,
but all through this sore trial I felt a spirit in me to contradict all these presentations,
and when the darkest shades of despair came over me,
it kept a little spark of hope alive, which could not be put out.
I was reduced under these trials to an almost helpless condition;
to deny all that I had ever found comfort in, I dared not, without an evidence of light,
that would bring peace and quiet to the mind--this I did not find.
To try to comfort myself with past experience, I found, gave no relief.
I turned and turned, but found no ray of solid comfort,
until I gave up to die in that country,
in just such a manner as the Lord was pleased I should;
for in all these rolling thoughts,
there was nothing in me that would consent that God was not perfect goodness,
and equally just.
This grain of faith I never gave up, and it proved enough to keep the fire of hope alive.
For a number of days I dared not converse with any person, only to ask for what I needed.
I dared not look into a book, as I found my mind could not bear it.
I lay for days and nights, keeping as still as possible in body and mind;
the only theme of meditation was, "`I am here before you, O Lord! a poor,
helpless creature!
If I have been wrong, less or more, You know it all, and can show it me;
if I have been right, You can confirm it to me,
and strengthen me to endure whatever You will I should, without a murmur.
Here I am, in life, in death, and in judgment; do with me what is good in Your eye.`"

In this state of mind only, could I feel composed,
and enjoy a little the comforts of hope, until the Lord was pleased in mercy,
to take me out of the horrible pit, and give me to see in the clear visions of light,
that it was the hour of temptation which I had passed through, in which,
and with which kind of floods the old dragon had swallowed up many,
and would draw down many with the sweep of his tail;
and as I did not run with the temptation, nor lean to my own understanding,
but had regard to that Spirit which withstood the tempter in me,
and had called on Him alone, and not on another--therefore He heard me,
and would hear all such, and keep them in the hour of temptation from falling.
The floods passed away; I seemed as though I was in another world, much like a Paradise.
I found the feet of my mind once more set on the Rock of all Ages,
that was never prevailed against, and was higher than I,
and where I could sing praises to the Lord God, and the Lamb,
who was slain from the foundation of the world.

I soon recovered, and spring having come on, I made preparation to return to the States.
19th of the 4th month, I came to Digby to seek a passage, but had to wait several days,
in which time I felt a draft on my mind to make some visits.
I attended to it, and attended a meeting at James Hollinghead`'s, at Jogins,
and one at Joseph Young`'s, at Digby; both were comfortable and refreshing to me.
23rd of 4th month, I embarked for the States about 9 in the morning, with a fair wind,
but had sailed only a few hours, when there came on a heavy northeast storm;
before it we ran three days and nights.
When in sight of and opposite Cape Cod, the storm ceased,
and for twenty-four hours we had a calm.
The sea having been blown into great swells, and the wind ceasing at once,
we could not sail at all, and the vessel rolled exceedingly.

The next morning the wind started from the W. N. W., with a tremendous blow,
so that we were in imminent danger for six hours.
About the middle of the day it abated, and I was set on shore at Martha`'s Vineyard,
near the house of a Friend named Coffin, who, with his family,
were glad to see me return.
I had not been long here, before I felt drawings of mind to pay a visit to Gay Head.
I went and had a solid meeting with the people of color,
and found my mind entirely relieved, and at liberty to take a final farewell.
We returned to William Coffin`'s, and on first day the 2nd of 5th month,
had a meeting there,
and one in the afternoon a few miles off at the house of Obed Coffin,
both to good satisfaction.

5th I was landed on Nantucket, and the day following I attended the South meeting.
Next day had a meeting at New Town,
and felt well satisfied it was right that I attended to the opening on my mind.
9th, first day, I attended the South meeting in the morning,
and at the North in the afternoon.
In both these meetings,
I was enabled to clear my mind in the most relieving
manner that I ever experienced in this place.
The packet not being ready to sail, I had to stay until after their mid-week meetings.
In both these, I felt constrained to come to close, plain work,
there having been a division among them, that had done much hurt.
After these meetings, and having had private opportunities with several of them,
I felt clear, and saw my way to leave them.
14th, I took my departure from Nantucket, with the enjoyment of a peaceful mind,
that made all around me look beautiful.
15th, I was set on shore at Yarmouth, and first day, the 16th, I attended that meeting,
and had the company of dear, aged Mary Mitchell,
and heard her blow her little trumpet as clear as a bell.
It was like marrow to my bones to see such greenness in old age,
and such precious fruit brought forth.
After meeting, rode to Sandwich, and went to Paul Wing`'s,
who appeared rejoiced to see me return,
and soon walked over to Joseph Wing`'s--my former companion for
several months--who seemed as much rejoiced to see me return.
On returning to Paul Wing`'s I found myself unable to travel,
so lay by several days and attended their mid-week meeting.

It being known that I was expected there, the meeting was full.
I felt my mind uncommonly shut up, and much composed in stillness.
Musing, why is it that I am so shut up, and feel so easy; a language ran through my mind,
"`There are a number of members here who would not have been present,
had they not expected you; they are waiting for, and looking to you, and not to Me,
the Giver of all good.`"
I became satisfied, and passed the meeting in silence,
feeling great peace of mind in so doing.
Not feeling clear of the place, I went to see the sick, made some social visits,
and had religious opportunities in two or three families.
After attending their meeting on first day,
in which I had good service--but mostly for other people--in the line of doctrine,
not yet feeling clear, I proposed to meet with them on second day, which was agreed to.
In this meeting my mind was bowed under a deep and clear sense,
that there was a trying day coming on Friends, in that part of the land; a sifting time,
in which every foundation would be tried.
I had to sound the alarm in a solemn, moving manner;
it seemed to settle on the minds of the people, and I felt fully relieved.

24th, I took leave of my Friends affectionately, and went to Pembroke,
and attended their Preparative Meeting, and not feeling clear, made a short tarry.
I went to Marshfield, and had a meeting at Joseph Rogers`',
and another in Hanover at Mordecai Ellis`', and returned to Pembroke,
and attended that meeting on first day, In all the above meetings,
ability was given to discharge the duty required of me, so as to feel relieved,
and to enjoy a peaceful mind.
I then moved on to Lynn, and attended their fore and afternoon meetings on first day,
the 6th of 6th month.
In the first I was silent--in the latter, much enlarged,
to the satisfaction of my Friends, and the relief and comfort of my own mind.
From there to Salem, to attend the Quarterly Meeting, which was large,
and though exercising on account of the state of
Society as shown in the accounts brought up,
yet in the main, was a favored meeting.
I then proceeded to the Yearly Meeting, and was able to attend the several sittings,
though much unwell.
The business in general was conducted with a good degree of harmony.

After the close of the Yearly Meeting, I returned to Providence,
and on the following day had a favored meeting at Cumberland, among a thoughtful people.
On first day, 20th, I attended a meeting at Smithfield in the forenoon,
and Providence in the afternoon, and had good service in both.
I expected to go direct to New Bedford,
without making any stop excepting for refreshments, but was suddenly taken sick,
so that I could not travel.
When a little recovered, it was shown me that I had to go to Swansey,
with which I complied, after some close exercise.
I attended one meeting, and had another appointed among and for other people,
which was large, and much favored.
My way being clear, I now went to New Bedford, enjoying a peaceful mind.
I there made my home with William Rotch, the elder, where I was kindly taken care of.

When I got here, my mind was much depressed,
and in this situation I thought it not safe to move, and lay by the most of two days.
I came here with an expectation to attend the Quarterly Meeting soon to be held on Nantucket,
but when the packet came in sight that was to carry Friends,
the cloud passed off my mind, and I was shown in the clear light of the Lord,
that the resigned will was taken for the deed,
and I was at liberty to turn my course towards Portland--a joyful release this was to me.
I made ready, and in a short time was on my way with John Winslow for company.
On our way, we attended Seabrook mid-week meeting, and not feeling clear,
another was appointed next day.
A number of members came to it, who seldom attended meetings in the middle of the week,
and way opened to address that class in a weighty, feeling manner,
in the authority of Truth, which rose into dominion at that time.

We were next at Almsbury; the meeting was small; there were a few plain, aged Friends,
who were concerned to keep up their meeting.
The testimony of Truth lay low among them.
I returned to Seabrook, and attended their meeting on first day,
where my mind was much enlarged in the doctrines of the Gospel, and it went forth clear.
There being a number present who were looking towards Friends,
it was a satisfactory meeting, and fully relieving to my mind.
We passed on to Epping, and found when we came there,
that the Friend who undertook to notify for the meeting, had not been faithful.
Of course, the meeting was small, and not feeling easy, I appointed another the next day,
which was large and favored.
From there to Lee, a small meeting,
and I thought it poorly attended in the middle of the week.
I was led to treat the subject with plainness,
and to remind Friends of the sufferings of our fore-fathers for that testimony;
and that by their faithfulness, they purchased the liberties we enjoy;
and how lightly they are thought of as appears by
neglect in the attendance of our meetings.

Next we went to Dover,
and from impressions that I felt in attending their mid-week meeting, which was small,
I believed many of their members were not there.
I felt most easy to call a meeting the next day, when they generally came.
I had to speak at large on the subject of Friends`'
neglect of duty in the attendance of meetings;
bringing to mind the testimony we profess to bear, the integrity of our first worthies,
and our reaping the harvest of their faithfulness,
showing the responsibility that rested on us, to support the noble testimony.
I was mercifully helped to lay these truths so close and tender,
that they seemed to settle home on the meeting at that time.
May the Lord cause it to be as the nail in a sure place.

The following meeting was at William Brown`'s. It was large,
and favored with the presence of the Holy Shepherd of Israel.
We attended meeting on first day following, at Berwick,
which was a trying one to my feelings, for it appeared clear to me,
that the form of godliness was much more affected in some of the leaders of the people,
than they were concerned for the life of it;
and by these the power of God was rejected in themselves, and by them opposed in others,
who were willing to obey the Truth.
The effect was great spiritual desolation, heart-broiling and contention among the old,
while the dear youth were left exposed to the glitter of the world, too much unassisted,
but rather staggered.
My feelings were aroused; I had to put on my armor,
and go into the field with the drawn sword of the Spirit,
and to wield it under my Master`'s banner, until His mighty power rose into dominion,
and the battle was turned to the gate for the day.
Blessed be His ever Holy name!
I felt great peace, and full relief after this meeting.

On second day morning, the 12th of 7th month,
I set out for Portland with my agreeable Friend, Peter Morrell, for my companion.
13th, we had a meeting in the town--a large, mixed multitude, but in the main,
a favored meeting; but I hurt myself in speaking too fast,
and I think it hurt the force of my testimony;
yet through the unmerited mercies of the Most High, the meeting ended quiet,
and the people appeared to feel serious.
From here we went to Falmouth, and attended their Preparative Meeting--shut up in silence.
At Windham, the day following, and silent there also.
We left an appointment for seventh day, hoping way might open to get some relief,
as my mind seemed loaded, and my heart greatly distressed.
There was also a meeting appointed at Gorham on 6th day;
we attended to the appointment--still my mouth was sealed,
and the people appeared much disappointed.

We returned to Windham, where the meeting was.
Here again my lips were sealed, and my heart shut up.
I passed the meeting in silence, but not without deep searching of heart,
questioning the rectitude of my movements; for the people were not only disappointed,
but some of them dissatisfied, and thought themselves not well used.
This, in addition to my burden, gave no relief,
so that I knew not what to do or what to think,
until my Lord and Master gave me clearly to see that the appointments were not wrong;
and it was right for me to go, in resignation to His will,
and better for me and the people, to be a sign to them,
in the will and wisdom of the Lord, than to speak out of it; that it was right for me,
when the Lord directed, to go from meeting to meeting,
and see and feel the states of meetings and the people, in silence,
as it was for Nehemiah to view Jerusalem throughout, before he put his hand to the work.
This opening fully relieved my mind; I said, "`Good is the will of the Lord,
and let it be done.`"

The next day and first of the week, we attended Falmouth meeting.
In it, I had to lift up my voice like a trumpet, to show many their transgressions,
and the high, superficial professors their sins.
The word went forth in its own authority; the Truth prevailed over all opposition,
and the meeting became solemn, Magnified be the name of the Lord.
In the afternoon we attended Portland meeting, which was large,
and favored with renewed visitation.
Second day we had a meeting at a place called Little Falls,
and found a people who professed to be Friends; but being lacking in the possession,
it was hard getting along with them to satisfaction.
We returned to Portland, and the day following attended their Monthly Meeting at Falmouth.
I was silent in the meeting for worship; in that for discipline,
I had satisfactory service on the women`'s side, and made some remarks to the young men,
which gave relief to my mind.

22nd we went to Durham,
and attended their Monthly Meeting the next day in suffering silence,
for things were not in good order among them.
In the last meeting, way opened to clear my mind in a plain way,
but not very pleasing to all of them; yet the faithful being encouraged and rejoiced,
I got my penny of peace, and that satisfied me.
The next meeting was at Lewistown, on 7th day.
First day we were at Leeds, the meeting was large and satisfactory.
After meeting we rode to Winthrop; here we found a little company of goodly Friends,
among rigid Presbyterians.
We had a large, favored meeting here, to the rejoicing of the few,
in that the Truth made its way over all opposition.
After this we went down the Kennebeck river to Dresden,
and had a little meeting at George Ramsdell`'s. 29th,
rode to Bristol and had a meeting there on 6th day, mostly of other societies.
Here my mind was set at liberty; the truth flowed freely,
and settled on the minds of the people.
May it last long to their comfort and durable good.
Oh, good is the Lord to the children of men.

On first day, the 1st of 8th month, we were at Camm;
had a considerable gathering of people too much at ease,
and insensible of their condition, taken up with the cares of the world;
the few well concerned had about enough to do, to keep their ground;
so that painful were my feelings and laborious my services among them;
but through the mercies of Jehovah,
ability was given to relieve my mind and pass from them in peace.
Second day we rode to Kennebeck, and had a meeting there on third day,
with a number of sober looking people.
I was favored with a short, penetrating testimony,
that seemed to reach the minds of the people, and gather them into seriousness of spirit.
The meeting ended to my satisfaction.
Blessed be the Most High.

On the 5th of the month we were at Vassalborough East Pond meeting;
after sitting awhile leaning forward, suddenly I felt my mind in a state of stupor,
almost to insensibility.
I raised up, and looked over the meeting, and to my surprise,
I really thought that one quarter of the people were nodding with sleep; as one waked up,
another would fall asleep; the like I never saw before.
At least one half of the meeting had taken a sound sleep.
This discomposed me for preaching, and after sitting a long meeting,
I arose with this remark, "`I conclude there are many who have come to meeting,
expecting to hear a communication, but I think I should look like a fool,
preaching to a parcel of people asleep, and I am sure I should feel like one.`"
I then sat down and closed the meeting.
Benjamin Worth, of that place, an aged minister, took me by the hand with these words,
"`Joseph, I am glad you have been favored to keep your place today.`"

From this we went to Fairfield, and had a meeting, and returned to East Pond,
to attend a meeting by appointment on first day afternoon; many came to it;
the life of pure religion appeared very low;
the Master of Israel`'s assemblies was pleased to favor
the people with a plentiful shower of Gospel rain,
that seemed to tender the earthly part, and somewhat broke it up;
may it prove to the lasting good of the people,
and to the everlasting praise of the Most High, for He is worthy of it.
On second day we were at Belgrade, and third day at Sidney.
In both these meetings,
the overspreading of Divine favor was felt in a renewed
visitation to the people--may it prove a blessing to them,
to the gathering to Shiloh`'s rest.

Feeling now clear of these parts we returned to Portland and went to Samuel Hussey`'s,
where I made my home, and was taken as good care of as I could desire.
Soon after coming there I was taken sick, so that I could not travel for some time;
but most of the time was able to sit a meeting.
My companion returned home; we parted in mutual friendship.
I attended meetings steadily and passed four or five of them in silence,
under great depression of spirit, until the last meeting I was at,
where all present were members except one.
The Lord showed me that the cause of the distress I felt in their meetings, was,
some of the heads of the people had drawn their swords on their fellows,
who were better than themselves; that they had disordered the flock,
and confused the heritage of God, and if there was not a stopping, turning about,
and withdrawing the hand from oppressing the innocent,
the Lord would arise and make bare His arm.
He would turn and overturn; there should be a cutting off to rise no more;
for the Lord would arise and support His dependent ones.
I had to deliver it all in full plain terms; felt my mind fully relieved,
and at liberty to depart.
In about half an hour after the close of the meeting,
I mounted my horse and rode several miles without looking back, or conversing with any,
with my mind filled with peace and joy.

I went to Falmouth Select Preparative Meeting, and attended the Monthly Meeting following.
In the meeting for worship I was silent, and in that for business until near the close,
I was constrained to stand up and tell them plainly how
it appeared to me some of them had treated their friends;
that the Lord was not pleased with it, and in all their affected zeal and show,
the Truth had not been advanced, but hurt, and the feelings of the pure in heart wounded.
This appeared to offend several,
notwithstanding it was acknowledged by Friends that it was so, and they all knew it.
In this meeting it was shown me in clearness that
I was at liberty to take my leave for home,
with taking two meetings on my way--a joyful prospect.
I informed my friends, and took a solemn farewell.

On the 26th of the 8th month, in a feeble state of health, I rode to Livingston,
twenty miles.
27th, had a favored meeting there which seemed to revive my spirits a little.
28th, I rode to Sandwich, New Hampshire,
and attended their first-day meeting on the 29th,
in which my mind was tried in a singular way for me,
for after sitting a considerable time,
it was made known to me that the people were waiting on me, and not on the Most High;
looking to me and not to the Lord,
which would close my way and I must tell it to the people.
The singularity of it tried my mind, but not feeling easy without doing it, I gave up,
simply told them my feelings and sat down; but soon felt like a vessel pressed full,
which needed vent, and could not have it.
In this suffering condition I had to sit as long as meetings commonly hold,
until the people gave up their expectation of hearing preaching, and became quiet;
then my way opened in a lengthy, searching testimony,
that reached the witness for God in their minds, and broke them down to a tender feeling,
and an acknowledgment of the truth.
Oh! may the Lord fasten the Truth in their hearts, as a nail in a sure place,
and bless the service of the day to the people.
The 30th of the 8th month I started for home, reaching there in three days,
found my family well, and we were mutually glad to see each other once more.

The following occurrences took place during the foregoing journey:

Abigail +++_______+++ and her husband, with their adherents,
(the woman who attacked me in the gallery,
in my early travel in that part of the country,) entered
a complaint against me for preaching false doctrine,
and prophesying their downfall.
This was when I was on my way for Portland the last time.
The Elders came apparently strong.
I told them "`It was happy for me that I remembered the subject well,
and I thought I could repeat the discourse nearly verbatim, for it was a short one.`"
I informed them of the subject, showed in what point of view I held it forth,
and the language I closed with, and added this remark,
"`Who of you can say this is not truth?`"
They sat awhile, and the leading Elder said, "`Joseph,
I am glad to find you on such good ground; it is good sound doctrine;
I will not only acquit you, but I will stand by you.
Do you keep that ground, and you will stand.`"
And so we parted.

The above named Abigail +++_______+++ and her husband have since run into Ranterism,
and are disowned by Friends.
Shortly after this I stopped at Berwick on my way to Portland.
After meeting, four or five very grave-faced persons came to the house where I was,
and with much affected sanctity,
questioned me as to how I felt in the company of my intended companion.
I answered, "`Very well; he appears an agreeable man.`"
Question--"`Do you feel no disagreeable feelings when in his company?`"
I answered, "`No, not at all.`"
The reply was, "`I marvel that such a great seer as you are,
can be with such a man and not feel him out.`"
I answered, "`Friends, I have no unity with your conduct;
neither do I think you are sound; for was I such a one as you state,
it is neither right nor wise to talk so in my hearing; it has the appearance of flattery.
And that is not all, I am but a man,
and can only see the state of a meeting or an individual when my master gives me eyesight.
So that it is not me but my master; these things are at his disposal,
and you ought to understand them, to be fit for judges.`"
The reply was, "`Well, we hope if you do feel anything, you will be faithful.`"
I answered,
"`If I should feel anything I should strongly suspect it arose from what I have heard,
and should be very cautious how I meddled.

You have blocked up my way, and if there is anything needed to be done,
you have got to do it.
You ought never to treat anyone as you have treated me,
for if there was anything in the way, you ought to have told him,
he could not go without doing his part to remove the objection; and if he did not do it,
to have provided me with other company, and not let me know anything of the matter.
You have had time enough, for some of you were sitting by when he offered his service,
and I accepted it.
Some might be hurt by such treatment, and get off the right ground;
so that it is clear to me you are lacking in best wisdom.
Have you told the Friend of this objection?`"
The answer was,
"`No.`" Question--"`Did you know of it as long ago as when he offered his service?`"
The answer was, "`Yes.`"
Question--"`Why have you lain still?`"
The answer was, "`We feel very weak, and were in hopes you would feel him out.`"
I answered, "`Friends, you are wrong;
for the Great Master portions the work to every servant, and hand-maid,
and gives them knowledge what his will is, and ability to do it.
It is not reasonable to believe He will lay all the service on one servant;
for without His help they are no more than other men.
And now, Friends, for you to want more laid on me than the Master has appointed,
is not right; it is an evil covetousness, and your prayers are not granted,
for I feel as though I had no business with the concern you want me to meddle with;
and you have got to clear my way.`"

At this they seemed like people amazed.
I then said, "`Friends,
you have said so much that I must know there is something the matter,
and have you looked into the affair,
so as to know whether there is a just cause for uneasiness or not?`"
The answer was, "`No.`" I then replied,
"`How do you know there is any just cause of complaint; and if not,
what ground is there for me to have any uneasy feelings with the Friend?
Now, Friends, I want you to see where you are.
This Friend is in the station of an elder, and so are several of you;
and you are here holding up ideas of reproach against his character,
and do not know whether there is any cause for it or not;
and that to a stranger who ought never to hear of it.
It is evident you are very unsound or very unfaithful to the righteous cause,
and your brother, or both.
I have no favorable opinion of such conduct; I have no unity with it.`"

Here again was a silence; at length it was proposed for me to lay by a day or two,
for them to look up company for me.
I then told them I had been gone from home, going on two years.
I left a wife in small circumstances, with a large family of children,
in a poor log house, and that I did not feel easy to idle away one minute; therefore,
if they would provide me a pilot, if it was only a youngster,
who knew the way to Portland, I would take up with it,
but they must let the Friend know why he was rejected.
They answered, we expect you to do that.
I told them, that I would not do,
unless I had the liberty to make use of their names as the objectors,
and to do it by their request, for in my feelings I had no objection.
I then pressed them to go and see the Friend, as he was near by,
but could not move them thereto.

It was then proposed for me to go with him to Portland,
and then dismiss him and send him home, and was asked if I would do it.
I said, by your orders, and not without.
I was answered, that would not do, for he would then take them in the discipline;
but they thought I might tell him I was not easy to travel with him,
for they did not see how I could feel easy knowing how they felt.
I told them that part of their uneasiness, as respected themselves, I could tell him,
but as to make any pretentious of uneasy feelings as my own, when it is not so,
only to gratify your feelings,
when you do not know whether there is any just cause for those feelings or not,
that would be playing the hypocrite; that I should not do for any of you.
I shall act candid, open and honorable with all men; my station calls for this,
and as for making any pretentious of Divine impressions or revelations,
when I did not feel it, it was in my opinion very near blasphemy; that,
while I had my senses, I should never do;
and as for their exposing themselves to the discipline, they had already done it,
was I to tell what they had said,
and they had no way to get out unless they denied their own talk;
but that I was not disposed to do if they would treat the matter honorably
with the Friend according to gospel order and provide me with company,
I would go along quietly.

They then concluded to go and see the Friend;
but shortly returned and told me they did not see that they could attend to it,
and had concluded to let the Friend go with me,
but hoped I would see my way clear to dismiss him, after I got among Friends again.
I then took up the subject.
"`Friends,
you seem determined to place me in a situation that
you can criminate me or make me hurt myself;
for look at it, for to send the Friend back, without good reasons--he comes back,
he has his friends, and perhaps many of them; he is a man of sense,
and knows what good usage is; his friends ask him why he returns so soon; he answers,
Joseph Hoag sent me home.
Where from?
As soon as I got to Portland.
For what?
I do not know; I went with him for the respect I had for him,
and waited on him as well as I knew how, and did all I could to make him comfortable.

When I got there he told me to go home, without a reason,
only he was not free to travel with me.
He tells this to his good friends, and perhaps these are one-half of your Monthly Meeting.
What would be the remark?
Why, I did not take Joseph Hoag to be such a man.
He answers, neither did I; but so it is.
Now see what a block this would put in their minds,
should I have a mind to come into this country again.
What good would it do for me to preach to them?
I might as well preach to the stumps.
What excuse could I plead?
Could I say it was acting the Christian--doing as I would be done by?
No! and you would not, neither, was you in his place.
Is it acting the gentleman?
No!
Is it acting the brother?
No!
Friends, this will not do.
Now take it on the other hand; suppose it to be as you have stated,
in the minds of many others, that I am a favored man, and a seer,
and after I am gone there does actually come to light some conduct of his that is scandalous,
what would be the language of these people?
Would it not be like this,
how could that good man and great seer go off with that
monstrous hypocrite and he have no sense of it?
Here you may see they are staggered and blocked up.
Would not the result be, O,
I do not believe there is so much in religion as they tell of and
so the good is destroyed that they might have been benefited by.`"

This brought tears into some of their eyes,
and they faithfully promised me that if any of these occurrences take
place that they would inform the people I had been long from home,
and was in haste to get along; there was no other to go,
and it was a matter of necessity, and that my credit should not be hurt,
and were willing the Friend should go with me; and they hoped he would not be burdensome,
and so we parted.
The Friend went, I found him pleasant, agreeable, kind company as my heart could desire.
I never so much as hinted a word of this to him,
but when we parted I looked him in the face and said, Peter,
I want you to keep your eyes in your own head, and take care how you step.
He answered, I understand you, and so we parted.
He went home and found what a report had gone abroad, and by whom.
He took it up and made some of these very Friends go about
the neighborhood and take back their own talk,
and testify the report was false.
That stilled and ended the uproar.

Another that I have to record is, as I was passing through that Yearly Meeting,
I often heard +++_______+++ spoken of as the greatest minister
in the Yearly Meeting--man of great talents,
and a fine man, which made me crave to get to his house as soon as I could.
But alas! when I got there I was plunged into such
distress and darkness as I am not able to describe.
I knew not what to think of myself,
for I dared not think anything but good concerning him.
When I went to his meeting the next day, it was hard enough, and seemed all dark;
this puzzled me much.
He offered to pilot us to several meetings, which I readily accepted,
thinking I should have some good help.
He preached at every meeting, but alas, I got no help,
neither could I find where his preaching came from.
I dared not think otherwise than that it was all good, and the fault was all in me,
until I got so that I could hardly contain myself, my agony was so great.
I went alone, and exclaimed in my heart, "`Lord, have mercy, what have I done?`"
And I was answered in as intelligible language as
ever I heard vocally with my natural ear,
"`it is nothing you have done;
it is on account of +++_______+++ that your feelings are as they are,
and you have got a close message to deliver to him for Me;
see that you do it faithfully.`"
This brought me very low; it looked great, he being in high standing,
and looked upon as a great man, but I dared not think of giving back;
the Lord had shown me what the message was, and I was afraid.
I prayed the Lord to make and open a way, and give strength to do my duty.
I think it was the next day +++_______+++ entered into a long detail
of the distressing days and nights he had passed through of late,
so that he had almost despaired.

After getting through he turned to me and said, "`Joseph, what do you think of me?`"
I replied, "`at a suitable time I am willing to tell you.`"
We rode on until we came to a Friend`'s house.
I soon gave a motion; we walked into a field and sat down.
I soon began with these words, "`+++_______+++ I have undergone much exercise on your account,
and I believe it has been given to me to see in that light,
in which there is no deception, how it is with you.
It appears to me you have been one that has been anointed with the royal oil,
and has had an excellent gift in the ministry bestowed on you,
and has been promoted to ride the King`'s horse, and to be arrayed with the royal robe.
The proclamation went forth,
this shall be done to the man whom the King delights to honor.
But when you rode the King`'s horse, you forgot to remember mercy.
You have put your foot on the necks of those that were as righteous as you ever were,
and have trodden them down.
And you may think it a favor,
if you are permitted to undergo enough to atone for the
evil you have done to them that are as good as yourself.
And if you live through it, you have got to go over all the country,
where you have put on these yokes and burdens, and take them all off.
And if you refuse to do this you will be left to fall to the bottom
of the hill and shall never rise any more.`"

He seemed to struggle under it a little while, then looked up and said,
"`you are a stranger and I will not get angry with you,`" arose,
turned his back on me and walked to the house.
In a short time we parted.
I named one of the Friends he had trodden down; the blood flashed in his face.
I said in my heart, poor +++_______+++ is gone, for warning he will not take.
And it proved so.
I have not seen him since to speak with him.
Afterwards he took to ardent spirits,
and in a very few years got so as to give way to immoral conduct,
and used profane language,
for which he was taken up and was turned out of the Select Meeting,
and his ministry disowned;
but he begged so hard that after awhile Friends accepted an acknowledgement,
and let him stand a member, and there he stands, his credit and influence lost,
and is at the bottom of the hill.
I have written these accounts, my children, for you to look at,
believing the circumstances are such that if you will read candid,
and think on them seriously,
they will afford useful and comfortable instruction several ways, through life,
and to your children after you.

Here I close my account of this long journey in which
I had to pass through many deep tribulations,
and witnessed the Lord to be my helper in every needful time,
and in the might of His strength I was enabled to run through the troops that I met with,
and to leap the walls of opposition that were raised in my way.
Glory, honor and everlasting praise,
be ascribed to the Holy name of the great King of Heaven,
for all His mercies that endure forever.

I think best to relate two occurrences that took place while I was at Nova Scotia.
The first was in a short time after I left Halifax.
There came a message to me to know if five hundred pounds Halifax money,
a good sized house, well furnished, a cow, kept the year round,
and brought to my door to be milked, and a horse and chaise the year round,
at my command, with all my wood cut at the door, and at the close,
I was earnestly desired to let them know if the salary was
enough to make me satisfied to come and settle with them.
This brought a close trial over my mind;
not that the offer was any temptation any more than the dust I trod on,
but how to get along with the business, and not hurt the people, nor the good cause.
But, beyond my expectation,
way opened to give them my reasons why I could not comply with their desire,
in so plain a way, they understood me, and in that pleasant way,
that they took no offence, and we parted very friendly.

The other was in another part of the country.
They offered me a farm of five hundred acres of land, sixty acres under good improvement,
with a good house and barn on it, for one hundred pounds,
and they would furnish it with five cows and a yoke of oxen, a span of horses,
and all farming utensils; and all these I should have at my own price,
and from seven to fifteen years to pay it in, and without interest.
And they thought I might accept this offer,
for it would not be taking a reward for preaching,
but only accepting a chance that would put me in a situation
that I could attend to my duty without being embarrassed,
or my family suffering deficiency.
This, I had much more of a task to open in all its bearings,
so that they could clearly understand me, and to show them in what point of view I stood,
and the difference between their views and mine; and when they understood,
they acknowledged that I could not accept it, and they believed I was sincere,
and they must give it up; but they were sorry.
So we parted very friendly and loving, which I thought a great favor.
