== Chapter VII

On the 24th of 9th month, 1816,
having obtained the unity of my own Monthly and Quarterly Meetings,
I set out with Selah Gregory, a member of my own Monthly Meeting,
to pay a religious visit to Friends and others, within the compass of Philadelphia,
Baltimore and North Carolina Yearly Meetings.
On my way.
I visited my daughter, Elizabeth Taber, living in Chester, State of New York,
and sat with the few Friends of that meeting,
and had two appointed meetings with other people, to good satisfaction.
I was always glad that I made this little visit,
for I never saw my truly beloved son-in-law, James Taber, after; for, before I returned,
he was laid in the grave.
He told me a little before we parted, that he should not live long;
spoke with much assurance, and made some feeling remarks on himself,
the situation of their meeting, and why it was so.
He was a bright, talented, clean-handed, sweet-spirited man.

From here we went to Queensbury, and attended that Monthly Meeting.
I was enabled to clear my mind to solid satisfaction.
From there, we went directly to Stanton Hill, and attended that meeting on first-day,
which was large and much favored.
After meeting, we drove to Athens; from there to Cornwall, where we tarried two nights,
attended Cornwall mid-week meeting,
and took our leave of the last meeting in our own Yearly Meeting on our way.
The next stop among Friends, was at Stroudsburgh, in Pennsylvania,
where we arrived on seventh-day evening.
We attended that meeting on First-day, and had another in the afternoon;
both to good satisfaction.
From there we went across the country to Wilkesbarre on the great flats of Susquehannah,
where we found a few members of our Society, with whom, and the inhabitants of the place,
we had an exercising meeting;
but the Good Head of the Church raised the standard of Truth,
over the head of giant opposition--to the praise of His own name!
We went up the river about twenty miles, where we found a number of our members.
With them and their neighbors, we had a comfortable, refreshing meeting.

After this, we went for Berwick, and got there on seventh-day,
the 19th of the 10th month, and attended that meeting on first-day.
21st, we had a meeting at Fishing Creek.
Here is a good-sized meeting, and some valuable Friends.
We passed from this to Muncy,
and attended their Monthly Meeting the 26th. It was small and weak,
many having moved away.
The life of pure religion appeared very low in these parts,
and a worldly spirit much cherished.
Next we went to a small meeting on the mountain, called Elkland,
consisting of a few families of poor Friends, who were rejoiced with the visit.
We were favored with the comforting presence of the Shiloh of Peace.
When I had returned to Muncy, I was almost sick with fatigue,
for I had to ride on horseback, the roads being uncommonly bad.
Soon after we got to our quarters, a neighboring woman, a ministering Friend, came in,
and inquired how we got along, and what kind of a meeting we had.
I replied, "`They were glad to see us, and we were not sorry we had been with them;
and that we had a good comfortable meeting.`"
She exclaimed, "`I am glad, I have wanted to go there these four months, and could not;
and when you came into the place, I prayed that you might have to go.`"
I remarked, that I had seen many who were fond of cutting out work,
and were ingenious at it, who would not put forth a finger to make it up.
She paused a little and said, "`It is no matter; for I have heard say,
that if a garment is well cut out, a bungler can make it up.`"
So I concluded I had got my returns in ready change, and would let it go at that.

We stayed at Muncy, and attended their first day meeting the 27th,
and had another at evening, in Penn`'s village.
28th. We had a meeting at Pine +++_______+++, and another in the evening at Williamsport,
somewhat favored.
I have had generally, the most favored meetings among other people,
where the doctrines of the gospel are most needed to be held forth;
but among Friends in these parts,
it has been abundantly my lot to combat a worldly spirit; beds of ease,
and a form of godliness, without the life and power--hard places to get entry,
painful to my feelings, and laborious to get along with.
We returned to Muncy, and attended their mid-week meeting,
and Fishing Creek mid-week meeting.
We then took Roaring Creek and Catawissa meetings;
in them very little of the life of Gospel love was felt,
and they were not overdone with the form.

First-day, the 3rd of 11th month, at three in the afternoon,
we had a meeting at a village about three miles from Catawissa.
From there we went to a place called Buffalo, and had a meeting in that place.
Here we parted with Henry Batten, a kind Friend and Elder,
who had been with us for several weeks, as a pilot and company; and also Chandly Eves,
who had in kindness found us horses to travel with one week,
and took our horses and fed them well during that time;
being Friends to us in the needful time, in a strange land;
so that it seemed like parting with own brothers.
We passed on to Bellefonte--two days travel.
The day following, we had a meeting with Friends and others, at Bald Eagles,
to the comfort of Friends there, and our own peace.
The next day had a meeting at Millsbury village; this also was to good satisfaction.

We had another at evening in Bellefonte village; it was large, and an open,
favored meeting.
From this, we went to Half-Moon settlement of Friends,
and attended that meeting on First-day.
Then went to Chesterfield, about fifty miles,
and across the Allegheny to a small indulged meeting.
We had a comfortable meeting with them, and had another at evening,
sixteen miles on our return to Half-Moon, where we put up with George Wilson.
Having been enabled to clear my mind of this part of the country,
we passed on for Dunning`'s Creek, and arrived on seventh-day evening,
and attended that meeting on first-day,
the 17th. This was the largest body of Friends we had fallen in with,
but they were not without the trouble of false brethren;
into a sense of it my Master plunged me, and helped me out again;
much to the relief of my mind,
and I hope to the strengthening of the hands of the upright.
We appointed a meeting at four in the afternoon, for those not of our Society;
it was a very crowded, satisfactory meeting.
From there, to Pipe Creek, one hundred miles steady travel,
in order to attend Warrington Quarterly Meeting, which was held the 25th of 11th month.
It was a favored meeting;
the presence of the Master of Israel`'s assemblies was felt to be over all,
through the several sittings of the Quarterly Meeting.
The business was conducted in much condescension and harmony.

From this, we went to Monallen meeting on fifth-day.
In the verge of this meeting, our aged Friend Abel Thomas, a faithful Minister,
spent his last days.
We made his family a visit, which was acceptable to his lonely widow.
We took Huntingdon, Warrington, and Newbury.
In all these meetings I had to come to close labor and plain testimony,
particularly in the latter.
The 1st of 12th month, first-day, we were at the meeting in York in Pennsylvania.
On third-day, we went to Faron, and had a meeting there on fourth-day.
On fifth-day, we had one at Deer Creek.
Here, I was led to speak on the subject of Nebuchadnezzar`'s setting up an image,
and compelling all others to worship it; showing the principle, its rise,
and unfeeling cruelty; that it was very far from a Christian spirit.
I was told after meeting, that there was a man at meeting,
who had for a long time refrained from eating flesh of any kind,
and had got so strong set in it,
that of late he had compelled his family to refrain from eating flesh,
against their belief; not allowing it to be cooked, or eaten in his house by anyone;
and the reason he gave, was, that his God commanded him to do so,
and that it was his duty to make his family comply with it,
whether they saw it a duty or not.
Friends were rejoiced, in hopes the communication would be of use.
The account was truly strengthening to my mind, on my own account,
for I had weighed it for several days, under great depression of spirits.

On sixth day, we were at Bush river meeting,
and seventh day we had a meeting at the Forest.
First day, we attended at Little Falls; it was a lively, comfortable meeting.
Second day, we rode to Gunpowder, and met with Friends of that place.
There, were sympathizing Friends,
who had to wade along under the pressure of a gainsaying, worldly spirit,
in their professed brethren.
11th, we attended the upper meeting in Baltimore.
12th, we attended the lower meeting.
While in this place, we made our home with John McKim; stayed until first day, the 15th,
and attended the upper meeting, where there appeared much rubbish.
My good Master enabled me to bear a faithful testimony among them,
and rewarded me well for it.
We had a meeting the same day, about five miles from the city, towards Elk Ridge.
Third day, we had a meeting at Elk Ridge.
Fourth day, we went to Bush Creek, and next day had a meeting there.
Sixth day, we attended Sandy Spring Monthly Meeting.
Seventh day, we went to Indian Spring, and attended that meeting on first day.
Second day, we rode to Washington, and had a meeting in the city on third day evening.
Fourth day, we had a meeting at Alexandria in the evening.
Fifth day, we rode to Waterford, and repaired our wagon on sixth day,
and had a meeting there on seventh day.
First day, at Goose Creek meeting.
Second day, we had a full meeting at South Fork.
Third day, we returned to Waterford.

On the 1st day of the year, 1817, we attended Fairfax Monthly Meeting,
it was comfortable and favored.
2nd, fifth day, we attended Goose Creek Monthly Meeting, and next day rode to Barclay;
had a meeting there on 7th day.
On first day, we attended Hopewell meeting, where I was much enlarged, in clear,
settling testimony, which has been the favor given at several meetings.
Second day, we had a meeting at Middle Creek,
where I had to dig about the fruitless fig trees.
Third day, were at Ridge, a small, weak meeting; from here to Winchester, in Virginia,
and stayed the night with Goldsmith Chandler.
From this, we went to Centre, and had a meeting.
The day following, we attended Hopewell Monthly Meeting.
Here I was led into feeling sympathy with the afflicted,
who wore sackcloth of mourning for their inner garment,
and my horn was filled with the oil of encouragement to anoint them.
11th, we had a meeting at Crooked Run.
12th, First day, we attended Mount Pleasant meeting.

Second day, we had a meeting at Back Creek.
15th, at Dillin`'s run.
This closed our visits in Baltimore Yearly Meeting.
From this place, we set forward for Redstone, and it took the 16th, 17th, and 18th,
to get across the Allegheny Mountains, it being severe, snowy weather,
so that we suffered much with the cold,
but were favored to get into Sandy Creek glades on first day, just at evening,
among Friends, who received us kindly, and did what they could to make us comfortable.
We had a comfortable meeting with Friends on second day,
and drove to Providence on third day.
Fourth day, we attended Redstone Monthly Meeting, held at Providence,
where they made me think of Ezekiel`'s dry bones in the valley,
which needed a shaking to bring them together; for they had got wide apart,
and they needed the spirit of the Lord to move upon them, to make them live.
My Lord enabled me to sound an alarm.

From here we went to Centre, where I was taken sick, and continued two days.
On seventh day, the 25th, we had a meeting there, and first day were at Providence.
27th, we went to S+++______+++, and had a meeting with them on the 28th,
and returned to Providence the same evening.
29th, came to Redstone, and had a large meeting there on the 30th,
where I found hard work enough to get along to my own satisfaction.
After meeting, we rode to Westland, and attended their Select Quarter on sixth day,
Next day was their meeting for worship and discipline.
Here I had to proclaim the word of the Lord against tattlers, liars, mischief makers,
and spreaders of discord among brethren.
It was a sifting time, but my good Master carried me through all,
and over the head of all opposition.
Blessed be His name!
On first day, the 2nd of 2nd month, I was at that particular meeting.
3rd, were at Pike Run meeting; returned to Redstone and attended their first day meeting.
Second day, we returned to Providence,
and proceeded to have a meeting in Robertstown village.
Next day, we had a meeting at C+++______+++town, and proceeded to visit Sandy Hill meeting;
and at evening we had a meeting at Uniontown.
We returned to Centre, and had an appointed meeting there.
First day, we were at Providence again.
Second day, we had a meeting at P+++_______+++, and another at evening;
the day following at Colwellsville.
This concluded our visits in this part of the country.

When I was about to take my departure, Friends solidly told me,
I need not be uneasy about my labors being so close, and plain at all their meetings;
that there was a cause for it, and they were satisfied with my labors.
So I passed away from them, feeling thankful to my Lord and Master,
for preserving and keeping me right;
much desiring that the Lord may bless the labors to their help.
After this, we set forward to cross the Allegheny Mountains into Virginia,
and got to Dunning`'s Creek on 7th day afternoon, and attended that meeting on first day,
23rd. 24th, we lay by on account of a heavy snow storm.
25th, we had a meeting in Bedford Village, and then went to Little York;
reached there 7th day evening, and attended that meeting on first day,
the 2nd of 3rd month.
Second day, we rode to Lampeter.
Third day, we attended Sadsbury Monthly Meeting, held at Lampeter.
Fourth day, we had an appointed meeting at Sadsbury.
Fifth day, we had a meeting at Fallow Field.
In these parts my exercise was heavy, and my labors painful;
having to combat an infidel spirit that was creeping in among Friends in many places.
It is a dark, defying spirit, but the Lord harnessed me for the day,
and enabled me to wash my hands from the blood of all men in these parts.
Oh, good is the Lord, and greatly to be feared, and highly to be praised forevermore!

On sixth day, we rode to Wilmington, in the State of Delaware.
Here we stopped and got our wagon mended.
Seventh day, we rode to Apaguima, and attended that meeting.
First day, at Smyrna; third day, at Little Creek; fourth day, at Camden.
In these parts, Friends`' meetings are generally very small,
where once there were large meetings; but Friends in this land formerly held many slaves,
and many of them refusing to free them, went out from Friends in a bitter state,
and carried their families with them.
Some zealous people in that land, who refused to join Friends for several years,
because they held slaves, after they got clear of them,
came forward and joined our Society; and had it not been for these,
there are several meetings that would now have been extinct,
which are kept up by the offspring of these humble, faithful people.
Friends there, giving me this account, I thought it just to give it a place in memory.
We had the opportunity to be in their company several times;
they appeared to be a zealous people, much in the simple innocency;
while the offspring of Friends, who were negro masters, are now the tyrants of the land.
A standing proof of the evil of slavery, and the blast such left on their offspring.

On fifth day, we had a meeting in the State House, at Dover, which was large and favored.
This is the handsomest village I saw in Delaware.
Sixth day, we had a meeting at Motherkill.
Seventh day, we were at Milford, and in the evening had a favored,
satisfactory meeting at a small village called Fredericka.
First day, we were at Cold Spring meeting.
The house was very full, and the people quiet, and attentive.
Here is a meeting, that has, I think, three or four small families to keep it up.
They live wide apart, and are not very zealous, so that in this,
and some other places in these parts,
it looks very discouraging as to the testimony of Truth being held up long.
In Bowerstown, we had another large meeting the same day.
Hereabout the people were more attentive to get to meetings, than at some other places.
Second day, had a small meeting at Milton; then took the meetings of Centre,
Northwest Fork, Marshy Creek, Choptank, and were at Third Haven meeting on first day.
Next day, we were at the Bayside.
Our meetings in this part of the country are generally small, and dreary getting along;
for it does seem that the mildew of slavery,
and the rust of barbarity had nearly consumed all the humane,
benevolent principles of the Gospel; and Infidel darkness,
and savage barbarity are taking the room in many minds.
Sorrowful to reflect upon!

Third day, we were at Tuckahoe Neck, and fourth day at the Neck meeting.
Fifth day, we rode to the head of Chester, and had a meeting at that place on sixth day.
Seventh day, we had a meeting at Cecil.
First day, we had a meeting at Chester Neck.
This ends our visit in that Quarter; and now in looking it over,
I felt deeply to acknowledge,
that although deep and sorrowful often have been my wadings in this land,
and dark and gloomy have been many of the hours, yet good is the Lord, that in,
and through it all, His holy arm has hitherto borne me up,
and sustained in times of sharpest trials.
He showed me clearly what His will was that I should do, and gave me fortitude,
that I feared not the face of the sons of men, and ability to do His will at all times,
and now favors me with a return of a rich and joyful reward.
Blessed and adored forever be His Holy name!
Oh, may I evermore serve Him, with a ready and willing mind!

Second and third days, we spent on our road to Maryland,
and had a meeting at East Nottingham on 4th day.
Next day, at West Nottingham.
Sixth day at Eastland, and seventh day at Little Britain.
On first day, the 6th of 4th month, we crossed the Susquehannah river,
and went to Deer Creek meeting.
Next day, we returned to Dunmore, and had a meeting there on third day.
Fifth day, had a meeting at Darien.
Sixth day, we were at Westport, and seventh day at Spencer.
First day, the 13th, reached New Garden, in Pennsylvania.
14th, we were at Hockesson.
15th, at Stanton.
16th, at Wilmington: this is a large meeting.
17th, at Chichester.
18th, at Chester; both these were small meetings.
In this last little tour, the Gospel spring ran lively.
I was led into the state of several meetings, and enabled to clear my mind,
to the satisfaction of my Friends, and my own peace.
Though there is much rubbish that needed to be removed out of the way,
there are many well concerned Friends in this part of the land;
so that the testimony of Truth may yet be held up with clean hands.

From here, we went to Philadelphia, to attend the Yearly Meeting, which was large.
Several weighty subjects came before it, which took up much time,
and caused deep exercise to the rightly concerned and discerning part of Society.
On one of these subjects, I felt my mind weightily impressed,
and forcibly drawn to give a sentiment, and my reasons therefor; for which I got a quick,
sharp reply, and a heavy censure in the face of the meeting.
This occasioned deep searching of heart for some hours,
until my good Master was pleased to show me that all was well, as I had done His will;
which gave my troubled mind relief.
The day following, the subject was brought up again,
and after much reasoning had passed on it, feeling my mind weightily impressed,
I saw my way clear to speak to it again, and proceeded calmly, and deliberately:
being enabled to treat the subject so clearly in all its parts,
feeling the authority of Truth to accompany the words, that there was no reply.
That subject was soon disposed of for that time,
and the business passed on pretty harmoniously for the day.
After this, there was one subject, that took up much time to no good purpose;
there being much of a libertine spirit in this country,
that is inclined to run out of order, and some day will give Friends much trouble.
The meeting closed in a favorable quiet, on sixth day.

On first day, following the Yearly Meeting, we attended Arch street meeting,
and in the afternoon we were at the Northern District meeting.
Second day, we were at Abington Monthly Meeting.
Here I had some close work to do, yet it was acknowledged there was cause for it.
Third day, we attended Byberry Monthly Meeting,
and fourth day had an appointed meeting in the same house.
Fifth day, we had a meeting at Frankfort.
Sixth day, we attended Germantown in course, and after meeting we went to Plymouth,
and put up with Jacob Albertson.
First day, the 4th of 5th month, we attended that meeting.
Second day, we were at Gwynedd meeting.
Third day, were at Upper Dublin.
Through this part of the country I had many deep conflicts of spirit to endure,
being much led into close, plain labor; many of the aged so buried in the earth,
and some have fixed themselves in a security that will fail them in the end,
and seemed determined not to be aroused from their couches;
while the young are taking their flight upon the wings of the morning of their day,
in pursuit of the gaudy trimmings of the world, and airy, but poisonous notions,
that are too prevalent in our land; so that mourning has been my lot,
and my morsel has been eaten as with bitter herbs.
The few who walk faithfully in the path that is cast up for the ransomed,
have to keep much on their watch, and walk in fear, lest the glitter deceive them,
or the charms of the enchanter draw them out of the way of safety.
Oh, may the Lord remember this once favored land,
and shake their earth and their false heavens,
and gather the people to a foundation that cannot be shaken!

The 7th of the month, we attended Abington Quarterly Meeting of Ministers and Elders,
held at Horsham, and the meeting for worship and discipline on fifth day.
Sixth day, had a meeting at Radnor.
Seventh day, at the Valley.
First day, the 11th, at Charleston, and in the afternoon was at Providence meeting.
Second day, at Potts Grove.
13th, at Exeter.
14th, at Reading.
15th, at Maiden Creek.
16th, we drove to Richland, almost forty miles.
17th, we parted with our beloved Friend, and agreeable companion, Jacob Albertson,
who had been with us about twelve days.
First day, the 18th, we attended Richland meeting.
These latter meetings were generally small in number of Friends,
yet many others came in when notice was given--a
token that they lived peaceably with their neighbors.
Though we fell in with a number of well concerned, faithful Friends,
there is far too much assimilation with the spirit and customs of the world,
and a mournful letting down the ancient simplicity and faithful
integrity that once so beautified our Society;
and if they cannot be prevailed upon to return to the true Shepherd of Israel,
and abide in His fold, the effect will be a great falling away,
and running into the wilderness of vain imaginations;
from which they never will all return--a heart aching view of the times.

Second and third days, we had meetings at Plumstead and Solesbury,
and went to John Balderson`'s. Fourth day, we attended Buckingham meeting.
It was very large,
and my Master gave me not a word for the people--a great disappointment
to them--yet I felt great peace in being resigned to the Lord`'s will,
believing He knew best, what was good for them and me.
Fifth and sixth days, we were at Makefield and Wrightstown;
in both meetings I had satisfactory service.
On seventh day, we appointed a meeting at Middleton in the morning,
and another at four in the afternoon in Newtown, where was a large gathering,
mostly not members of our Society.
I soon found that my lips were sealed, which caused deep searching of heart,
and close enquiry whether the appointment was right,
but could not see anything amiss on my part, and was favored to settle down resigned,
in a quiet feeling of mind.
Almost at the same instant, in stepped a public Friend from New England,
on a religious visit.
I was glad to see him.
It was not long before he was well furnished with good matter and Gospel authority.
It was a favored time, and truly strengthening and comforting to my mind,
standing resigned to the Lord`'s putting forth.
After meeting, the Friend told me that he heard of the appointment,
and felt a draught to come to it, but hesitated some time,
thinking he might be in the way, or intrude,
until it was so heavy on him that he was afraid to forbear,
and thought he now saw it was best to believe and obey his good Master;
for had he not delayed, he might have been in better season.

We returned to Buckingham, and attended that meeting on first day, the 25th,
and way was opened to relieve my mind pretty fully.
After meeting, we went to Thomas Carey`'s, a Friend, who had been with us several days.
On second day, we had a meeting at a place called Milton, and on third day,
came the meeting for Ministers and Elders of Buckingham Quarter, and on fourth day,
the meeting for worship and discipline.
Though I passed this meeting in much exercise,
I had no liberty to impart to them what I saw and felt, but enjoyed a peaceful mind,
in being willing to fill up my measure in silent suffering.
After the Quarter, we went to Falls, Penn`'s Manor, and Bristol,
and had meetings at each place.
At the latter, my mind was clothed with Gospel life and love, and utterance given;
the like I had not felt for a length of time,
for it had been much my lot in this land to labor in a plain, simple style,
not at all pleasing to the tasty, but best pleasing to my Master,
or He would have given it otherwise, and I was content to please Him.
From here, we returned to Philadelphia, to John Morton`'s, our former home.
Third day, attended the Northern Meeting,
had nothing for them but the example of silence, which has often been my lot of late,
and however trying to the people this may be,
I find my peace much depends on keeping resigned to the Lord`'s will,
and being careful not to be drawn to utter words by the spirit of the people,
without Gospel authority, for this would never profit the people,
or build up the ways of Zion.
After this, we attended Green street, Marion, and Haverford meetings.
In these last, I was enabled to clear my mind in a plain, close way,
so as to feel quite peaceful.

On second day, the 9th of 6th month, we had a meeting at Darby,
an ancient settlement of Friends and a large meeting; but an enemy had got among them.
I was led in a very close and pointed manner, and had to tell them what it was,
and how it was that the unity of the Spirit of the Gospel was formed with,
and among brethren, and that it was kept only by abiding in the Truth,
that first formed the unity, and those who went out of the Truth, broke the unity.
In vain it was for those to call for unity who had gone out of it;
for those who kept in the Truth,
were bound in the bonds of the Gospel to stand by the Truth and support its honor.
There was no other way to enjoy the unity,
but for those who were out of the Truth to return to their first love,
and mend their own faults, as none other could mend them for them;
that would heal the breach, and their brethren would receive them with open arms.
Some of them turned and twisted about, and some wept.
After meeting, I was told by a Minister of that place, that if I had lived among them,
I could not have gone through the situation of their meeting more exact;
and with tears running down her cheeks, expressed, she hoped it would be of use,
and do them good--a humbling time to me,
in that it was a renewed confirmation that I was in my Master`'s field of labor,
and that He was leading me about to do His will;
and that I may be preserved to do it is my chief desire,
for this have I chosen for my food and my drink.

We passed from here to Springfield, Newton, Middletown, and Providence,
having meetings at all these places,
and felt the arm of the blessed God of Jacob to be underneath,
to bear up and carry through all the exercises allotted me.
On seventh day, we had no meeting, it being market day.
First day, the 15th, we were at Williston in the morning, and at Goshen in the afternoon,
both large, favored meetings.
Second day, we were at Westchester, and third day, at Birmingham.
Between these meetings we visited West-town school,
which appeared to be kept in beautiful order, and much simplicity.
Fourth day, we were at Concord.
Fifth day, at Center.
Sixth day, at Kennet.
Seventh day, was at Marlborough.
First day, the 22nd, was at Kennet Square.
Second day, at London Grove.
From there we went to Dunmore, and attended their meeting on fourth day.
Fifth day, at Little Britain again.

This ends our visit in Pennsylvania, for the present.
We crossed the Susquehannah to Deer Creek, and put up at the house of Samuel Coles,
and attended that meeting on first day, the 29th. Second day, had a meeting at Dublin.
Third day, we had a meeting at Thomas`' Run.
4th, we appointed a meeting at Bel Air.
On fifth day, we attended the Little Falls Preparative Meeting.
It was trying to my mind, to go to so many meetings, where I had so lately been,
but my good Master was kind and true to me, and gave me to see what he sent me back for,
and ability to do all he required, and rewarded well my obedience.
After meeting, we rode to Baltimore.
Being much fatigued and some unwell, we lay by until first day, the 6th of 7th month,
where we attended both meetings in the city, where painful,
heart-aching labor was my lot.
Second day, rode to Alexandria.
3rd, rode to Occoquan, and had a satisfactory meeting there in the evening.
Fourth day, we rode to Dumfries, and had a meeting there just at evening.
5th, passed on to Fredericksburg.
Sixth day, we had a satisfactory, comfortable meeting at that place.
After meeting we rode to Carlisle, and lodged with Joseph Terril.

Next morning we reached Cedar Creek Monthly Meeting, where I had close labor;
showing that those who ruled in the Lord`'s house,
ought not to lord over God`'s heritage; for where any lorded over their brethren,
the lambs could not grow up in good liking, and the flock was not healthy.
Though some of the great ones looked somewhat shy on me, I felt such serene peace,
that I was satisfied.
I had the Lord for my leader, with which I was content, let what would come.
After meeting, we went to Micajah Crew`'s to dinner, and proceeded to Richmond,
and attended that meeting with the few Friends of that place,
and another at four in the afternoon, appointed by Isaac Hammer, a Dutch Friend,
from Tennessee.
He was small in the Ministry, but sound and weighty in spirit.
Both these meetings were attended by many not of our Society,
and Gospel truths flowed to them freely.
Second day, the 14th, we went to Petersburgh.
Third day, rode to Gravelly Run, and had a meeting at 5 o`'clock in the afternoon,
and lodged with John Andrews.
Fourth day, we journeyed to Stanton, and attended that Preparative Meeting on fifth day.

The meetings of Friends here are generally very small,
many having moved away on account of slavery,
and many of the young people marrying into slave-holding families,
and of course go from Friends;
so that the prospect is that Friends must cease to be a people in the slaveholding countries,
unless a great alteration should take place with the inhabitants at large,
which there is no prospect of, short of the strong hand of Divine interposition.
For to see the poor blacks crowded into little huts, like hogs in a pen,
or sheep in a yard,
all ages and sexes together--and their masters strive to have it as much so as they can,
in order to eradicate all feelings of humanity, honor, modesty,
or virtue--and plead it is best for the blacks,
that they are less sensible of their depravity.
This is not all;
the masters even sell their own Mulatto children to make their white children rich.
In general, the blacks are talked to, and used more like brutes than the human family.
Children from eight to twelve years of age, would talk to aged,
gray-headed men and women, and call them black dogs,
and worse names than a civil man would call his dog by;
yet the poor things dare not show any resentment.
I often said in my heart, "`How long will this be allowed?`"

While my heart was ready to melt with compassion for the black people,
my thoughts were often turned to look over the white people`'s situation;
a people endued with superior light and talents, capacitated to be eyes to the blind,
and leaders of the ignorant; but are so far the reverse,
that they seem bent to display the utmost stretch of their power,
and gratify their own wills,
and to grind down the poor blacks as much below the dumb animals as they can.
Thus, in musing and looking over the state of this wretched country,
and seeing that the whites, for a few days of fleeting pleasure,
were preparing themselves to the utmost of their power,
for the never ending ages of eternity to be the companions of demons,
and for that place where the fire shall never be quenched;
their worm dies not and the fire is not quenched.
And to reason with, or preach to them seemed to have no more effect,
than water poured upon a rock.

This appears to be the state of the ruling class of the people,
while there is another class who use their slaves more humanely;
and still another class who would be glad to free their blacks,
if the laws of the land would protect them.
And these last are despised by the others; so that musing on their situation,
my sleep often left me, my appetite failed for food, and I became feeble;
feeling a necessity laid on me to be faithful in every place,
and with all people to whom I had anything in charge from my Master,
feeling a heavy woe if I gave back,
so that my companion often thought I hazarded my life.
I have no language to set forth so that another can
realize what I passed through in these varied exercises,
unless they are placed in a similar situation.
I verily feared I should lay my bones in this gloomy land.
Yet, marvelous to reflect upon, I was never once drawn into action,
either public or in private, but that the fear of man was taken from me.
They appeared no more to me than grasshoppers, in the time of action;
and I felt no lack of matter or language, to confute their reasoning,
or confound their boast in favor of slavery.

I suppose I was attacked in my travels in these slave states,
more than one hundred times; and sometimes by the learned and great.
So that in all of these disputes my great and good Master furnished and helped me,
they were always brought to acknowledge, (with but two exceptions that I remember of),
that it was wrong to hold their fellow creatures in slavery,
and were convinced it was contrary to every attribute of the Divine being.
And then would exclaim, what shall we do, we have got them,
and it will not do to free them and let them be among us;
they would overrun us--and to wind up, we must keep them in slavery,
and as ignorant as we can for our own safety;
and seemed determined not to admit the thought,
that it was the Lord who had opened their eyes, and if He was sought unto, I could,
and doubtless would, grant wisdom and open a way,
which would be right and good for both black and white.
But, as there is a standing against Divine justice and mercy with their eyes open,
God will not be mocked, neither will His justice always slumber.
O, may the Lord, in the counsels of His great wisdom, open a way for the oppressed,
to be set free with out the effusion of a river of blood.

Sixth day, the 18th, we returned to Gravelly Run.
19th, attended that Monthly Meeting, and was comforted,
having the company of a number of solid, lively spirited Friends.
First day, the 20th, we attended that meeting again,
and attended an appointed meeting at five in the afternoon at Petersburg.
21st, rode to Burleigh, and attended an appointed meeting there in the afternoon.
22nd, we rode to Staunton.
23rd, rode to Vicks; having stopped on our way at Jerusalem,
and had a satisfactory meeting in that place.
24th we got our carriage mended.
25th, we rode to Murphysborough and had a meeting there at five in the afternoon,
among staunch Presbyterians, who came on their guard; and far beyond my expectation,
He who has all power given Him in heaven and earth was pleased to open a gentle stream,
in Gospel light and love, which drew the attention of the people,
so that they forgot their coats of mail, and the stream increased to a river.
Gospel truths flowed freely and forcibly, and settled solidly on the meeting,
and it ended quietly.
So that the people acknowledged they were satisfied;
that what they had heard were gospel truths.
And the Lord was pleased for His own name`'s sake to exalt the Truth this day,
in the eyes of the people.
Blessed be His holy name.

Seventh day, 26th, we rode to Rich Square, and went to Jesse Outland`'s. First day, 27th,
we attended that meeting and had good service.
28th, we set forward for Mattimuskeet,
and arrived there the 31st. We had a meeting there with Friends, 1st day of 8th month.
Seventh day, we had a meeting with the Baptists up the Lake.
First day, the 3rd, we had a meeting at the lower end of the Lake, in a Methodist house.
The meeting was large and the people were civil and attentive.
In this place I saw a master beat a colored person wickedly with a knotty cudgel.
It moved my feelings so, that when the master got over his fret,
I told what I thought of such conduct.
He seemed to resent it for a while, and rose three times from his seat,
either to frighten or give me a blow.
But it did not move my feelings with fear at all.
I kept my eye fixed on his, and continued my speech until he sat down, and kept quiet,
hung his head and heard me through,
then acknowledged it was not right to hold them in slavery, or use them so.

Upon this, after making a few remarks, we closed the discourse and parted.
I left him with a loaded mind, which I hope will produce some good effect.
We had on meeting the same day on the South side of the Lake,
at the Baptist meetinghouse, which was also large, and the people gave good attention.
Hereaway, the Lord in the riches of his mercy and love to the people,
plentifully furnished with matter and utterance,
though much of it seemed to me like the rain that falls on the barren land and rocks,
where it can make no entrance to profit,
but has to make its way to the valleys and streams,
and return to the fountain from which it was taken.
The Lord`'s will must be done.
The barren land must be rained on as well as the fertile soil.

After this last meeting we rode eighteen miles on
our way towards Core Sound to a place called Germantown,
where we had a meeting with a parcel of slaveholders,
where the Lord my Redeemer strengthened my mind to bear a faithful testimony,
for the cause of Truth and Justice.
Third day and fourth day we journeyed to Washington.
Fifth day we had a pretty full meeting in that village,
where the Most High for His own name`'s sake, and in mercy to the people,
was graciously pleased to give strength and ability to bear
a faithful testimony to the noble cause of justice,
mercy and Truth, in that authority which prevailed over all opposition,
and Truth reigned for that time.
Sixth day, the 8th of the month, in Newberne, my companion was taken very sick;
also our pilot and myself became quite unwell.
This brought deep thoughtfulness over my mind, it being a very sickly,
dying time in all the lowland country that we could hear from, with man and beast.
We saw hogs and horses dying by the side of the road frequently, as we traveled.

After considering our situation seriously, and asking counsel of my Master,
I felt my mind clearly at liberty to turn our course for Contentney,
and get into the hilly, healthy country, as soon as we could.
It took us until the 12th to get there.
Being much fatigued and sick, we stopped with Friends here a few days,
and attended their meeting on fourth day.
Fifth day we attended another meeting in those parts.
Sixth day we had an appointed meeting at Holly Springs, to good satisfaction.
We then set forward for Eno, and arrived there the 18th of the month.
We stayed about here several days.
I had a meeting about five miles from Eno, much to the relief of my mind.
My companion was prevented from being with me, by indisposition.
We attended Eno meeting as it came in course.
Seventh-day we attended Providence Monthly Meeting.
I was well satisfied in being with Friends here.

First day, the 24th, we attended New Garden meeting, North Carolina.
At this parting opportunity, the Master of Israel`'s assemblies,
favored with His life giving presence, to the gladdening of many hearts.
On second-day we lay by, and my companion becoming more sick, and myself quite unwell,
we felt most easy to turn our course for Alexandria,
where was a physician with whom I had formed some acquaintance,
under whose care I felt desirous of placing my companion.
On third day we set forward, the distance being over three hundred miles,
the way we traveled.
The weather being very warm, and our horses much fatigued and we both sickly,
it took us nine days to reach there.
By this time my companion had become so ill, that I was somewhat alarmed.
The doctor was soon sent for; he readily gave medicine which had a good effect,
so that in about a week, my companion was getting smart and lively.
While here, I attended Friends mid-week meeting, and their fore and afternoon meetings,
the 7th of 9th month.
In all these meetings I had good satisfaction in sitting with Friends,
though I had not much public service among them, but felt that peace that satisfied me.
We continued here until fourth day morning,
when we moved forward to attend the little meeting in the city of Washington,
where our Friends showed great gladness to see us.
It was truly comfortable to be with them again.

On fifth day we moved on towards Baltimore.
The weather yet warm, and my companion not having got strong,
we went no further than Samuel Snowden`'s, who received us kindly.
We stayed here (my companion being feeble,) until seventh day.
Then went to Baltimore, to our old home at John McKim`'s,
who with his wife received us kindly.
First day, the 14th, we attended the upper meeting in the morning.
In this meeting I was led largely to warn Friends,
against speculative inquiries and embracing unfounded notions;
for this would lead to disbelief of all former revelations,
as testified in the Holy Scriptures;
and to reject the Gospel of our Lord and Savior Jesus Christ,
as testified by the apostles; and would finally end in dark infidelity.
And the propagators of those dark principles would often
go or creep about slyly under the mask of religion,
and bring forward questions calculated to puzzle the unguarded mind.
For should they show at once what they were at, they would alarm and lose their object.

And just so the devil works; first get hold, and then lead on to destruction;
and so do those first get the mind shaken, and then introduce their dark principles;
and they creep about to do it under the mask of religion,
as the serpent crept on his belly.
I had to warn Friends to be on their guard.
While I was on my feet speaking, there were two members of our Society, who sat near me,
(and who I had noticed to be quite active in their meetings for
discipline,) who got up with an air that showed discomposure,
and went out, and round,
and came in at the back door and placed themselves as far from me as they well could;
but through mercy it did not jostle or move me.
After meeting a number of Friends expressed their
full satisfaction with my being with them as I was.
My good Master richly rewarded me for blowing my
ram`'s horn faithfully against the harlot`'s walls.
In the afternoon we attended the Old Meeting.
Here I had to dip deep in sympathy with the oppressed, and to mourn with the afflicted,
and to encourage them to steadfast patience,
that they might obtain the immortal crown when time with them should be no more.
Third day, we drove to Gunpowder.
4th, attended that meeting.
Notice being given, it was large and much favored.
Fifth day, rode to Little York.
Sixth day, we rode to Columbia, on the Susquehanna,
arriving there in season to have a meeting in the evening, which was full,
and closed to my satisfaction.
Seventh day, we drove to Robeson, forty-five miles.

First day, the 21st, we attended that meeting in Pennsylvania.
We lodged at Rebecca Scarlet`'s. Second day, we drove to West Caln.
Third day, we had a meeting there.
Fourth day, we were at East Caln meeting.
Fifth day, we had a meeting at Bradford Sixth day, we had a meeting at Downington,
Seventh day, we had a meeting at Uwchland.
First day, 28th, we were at Bradford again.
Second day, we had a meeting at Pikeland.
Third day, 30th, at Whi+++_______+++. Fourth day, 1st of 10th month,
we lay by at our esteemed Friend, Jacob Albertson`'s. The next day,
attended their Monthly Meeting, at Plymouth.
In the meeting for worship, I was entirely shut up.
In that for business, my mind was furnished in a short testimony with a few, clear,
plain remarks that settled on the meeting like dew upon herbs.
After meeting we went to Germantown.

Sixth day, we passed through Philadelphia, and crossed the Delaware at Waterford,
and went to Benjamin Cooper`'s, in New Jersey.
Seventh day, we had a meeting at Newton.
First day, 5th, we were at Westfield in the morning, and at Chester in the afternoon.
Second day, we had a meeting at Evesham.
Third day, we were at Easton meeting.
Fourth day, we attended meeting at Upper Evesham.
Fifth day, we had a meeting at Cropwell.
Sixth day, had a meeting at Haddonfield, and returned to Cropwell,
and attended Evesham Monthly Meeting; and had a meeting appointed at four o`'clock,
at the Crossroads, among Presbyterians,
where Friends had seemed very backward in consenting for me to appoint one.
Yet, several Friends attended and frankly acknowledged after meeting,
that the appointment was right, and that Truth arose in dominion,
beyond what they had any idea of.
It has been much my lot through a number of meetings, to stand much alone,
and made to feel the sure stepping stones,
there being so much ease and self-security in this part of the land;
so that if the bow is not drawn in full strength, the arrow never enters.
Yet, there are a number who are endeavoring to be what they ought to be.
But there are so many dead weights around them,
I think it must often cause them deep wadings to keep their standing at all times,
and fill up their measures.
May the Lord keep and support them and add to their number!

First day, the 12th, we attended Newton meeting again, and traveled twelve miles,
and attended an appointed meeting the 4th hour in the afternoon,
at a place called Green-tree.
From here we returned to Haddonfield, and attended their Monthly Meeting on second day,
and rode to Woodbridge, and had a meeting at that place on third day.
Fourth day, I attended a little meeting at Chestnut Ridge.
Fifth day, we had a meeting at Woolwich.
Sixth day, had a meeting at Upper Greenwich.
Seventh day, we had a meeting at Penn`'s Neck.
First day, the 19th, we attended Piles grove meeting.
Second day, we had a meeting at Salem, and third day, at Alloway`'s Creek.
Fourth day, we had a meeting at Greenwich, Cumberland County.
The next meeting was at Morris River, and another at Morris River Point.
Seventh day, we had a meeting at Cedarville, and returned to Morris River,
and attended that meeting again on first day,
the 26th. I had much Gospel labor in this part of the country.
A number of the meetings I have noted, were where no Friends live.
May the Lord bless the labor!

We next went to Cape May,
where we found a little meeting much laid waste by the bad conduct of a Minister.
The next we went to Great Egg Harbor.
Here we found a small, weak meeting.
We crossed the water to Little Egg Harbor, and found a body of Friends.
Among them there was a number of well-minded, lively-concerned members;
we had a comfortable meeting with them.
We passed on to Martha Fearney`'s, and had a meeting there;
and had another at Bastoe Furnace, and though they were civil,
they were a hardy people to preach to.
We had a satisfactory meeting at the Bank, where we stayed the night with David Mapes,
a colored man, who is a respectable Friend.
From here we returned to John Hallock`'s, at Tuckerton, the 4th of the 11th month.
Fourth day, we went to Barnegat.
Fifth day, we had a small meeting with Friends there.
Sixth day, we went to Squanham, and had a meeting with the inhabitants of that place,
and seventh day, had a meeting at Squan.

Though I have thought best not to make many exposing remarks,
yet there is one subject I feel most easy to notice.
In passing through the southern and southeastern parts of Philadelphia Yearly Meeting,
I found active members in the Society, carrying on the distillery business,
buying up grain to make whisky of, and selling their liquor by wholesale or retail,
to anyone, or in any way, that would bring gain to the seller.
Some merchants sold by wholesale, and some by retail; others, who kept public houses,
would sell by small measure to their neighbors, until they were drunk.
These different branches were carried on in several parts of that Yearly Meeting,
and I was credibly informed, also, to some extent in the city of Philadelphia.
This subject lying heavily on my mind,
I felt a necessity at times to labor faithfully with Friends thereon,
for which I was heavily censured by some.
Notwithstanding this,
I was made willing to bear a faithful testimony against
those evils whenever my Master required it of me;
who renewed the bow in my hand, which caused sundry attacks in a private way.

When I came to bring into view the inconsistency of destroying so much of the grain,
that should be for food; and so far from supporting human nature,
it became a great destroyer of it, worse in many places than the sword;
and so also with the sweet of the cane,
and the goodly juice of the grape made into spirits,
that it augmented the burden of slavery.
When I brought these views before Friends in a calm, clear and solid manner,
with the baneful effects thereof in our land, and the inconsistency for Friends,
professing as we do, to be actors in and actual encouragers of all those evils,
so incompatible with the philanthropy and precepts of the Gospel,
that they could not be reconciled; these reasons,
with the energy that my good Master favored me with, both in and out of meetings,
silenced all opposition;
and sometimes brought to a full acknowledgment of the truth of the sentiments.
Yet, through all these painful straits,
I had consolation in finding my Great and good Master always true to His promise,
that He would be with me in all my trials,
a ready and sufficient helper in every needful time.
Gloriously good is He in all His attributes; worthy to be honored, worshiped and obeyed,
and His Holy name praised forevermore!

First day, the 9th of 11th month, we attended Shrewsbury meeting.
10th, at Long Branch.
11th, at Poplar Swamp, I and a meeting in the evening at Edington.
All these were favored, satisfactory meetings.
12th, attended the Select Quarterly meeting at Shrewsbury, and at four in the afternoon,
we had an appointed meeting in the neighborhood of Black Point,
which was acceptable to the people, and satisfactory to us.
13th, attended the Quarterly Meeting for worship and discipline; in both of which,
it was my lot and business to fill up my measure in suffering silence;
being made sensible there was more of a disposition to hear tell of good things,
than to practice them.
14th, we had a meeting at a place called Highlands.
15th, at Middleton village.
First day, the 16th, we attended Shrewsbury meeting,
and had another in the afternoon at a place called the Falls.
17th, we rode to the East Branch,
and had a meeting with the people there on the 18th. 19th,
we had a meeting at Upper Freehold.

In most of these meetings, my Lord and Master favored me with His Holy presence,
and caused the Gospel spring to run freely,
and settle on the people as the dew on the tender grass.
In some of the old meetings my Master laid it on me to dig about the fruitless fig trees,
and endeavor to enliven the soil with Gospel counsel.
20th, we were at Upper Springfield meeting in the morning,
and at another meeting in the afternoon at the Mount.
21st, at Vincentown, and another in the evening at Mount Holly.
22nd, had a meeting at old Springfield.
First day, the 23rd, we were at Mansfield meeting.
In some of these last meetings, I was not only constrained to dig about them,
but closely to examine the roots, and show the people what manner of fruit, old, corrupt,
unsound roots would bring forth, warning the people,
and closely admonishing some to seek the Great Healer of maladies for soundness.
24th, attended the Select Quarterly Meeting of Burlington, held at Chesterfield,
and next day the meeting for worship and discipline.
26th, we had a meeting at Rancocus.

27th, we attended Burlington meeting, where I was led into plain, close labor,
for which I enjoyed peace.
28th, we had a meeting at Lower Mansfield.
29th, at Bordentown.
First day, the 30th, attended Crosswicks meeting,
and in the evening had a large meeting in Trenton; the people sat quiet.
The 1st of 12th month, second day, we had a meeting at Stony Brook.
2nd, we went to Kingwood, and had a meeting in that place next day,
which was relieving to my mind.
4th, we went to Hardwick, and had a meeting there next day.
6th, we rode to Randolph.
First day, the 7th, we attended that meeting.
8th, we passed on to Plainfield, and had a meeting at that place on the 9th. 10th,
we had a solid meeting at Rahway.
This was the winding up meeting of this long journey of fifteen months.
After passing Burlington, it felt to me like a clearing off shower, after a long rain.
Though I was often led into close communications, as also encouragement to the upright,
I thought I was never favored to see the states of meetings more clearly.
Easy utterance was given to open subjects, and apply them in the clear openings of Truth.
The Gospel spring continued unabated, and its current flowed strong,
until it closed with the closing meeting;
after which I felt clear and at liberty to go to my family and friends,
with a bosom filled with peace.
Thanks be to the Most High God!
Glory, honor, and everlasting praises, be given to His eternal Holy name!

We crossed the water at Paulus Hook, and went into New York, where we stayed one night,
and went forward for home, without making much stop, until we got to the Creek Meeting,
in Nine Partners, my native land and meeting.
We sat with them on first day, and passed on until we arrived at Easton,
where we stopped and attended the Monthly Meeting;
then journeyed steadily until we reached home, where we once more I had a joyful meeting,
finding our families and friends well.
