== Chapter IX

In the year 1823, I felt my mind arrested from day to day, with drawings in Gospel love,
to pay a religious visit to Friends and others,
in the northern and western parts of my own Yearly Meeting, Ohio, Indiana,
and some parts of North Carolina Yearly Meetings.
After weighing the concern in my mind several months, I told my Master,
that my situation and circumstances were such, being much in debt,
and there had been so much division of sentiment in the Monthly and Quarterly Meetings,
and I, in obedience to Him, had taken an active part in them, to maintain discipline,
that Truth, and Society should not be scandalously reproached; and in so doing,
I had offended so many, that they would not let me go.
My Master returned me the answer, "`Do what I bid you, and if I do not make way for you,
you shall be clear.`"
So I laid my concern before the Monthly Meeting; it had a month to consider of it;
it was then united with, without a dissenting voice.
I took my certificate to the Quarter, and laid it, with my concern, before that meeting;
it took time solidly to consider it, and uniting fully with my concern,
set me at liberty.
I made preparations, and took leave of my family and friends the 6th of 12th month, 1823,
Samuel Knowles being my companion.
We crossed the Lake, and arrived at Peru on seventh day.
We stayed (having several meetings thereabouts) until fifth day following,
when we set forward for Black River.
It took us four days to reach Indian river,
the first settlement of Friends we came to--(it is now called Philadelphia),
and had a meeting there on the 15th, with Friends and others;
and found the same old Satan,
who met with the sons of God in Job`'s day--and as his manner was in that day,
to set them to accuse and hurt one another, so it is with him now;
he had got into this little meeting, and had sown so much of the seed of jealousy,
that it had broken out into a flame, and almost destroyed the meeting.
The flame had a little abated, but its anguish still remained.
We had much painful labor with them, but were mercifully enabled to clear our minds,
so as to feel relieved.

On the 16th, we had a full meeting at Le Ray; this was also deeply exercising,
there being much lack of true Gospel love among them.
Holy help was mercifully felt, to enable me to clear my mind, so as to feel well relieved.
From here we went to Brownsville and Lowville,
and had a satisfactory meeting at each place.
23rd, we had a meeting at Western.
I was at that place some years before, and it appeared a hopeful,
growing meeting in the Truth; but the old serpent had got among them,
and on the seat of judgment,
having nearly destroyed all the precious life of the Lamb of God among them--a dried up,
barren meeting.
24th, we were at Lee meeting; here was felt a lively concern among them,
though all was not well; but much more comfortable than the other meeting.

25th, we returned to our kind Friend, Thomas Townsend`'s, in Lowville,
and proceeded to Germantown, where we had a satisfactory meeting.
Then, to Pleasant Creek Meeting, and returned to Brownville, and had a good,
solid meeting there; mostly with those not members of our Society,
and returned to Pleasant Creek.
From here, we proceeded to Morristown, on the river St. Lawrence, forty-five miles,
and got there just at dark.
The next morning we crossed the River, and went to Jedadiah Wing`'s,
in the town of Yonge, Lower Canada.
Here, we attended their Preparative Meeting, which, from a small beginning,
had become much increased, and a pretty lively meeting.
Here Friends had kept together in the quiet, and their neighbors loved them.
From this, we drove to Elizabethtown,
and got to Isaac Booth`'s the first day of the year, 1824.
The day following, we went to Brockville, and had a meeting in the town,
among a hardy set of the human family; returning to Elizabethtown the same day,
and appointed a meeting there, to be held the next day, in the afternoon.

Next morning, being first day, the 4th of 1st month, we drove twelve miles,
and attended Friend`'s Meeting at Yonge, and returned seasonably,
to attend our appointed meeting.
On second day, we set out for Kingston; drove fifty-four miles,
and got there in the evening, and put up with Peter Knight.
Third day, we had a meeting at Kingston;
this has become very small by Friends moving away.
We had another in the evening in the village, at the Methodist meetinghouse,
which was pretty large; the people sat respectfully quiet, the meeting was favored,
and the Truth was felt to spread over it, and it closed with solemnity.
From here, we drove to Earnest town, forty-one miles, and stopped at John Burley`'s,
and had a meeting in this town, on sixth day; and after meeting we drove twenty miles,
to Daniel Haight`'s, in Adolphus town.

Seventh day, we lay by.
First day, 11th, attended that meeting.
Here, some years ago, was a large, lively meeting,
but some of its members having a high opinion of themselves--much more so than they
were worthy of or their Friends had of them--they sought the rule and government,
and were much uneasy; and in order to get power into their hands,
they stirred up false jealousy against their better brethren,
and had much borne them down, and laid the meeting almost in a state of desolation.
They greatly oppressed the better class,
were still disposed to lord over God`'s heritage;
they seemed afraid that anything should rise above them, however clear in the Truth;
so that the innocent, righteous seed, was much oppressed in this place; and will be,
until the Lord is pleased to rebuke spiritual pride in high places,
and lay giant self confidence low; which may He do for His own name`'s sake,
and in mercy to His suffering remnant and precious seed!
Some of the leaders of this mischief moved into other meetings,
where they could have more influence.
It was mournful to feel and see what the old enemy,
by spiritual pride through his agents, had done.
I had much painful labor with Friends in these parts, both in public and private.

Second day, we went to Grassy Point, and had a little poor meeting,
in a big-feeling member`'s house.
Third day, we went to Hollowell, twenty miles, and attended that Select Meeting,
on fourth day.
It was seriously painful, and deeply exercising,
for I perceived that self-importance had got into this department,
and it was jealous and afraid; but through the goodness of the Most High,
I was strengthened to discharge my duty faithfully, and felt peace.
Fifth day, attended their Monthly Meeting; after it we went to Sidney,
where we had a meeting with Friends, and two among other people;
all of them to good satisfaction, being favored meetings.
Second day, 19th, we went to Coal Creek, and had a comfortable meeting there the 20th,
and after it, we went back to Sidney.
Fourth day, we returned to Hollowell, and made our home with Jonathan Clark,
and attended that meeting on fifth day.
Sixth day, we had a meeting in Hollowell village, a cold, careless place,
and hard getting along.
First day, 25th, we attended Ameliasburg meeting; it was a solemn, favored time,
and we returned to Jonathan Clark`'s, where we lay by on the 26th, not being well.

Third day, the 27th, attended the Select Half Year`'s Meeting.
It was deeply exercising; the lack of Gospel love, true charity, and fervent zeal,
were sensibly felt among them.
Fourth day, attended the meeting for business;
in it I had an opportunity to see their jealous fears,
and also to clear my mind in a plain, feeling manner, and was well relieved;
it stilled them much for the day.
Fifth day was the closing and parting meeting, and was a favored, precious time.
From this, we went to the Carrying Place, had a meeting there on the 30th, at evening,
which was said to be the largest ever held in the place.
The people were civil and attentive; the meeting became solid, and ended so.
Then went to Cramahe, where we had a meeting in the Methodist meetinghouse,
on first day the 1st of 2nd month, and had another meeting in the evening at Holderman;
both to good satisfaction to ourselves, and appeared so to be with the people.
We lodged with Freeman Clarke.
Second day, we drove to Cyrus Richmond`'s. 3rd of the month, we had a meeting in Hope,
and another in the evening in the same town.
In both of these meetings the doctrines of Truth flowed free and clear.
4th, we proceeded to Whitby.
5th, we attended that Preparative Meeting.
And it was a tough meeting; it seemed as though I could but just live through it;
for some who sat at the head appeared rotten-hearted, and full of mischief.
I had to deal out coarse medicine to them which made my heart ache,
but my good Master rewarded me well for it.
After meeting we went to Timothy Roger`'s, where we were well received.

Sixth day, had a meeting at one M+++_______+++`'s,
and another in the evening at John Haight`'s; the latter a very satisfactory meeting.
7th, went to Uxbridge.
First day, the 8th, we attended that meeting.
9th, went to Whit Church.
10th, had a meeting there.
11th, we went to Queen Street Meeting; here are a number who have dissented from Friends,
and gone into wild Ranterism.
Several of them came to the meeting; though I knew it not.
I had a solemn testimony to bear,
and felt the mighty power of the Lord to go over
the heads of all opposing spirits so that Truth reigned.
Fifth day, was at Yonge Street Monthly Meeting; in it I had good service.
Sixth day, went to Luke Stoutenburg`'s. 14th, went to Little York (now Toronto),
had a meeting in the town, at evening.
To it came a number of gay people, who sat quiet and attentive, and passed soberly away.
15th, and first day, we attempted to return to Stoutenburg`'s,
to have a meeting in that neighborhood in the evening,
but there came such a fall of snow that we could not get in seasonably.
16th, we returned to Yonge Street, with our horses much fatigued.
17th, we attended Queen Street Meeting;
but not feeling clear we had a meeting appointed in the evening.
In it way opened to relieve my mind pretty fully.
18th, we had an appointed meeting at West Gillensbury, returned to Yonge street,
at evening, and attended that meeting again on fifth day.
Sixth day we attended a meeting at Markham in the evening.
Seventh day, we drove to Pickering, and attended their meeting on first day,
the 22nd. Second day, we drove forty miles, and on third day, fifty-two miles,
to a small settlement of Friends in Ancaster;
we stopped and had a meeting with them on fourth day.

On fifth day, the 26th, we drove to Norwich.
Here I had my feelings exceedingly tried; for I had not been long in the Friend`'s house,
where I put up, before he wanted to have my opinion on some affairs among them.
I told him I came there knowing nothing, and it was my right to go away knowing nothing,
except they saw a wrong in me, and then they should let me know it.
I desired him to forbear, and not tell me anything.
He pressed me so hard to hear him, that I told him at last, if he would not forbear,
I would leave his house, and go where they would let me be quiet;
for I would not have my ears filled with outward information.
After that, he let me alone.
When I came to meeting I found myself plunged into thick darkness that could be felt,
and felt a spirit among them as bitter as the waters of Meribah.
My Master laid it on me to deliver His word faithfully and plainly,
without any shadow of turning; it was a solemn, trying day to me,
but strength and fortitude were given, sufficient for the day,
and utterance for the occasion, through the tender goodness of Israel`'s holy Helper.

First day, 29th, we attended the same meeting, where I was silent.
There came in a Minister of their own from another a meeting,
who took up such a length of time in preaching,
that I had no opportunity to relieve my mind.
I thought his communication was not to the purpose,
so that I had to pass the meeting in deep suffering, being led into a clear sense,
that the destroyer of all good had got among them; he had got into the seat of judgment,
where he had not only exalted himself above all that is called God; but through agents,
was endeavoring to destroy the man child as soon at it was
born--he had cast out his floods to swallow up the woman,
the mother--but the Lord, in mercy,
has hitherto caused the earth to open her mouth and swallow up the floods,
so that the child and its mother are not quite destroyed,
although they are under great sufferings.
Oh! may the righteous Lord, for his own Name`'s sake,
and the promotion of Truth and righteousness in the earth,
continue to sustain the true mother, and lift up the head of the holy child,
to the casting down and dethroning the old serpent from lording it over God`'s heritage!

The 1st of 3rd month, second day, we had a meeting at Pine Street;
there are but few Friends here, and the meeting small and weak.
From there to Yarmouth, fifty miles.
The country being new, and roads bad, it took two days.
Fifth day, we had a meeting with Friends and others of that place;
notice being given the meeting was large, and much favored.
Here is a hopeful prospect of a growing meeting;
the members appeared to be in good friendship one with another,
and to live peaceably with their neighbors.
Sixth day, we had a meeting at Talbot street.
Though small, it was satisfactory.
From this, we returned to Norwich, and reached there seventh day.
First day, the 7th, we attended that meeting; in it holy help was richly felt,
and my mind was so strengthened thereby, that I spoke in undisguised plainness,
and got much relief.
Second and third days we had no meetings.
On fourth day, the 10th came on their Monthly Meeting; we attended it.

They came in from all the different meetings,
and brought themselves along just such creatures as they were at home,
and brought their rubbish with them.
My mind was brought into a deeply bowed state before
the Lord in the early sitting down of the meeting,
and was led into so clear a view of the state of it,
that I could have no doubt or scruple of the opening.
Under the increasing weight of the subject, I felt a necessity to rise on my feet,
in the impressive flowings of the Gospel.
I was led in much plainness to show the sad effects of surmising jealousy, which,
tormented with a fear that others would be better thought of than themselves;
when nursed with imagination, this soil produced heart-burning hatred,
which fed the hot coals of malice,
that not only tormented them in whom they were nursed and kept alive, but after,
broke out in destroying flames of slander, which spread discord among brethren,
and separated near Friends.
I was led solemnly to warn them against these evils,
and was strengthened to proclaim the day of the Lord among them,
greatly to the peace and relief of my own mind.

Fifth day, we went to Long Point.
Sixth day, we went to Richard Meade`'s. Seventh day,
we had a meeting in the town of Woodhouse, and another in the evening, in Charlotteville.
First day, the 14th, we had a meeting at Burford, at eleven in the morning,
another at three in the afternoon, at Windon meetinghouse, and the third,
at candle lighting, at a village called Waterford.
Second day, returned to Norwich, and third day, being snowy, we lay by.
Fourth day, we attended that meeting for the last time,
where I had to proclaim a solemn alarm among them,
so that I felt clear of the blood of all mankind in that part of the country,
and left them with a peaceful mind, and a heart full of pity.

Fifth and sixth days, we drove to Pelham, and put up with Samuel Taylor.
Seventh day, we had a meeting there, and had a meeting at Lyne`'s Creek in the evening.
First day, the 21st, we attended Black Creek meeting,
and were favored with the presence of the Lord to our comfort,
and much to the renewal of our strength.
It being the last meeting, we took our farewell of the British government.
Second day, we traveled thirty miles, and on third day,
we crossed the river into the State of New York, arriving at Lockport in the evening,
and put up with my much esteemed Friend, Jared Comstock.
Fourth day, we lay by, and attended that meeting on fifth day.
We then passed on to Hartland, and had a meeting there on sixth day.
On seventh day, we returned to Lockport, and attended their meeting on first day,
the 28th, where I had an opportunity to clear my mind to satisfaction,
and after meeting we returned to Hartland.

Second day, went to Somerset, and had a meeting with the few Friends of that place,
and their neighbors, and returned to Hartland.
Fourth day, we drove to Royalton, and attended their mid-week meeting;
but not feeling clear, we appointed another meeting for fifth day, the 1st of 4th month,
which was much to my satisfaction.
We then passed on to Shelby, where we had a meeting on seventh day.
First day, we attended a little meeting at Elba.
Several of these last meetings were small.
It was easier getting along than in the large, old meetings,
where wealth and distinction are looked at,
for in new countries they have much to struggle with,
and have to be helpful to each other.
They are glad to see their Friends,
and generally stand open to receive what we have for them,
with less extravagance and more true humility,
than is often the case in old and populous places.

Second day, we drove to Riga, and had a meeting there on third day.
Fourth day, had a meeting at Wheatland.
Fifth day, at Henrietta, where my Master gave me nothing for the people.
After meeting, we drove to Rochester, and had a meeting there on sixth day.
We went to Macedon the same day, and attended an appointed meeting there on seventh day;
and another at four in the afternoon, in Palmyra village.
First day, the 11th, we attended Farmington meeting,
and second day appointed a meeting at South Farmington.
Third day, had a meeting at Galen.
Fourth day, we were at the mid-week meeting at Junius.
After meeting, we drove fifteen miles,
and reached Milo in season to attend that meeting on fifth day,
but had nothing to impart to them.
I sat and looked on them with pity, for it appeared clear to me that a slack, easy,
unbelieving spirit, was making its way among the people in that part of the land.

On sixth day we drove twenty-eight miles to Scipio, and first day, the 18th,
we were at Springport meeting.
Second day we visited Scipio North meeting.
In this meeting my mind was feelingly arrested with a sorrowful sense,
that an infidel spirit was prevailing among them.
I felt constrained to bear a faithful testimony against unbelief,
and invalidating the Holy Scriptures, ridiculing the truths of the Gospel,
and making light of those truths that God had already revealed.
As I stepped along in the exercise of my testimony,
I felt the power of Truth to go forth in the name of Jesus Christ, in such authority,
that their walls gave way, and their weapons fell.
Truth arose in dominion, and reigned that day to the joy of many minds,
which had been much borne down with this unbelieving, rending spirit,
that had crept into our Society.

Third, fourth, and fifth days, attended Farmington Quarterly Meeting, held at Scipio.
In the Meeting of Ministers and Elders,
I was made painfully sensible that unbelief had got into this part of Society.
It had crept in as the serpent creeps on his belly among the weeds,
unperceived and unthought of, and was secreted under the plain Christian cloak,
while it was endeavoring to undermine the truths of the Gospel,
and lay waste the discipline, and destroy all good order in our Society.
I had to sound an alarm among them, and it made a stir.
I felt great peace for the discharge of duty on this occasion.
In the other meetings I had but little service, except to set the example of silence.
After Quarterly Meeting, we took Salmon Creek, Sempronius and Skaneateles.
From there we went to De Ruyter, where we stayed until their Monthly Meeting.

Fourth day, the 28th, which was another trying meeting;
for where the head is sick or unsound,
it is not to be marveled that the body becomes diseased.
Strength was given to bear a faithful testimony and sound an alarm among them,
so as to feel pretty well relieved.
I could but mourn in seeing how insensible that meeting was of its own state,
so that I said in my heart, poor meeting! you needest eye-salve to give you true sight;
may the Lord grant you that favor before it be too late!
Then returned to Scipio, and attended that meeting on first day, the 2nd of 5th month.
From there to Hector, and had a meeting, and another at Elmira, on our way to Deerfield,
where we found Friends in a sad condition.
A Minister belonging there had gone into immoral conduct, and drawn a party with him,
and got the meeting into such a state, that it had been put down for awhile.
After some time, a few of them not feeling easy to live so, met quietly by themselves.
The Monthly Meeting hearing of this move, appointed a committee to visit them,
who went and sat with them, and approved of their meeting,
but advised them to go to the meetinghouse, instead of meeting at a dwelling house.
This displaced the Minister from his usual seat, which so offended him,
that he and his company went and sat on the back seats.

When I came into the place I felt my mind arrested to call
Friends and their families together by themselves.
Friends had kept me entirely ignorant of their situation, and when they came together,
to see them sit down in two distinct bodies,
and an empty seat between them across the house, it looked strange.
But I soon felt there was a cause for it.
I sat near an hour, until my Master gave me the command to delay no longer.
I rose on my feet in faith, and He was bountifully good to me; He furnished with matter,
ability and utterance, so that it was acknowledged, after meeting,
the testimony was appropriate and well applied.
Blessed be His name!
We stayed hereabouts until first day, the 9th of 5th month,
and had a large public meeting, which was truly satisfactory.
We then set forward for Farmington, and on our way,
had a meeting at Penn Yan with the towns people.
It proved a comfortable time.
After attending Farmington meeting, we had a meeting at Palmyra village, on sixth day.

First day following, attended Farmington meeting,
where I was enabled fully to clear my mind, and felt much relieved.
Second day, we took our departure, and journeyed to Moscow,
and fell in with Phineas Butler, at whose house I stayed twenty years before,
when in the eastern country, and now found him and family settled here,
a pleasant meeting to us both.
Fourth day, attended their meeting, and passed on to Orangeville, and had a meeting there.
Then went to Hamburgh, and had a large meeting there.
Here, I fell in with many of my old Friends, who appeared rejoiced to see me.
From here, we took Holland, Boston and Eden, three small meetings, in our way,
to Collins, where we had a meeting with Friends, and had another meeting the same day,
about three miles from Friends meetinghouse.
Then, passed on to Clear Creek, and had a meeting with Friends there.
This closed our labors in Farmington Quarter.

We took an affectionate leave of our Friends,
and set forward for Ohio the 27th of 5th month, passing over the Indian Reservation,
a fine tract of rich farming land as I had ever seen.
Next day, we got into Pennsylvania, having traveled fifty miles, through a fine,
flourishing country of farming land, and good roads.
29th, we traveled forty-two miles through a new country, and lodged at Kingsville,
in Ohio.
First day, 30th, we drove fifty miles, mostly on the turnpike, through a new country.
31st, we drove thirty miles and reached Salem before night, and put up with Samuel Davis,
where we found kind reception.
Fourth-day, the 2nd of 6th month, we attended Salem meeting in course.
Fifth day, at Springfield meeting--both satisfactory meetings.
Sixth day, at Goshen.
Seventh day at Lexington.
First day, the 6th, we were at Deer Creek Meeting.
At all these meetings, the Master of Israel`'s assemblies, furnished with matter,
ability and utterance, to the satisfaction of my own mind, and my friends,
among whom my lot was cast.
Second day, we were at Marlborough meeting.

Third day, we drove to Kendall, and made our home with Mayhew Folger.
In this part of the country, we saw much land made almost barren,
by the timber having been destroyed by fire.
After having a poor meeting at Kendall, we set foreward for Augusta, thirty miles,
and had a meeting there on sixth day.
Seventh day, had a meeting at Sandy Spring.
First-day, the 13th, attended New Garden meeting,
and another at four in the afternoon at the Grove.
At a number of these last meetings, a coolness too generally appeared among Friends,
in a concern for the cause of Truth, and the things that belong to their peace.
Much of an eager pursuit after the world, prevailed,
and in some meetings unity and Gospel love were much lacking, all which made it painful,
exercising getting along.
But the Lord, who is rich in mercy, and bountiful in helping,
so strengthened from day to day, with ability and utterance,
that I enjoyed sweet peace and solid satisfaction.
I often had to acknowledge, it is You, O Lord! who carriest on the work; for without You,
I can do nothing to Your honor, or my own peace.
Therefore, leave me not in this strange land, for You are my all in all;
be pleased to guard, guide, and lead me in the right way; for Yours is the kingdom,
the power, and glory forever more!

Second day, we had a meeting at New Lisbon.
Third day, at Middleton.
Fourth day, at Beaver Falls, in Pennsylvania.
From there we went to Dry Run, and had a small meeting.
Then to Carmel, where we had a large, comfortable meeting;
and seventh day we attended their Monthly Meeting, to our own and Friends`' satisfaction.
First day, the 20th, we attended Eckron meeting.
Second day, at Middleton Monthly Meeting, where my Master enabled me to bear an honest,
faithful testimony, and rewarded me well for it.
Third day, had a meeting at Fairfield, and attended Salem Monthly Meeting on Fourth day,
the 23rd, where was a body of solid Friends.
Their business was conducted regularly, and in harmony,
though they told me it had been far otherwise.
A class had risen up, who denied some of the doctrines of Friends, exclaiming against,
and endeavoring to lay waste the discipline, saying,
"`It is superstition--a dead letter--tyrannizing
over conscience--and we must go by the Spirit,
and have liberty.`"

These became so wild and noisy, that Friends could see no other way,
than to disown more than forty persons, within the compass of Salem Quarterly Meeting;
since which their meetings have been quiet and orderly.
Fifth day, we attended New Garden Monthly Meeting,
and Sandy Spring Monthly Meeting on sixth day, in both of which I had to go into close,
searching labor, and plain dealing, and was relieved thereby.
Seventh day we had an appointed meeting at Franklin.
First day had another at +++_______+++. From there to Richmond,
and had a meeting there on third day.
We then drove to Benjamin Ladd`'s, at Smithfield,
where we had a large meeting on fourth day, made up of different societies.
Here I was led into doctrine in a plain, clear, manner,
showing the emptiness of ceremonial religion without the power and spirit of the Gospel,
and where this spirit was enjoyed, and had its work on the soul,
it produced regeneration, and effected its salvation, without the aid,
and independent of all ceremony.
I was also led to warn them not to pin their faith too much on their teachers;
but to believe in the Light, and walk in the Light, that they might see for themselves.
I was enabled to show them what the Light was, and how to know it.
I was told that my doctrine did not suit all; but knowing it to be the truth,
and upon serious reflection,
feeling conscious that I was rightly authorized to deliver it,
I was well satisfied on my own account.
But to my sorrow, I have often observed that there are those among Friends,
who seem more concerned to have their neighbors pleased,
than to have sound doctrine preached.

After this meeting, we went to Short Creek, and attended their mid-week meeting,
on fifth day, the 1st of 7th month,
and had an appointed meeting the same day at Mount Pleasant.
2nd, we had an appointed meeting at Concord.
In these three last meetings, the Gospel flowed gently and clear,
and I found good acceptance with my Friends here.
From there to Plainfield, where we attended their first day meeting on the 4th. 5th,
had a meeting at Goshen.
6th, had a meeting at Captina.
7th, at Somerset.
8th, attended the Ridge meeting.
In this route, my labors in general, were close, searching, and plain.
There appeared too generally, a slackness in the minds of Friends,
in regard to feeling after the life of pure, spiritual religion;
and many were settled down in the smooth form of godliness,
entirely void of the substantial power, and vital life of the Gospel day;
burdens to society,
and often bringing grievous burdens on the shoulders of the living in the Church;
which they will not touch with the tip of their fingers to give relief.
But in most of these meetings, there were those who endeavored to stand faithful,
and labor honestly, for the support of the cause of truth and righteousness.
I was led to feel much for these, and sometimes was authorized to encourage them,
in feelings of pure love and Gospel sympathy, to hold on their way, to stand faithful,
and fill up their measure in their generation, that the crown at the end of the race,
thereby would be made sure; an ample reward for all we pass through in time.

Sixth day, the 9th, we visited Stillwater; a large meeting,
and a number of substantial Friends there; yet there were other descriptions among them.
We had a favored meeting, and the Truth went forth in its own authority.
On first day, the 11th, we attended that meeting again,
and was authorized and enabled to bear a faithful testimony against oppressive speculations,
over-reaching in trade, and dealing one with another, to get gain;
showing that it was often oppressive, causing the needy to groan,
and the hearts of the oppressed to cry, whose cry reaches the ear of the Lord of Sabaoth,
and he reserves a just retribution for the oppressor,
against the awful day of solemn account.
I had to proclaim a solemn warning, and leave it with them,
and felt my mind not only relieved, but refreshed.
The hearts of many Friends were made glad; and some of them told me,
that my testimony was entirely appropriate,
and fittingly applied to the conduct and states of some in that meeting; sufferers,
as well as oppressors.
Oh!
I felt renewed cause, in deep humility, to recount the marvelous,
tender dealings of my God, in leading me in the right way,
and sustaining me through the many and deep exercises He was pleased to lead me;
making strong my arm in the day of battle,
to the exalting of the standard of Truth and Righteousness;
I hope to the praise of His ever adorable name!

Second day, the 12th, we had a meeting at Richland.
Third day, went to Gurnsey, and attended their Preparative Meeting on fourth day.
Fifth day, had a meeting at Freeport.
Sixth day, at Bushy Fork.
Seventh day we drove to West Grove, and attended that meeting on first day,
the 18th. Second day, we had a meeting on our way to Short Creek.
These latter places visited, are mostly in new parts of the country; the meetings small,
and some of them weak.
I felt much for them,
and was enabled to impart such counsel and encouragement
as my good Master furnished me with.
Third day, we attended Short Creek Monthly Meeting,
where the business was conducted in harmony, and with condescension.
Fourth day, we attended Concord Monthly Meeting.
I sat the meeting for worship through in silence, occasioned by a woman Friend,
who suppressed her gift.
I passed through the meeting, and got no relief.
After meeting, I told the woman of it; she confessed, with tears,
that she had withheld her gift, fearing she would take up the time from others.
Thus, by giving way to reasoning, and not minding her Lord`'s direction,
she shut up the door of the Ministry that day, and hurt the meeting much,
so that through the business meeting, things dragged heavily.
As I got no relief that day, I had to return there again,
and was enabled to clear my mind, and get relief.

After the Monthly Meeting closed, we went to Wheeling,
and had a meeting there that evening.
Fifth day, we set forward for the head of Wheeling,
and had a small meeting with the few Friends there, on sixth day.
After meeting, we drove to Washington, in Pennsylvania, and lodged with William Minnakin;
he and his family were kind, and the only Friends in the place.
Seventh day, we journeyed to Pike Run, in Red Stone Quarter.
First day, the 25th, we had a large, favored meeting there.
Second day, we had a large, solid meeting at Westland.
Third day, we drove to Muddy Creek settlement.
Fourth day we were at the Ridge meeting, and went to South Fork, where, on fifth day,
we had a large meeting at a Baptist meetinghouse.
The doctrines of Truth, in the love of the Gospel, flowed freely,
and a comfortable solemnity spread over the meeting; but soon after I sat down,
a noisy man rose, and undertook to explain what I had delivered,
and ran into wild ranterism, exclaiming against all government.
He detained the meeting sometime, and got it all in a jostle.
When he stopped,
I saw it necessary to make some plain remarks on some of his movements and discourse,
showing the people what was our belief, and our reasons therefor.

This, gathered the people into a quiet again, much to their satisfaction;
which they expressed after meeting; and as I sat down,
I informed the people that the service of the meeting was closed;
and so gave him no opportunity for the second harangue, for which the people were glad;
so I parted with them, glad to escape so well, and went to Redstone, where, on 6th day,
we had a meeting.
This was once a large meeting, but now much run down.
After sitting in this meeting some length of time under a weight of exercise,
I felt constrained to arise on my feet.
But looking to the right hand and left,
I saw several on the front seats who appeared to be fast asleep,
and a number in the body of the meeting in the same situation.
I concluded it would be of no use to preach to them; but feeling no release,
I rose on my feet, and after speaking a few words, I spoke with a sharp tone of voice,
"`Friends, do wake up, for I think I am rightly authorized to deliver a discourse,
and want you to hear me, so as to understand what I say,
which you cannot if you are asleep, so as to have any correct judgment about it.`"

By this time they were all awake.
I then proceeded as matter and utterance was given, and was led into a close, plain,
searching discourse, and mercifully enabled to clear my mind,
so as to feel well satisfied.
Seventh day, had a meeting at Centre.
First day, 1st of 8th month, we attended Providence Meeting.
Second day, at Sewickly Meeting, held the 3rd hour in the afternoon.
Fourth day, following, we attended Redstone Monthly Meeting,
where there was room for much labor.
May it prove useful to them.
After this meeting, we crossed the river, to attend the Quarterly Meeting,
to be held at Westland, on 6th and 7th days of of the month and week;
and though the life of pure religion was low in those parts,
and several meetings had almost run down, yet it pleased the holy Shepherd of Israel,
in his tender mercies, to favor with His presence through the several sittings thereof.
The business was conducted in harmony,
the honest-hearted were encouraged to faithfulness, both in their private walk,
and in the honest maintenance of the discipline; the latter being too much neglected.
Wherever this is the case, weakness and a falling away, are certain to ensue,
and such meetings get into a lifeless, formal state of security--hard to be helped,
or made to believe they need a helper--a dangerous, pitiful condition, much indeed,
to be mourned over in this land.
I had to travail, clad with the spirit of mourning,
and to labor under the weight of its impression.

First day, the 8th, was the closing, parting meeting.
The power of the Gospel arose in dominion over all opposing spirits;
its doctrines flowed freely, and the meeting closed under a heavenly solemnity.
Honor, thanks, and everlasting praises, be ascribed to the Lord God, and the Lamb,
says my soul!
Not feeling clear of Redstone,
we had a meeting appointed at the fourth hour in the afternoon, at this place.
The Lord enabled me to sound the alarm, in a solemn, searching manner,
and was led to show how Satan had got among them, and what he had done,
and that that the love of many had waxed cold.
I felt my mind well relieved, and thankful to the Lord therefor.
Second day, we had a meeting at Sandy Hill, and on third day we crossed Laurel Hill,
and had a meeting there on fourth day.
The next day, we again crossed Laurel Hill, to a neighborhood near Waynesburgh, where,
(after traveling ten miles), we had a meeting with the Baptists and others.
It was as full a meeting as could be expected; the people sat quiet,
and appeared attentive, received the visit courteously, and made no objections,
though plain truths were told them.
After this meeting, we drove to Pike Run, and on first day, the 15th,
attended that meeting; it was large, and a favored time.

Second day, we had a public meeting at Fallowfield;
the house not being large enough to hold the people, it was held in the woods.
It was a satisfactory meeting to me, and I now felt clear to return to Ohio.
On third day, we arrived at Washington, in Pennsylvania,
and made our home with William Minaken.
I felt my mind arrested to have a meeting in this place,
but a member of our Society from the city of Washington, a little before,
and who had a meeting there--had given such general dissatisfaction,
that the prospect of getting a meeting, looked gloomy.
But not feeling easy without making a trial,
we appointed one for the evening of the 19th, when quite a body of people came together;
yet many said they would not come to be black-guarded, but those who came, sat quiet.
I sat sometime under deep exercise and fear--but not of
man--until I felt the authority of Truth to put me forth,
and in it I arose on my feet, and as utterance was given,
the Gospel was preached without equivocation or flattery.
It went forth in its own authority, and settled on the people, and they settled under it.
I was told the people acknowledged to the truth of the doctrine.
I felt my mind much relieved and made glad, and had thankfully to acknowledge,
that strong is the arm of the Lord, and mighty is He, in the day of battle!

Sixth day, we drove to Wheeling, in Virginia, and put up with a Friend,
who had been made considerable account of.
We proposed having a meeting in the town,
but he refused to give any aid or countenance to the prospect; so on seventh day,
we went to Concord, and attended that meeting on first day, the 22nd,
and stayed thereabout until fourth day, and attended the Monthly Meeting there.
Here I fell in with a preacher from Long Island--headquarters--with a good certificate.
He seemed glad to see me, but my feelings drew back from him,
and I could not account for it.
However, when the time came, we went to meeting.
It was my lot to bear testimony first; he soon followed,
and at first seemed to unite with what had been said, but soon run across,
and quoted the fall of Adam and Eve in the Garden,
with what transpired--pretty correctly--and drew some rational inferences from them;
then wound up with asserting, "`These things are all allegories.`"

After meeting, I asked him, what house he was going to, and went to the same.
As soon as I could get an opportunity,
I remarked to him that I very much doubted any Quaker
Minister ever having right authority to state,
that those facts of truth which are stated in the Scriptures,
were nothing but allegories.
He made no reply, so I let it pass, in hopes a few words were sufficient.
After dinner, we went to Plainfield, to attend that Monthly Meeting,
which was held on fifth day.
Here, it was my lot to bear testimony first, again; and, as it turned, I was glad;
for he went on the same ground, spread broad sails, run across my testimony,
and asserted that several accounts stated in Scripture as facts, were allegories;
and this, with a good deal of confidence.
After meeting, I went to the same house that he did, and remarked to him,
that I had no opinion of Quaker preachers telling the people that this, that,
and the other part of the Scriptures, were nothing but allegories,
and so turning it into a novel book;
for it set the young people to reasoning and disputing it, (the Bible),
introduced divisions, and did much hurt; religious speculation ran high in our land,
and it was highly needful for Friends to keep to sound principles.
He turned and looked me full in the face, and said,
"`All the Ministers who come from England believe that the
death and sufferings of Christ did something for us.`"

I then saw that he was one of those who denied the Divinity of Jesus Christ,
the propitiatory sacrifice, and the atonement;
and believed that he came into the world as all other men; that he was a good man,
and died a martyr to his principle.
They also deny the being of Satan, and they say and preach that there is no devil,
only what originates in man.
I looked him as full in the face, and replied, it is our ancient principle,
that agreeable to the statement of John the Evangelist:
In the beginning was the Word; and the Word was with God, and the Word was God.
And the worlds were made by Him.
And without Him was nothing made that was made.
And the Word was made flesh, and dwelt among men.
So that we see Divinity took on it humanity,
and Jesus Christ never resigned the glory He had with the Father, before the world was,
and took on Him humanity for the sake of devils; that is out of the question;
Neither did He come for the animal part of creation,
for they are not possessed of immortal spirits; so that His conception, birth, life,
ministry, miracles, crucifixion, resurrection, and ascension were all for man.
These are our ancient principles, and they are mine;
and I can find no where to part or divide Him.
And, it is marvelous to me that any finite creature should suppose
that the great fountain of eternal knowledge had not wisdom,
so to order the business and lay the plan, so as to answer the great purpose designed,
for the past, present, and to come.

At this, he turned from me without any reply, and seemed shy of me afterwards.
I sought an opportunity to clear my mind to him, but he would not hear me.
I then gave him up to run his own course.
But it brought me into a sad strait, he being from head quarter,
and I only a back-woodsman, and both from the same Yearly Meeting,
and directly across each other in our testimonies.
This, I saw would bring exercise on Friends,
for I felt no liberty to deviate from my principles nor give up my testimony.
So I concluded to let him alone, and let Friends decide between us.
After this, my companion and myself went to St. Clairsville,
where I had once been disappointed in obtaining much of a meeting,
owing to the neglect of those Friends, who took it upon them to inform the people.
I now went to another house, and employed others, who were faithful; we had a large,
crowded meeting and a highly favored time, so that those who neglected me before,
wanted me to go to their houses; but I thought if I had got my credit up,
it was best for me to go about my own business.
After this meeting, we drove to Stillwater.
Seventh day, we attended Stillwater Monthly Meeting, where I had good service,
and felt sweet peace therein, as also the first day meeting, the 29th, at the same place.
Second day, we attended Somerset Monthly Meeting.
Third day, attended the Quarterly Meeting for Ministers and Elders at Stillwater.
Fourth day, the 1st of 9th month,
we attended the Quarterly Meeting for worship and discipline.
Here, I fell in with my Long Island friend again, and, as before, I bore testimony first.
We both went our own way.
While I was on my feet, my aged Friend, Hugh Judge, sat quietly;
but soon after the other Friend arose, he grew uneasy, and would look on him wishfully.
Soon after he sat down, the meeting proceeded to business,
took hold of it in a solid manner, and conducted it with dignity, and in harmony.

Fifth day, we attended Plainfield meeting,
and then bent our course for the Yearly Meeting, to be held at Mount Pleasant.
It commenced on Seventh day, the 4th of 9th month.
When we arrived there, we found many Friends much stirred in mind,
and they frequently came to me to know,
if I believed in that man`'s doctrine--and told me that
he had asserted in one of his sermons in that place,
that Jesus Christ came into the world as all the rest of us did, sin only excepted.
Did I believe that?
I told them no, I did not, as I had answered several times.
This inquiry came so frequent,
I told some of them I had always been an open man with them,
and had always preached the principles I believe in;
I had gone over a great part of that Yearly Meeting,
and I thought they had had opportunity to become acquainted
with my public and private conversation enough to be satisfied.
They acknowledged they had not discovered anything,
and after that they let me alone on that head.
But the Friend went on his own way, and gave great dissatisfaction.
Friends let him know that his sentiments were unsavory,
and that some of his communications were not acceptable.
He neither replied, nor paid attention to it.

At length, when the meeting had the query before it,
on the subject of reading the Scriptures, this Friend arose and stated,
that it was an unsuitable book for children, and young, inexperienced persons to read;
and he thought dangerous, as they could not understand it,
and that none ought to read it, except when the Spirit of Truth was on them,
to give them a right understanding of it.
This cut me to the heart,
hearing such a communication from a member of my own Yearly Meeting;
and knowing for myself that when I was quite a child,
reading the Scriptures had introduced my mind into
the most substantial ideas of the Great Supreme Being,
and into the sublime views of His divine attributes.
It caused my heart to bleed, and all within me to reject the communication.
While I was musing, the subject was taken up by several, largely and fairly investigated,
and the meeting closed, without a dissenting voice,
in judgment of the unsoundness of his communication, and that it was false doctrine;
this pretty much stilled him through the remaining part of the meeting.

At the close, the meeting refused to give him any return of approbation to take home.
A solid committee had an interview with him; he gave them no satisfaction,
but refused to give them any answer to what they said.
I was told he was advised to go home.
He paid no attention to it, but went into Redstone Quarter,
visited nearly all its meetings, and continued to preach his spurious doctrine.
These occurrences embarrassed me more than anything
else that ever happened to me while away from home.
It rendered me almost useless through the Yearly Meeting,
though I had solid satisfaction,
in seeing the meeting transact the weighty and interesting concerns that came before it,
with solemnity, dignity, and harmony.
It was truly strengthening to my drooping mind,
to see that the Lord continued to be the wisdom of His people,
and the crown of their assemblies.
In the latter part of the Yearly Meeting,
I felt my mind so solemnly arrested to return into Red Stone Quarter,
that it tried my feelings exceedingly,
having had a prospect of attending Indiana Yearly Meeting; but this lay so heavily on me,
that I could see no way to enjoy peace than to stand resigned to it.

The Yearly Meeting ended on sixth day the 10th of 9th month.
We stayed thereabout until second day, the 13th, and then went to Wheeling,
in order to have a meeting.
I had told Friends how I had fared when there before;
they informed me that the Friend and his wife whom I called on, were both under dealing,
which they supposed was the reason I met with such crusty treatment.
We called on other Friends and found no difficulty in getting a full meeting,
which was a favored time.
From this we went to the head of Wheeling, and had a meeting there on fourth day.
After it, we drove to Washington, and put up at my old Friend Minaken`'s. Fifth day,
drove to Westland, twenty miles, by meeting-time.
Sixth day, drove to Muddy Creek, and on seventh day had a meeting there,
and returned to Frederickton, sixteen miles, where we had a meeting in the evening,
and after this we went to our esteemed Friend, George Smith`'s, to lodge; he, I think,
is a good pillar in the church.
First day, the 19th, we went to Pike Run,
and had a meeting at Bettysville at three in the afternoon.
Second day, we went to Red Stone, and had an appointed meeting.
Third day, we attended their Monthly Meeting, and drove to Sewickly, fifteen miles.
Fifth day, the 23rd, we attended Providence Monthly Meeting,
where I was led to sift and investigate doctrines--to me it was marvelous.

After meeting I met with several of their first members, one of whom,
in the presence of the others, told me that it was believed by the solid part of Friends,
that my coming among them at that time, was in the ordering of Providence;
as that Long Island preacher had gone through but a few days before,
had given great uneasiness, and set many of their members to reasoning,
and questioning the correctness of our principles; that they were alarmed,
but had observed that in my movements, I had followed after the Long Island man,
and as far as I had heard, wherever he had held up his erroneous sentiments,
in the course of my communication, I had gone over the same subject,
and had been enabled to lay it waste with such clearness,
that they thought it was in Divine mercy to that land that I was sent back;
that several times I had taken the same text that he did, as I had that day,
and from it refuted his preaching in such a manner,
that it was not only marvelous in their eyes, but rejoicing to them;
and they hoped it would check the rage, if not put out the strange fire that was kindled,
and strengthen and settle those who were inclined to adhere to the principles of Truth.

These remarks very much relieved my mind, for to come back had seemed, I thought,
more bitter than wormwood and gall.
I had traveled with a heavy heart, often asking in my mind, why I was brought here,
where I had labored so much, and why I was led in testimony in the manner I was; but now,
the Lord was pleased in this way to show me why.
It was not only relieving but humbling to my soul, and I said in my heart, "`O,
surely the Lord knows best what is best, how, when and where to send His servants;
who also goes before them in all His puttings forth, and safely leads them,
causing them to behold His wonders in the deeps,
'`which is marvelous in their eyes!`'`" After this, I went on pretty cheerfully.
Sixth day we had a meeting at Union schoolhouse, and returned to Westland.
Seventh day, we had a meeting at Waynesburgh,
and after meeting we drove fourteen miles to John Haines`'. First day, the 26th,
we rode to Centre, twelve miles, and attended that meeting,
and appointed another for second day,
where I had an opportunity to relieve and clear my mind.

Third day, we drove to Sandy Hill.
Fourth day, we set forward to cross the Allegheny and Blue Ridges,
for Lynchburgh in Virginia, and traveled industriously until the 2nd of 10th month,
when we got among Friends, and put up with Joseph Lapham.
First day, the 3rd, we attended their little meeting,
which was almost run down by Friends moving away, the aged ones dying off,
and the young ones leaving the Society--many of them by marrying into slaveholding families,
which stride, generally proves fatal to principles and morals.
Second day, we resumed our journey, and arrived at Lynchburgh on sixth day, the 8th,
and attended their Monthly Meeting,
which I found much better than I expected from reports.
Though they were but few, they appeared concerned to keep up their meetings reputably,
and to conduct their business regularly and in order.
I felt authorized to encourage them to faithfulness,
believing I felt the presence of the Lord to be with us, agreeably to His promise,
that where two or three are gathered together in His name, He will be in the midst;
and where His presence is felt, there is life and strength.
We stayed their first day meeting, which was a favored time,
and then parted with them affectionately.
I felt well rewarded for my visit.

On second day, the 11th, we set forward for New Garden, in North Carolina.
When we had traveled two days, one of our horses was taken sick and died.
This detained us two days more, and not being able to procure another,
we proceeded with one horse, traveled twenty miles a day,
and in two days got among Friends at Hopewell on seventh day, where, in a short time,
we attended the burial of an aged Friend.
This gave opportunity, and we embraced it,
to give notice of our intention to be at that meeting next day,
which was large and much favored,
there was great openness in the minds of the people to hear the truth,
whether they were disposed to obey or not.
Second day, the 18th, we had a meeting at New Garden,
and next day we lay by for Friends to provide us a horse,
which they appeared to do cheerfully, showing much sympathy for us.

Fourth day, we were at Concord meeting.
Fifth day at Centre.
Sixth day, at Providence.
First day at Back Creek meeting.
Second day at Marlborough.
Third day, at Salem.
Fourth day, we had a meeting at Springfield,
where I felt the Truth to arise in dominion over all opposition--the
sturdy had to bow and acknowledge to it.
Next day, we were at Deep River, from there to Providence again on seventh day,
and had a meeting there; returned to New Garden,
and attended that meeting on first day the 31st, where, after delivering a testimony,
relieving to my mind, I took, I believe, my final farewell of North Carolina.
In this little tour, my gracious Lord and good Master enabled me to relieve,
and clear my mind of a burden, that had laid upon it for a number of years.
I also cleared my mind to several individuals,
some of whom had used me very ill when I was there before, without any just provocation.

After getting clear of this land, on second day morning, the 1st of 11th month,
we took our departure for Tennessee, with joyful hearts,
and thankful to the God of all our sure mercies,
for His abundant help in this needful time.
And I now have to acknowledge, that I fully believe,
that he was mercifully pleased to be my director, and to furnish with matter,
ability and understanding, how and where to labor, suitable to the occasion.
Oh, let pure worship and thanksgiving be rendered to His holy goodness,
and everlasting high praises to His eternal, worthy name, says my soul!
We traveled two hundred miles on our way,
without making any stop except what nature called for.
Our new horse failing, it took us seven days with diligence,
and great expense to get among Friends.
We arrived at Mark Reeves`', second day, 8th of 11th month.
My companion being unwell we remained thereabouts several days and had several meetings,
one at a school house near Mark Reeves`', at the boat yard;
both of these were satisfactory.
Had another at Lime Stone, a poor run down meeting;
several of its leading members having gone from Friends, and joined the Ranters,
who call themselves Christians.

First day, the 14th, we had a meeting at the same place, painful enough.
There came a number of these dark, wild people to it.
The Lord in his customary goodness, gave me a clear sight,
and strengthened me to deliver His message to them in such
authority that I met with no interruption from them.
Good is the Lord and greatly to be loved and feared!
Second day, we went to New Hope.
Third day had a meeting there, and attended their Preparative Meeting on fourth day.
Fifth day, we had meeting at Westland.
Sixth day the Quarterly Meeting for Tennessee came on, held at that place.
It was much larger than I expected, as many Friends had moved into the western country.
It was evident that Truth owned the several sittings of the meeting.
Their business was conducted with weight, order, and much harmony.
I was comforted in being with them,
feeling the Gospel spring to arise with life and strength, and to flow freely;
settling upon the people as dew upon herbs.
Truly it was a refreshing time to the drooping in spirit,
through the continued tender mercies of our God.
We attended their first day meeting on the 21st,
also their Monthly Meeting on second day, wherein I felt much for them, and was enabled,
in a feeling, tender manner, fully to relieve my mind,
in my last legacy and farewell address to them--a humbling, tender time to me,
not easy to be forgotten.

Having procured a good horse, we set forward for Lost Creek; reached there fifth day.
Sixth day had a small meeting at Grassy Valley.
Seventh day, being their Monthly Meeting at Lost Creek, we attended it,
also their first day meeting,
the 28th. Both these meetings were favored with the owning presence of Israel`'s Shepherd.
Second day, we set forward for Newbury, arriving there on third day.
On fourth day, the 1st of 12th month, we attended their Preparative Meeting,
and their Monthly Meeting coming on seventh day, we stayed to it, and I was glad I did,
finding the Lord was with His people everywhere--however scattered
abroad and small the remnants are--when gathered in His name,
His presence is felt in the midst.
We stayed to their first day meeting also, where I was enabled, through Holy help,
so to relieve my mind, that I felt clear,
and entirely easy to take my leave of friends in Tennessee.
After meeting, we rode back to the Ferry, where we had a satisfactory meeting.

Next day, we went to Knoxville, and had a meeting there at evening; this was a dark,
hard place.
A suffering time we had, under a sense that oppression reigned,
and the pure Gospel principles were trodden under foot,
while they make great pretentious thereto.
Through it all, my great and good Master, whose arm is strong,
so strengthened and enabled me to bear a faithful testimony, to the great, good,
and righteous cause of justice, mercy, and truth, that I felt my mind well relieved;
and some of them acknowledged to the truth of the testimony.
On third day, the 7th of the month,
we parted affectionately with the Friends who accompanied us here,
and went forward for Blue River, Indiana.
It being winter, and often rainy, the roads were muddy, and much of the way,
the mire very deep, so that it took us eleven days, to get to Friends,
a distance of two hundred and eighty-one miles.
Nearly all of this solitary travel was in Kentucky, where,
to hear of their cruel acts to the slaves, and see what we did,
was shocking to all human and christian feelings;
and it made me think of the soul of just Lot, that was vexed from day to day,
with the filthy conversation, and the corrupt conduct of the people of Sodom.
It was a heavy-hearted travel to me.
We got among Friends at Blue River on seventh day, the 18th,
and providentially fell in at James White`'s, where we were tenderly taken care of,
and treated with parental affection, being almost worn out.
May the Lord bless them for it!

First day, the 19th, we attended Blue River meeting,
where I had to pass through some painful sensations, but had no opening in the Ministry.
Not having recovered from our fatigue, we rested on second day, and on third day,
we had a full, satisfactory meeting, at Salem Town.
Fourth day, the 22nd, we had a meeting at Poplar Grove.
Fifth day, were at Blue River again, where I was enabled,
so to labor in the authority of Truth, as to get some relief.
Sixth day, we went to Driftwood.
Seventh day, we lay by for notice to be given.
First day, the 26th, we attended that meeting, and drove to Sandy.
Had a meeting there on second day, and returned to Driftwood.
Third day, we returned to Matthew Coffin`'s, at Blue River settlement.
Being unwell, we lay by until sixth day, the 31st,
when we attended a meeting at Mount Pleasant, and returned to Matthew Coffin`'s,
and attended Blue River Monthly Meeting, on seventh day, the 1st of 1st month, 1825.
Here, the Lord, in His abundant mercy, gave strength, confidence, and utterance,
to relieve my mind of a grievous burden that had lain on me,
ever since I came into the vicinity of Blue River Quarter,
on account of unsoundness in the faith,
and that among the leaders of the people--which had spread much in that Quarter.
I had to labor in much plainness with them, both in public and private.
At this meeting we had the company of Stephen Grellett.
On first day, the 2nd, we attended meeting at the same place,
where I was enabled so fully to relieve my mind, and clear my skirts of them all,
that I left that part of the country, receiving a plentiful harvest,
and a full bosom of well loaded sheaves.

Second day, we went to Lick Creek, and had a meeting there the next day,
where Satan had been at work, and had made sad division among the brethren,
on account of the appointment of an Elder.
The meeting had proposed one, but there was another member who wanted the appointment,
and thought himself much better qualified for the office, than the one named.
He had got a party, and so resolutely opposed the appointment,
that it stopped in the Monthly Meeting.
I commended the meeting for not bringing forward the one who wanted the place,
for I never knew one of that disposition, who was put into that office,
but who proved a self-confident, overbearing,
burdensome member to the living in the Truth,
and a very dead weight in a select capacity.
Truly, there is great need in these days,
for meetings to be careful whom they put into the office of Elder,
and to ascertain clearly that they are sound in the faith,
and well baptized for the office;
for such will feel the responsibility that devolves on them,
and their accountability to the Great Head of the Church.

Such ones are not looking for promotion, or the praise of men;
but are favored to see the awful state of those who become drunk with self-confidence,
and beat their fellow servants and hand-maidens.
They will not dare to lift up the hand in judgment,
without a renewed anointing from the Lord, and a clear command from the Most High,
any more than a Minister who keeps his place will dare today to rise on his feet,
to deliver a testimony, because he was favored yesterday.
The lack of this care in Elders, I have sorrowfully seen in the light of the Lord,
has done much hurt in many places.
On fourth day, we had a meeting at East Grove.
Fifth day, at the Branch; in both these meetings Holy help was afforded,
sufficient for the day.
After this last meeting, I felt easy to leave them to the Lord,
and truly glad of the release.
Sixth day, we went to White River, and had a meeting with a few Friends there,
on seventh day, after which, we drove twelve miles, in a new part of the country,
a very tedious road, and fatiguing to the poor horses.
We got among Friends at Indian Creek,
seasonably to attend their little meeting on first day, the 9th. Second day,
we rode twenty miles, made a short stop, and went to Ephraim Owen`'s,
where we had a comfortable meeting on third day.
Fourth day, we drove to Jonathan O`'Neil`'s. Fifth day, started for Palmyra,
in the State of Illinois, to find a sister of my wife.
We traveled thirty miles that day, and lodged in Washington, Indiana.
Sixth day, we drove thirty miles.
Seventh day, we crossed the Wabash at Ramsey`'s Ferry,
where we heard from my brother-in-law, who was gone from there.

Here, I think it right to give some account of my brother-in-law.
He was a man of middling capacity.
He and his wife came among Friends by convincement.
They acquired a handsome property by their labor and prudence.
When the second war took place between England and America,
he lived in a part of the country, where the authority was pretty severe with Friends;
they repeated their demands, and took away his property, which made him very impatient.
He turned out, and went with the militia to save his property,
and not being willing to condemn this conduct, Friends disowned him;
at which he took such offense, and with the Government,
that he was determined to leave the country.
He sold to disadvantage, and fled to another part of the country,
where he found it no better;
so continued moving from place to place--until his property was gone.
He and his family became very poor.
Then he took to hard drinking, and had gone from the place,
(where he and family had been some time), down the river four hundred miles,
on to a slave holder`'s farm, and had taken the business of slave driver.

As this came to my knowledge, so correct that I could not doubt it,
it so bore me down that I had as much as I could do to support the man,
in that quiet composure that became the dignity of a christian;
for I could not refrain from musing on the subject, for several hours;
and to reflect that a man once in the enjoyment of the Truth, and knew what right was,
for the sake of saving a little property,
and to shun bearing the cross for Truth and righteousness`' sake,
would give way to make shipwreck of faith that he had once embraced,
and a good conscience that he had once enjoyed, and had brought on himself and family,
such woeful destruction, in every sense of the word.
The thoughts of it awakened such feelings in my mind,
that I do crave that this event may be a warning to my offspring to the latest generation,
when they are brought to the trial, that interest or good principle must be sacrificed,
let the interest go, and never wound a good conscience,
for that which cannot stay by nor befriend in the needful time,
when the blast of the Almighty is blown upon it.

And be sure not to do wrong in acquiring it,
that you may enjoy in peace what the Lord gives.
And if you should leave a little after you, honestly gotten,
it will be a blessing in the hands of your children.
After wading as above described, under the pressure of this severe trial several hours,
my great and good Master was pleased to give a hand of help in the needful time,
and strengthened me to give it all up, so that I became calm,
and then saw my way clear to pursue my religions concern.
We turned up the river, on the Illinois side, twenty-five miles, to Lawrenceville.
First day, the 16th, we drove to Thomas Lindley`'s, on Union Prairie, forty miles.
Second day, we had a meeting with Friends and others of that place,
which seemed to rejoice the few Friends thereabouts.
Third day, we crossed the river to Indiana, and went to Tarman`'s Creek,
and had a meeting there on fourth day.
After meeting we drove to Henry`'s Creek,
and had a comfortable meeting there on fifth day.

At this place there seemed to be some life and concern among Friends,
and we felt a comfortable hope, they would dwell therein.
Sixth day, we drove to Spring Creek, and had a meeting there on seventh day.
First day, the 23rd, we crossed the river to Illinois side, and went to Vermillion,
and on second day we had a meeting in this place--a
comfortable time--then rode eight miles,
and had a meeting in the evening to good satisfaction,
and stayed the night with Henry Canady.
Third day, we journeyed for Leatherwood Creek, arriving there about dark.
Here, we obtained a pretty full meeting the next day; for,
notwithstanding our late getting in, Friends seemed lively and spirited,
in giving notice to each other, and their neighbors; also, in coming to meeting,
which much revived my drooping mind.
We had met with so much indifference in a many places about giving notice of our appointments,
it made heavy getting along.
The bountiful Shepherd of Israel,
was pleased to bless this meeting with His holy presence, which was felt in the midst;
it was a solemn, good time to many minds.
May it be remembered with thanksgiving to the Great Giver, by all who were there!

We then proceeded to Sugar Creek, arriving there on sixth day.
Seventh day, we had a meeting with the few Friends of that place,
who were much tired with a person,
who had been disowned and had frequently come into their meetings,
and took up much time in preaching, to the burdening of Friends;
and what made it more grievous, he preached what were not Friends`' principles,
and when spoken with, he justified himself, saying,
that if he could not preach among them agreeable to his own conscience,
he would not meet with them.
After weighing the subject, I believed it right to tell Friends,
that I thought it would be best for them to let him
know they could not receive his testimony,
and why; for if you allow him to continue on, and he preaches as you have stated,
it will do more hurt in this new country,
by your giving him countenance--where Friends and their
principles are but little known--than all he can do,
should he make a noise abroad; for you can then inform the people why you rejected him.
Thus, you will be bearing a testimony for the Truth, in which you will be justified.

First day, the 30th, we had a large, favored meeting in Crawfordsville.
Second day, we moved on for White Lick, and arrived there third day evening,
and fourth day we attended that meeting.
Fifth day, we had a meeting at Fairfield.
Sixth day, we went to Indianapolis, and lay by on seventh day.
I felt my mind seriously drawn to have a meeting in this village,
and the people thought that as it was Court time,
if I could stay with them over first day,
it would be their desire generally to be at the meeting.
I felt easy to comply therewith, and on first day, the 6th of 2nd month, we had a large,
crowded meeting in the County House.
Divine Power was felt to arise in dominion in an eminent degree.
The word went forth in Gospel authority; the meeting became solemn, and ended, I think,
under a sweet and heavenly calm.
Blessed be the Name of the Lord, for when He leads into the deeps,
His arm is underneath and upholds; when He raises on high,
it still sustains and carries through in safety,
to the promotion of His own righteous cause, and the glory of His holy Name,
to whom all honor, worship, and high praises are due, forevermore!

Second day, we set forward for little Blue River, and reached there on third day.
Fourth day, we had a small meeting with a few Friends,
and some of their neighbors at Duck Creek; Fifth day,
we had another small meeting with Friends and others, at Flat Rock.
Sixth day, had another at Simon`'s Creek,
and though the prospect was not very promising thereabout,
we were well satisfied in being with our Friends;
having renewed cause to believe that the Lord is mindful of His people everywhere,
and rich in kindness to impart such spiritual food and help as they stand in need of.
Blessed be His holy name!
We drove to Milford, and lay by on seventh day, and on first day, the 13th,
we attended that meeting; then drove to West Union, and on second day,
had a meeting in that place.
On third day, we were at meeting at West Grove.
16th, at Fairfield.
17th, at Springfield.
18th, at West River. 19th, at Dunkirk.
20th, first day, at White River. 21st, at Jericho.
22nd, at Norwich.
23rd, at Arba.
24th, at Lynn.
25th, at Cherry Grove.
26th, at Centre.
First day, 27th, at New Garden, 28th, at Dover.
We also visited Chester, Woodbury, and Smyrna, before the Quarterly Meeting,
at Richmond came on.

It may appear strange that after visiting such a chain of meetings,
there was no particular observation made; but they being divided into two parties,
in one quarter and part of another, and great disunity having spread among them,
it occasioned much repetition in my public labors,
which caused me many hours of deep searching of heart, so that I called all in question;
but, relying on the arm of the Lord, I was strengthened and enabled from time to time,
in a plain, solemn, searching manner to labor so as to feel my mind relieved,
and clear of all their blood.
In passing through this part of the country, Friends let me entirely alone,
until I had finished my visit with them, which was perfectly right.
They then told me how it was with them, which was an additional relief to my mind,
in finding I had not been deceived in my feelings, nor misled in my labors,
and I can gratefully acknowledge that hitherto the Lord has helped me.
Forever adored be His goodness, and eternally blessed be His holy name!

We attended the several sittings of the Quarterly Meeting, in which my lot was deep,
painful exercise, finding the love of many had waxed cold, towards each other.
Great lack of true and living zeal, for the righteous cause of truth,
and great cause of humiliation and mourning, to the rightly concerned among them,
to whom a portion of cordial encouragement was imparted,
as also plain truths to the other class.
I felt well relieved at the close of the meeting on first day.
Third day, the 8th of 3rd month, was at the Ridge meeting; from there to Silver Creek,
Poplar Ridge, Salem, and to Newhope, on first day, the 13th. After which,
being much fatigued, and having a heavy cold in my head, I lay by on second day,
at the house of Joseph Maxwell, where I was kindly nursed.
Third day, we moved on to Westfield, attended that meeting on fourth day,
and went to Elk, and fifth day attended that meeting.
The Quarterly Meeting coming on at this place,
we met with Friends in the several sittings of it.

At this Quarter and in its vicinity,
my mind was solemnly impressed with a sense that false principles
and spurious preaching were creeping in among Friends,
and I had to give the alarm among them,
and felt great peace in being faithful to my holy Lord and good Master.
From this place we went to Rocky Spring, and had a meeting there on third day.
Fourth day, went to Union, and met with Friends of that place on fifth day.
From there to Concord, when we met with a small number of Friends to good satisfaction.
Then took Mill Creek before their Monthly Meeting came on,
at which we were on seventh day, and stayed their first day meeting, the 27th,
which proved a relieving time to my mind.
From there to Randolph, and had a meeting there on second day.
Third day, went to Sugar Creek, and had a meeting there on fourth day;
then drove to Springborough, and had a meeting with Friends of that place,
the 1st of 4th month, and drove to Henry Paddock`'s, at Reading.
Seventh day, we went to Cincinnati, and on first day, the 3rd, we attended that meeting,
in which my mind was led into a deep concern,
under a sense of the great lack of faithfulness in many high professors,
in not walking answerable to what they professed, and knew was right.
Such are stumbling blocks to the honest seeker, a reproach to the Truth,
and a sore grief to the upright-hearted.
Yet, through the tender mercy of Israel`'s unslumbering Shepherd,
strength and utterance were given to relieve my mind to good satisfaction.
After meeting, we returned to Benjamin Paddock`'s.

We had a pretty full meeting in Reading village, on second day.
Here, the Truth had the dominion; its doctrines went forth in Gospel authority,
greatly to the relief of my much tribulated mind,
and I hope to the honor of the great Head of the Church, who is truly worthy forevermore,
of the praise of all His works throughout His vast empire!
After meeting, we rode to Benjamin Butterworth`'s,
and had a meeting in that neighborhood, on third day.
Then passed on to Hopewell, where, on fourth day, we had a meeting; then to Turtle Creek,
and met with the people of that place on fifth day, and went forward to Waynesville,
where we had a meeting on seventh day.
On first day, we attended Dayton meeting.
In these parts, it was as in many other places,
such a likeness in the states of meetings,
it seemed too much repetition to descend into particulars.

Yet, we had this comfort, from impressions felt,
that there were well concerned minds in nearly every meeting,
to whom the Lord had special regard,
and for whose sakes He continues His favors to the Church;
and in answer to their prayers,
often renews His visitations to those who are settled
down at ease in a profession of the Truth,
as on their beds of ivory, in the outward form, which will do no more for them,
than ceremonies do for other Societies.
It finds them under the dominion of sin, and leaves them under condemnation in the end;
for there is nothing of man`'s wisdom, doings, or contrivance,
that can ensure peace in the end;
nothing short of a full belief in the law of the spirit of life in Christ Jesus,
our Lord and Advocate with the Father,
and a full and faithful obedience to all its manifestations,
that can set us free from the law of sin and death,
and enable us to rise superior to all the enchantments of a glittering world,
the lusts of the flesh, and the temptations of the devil,
and enable us to experience a going on,
conquering and to conquer principalities and powers,
and casting down all vain imaginations of the human heart.

The same day, we had a large, favored meeting at Dayton village,
in the meetinghouse belonging to the Methodists, who seemed very free to accommodate us.
We parted with them in much good will.
May the righteous Lord bless that favored season to the people!
Third day, the 12th, we had a meeting with Friends and others at Plumb Grove.
We then went to Greenplain, and made our home with Samuel Sleeper, an old acquaintance.
Fourth day, attended that meeting.
Notice having been given, the meeting was large,
and owned by the presence of Divine power, which was sensibly felt,
to the tendering of many minds, and I hope the contriting of some.
Oh how much we have to humble our minds,
under a sense of the continuation of Divine favor, far beyond our worthiness!
Fifth day, we drove to King`'s Creek,
and on sixth day had a meeting with the inhabitants of that place.
Then went to Goshen, and were at that Monthly Meeting on seventh day.

First day, the 17th, we were at the same place,
which gave opportunity for me fully to relieve my mind,
where there truly was need of well authorized labor.
From here, we went to Upland, where we had a small meeting on second day.
Third day, we were with Friends and others at a meeting at Westland.
Fourth day, had a meeting at Darby.
Fifth day, returned to Samuel Sleeper`'s, at Greenplain.
Sixth day, had a meeting at James Orin`'s, who lived in a little village,
a little out from Friends, which appeared to be a satisfactory opportunity,
both to Friends and others.
Afterwards, we drove to Seneca, where we had a meeting on seventh day;
then went to New Hope, and met with Friends on first day,
the 24th. Then passed on to Grassy Run, where we had a meeting on second day.
We then drove to Dover and had a meeting there on fourth day,
and proceeded on to Clear Creek, Fall Creek, Fairfield, and Walnut Creek,
where we lodged with Jacob Todhunter.
From there to Dry Run and Fairfield.
We generally had full meetings in the above named place.
The Gospel spring ran lively and free,
and I told my Friends that it seemed to me a clearing out, solemn, parting time,
and it appeared to be so with many of them.

We lay by on fifth day, I being sick.
On the 6th of 5th month, we attended the Select Quarterly Meeting, at Fairfield,
and next day, the meeting for worship and discipline,
and also the first day meeting on the 8th, and after it drove to East Fork.
On second day, had a meeting there, then took Greenbury, Newbury, and Wilmington,
having meetings in each of these places, much to the relief of my mind.
From there, to Miami Quarterly Meeting, held on sixth and seventh days, which was large,
and much favored in its several sittings.
Truth arose in dominion over all opposition,
and reigned to the praise of the holy Shepherd of Israel.
First day, the 15th, we attended meeting at the same place, to good satisfaction.
Then went to Grove, Springfield, Little Creek, Chester, Cyrus Creek, and Richland.
We had meetings in all the above named places, and then went to Greenplain,
and had a meeting at a place called Charleston, at four in the afternoon.
Third day, we drove to Springfield, where we fell in with Elizabeth Robson,
a Minister from England, who had appointed a meeting in that place.
We attended with her, and were truly edified with her lively Gospel testimony.
I was brought into near sympathy, and sweet unity with her.

After meeting, we parted with our friends, and put forward for Urbanna, where,
on fourth day, we had a meeting in that village to good satisfaction.
From there we journeyed till we got to Columbia, and on sixth day, we had a meeting there.
The people appeared well satisfied, and I felt my mind well relieved.
Seventh day, we drove to Delaware, and lodged with Joseph Howard.
First day, the 30th, we drove to Horton Howard`'s in C+++_______+++, Weston, and on second day,
we had a meeting with the Friends of that place.
Then proceeded to Alum Creek, and put up with Aaron Benedict.
Fourth day, the 1st of 8th month, we had a large meeting there, much favored,
and truly relieving to my pained mind.
Fifth day, we attended their Monthly Meeting,
and then continued our journey till we got to Lewis Taber`'s,
where we stopped and had a meeting.
From there to Joseph Washbourne`'s, where was a small settlement of Friends,
and had a meeting with them.
There appeared a lack of a lively, fervent seal among them,
and the spirit of the world creeping in;
so that the prospect of Truth`'s flourishing in that place is rather dull.
From there, to Benjamin White`'s, and had a meeting, and proceeded to Owl Creek,
and attended that little meeting on first day, the 12th. From this place,
we went to Zanesville, and had a meeting in the town on fourth day.
On seventh day, we went to Meig`'s Creek settlement,
and met with Friends at Blue Rock meeting, on first day, the 19th.

We then turned our course homewards, and took the following meetings.
First day, attended Plainfield Monthly Meeting,
and Flushing Monthly Meeting on seventh day.
First day, the 26th, we attended Short Creek meeting.
Here I was enabled to clear my mind of a burden I had long carried;
for when I was at the Yearly Meeting and thereabouts,
I was much embarrassed with the unsound preaching of a Minister from my own Yearly Meeting,
(which preaching caused a considerable stir among Friends),
so that I passed from those parts, not getting the relief I wanted.
But now, on my return this way, finding my way clear,
and that my Master had renewed his bow in my hand, with additional strength,
I stopped and visited several meetings hereabouts, and Mount Pleasant in the afternoon,
on first day.
Second day, at Harrisville.
Fourth day, Carrolton, Fifth day, we returned to West Grove,
and had a meeting there the 1st of the 7th month.
Then went to Smithfield, attended that meeting on first day,
the 3rd. In all these meetings, the Gospel current flowed free and clear;
I felt my mind fully relieved, and filled with heavenly peace,
and enabled to return thanks and praise to the Lord, my Redeemer, who had led me about,
sustained and carried me through the heights and depths,
when no other arm could have supported me.
Blessed, forever, be His holy name!

From this place we put forward for New Lisbon.
On fourth day, we attended that meeting, and went to New Garden.
Fifth day, we attended that meeting.
Sixth day, had a meeting at the Grove.
My labors in these last three meetings were plain and laborious,
there being much lack of Gospel love among the professed brethren,
and false principles creeping into many families.
Yet, my good Master, through it all,
gave strength and utterance so to labor as to feel well relieved,
and clear of all their blood, whether they hear or forbear.
First day, the 10th, we attended Salem meeting,
which was large and a refreshing time to me.
Second day, we set forward for Conneaut.
Third day, we reached the settlement.
Fourth day, had a meeting with the few Friends there.
Fifth day, 14th, we set forward for home, where we arrived on seventh day,
the 30th of the month, having attended two meetings on the way.
In this journey we traveled seven thousand six hundred miles,
in a few days short of twenty months.
I found my family well, to my great comfort.
Here ends the account of my religious travels, to the sixty-fourth year of my age,
which I want should be kept by my children, for their warning, instruction,
and encouragement; and may the Lord bless its contents to them, for good.
