== Chapter XI

In the year 1829, having obtained the unity of my own Monthly Meeting,
I set out the 10th of 7th month,
to perform a religious visit in the vicinity of several
of the Southern Quarters in the Yearly Meeting,
and fell in at a small meeting at Danby on first day,
that seemed to me like a little company of kids couched down,
while the boasting Assyrian Spirit had filled the country with their clamor;
and when I came to sit down with them,
I was favored to feel the presence of the Lamb of God to be with them;
with a clear evidence that the Lord Almighty continues
to regard the low state of His people,
who look to him with unabated constancy, for counsel, direction, and protection;
and that His never failing arm always upholds--His wisdom guides--and
His almighty power enables them to fight under the banner of the Lamb,
so as to obtain the victory.
My heart was made glad, and my soul comforted in being with them.
At four in the afternoon,
I had an appointed meeting in a small village called the Borough,
where considerably more came than I expected.
They were mostly sober countenanced people; it was a favored, satisfactory meeting to me.
Some Friends thought there would have been many more at the meeting,
had not a Hicksite preacher come into the place a few hours before me,
and notice thereof spread ahead of mine.

Many of other societies were disposed to go and hear for themselves,
and see if he would preach up his principles; as many had heard him years before,
when he stood in unity with Friends; but now they were disappointed, several told me,
for he never touched his principles, appearing careful to preach an old fashioned sermon;
which gave them cause to think he was a hypocrite, and ashamed to own his principles.
This so nettled the Hicksites, that they resorted to their accustomed plea,
that the people did not understand him; they believed he meant otherwise;
which they could not reconcile with the people;
so that his visit proved not satisfactory to either party.

After meeting, I went to Noah Conger`'s, and stayed that night, and most of second day.
The Hicksites finding I was there,
several of them and a number of friendly neighbors came in.
Caleb Randall, one of the Hicksites, a subtle, oily-tongued man,
aimed at me his discourse.
I think for one hour and a half he kept up his caviling.
And by being guarded,
I was enabled to answer in a way that disappointed him in every attack.
At length, I told him that I knew he was as subtle as any other man,
and that he would not get me in that way, for I was aware of him,
and he might as well give it up first as last.
This so far dashed him, that he dropped his discourse and became mute.
This gave me an opportunity to make a number of observations on his expressions,
and to state a number of facts, which I was eye and ear witness to,
of their conduct and language;
very much to the satisfaction of those neighbors who sat by; upon which he left.
Though a number were present, we soon all became silent,
and were favored with a tendering, refreshing time, not easy to be forgotten by me.
After which I took my leave of them, and went to Christopher Almy`'s, in Tinmouth,
and had a meeting on third day, in that neighborhood, with a thoughtful people,
several of whom were looking toward Friends.
It was a favored time, I hope to the praise of the Lord,
and promotion of the righteous cause of the Gospel.

On fourth day, I had a meeting in another part of Tinmouth.
It was full; the minds of the people appeared open to hear the truths of the Gospel.
It was a refreshing, relieving time to my mind.
Thanks be ascribed to the Lord Most High,
for the continuation of his day of favor and visitation to the people,
and strengthening His poor dependent servants as He leads them about,
and they are obedient to do all he requires of them;
richly rewarding them with heavenly peace.
Blessed be His holy name!
Fifth day, I went to Abner Potter`'s, in Granville, State of New York.
On sixth day, I had a very small meeting in North Granville Village.
After sitting a little in silence, an infidel sitting in the meeting,
inquired the difference between the Orthodox Friends and the Hicksites.
I felt fully at liberty to answer him,
by stating the difference in sentiment on points of doctrine.
He broke in several times, to defend the Hicksites.
I told him, he had asked a fair question,
and I should answer it before I went on any other discourse.
When I had thus said, I took up his and the Hicksites principles,
and showed him that his and their belief had no proof but bare assertion,
for they both discarded the Scriptures as a test for doctrines.
It was folly, and they had no right to resort to a book to prop their fabric,
which they declared not to be relied on; so of course they had no proof but their wit,
eloquence, art or sophistry, to prop their fabric with, while we had the Scriptures;
for as we believed in them, we had a right to appeal to them.
Especially as they were ushered into the world in a different manner from other books;
God being pleased to bear the witness of them by signs and wonders,
and many miracles--a proof of their Divine origin.

Also, the records of several nations contemporary with them, had stated the same events,
in a number of instances; and I should not ramble about with him, but call for his proof.
He became mute, and after a short pause, feeling my mind much opened,
I took up the subject at large, and showed the few who were gathered,
the abundant proof there was in support of the Gospel,
and the great lack of it on the side of the infidel;
also the reason of our hope and faith, from the same store of proof.
When I felt the current to stop, and closed with it,
a perceptible solemnity was spread over the meeting, and some shed tears.
We sat a little; the people were then informed that I had nothing more for them.
All appeared well satisfied who spoke to me; one woman expressed, she believed every word.
I felt my mind fully relieved and comforted.

On seventh day, I returned to Danby, and attended that little meeting again,
and another in the afternoon, which was large for that place.
In both, the Master of Israel`'s assemblies was felt to be in the midst with His people,
to comfort and strengthen them to hold up the standard of Truth in its own authority;
to the praise of His own name, who is worthy thereof.
On second day, with Noah Conger, I went to Mount Holly,
where all the members but one were gone from Friends; the most of them Hicksites;
so we had a meeting in the Methodist meetinghouse;
many of the inhabitants and most of the Hicksites attending.
I was led in a way not usual for me,
having to state our principles on the fundamental points of the Gospel,
and those of the Hicksites on the same points,
contrasting the difference between the two, at considerable length;
bringing into view much Scripture proof of our doctrines,
so that it was a laborious day to me; yet through the tender mercy of Jehovah,
holy Help was given equal to the occasion, and sufficient for the day.
Blessed be His holy name!
For His heavenly presence was felt to spread over the meeting--a solemn, tendering time,
to many minds.

I went to the house of Samuel Cook, an elder who went with the Hicksites;
most of that class there, coming in, one of them began the subject.
This opened the way for me to inform them what the Hicksite principles were,
in all its bearings, and of their conduct, that I had been an eye and ear witness of,
relative to their rending, harsh conduct in words and actions.
They sat like people amazed until I got through, then asked a few questions,
which I answered plainly and clearly, so that when we parted with Samuel Cook and family,
he looked like a sick man.
I found they had been filled with false representations.
In answer to those questions,
I stated facts that could be supported by the best authority,
and a large number of accredited documents.
I left it with them to think for themselves,
with desires that the Lord might show compassion, in His boundless favors,
by His forgiving mercies to these poor, deceived creatures,
for they know not what they do.
With thankfulness, I may truly acknowledge,
that I felt as great satisfaction and peace in the labors of this interview,
as any service, I had performed in the cause of Truth, in this journey.

Third day, we returned to Danby.
On fourth day, I attended the small meeting there, where we were comforted together,
being favored to feel the Heavenly Father`'s love
to bind us together in the fellowship of the Gospel.
After meeting, I returned to Granville, and having taken cold,
I lay by sixth and seventh days to recruit, at the house of my valued friend,
Nathaniel Potter.
First day, the 26th, I attended Friends`' meeting,
and appointed another in East Granville for the afternoon.
In both, the spring of the Gospel was lively,
and its testimony went forth in the clearness of Gospel authority,
to the humbling and tendering of the minds of many;
Truth reigned to the glory and honor of the God of all grace, to whom all praise belongs;
and may He grant the favor of the day to be a lasting blessing to the people.

Second day, the 27th, I went to Cambridge, and called on +++_______+++,
a family that had been more than common attached to me for twenty years or more;
so much so, that they seemed hurt in their feelings if I passed by,
and did not call on them.
Of course, I often called when I passed that way;
for I had often been a guest at the table of his wife`'s parents,
for nearly twenty-seven years, and was always treated with great respect.
Her father had been deceased two or three years, and her mother was living with her.
When I entered the door, the wife was standing near; I offered her my hand;
she gave her hand with a remarkable sour look.
I then asked after the family`'s health;
she answered me with a voice that indicated ill-nature,
and I could not hear all she said.
I then asked, if her mother was living; she said, "`yes, she is in the other room.`"
She went in, and I followed, and took her mother by the hand, asking after her health.
She answered, "`I am a poor creature;`" then looked me full in the face,
withdrew her hand, and turned from me; her daughter told her who I was,
but it made no difference in her conduct.
I introduced some discourse, but got no answer.

When I got tired of this treatment, I went into the other room again,
and asked for the husband, as I wished to see him.
She sent for him; he was not far off,
(as he stood and looked at me when I drove up to the door,) but did not come in.
I urged it; she sent for him a second time, yet he did not come.
I asked twice for some food for my horse.
At length there was a small lock of hay brought,
which looked like the leavings of another; my creature would not touch it,
though she had been drove a long distance, and was quite hungry.
The wife--mother of the family--asked if I wanted some food;
I told her "`No`" (for the truth was I had got a full meal by this time,) but said,
"`I shall be glad of some cool drink.`"
She brought me a glass of warm beer, with a cold countenance, and slow step.
I endeavored to introduce discourse on different subjects; but got for answer, Yes,
or No; and sometimes no answer at all.
I had not often been beat in this way, and was not willing to give it up,
as I had called on them, for former friendship; not knowing how they stood.

After sitting some time silent, I pleasantly asked her, what I had done,
or what had transpired, that changed their conduct towards me;
as I did not know what it was, I wished to be informed; but got no answer.
I repeated the question several times, yet there was no answer.
She became dumb.
I then stated, that it was my right, if I had done anything, to know what it was,
that I might take it out of the way; and if innocent, to speak for myself;
when this answer was given: "`I have nothing laid up against anybody.`"
I said, "`This does not directly answer my question,
and from what I have seen and met with,
I shall consider myself excused from calling on you in future;`"
and left them with my mind filled with heartfelt pity,
with this conclusion: if this is the effect of Hicksite principles,
I am glad and thankful that I am no Hicksite.
I then had to ride nine miles, before I got any refreshment for myself and horse,
after driving a pretty full day`'s journey before--unless I had stopped at a tavern.

When I arrived at Cornelius Devol`'s widow`'s, I met with a kind reception,
good entertainment, and a fine night`'s rest,
which seemed to sweeten the bitter cup of the day before.
Third day, 28th, I had a meeting in the neighborhood,
which was pretty full for the place, and a favored time, to the tendering of many minds.
From there to Caleb Barker`'s, at White Creek, where I was received with kindness;
and the day following, had a small meeting in a little village near.
The next day I spent in a social visit, much to my satisfaction,
as it gave me an opportunity to clear my mind, without giving offence,
on the subject of the division among us.
From there I went to Pittstown, and on my way,
turned a little aside to visit J. A. I found his wife a tender, well concerned Friend,
and he a warm Hicksite.
He cast many reflections on Friends, and some false statements,
which I endeavored to correct, but to no satisfaction to him.
Observing this, I endeavored to close the discourse, but could not,
for he continued to bring up new charges, that grieved his wife,
and deprived me of the comfort I hoped for in the visit.
Seeing no prospect of its being any better, I took leave of them,
and went to Micajah Hunt`'s. He and his wife were kind, faithful Friends.
I stayed with them all night; and on seventh day, the 1st of 8th month,
I started for Schaghticoke Point,
and the day following I had a meeting in the South part of Pittstown, near one Slade`'s,
a Friend living much alone; it was a humbling, serious time to me,
which appeared to be the state of the meeting.
The next day we went to Adams, and called on a Friend by the way,
who was desirous to know the cause of contention.
I gave him all the information I could, which appeared to relieve him much.
His ears had been filled with sentiments entirely false.
I informed him how and where he might find all that I had stated,
supported by the best authority, and I parted with him in a tender state of mind.

When I arrived at Adams, I found that their mid week meeting was on Fifth day,
and that there was a funeral of a young man who was to be buried before the meeting.
Notice of my being there having been given, the meeting was large;
many of the Hicksites came, whose countenances bade defiance,
and they appeared to be armed with a coat of mail.
There champion came, and placed himself at my right hand,
and soon this language ran through my mind,
"`This is a Hicksite;`" but I felt to my comfort, that his spirit could not touch me.
After sitting a little in deep humility, I felt the Word of Life to arise,
and in attending to the Divine motion,
the Word of Truth went forth in the clearness of its own authority,
and arose into dominion;--the power of the Lord bound down that boasting spirit,
the meeting became solemn, and ended quietly;
I hope to the honor of Truth and the glory of God, who is worthy of honor, might,
majesty, and the praise of all His works forevermore!

On Sixth day, I had a meeting in Cheshire, to pretty good satisfaction;
yet there was not that openness in the minds of the people to receive the Truth,
as in some other places.--Seventh day, I had a meeting in Adams,
North Village--a favored season.
Thanks, honor, and praise, be ascribed to the Name of the most high God, for His safe,
directing hand through the heights and depths, and for His preserving power,
in abasedness and aboundings hitherto!
First day, I met with Friends, and was favored to feel with them in their tried state,
and had a word of encouragement for them to abide in the patience,
and keep to the faith once delivered to the saints.
Second day, I drove to Granville, to attend Easton Quarterly Meeting, held there.
The several sittings thereof were owned by the Great Head of the Church;
the business was conducted in harmony--a uniting solemnity was realized to the close,
and Friends parted from each other, I trust, with thankful hearts,
for the favor of enjoying our meetings without being disturbed.
Great are the favors of the Lord, continued to His people.
Blessed, forever, be His Name!

After meeting, with other Friends, we drove about twenty miles towards Easton,
and on sixth day had a meeting in a village, formerly called Whipple City.
The opportunity was much to the relief of my mind, and well accepted by the people.
The truths delivered were acknowledged by them.
After meeting, I drove to Abner Devol`'s and rested on seventh day.
First day, the 24th, I attended the small meeting of Friends near Schaghticoke Point;
wherein, to my comfort, and satisfaction, I found their meeting together,
was owned by the Head of the Church--three families that could not join with the Hicksites,
but met by themselves.
On second day, I went to Little White Creek, and next day had a small meeting there,
in which I was enabled to clear my mind, and left them peacefully.

Fourth day, I went to Cambridge, and had a small meeting at five in the afternoon.
Here is but one woman who is a Friend, the rest are Hicksites.
I went to the house of one of them.
At first he appeared very pleasant, and expressed his gladness that I had called on him,
saying I was welcome.
After some conversation,
I informed him that I came there with a prospect of having a meeting with the people,
if they were willing to meet with me, and asked him,
where he thought I could get a house.
He replied, "`There is the meetinghouse.`"
I informed him that I could go into it on my own right and no other principle;
having a right to any Friends`' meetinghouse in the Yearly Meeting.
This seemed to startle him a little, yet he said,
"`You have my consent if the rest agree to it.`"
The thought struck me, that I should not get the meetinghouse,
and I asked if there was a school-house in the neighborhood,
owned by different Societies.
He said, there was one near the meetinghouse.
I turned to the young Friend with me,
and told him to go to the others and find whether
they were willing for me to go into the meetinghouse,
if I felt free to do so; if not to go to the trustees of the school-house,
and obtain that if he could.
The Hicksite replied, "`I am a proprietor and a trustee, and will give my consent.`"
The young Friend went to several, who would neither fully deny nor consent;
but having obtained liberty to use the school-house, we notified for the meeting.
Near the time appointed, quite a body of people gathered,
and stood in the road before the meetinghouse;
and there in the presence of many of their neighbors, they denied us the house,
and we went into the school-house, which was soon filled and crowded.
It proved a good meeting, and the truths of the Gospel opened clearly, and flowed freely.

Next morning, my host, after all his pretended kindness,
wondered how I could have the confidence to come among them and want to have a meeting,
when I was one of those who had disowned them, as believers in false principles.
He went on so long, that I found it needful to exercise patience,
and after he got through, I observed,
that he must know that Friends often traveled among other societies,
and the motive was to convince them of their errors,
and to strengthen that which they found to be right; that thus I had come among them.
He quickly answered, "`You have not convinced me,
for I feel four times as strong as I did before.`"
I pleasantly answered him, that I did not feel myself accountable for his not believing.
After some moderate discourse, we parted.
I had not gone far, before I fell in with another of the same class,
and soon found that my getting a meeting in the neighborhood was not pleasing.
Their neighbors being so well satisfied appeared to perplex them.
He asked me several questions, which I answered in a plain, simple manner,
he seemed willing to let me pass, and we parted apparently pleasant.
I passed on to Job Allen`'s,--his wife is the only
Friend in that meeting--and took breakfast,
and left without anything disagreeable occurring at that time, and went to Pittstown,
to Micajah Hunt`'s, where I was confined for several days by indisposition.
In looking over what I have passed through the last week,
I find deep cause to be thankful to the Great Head of the Church,
for favoring me with patience and ability to answer
cavilers in a way that often disappointed them;
and to bear the tantalizing censures, with calmness,
as though all was fair weather--a thing I should
once have thought could hardly have been,
without having my feelings touched.
The preservation of the Lord to me is marvelous,
and His strong arm bore up and sustained through every trial.
Forever adored and magnified, be His Holy Name!

On first day, I had a meeting at Micajah Hunt`'s house,
one-fourth of a mile from Friend`'s Meetinghouse; it was large for that place,
and through Divine mercy, a favored, tendering time.
May the Lord bless it with increase to His own honor, and the gathering of the people!
Second day, I drove to Philipstown, and called on an aged aunt,
whom I had not seen for twenty years.
The family were glad to see me, and treated me with respectful kindness.
My uncle had moved there for the sake of enlarging his possessions,
when he was well off before.
Settling out from Friends,
and pursuing his object--the increase of wealth--he lost that love for the Society,
and that religious concern which he once had, and fell into weakness,
for which he was disowned.
His children all left Friends; and when he deceased, he left them as to property,
far short of his object--a sentiment that I had long entertained,
livingly revived while I was with them,
that Friends ought to have a strict regard to its being right for them to move,
as well as an eye to the advance of their pecuniary interest.
When the former is neglected, the latter may be blasted,
and families sustain great loss every way.

I went next to Chatham--not a large meeting--where most had gone off with the Hicksites,
except a few, with whom I had a meeting,
and a goodly looking company of their neighbors were present.
The meeting was favored and ended quietly.
From there I went to Ghent, and put up with Samuel Marriott,
and the day following had a full, satisfactory meeting in a school-house;
the Hicksites having possession of the meetinghouse,
Friends were debarred the use of it.
At four in the afternoon I had a good meeting in Hudson,
to the comfort of the honest-hearted.
On second day, I went to Little Nine Partners; had a meeting there on third day,
in Friends Meetinghouse; a mixed gathering, and exercising time;
yet the Lord in mercy to the people,
gave ability to hold forth the truth of the Gospel in clearness;
the meeting was solid and quiet.--Fourth day, I was at the Plains.
Those who had the care of giving notice of the meeting, being unfaithful,
the meeting was very small.
Fifth day, I attended Stanford meeting, in course, notice being given,
that I was expected there; it was well attended; ability was given to relieve my mind,
so as to enjoy a peaceful quiet.
Sixth day, I had a meeting at the Creek, my native place; which was large,
considering the situation; many having gone off with the Hicksites,
yet many of their neighbors came in.
It was a favored time; the Lord`'s presence was sensibly felt, to own the little,
stripped and tried company of that meeting.
Seventh day, I crossed the river at Hyde Park, and went to Rosendale.
Attended that meeting on first day.
Many not in membership with Friends were in attendance.
My mind was enlarged,
and I was enabled to hold up the standard of Truth over the head of boasting
Goliath and all his host.--Blessed be the name of the Lord.
I am now at Isaiah Tilson`'s, seventh of 9th month.
After this, I visited Paltz, Plattekill, and Upper Clove meetings.

In all of these I was mercifully enabled, so to clear my mind as to feel well relieved,
and the reward of full showers of peace,
having the evidence that Truth reigned over all opposition.
Next I went to Canterberry, first day of the week,
and had a meeting at six o`'clock in the evening.
It was large and crowded, consisting of a great mixture,
among whom were many hardy minds, so that the labor in the ministry was very trying,
feeling the necessity to stand on my feet a length of time,
and communicate to the people.
I felt it return like the rebounding of water cast against a rock,
refusing all penetration; it was so discouraging, that I fully believe,
had it not been for the sake of a better class among them,
I should have been excused from speaking.
I was led to show the Divine authority by which the
Holy Scriptures were ushered into the world;
and the abundant proof to substantiate them and establish
the Gospel of our Lord and Saviour Jesus Christ;
also, to contrast the doctrines of the Gospel, with the Infidelity of the present day.
I had to show that Infidelity was always built on the opinions of men,
which had never given any better proof, than the art of sophistry,
and casting censures and ridicule on the Christian religion,
by which conduct they deceive the unwary.
Some in the assembly, received the communication with gladness;
others listened to it with attention; yet there appeared to be a number, who,
in all the defiance of hardihood and confidence, stood out to the last.
When I sat down, my shirt was wet to my back, and I was brought to remember,
that it was the case with my Lord many times, that although the people saw his miracles,
they would not believe, nor receive him.
Although I was, in the tender mercy of my Lord,
enabled to clear my mind of all He gave me for the people,
yet I could but sorrow for those of the unbelieving class,
and parted with them with a heavy heart.

I then went to Marlborough, and had a meeting with a stripped few there;
it was a time of comfort and encouragement, to the honest of that place.
15th of 9th month, I attended a Monthly Meeting at Poughkeepsie,
and returned to Samuel Adam`'s, the 16th. 17th and 18th, I lay by.
19th, first day, had a meeting at Clinesopas, where a number of the Hicksites came,
I was enabled to hold up the standard of Truth, over the head of the Hicksite spirit.
Truth prevailed over all opposition.
I attended a meeting in the afternoon with +++_______+++; he preached a long sermon,
and acted out a deal of gesture, and I thought lessened the weight of his preaching.
The third day following, the Monthly Meeting was held at Rosendale Plains;
it was large for that place, and was a humbling, tendering time,
to the refreshment of the upright.
Their business was conducted in much harmony.
Fourth day, attended the Valley Monthly Meeting;
their business was managed very regularly, and in harmony.
My service was somewhat laborious, yet I was marvelously enabled to clear my mind,
and felt satisfied.

Fifth day, I attended Cornwall Monthly Meeting, where they are much stripped,
many having gone off with the Hicksites,
who had driven Friends out of nearly all their meetinghouses in those parts;
yet it was a favored time of renewal of strength.
The Holy presence of the Lord was felt to be near and present,
with the few faithful sufferers of this place, to the encouraging of the honest-hearted.
Blessed, and forever adored, be His holy name,
who never said to the wrestling seed of Jacob, seek My face in vain!
I returned to the Valley, and on seventh day, in company with Tristam Russell,
went to Marmakating Hollow, and put up with James Pine, for the night.
First day, the 26th, we had a meeting there to pretty good satisfaction.
Second day, we rode to Paul Horton`'s, in Bethel, where we had a meeting in the evening,
with the few Friends and their neighbors--a low time--the
professors of religion appeared to be much dried up,
if they were ever alive, in a true living concern.

Third day, we went to Mount Silby, where we had a meeting in the Courthouse, at three,
in the afternoon.
It was small;--it was thought by Maria Emley`'s having
been there and preached Hicksite doctrine,
which offended the people of the village,
and they concluded they would not be imposed upon--this shut up the way for Friends.
I found it my duty to set forth Friends`' belief
in the fundamental doctrines of the Gospel in full,
and to state, that whosoever denied those doctrines, we, as a people,
had no fellowship with.
From this, we went to Ebenezer Lounsbury`'s, where we had a full, good meeting at evening.
The truths of the Gospel flowed freely; the minds of the people were open to hear;
it ended well.
We then went to James Devine`'s, Upper Navesink; he and his wife were warm Hicksites,
yet appeared earnest that we should have a meeting at their school-house,
in the neighborhood in the evening, which we complied with.
It was a full meeting, and I was much enlarged in holding up the doctrines of the Gospel,
being led to show that Grace and Truth came by Jesus Christ;
and Truth was over all opposition, and reigned at that time.
The man and his wife above-mentioned, attended the meeting,
but had kept their principles out of sight.
After meeting we returned to their house; they appeared uneasy the rest of the evening.
Next morning early,
they broke out with heavy censures and bitter reflections against Friends,
mixed up with many objections against our principles and doctrines,
and yet contrived to assert, that they were Friends.
After they had nearly exhausted themselves,
we calmly endeavored to show the inconsistency of
their principles and conduct as a people,
and parted with them much more calm,
than it had appeared we should be able to--a favor that seemed to sweeten the bitter.

We next went to Daniel Reynold`'s, at Thunder Hill.
He and family were Hicksites.
They received us with courtesy, and when we opened our prospect of a meeting,
it did not disconcert him.
He sat calm a little, then said, we were welcome to the school-house, in which they met,
and of which he was chief owner; but that he could not assist us at all in giving notice,
as we had disowned them.
This honest conduct was so to my satisfaction,
that I felt better in his house than I did before.
The two Friends who were with me, went out and gave pretty general notice.
We had a full favored meeting in the evening, Daniel and his family mostly attended.
It was easily seen that Daniel was disappointed, in seeing so many come to the meeting;
yet he carried it through courteously, and we parted with them pleasantly,
and went to Greenfield, where I appointed a meeting, at evening,
in Friends`' meetinghouse, and met with no opposition on that account,
though they were nearly all gone from Friends.
It was large for that place.
I felt my mind clothed with Gospel authority, and was led to show,
that the spirit that confessed not that Jesus Christ has come in the flesh,
is not of God.
I was much enlarged in the authority of the everlasting Truth, which was in dominion,
and prevailed over all gainsaying spirits.

We next went to Benjamin Birdsall`'s, at Marmakating Hollow,
and had a meeting at the widow Anna Penny`'s, at evening;
a pretty full gathering of people.
Much of the formal, but little of the life of vital religion,
could be realized among them; yet through Divine goodness,
I was enabled to clear my mind in a plain, sifting testimony, to my relief,
and peaceful quiet--a good reward.
On seventh day morning, we returned to James Penny`'s, very much worn down with fatigue,
where I lay by, and rested on first day, the 5th of 10th month.
Second day, we went to the Valley and lodged with Tristam Russel.
Third day, I went to see the children of the late widow Heaton, five in number,
all single.
They appeared very sensibly to feel the loss of their valuable parents,
yet they were favored to bear their trials,
with a good degree of composure and resignation, which I was glad to see;
yet my feelings were tenderly impressed in sympathy for and with them.
Fourth day, I attended Platte Hill Meeting,
where I was favored feelingly to sympathize with that small meeting,
in the loss of two valuable pillars, as the two before mentioned Friends were.
Fifth day, I attended the Valley Meeting,
where they had undergone severe trials and siftings; yet, there was that remaining,
that kept the pure spring of life from a free circulation,
and caused the innocent life to suffer.
I was enabled to clear my mind to full satisfaction.

Sixth day, I went to Blooming Grove, and attended that meeting on first day,
where there was much rubbish.
Strength was given sufficient for the day, and utterance to clear my mind,
so as to feel a peaceful quiet.
Blessed be the Lord, for His sustaining help, and holy guidance!
Second day, I went to Smith Glove, to James Hazard`'s, where I had a full,
crowded meeting.
In the forepart of it, I felt stripped in spirit,
but laboring to be patient and resigned to the Lord`'s will,
I felt a gentle spring of the Gospel to open in clearness.
As I attended to it, it became as a river that a man could swim in.
Truth arose in dominion,
its standard was set up by the help and strength of Israel`'s Shepherd.
Blessed forever, be His name!

I returned to the Valley, to attend the Quarterly Meeting.
The several sittings thereof were owned by the holy Shepherd of Israel,
to the strengthening and encouraging of the right-minded.
I returned to the Clove again, and had a large meeting in the Methodist meetinghouse;
the people were sober and attentive--a favored time,
through the continued mercy of the blessed Shepherd of Israel!
We then went to William Conklin`'s, in Conegat, who had gone with the Hicksites,
but was more mild than many I had met with before.
He entertained us kindly.
I informed him we came with a view of holding a meeting in that place,
if the people were disposed to meet with us; and asked him,
where he thought a house could be had.
He said, there was the meetinghouse, that I could have.
I told him I could not go into it on any other principle than my own right,
for I considered I had not forfeited my right in any house in the Yearly Meeting,
nor had the Friends that I fellowshipped with.
He answered, he thought I had as good a right as ever, and I was welcome to the use of it.
The meeting was held in it, and largely attended by Friends,
Hicksites and their neighbors; it was to the relief of my mind,
as my Master furnished me with ability,
and utterance to hold up the truths of the Gospel; and to show the cloud of witnesses,
that ever had and ever would accompany and sustain
the Gospel of our Lord and Savior Jesus Christ.
We next went to Harristown, where there were but two members, and some friendly people,
who were under discouragement, on account of the confusion among Friends.
We had a meeting with them, which seemed to raise their drooping heads.

My stopping here so detained me, that I did not get to the Quarterly meeting in New York,
where I wanted to be, until the parting meeting;
where I had the company of many of my Friends,
enjoying the comforting holy presence of the dear Master of the true Israel of our assemblies.
After meeting I went to Flushing, on Long Island, and put up with Walter Farrington,
the 22nd of 10th month, and had a pretty full meeting for the place, at evening,
in their new meetinghouse, which the few Friends who stayed faithful, had built;
having been dispossessed of their former house by the Hicksites.
Friends had well accommodated themselves with a good one,
where they could meet together in the quiet.
Each one sat under his vine and fig tree, and none to disturb.
I was comforted in being with them,
and glad to find them cheerfully resigned to their condition.
I think they possess their souls in the quiet.

First day, I attended Westbury meeting, in their new meetinghouse;
they were similarly situated as their brethren at Flushing.
The meeting was larger than was expected,
as many of their neighbors came in and sat with us, in a sober, solid way.
Truth spread over the meeting to the tendering of many minds,
and comforting of the few faithful Friends there,
who have been deep sufferers in the great convulsion among us.
At four in the afternoon, I had a meeting at Thomas Willis`', in Jericho;
Friends being also deprived of their house, and but few Friends left.
The meeting was larger than I had reason to expect.
The great Head of the Church was pleased to favor with His holy presence in the midst,
to the comforting together of the upright in heart.
I then crossed to the Main, and attended Purchase Quarterly Meeting.
The several sittings were owned by the great Head of the Church;
His presence being sensibly felt among us.
The business was conducted with weight, condescension and solemnity,
to the satisfaction and comfort of many.
At the closing meeting, it pleased the righteous, holy Shepherd of the flock,
to favor His little ones, with a small portion of the best wine,
to the strengthening of the weak, and raising in hope, the heads that hung down.
Forever praised and blessed, be His holy name!

After meeting, I went to Lot Birdsall`'s, where I lodged, in Shapaqua,
the 29th of 10th month.
The day following I had a meeting there.
Then at Croton Valley, Peekskill, Croton and Salem;
in all which it pleased the head of the Church to favor with His holy presence,
and to comfort His tried ones.
From Salem, I went to Purchase to attend that Monthly Meeting; it was small, yet favored.
Their business was conducted in harmony, and I think in the right life.
The next day I was at Shapaqua Monthly Meeting.
I think it is not quite as much reduced by the division as the Purchase;
they also did their business in condescension.
The following day I was at Amawalk Monthly Meeting;
it was larger than I expected to find it;
their business was guardedly conducted in condescension.
In all those meetings, the presence of the holy Head of the Church,
was felt to be the strength of His people, and the lifting up the hands that hung down.
I then turned and went to Westchester, and put up with Lindley More,
on seventh day evening, where I stayed over first day, and attended that meeting.
Friends had been driven out of their meetinghouse,
and it was then held in Lindley More`'s house;
where it pleased the Beloved of souls to fulfill His promise,
that where two or three are gathered in His name, there He would be in the midst of them.
I continued at Lindley`'s on second day.
Third day, the 17th, I went back to Long Island.
Fourth day I attended Westbury and Jericho Monthly Meeting, which was small,
owing to dissension from our principles; yet their business was conducted in good order.

Fifth day, the 19th, I went, in company with John Titus, to Bethpage,
with the prospect of having a meeting with the people;
but we found that all who had been Friends, were now Hicksites.
We met with a cool reception,
and no way opened for a meeting until I was near giving out,
when calling at the house of one not of our Society, I informed him of our desire;
but he not readily giving an answer, I observed that I thought it best to be honest,
and let him know how I stood, desiring him to be free.
With a smile he said, "`I am willing to open my house for any good minister,
and a meeting may be held in it.`"
The day being considerably passed, we concluded to have it in the evening;
this man was ready and active in giving notice.
It was a favored opportunity, and larger than we expected.
On sixth day, we parted with the family, who appeared loving,
and the man expressed a desire, that if ever I came that way again, I should call on him,
adding that his house and heart were open for such Friends.

I then returned to Westbury, where Richard Mott had an appointed meeting,
in which he was favored; it was large for that place.
Seventh day, I returned to Flushing, and on first day, 22nd, returned to the city,
and attended their morning meeting, silent; In the afternoon,
way opened to clear my mind fully, and felt great peace.
On fifth day, I attended Shapaqua meeting, and after it drove to Salem,
and put up with M. Smith.
Seventh day, I went to New Milford, where I met with John and Elizabeth Meader,
(she is my youngest daughter but one;) they were on a religious visit.
We all attended that meeting on first day.
It was a large and good meeting.
We then went to the Branch, to an evening meeting appointed for them.
The members having nearly all left Friends, the meeting was small,
yet favored to feel the presence of Him who promised He would be in the midst,
when two or three are gathered in His name.
Second day evening, we had a meeting on the Hill, which was small from the same cause,
yet there were a few, who stood firm in the true faith.
With these we had a comfortable meeting, and went to Peter Dakin`'s together,
where we stayed until fourth day morning, when we parted, and I went to Beakman.
On fifth day, attended that meeting,
and at evening had a meeting at Isaac Flagler`'s. Sixth day evening,
had a meeting at Poughkeepsie, and seventh day evening I had one at Pleasant Valley.
In all these,
it pleased the great Head of the Church to give ability
to relieve my mind of all that He required,
so as to feel quiet and peaceful.

First day, I attended Oswego meeting.
It was small, owing to the great division that had taken place;
yet it was owned by the great Head of the Church, and we were comforted together.
From here I went into my old neighborhood,
and spent most of the week in social visits to my former neighbors and relatives.
Seventh day evening, I had a meeting east of Stanford,
at the house of a Friend by the name of Bartlett.
First day, attended Nine Partners meeting,
with the few Friends who had survived the rent in that place,
and had kept together in the truth.
Through the continuance of Divine favor, we had a comfortable and encouraging time.
Third day I went to Silas Downing`'s, in Pleasant Valley,
in order to attend Beakman Monthly Meeting, held at Poughkeepsie, the 16th of 12th month.
It was much larger than I expected--a solid, comfortable meeting.
The business was conducted with candor and harmony, and it was pleasant to be with them.
17th, I attended Nine Partners Monthly Meeting, which was small;
yet there were several valuable Friends belonging to that meeting.
I was entirely shut up as to any public labor, without material suffering,
further than to taste the low stripped feeling, the faithful had to bear up under.
Friends were favored at this time with the company of our aged Friend, Matthew Ferris,
from Oblong, who bore a short testimony that was comforting.

The eighteenth attended the Creek Monthly Meeting, and found it larger than I expected.
When I came to sit down with them, to my comfort,
I soon found my spirit with the spirits of a number who were travailing under exercise,
of a faithful concern for the cause of Truth and righteousness.
It was a good meeting; for where there is a faithful remnant,
the Lord will never allow his standard to fall to the ground.
Their business was conducted lively, and in good order.
Seventh day, I attended Stanford Monthly Meeting; it was favored;
they conducted their business pretty regularly, and in a good degree of harmony.
First day, the 20th, attended the little meeting at the Plains,
where my Master put on the whole armor, and Truth went forth victoriously.
May it prove a lasting blessing to the people, and honor to the Great Head of the Church,
for to Him it is due!
In the evening, I had a meeting, at the Plains Village,
which consisted of a mixed multitude, and was much unsettled in the forepart of it.
It was trying to my feelings to appoint that meeting,
and I sat feeling very poor in spirit, and much stripped for a length of time,
which tried my faith, and brought me into a close exercise,
fearing I had not done right in making that appointment.

After awhile, I was favored to get into a quiet, resigned state,
and soon felt a gentle motion to rise on my feet, accompanied with a clear opening.
I attended to it, but had to move slowly, and look well to my stepping stones,
and was favored to experience the little stream that only came about the ankles,
to become a stream to swim in.
The meeting became settled, and the people sat remarkably still,
for sometime before I took my seat, and continued quiet until the meeting closed,
and I felt a comfortable hope through the blessing of a kind Providence,
the meeting would be of use to them.
Second day, I went to Nathan Case`'s, my brother-in-law.
Third day, I desired to see another brother-in-law.
It came into my mind to take my own horse and carriage.
Nathan urged me to let my horse rest and he would take one of his that was gentle,
and go with me.
I gave up to him with reluctance.
We had rode but little over a mile, before his horse took fright going down a long hill,
and bounded at such a rate that our lives were in danger.
I endeavored to clear myself from the wagon as well as I could,
but fell on the frozen ground and cut one side of my face exceedingly,
and it bled freely, and I was otherways wounded.

When I came to my recollection, I remembered the first impression I felt,
to take my own horse, now I had to repent being persuaded from it,
as I have done in many other instances in my life, and left to suffer for it.
I was confined several days, and had to endure severe pain.
I so far recovered by first day, that I attended meeting with a very sore head;
yet in it had to bear a relieving testimony to my mind.
I put up with Nathaniel Mead.
On second day, I drove to Hudson, and lodged at Isaac Hall`'s,
son of John Hall of England--a valuable minister,
with whom I became acquainted when he was on a religious visit in America in 1801.
It was truly comforting to meet with his children,
finding them to be such Friends as I like to be in company with.
I stayed with them on third day, in order to attend an evening meeting in Hudson.
The meeting was larger than I expected, and proved a favored time,
though trying in the forepart; being much stripped in spirit,
and under great poverty for a length of time,
until there was an opening in the clear light, in the appearance of a bright star;
accompanied with a gentle motion to arise on my feet.
In attending to it, the Gospel spring arose to a forcible stream,
and through the tender mercy of the Lord to the people, it ran clear and free,
and settled on the people like the dew on the tender herbs.
May it rest long on them, and prove a blessing to them!

The day following,
I drove to Stanton Hill--fifteen miles.--I had to cross Coxsackie Flats,
a number of miles, where the mire was equal to anything I ever met with.
It took me nearly all day to get to Thomas Bedell`'s,
where I put up the last day of the year 1829.
The first day of the year 1830,
I had a large meeting at Coeyman`'s. The next day at New Baltimore,
and the day following, had a meeting at Isaac Babcock`'s, in Renselaer,
and another in the evening at Rensselarville; all of them large meetings,
and several of them were attended by a number of Hicksites.
In the last, I felt the life and power of the Gospel to rise higher,
and more powerful than I had in all this journey before.
Ability was given to open and hold forth the doctrines of the Gospel,
and contrast them with Infidelity, with such clearness, that I met with no opposition.
The power of the Lord so came over the people, that they were quiet in every meeting,
and closed under a sensible feeling of solemnity.
It was the Lord`'s doing.
Blessed, forever, be His Name, and greatly magnified be His glory!

After the last meeting, I went to Middlebury,
expecting that an appointment was given out at that place; but when we arrived,
Friends had heard nothing of it, and appointed one for the evening.
The time being short to give notice, and the weather unfavorable, the meeting was small,
yet favored and comfortable; but not seeing the people as I expected,
I thought best to make another appointment, and give time for notice.
The weather still being unfavorable, this meeting was not large,
but the presence of the holy Shepherd was felt among us.
Next I went to Oak Hill, and had a meeting in Friend`'s meetinghouse, on seventh day,
which was a considerable gathering, and Truth reigned over all.
On first day, I met with the few who remained with Friends, at Stephen Bull`'s;
Friends being deprived of the meetinghouse on the usual days and hours.
I had a third meeting at the fourth hour in the afternoon,
about three miles from the meetinghouse.
It was large, and through Divine mercy, a favored, tendering time.

Second day, we crossed the Highlands for Otsego; but the weather being very cold,
I suffered much, and put up several miles short of what I intended.
Third day, I got in among Friends, and on fourth day,
I attended their mid-week meeting in silence.
I also attended Joseph Bowne`'s meeting that evening in the village; it was large,
and Joseph was well harnessed for the occasion, with a lively, appropriate testimony.
Fifth day, the 14th of 1st month, I went to Oliver Gorton`'s, in Burlington,
and had a full, favored meeting there; then went to Butternuts,
and attended that meeting on first day.
Notice being given that I was to be there, it was large,
and the Gospel spring arose with strength and energy,
and flowed freely to a mixed multitude.
Through the tender mercy of the Lord it appeared to settle
on the people like the dew on the tender grass.
May it rest long on them!

I then went to Laurens, and had a meeting there on third day, which was a large,
mixed gathering, and an exercising time.
Holy help was granted;
strength and utterance were given to go through the labor of the day,
greatly to the relief of my mind, and to the satisfaction of my Friends.
I then went to Crumhorn, in company with Moses Hoag, where there was a small,
divided meeting--the few Friends were in low spirits;
to whom it was a cordial visit in a needful time,
which seemed to raise their drooping heads.
I was led to show to a number of Hicksites present,
the lack of foundation and proof to support the doctrine they held forth,
and the great cloud of witnesses,
there was in favor of the doctrines professed by George Fox and his contemporaries.
Truth evidently rose into dominion,
through the mighty power of the Lord to whom may all the praise be given, forevermore!

Next I was at +++_______+++ meeting, which was small and weak,
there being too much lukewarmness among them.
I had close, plain labor with them;
especially on account of their not taking their children to meeting when small,
yet large enough to behave well; also letting their children run about on first days.
I was led to show the responsibility that devolved on parents towards their children,
and the most certain effects that follow the neglect of those duties;
such as their leaving our Society and running into prodigality,
if not into all manner of evil; which some of them acknowledged was already the case.
O, may the Lord in mercy remember the poor, neglected children.

We returned to Laurens, and I went to James Brown`'s, on seventh day;
he and Andrew Hoag accompanied me to Bridgewater, and put up with Obadiah Williams,
who was very low in spirits,
on account of the sad division that had taken place in that meeting.
He was not willing that any notice should be given of our arrival,
as he thought it would do no good, and that Friends`' credit was so low,
that nobody would come to meeting.
However, notice was given, and there came a gathering of respectable looking people,
besides Friends, and we had a comfortable meeting together,
so that our disconsolate Friend seemed cheered up,
acknowledging the propriety of the movement.
Second day, we drove to Utica,
and put up at Zeno Carpenter`'s. He and his wife not being at home,
I was disappointed of their company, for I wished to see them.
I stayed one day, and had a meeting in the evening, which was pretty full,
and consisted of almost every description in that part of the land.
It was a deeply exercising meeting, yet through Divine mercy,
holy help was granted to clear my mind in a peaceful way.

After meeting, I had a visit from a Hicksite,
who reproves me for taking so much time in supporting that Jesus of Nazareth,
who was born of the Virgin Mary, and that He was the very Christ,
and not a divided Christ.
He asserted that the body of Christ did nothing for him, and that His blood,
shed so long ago,
he believed was of no more use than another man`'s.
I thought best to bring the subject to a point.
I replied, "`I perceive we do not both serve one Christ.`"
He said he believed in Christ within as much as I did; but Christ without,
he did not believe in.
I answered, "`I believe in that Jesus Christ who was born of the Virgin Mary,
and at whose birth the Angel of God announced, that in Judea, a child is born,
a Savior given, which is Christ, the Lord; and that it was known by many,
that His spirit was an all-powerful spirit, and very clearly bore witness to Him,
and to the Scriptures, that they were a true revelation of God.
I perceived that his Christ was never manifest in the flesh,
and therefore was antichrist;
and he always contradicted the revelation of the Christ of God;
he did it to our first parents, and told them they should not surely die,
and of course he made his followers, like himself,
contradictors of the followers of the Lamb of God, and accusers of the brethren;
while Christ taught His followers to be patient,
and endure all things for His and the Gospel`'s sake.`"
This stopped him for awhile, but he resumed the subject, saying,
"`I had not unity with the first part of your sermon--the last of it, I had unity with.`"
I pleasantly replied,
"`It is a fine thing that I am not accountable to such a man as you,
but to Him who overrules all.`"
He stopped, which gave me an opportunity to clear my mind faithfully, and we parted.

I then set forward for home, and went by the way of Greenfield,
attending their first day meeting, where it pleased the Master of Israel`'s assemblies,
to raise the standard of Truth over all opposition, and to silence the gainsaying tongue,
to the praise of His own name.
I passed on to Queensbury, and attended that Monthly Meeting,
and had a little acceptable service therein,
and had the satisfaction to see them conduct their business in much harmony.
I found them not so much reduced by the division as in some other places.
From there I went directly home, where I arrived the 7th of second month, 1830,
and found my own particular family well;
but my mother and my youngest brother had died in my absence; also, an aged woman,
out of my own house.
