== Chapter XII

About the middle of 5th month, 1831, having obtained the approbation of my Friends,
I set out for the Yearly Meeting to be held in Rhode Island.
Spring being unusually wet, the roads were so mirey,
it took me two days to accomplish one day`'s travel.
Having broken my wagon, I lay by on seventh day, in Montpelier, and repaired;
attended meeting there on first day,
where a disowned person had undertaken to keep possession of the Meetinghouse,
by taking the upper seat in the men`'s room.
I felt no freedom to give it up to him, having got there first, I took my usual seat;
several followed.
When he came, he walked to the upper seat,
and made several motions for me to give place to him,
but not noticing with that attention he desired, he stepped into the women`'s apartment,
and seated himself at the head of their part of the meeting,
which put the meeting into a jostle, which it did not get fully over,
though the latter part of it became measurably settled.
Second day, I moved on for Sandwich, in New Hampshire.

It still being rainy and the roads miry, it took me two days to cross the Mountains.
The fatigue was so great, I feared I should ruin my horse;
yet we were favored to get through one day before Monthly Meeting,
which gave an opportunity to rest.
I attended the Monthly Meeting.
There my Master set me to digging about some old fruitless fig trees,
which appeared when viewed at a distance, fair and flourishing,
but when thoroughly inspected, no appearance of fruit could be seen.
A laborious day to me.
The Good Master was pleased to grant Holy Help, so that I relieved my mind,
and gained my penny.
The next meeting I attended, was at Wolfsborough, on first day,
where I was set at pruning and digging about.
I found it required care and close application,
to do the work to my Master`'s acceptance and my comfort.
After the close of this meeting,
my Master gave me the garment of praise for the spirit of heaviness.
I then went and lodged with Jacob Bean,
and appointed a meeting among the Baptist inhabitants of that place,
where the Lord`'s favor was sensibly felt to solemnize the minds of the people.
Blessed be His holy name!

From there to David Dows, in Pittsfield, intending to attend Salem Quarterly Meeting;
but not being correctly informed, I fell behind the time of holding it,
which was no small disappointment to me; yet I was favored to be resigned to the event,
without repining or reflecting on my Friends;
desiring that their care in future may prevent the like taking place again.
I next went to Henniker, where I had a pretty full meeting,
which was painfully exercising, under a sense of a worldly spirit with parents,
that caused them to neglect their duty to their children,
in teaching them the principles of Truth and the fear of the Lord;
an evil much to be lamented in our Society, and hard to be removed by reason of unbelief.
This class settle down in the form of godliness,
and many of them are very zealous in the form, but having nothing of the power thereof,
are a grievous burden to Society;
for when parents feed their children with what they love,
and teach them what they admire,
thus the old Pharisee educated the young to follow his steps,
and these become a burden to the next generation.
The mourning women were called on, to teach their daughters wailing.

The following day, I attended Ware North meeting; it was large.
Here, infidelity, under the plain coat, stared me in the face,
with all its attendant evils; into which subject I was largely led;
the power of Truth came over this hard-faced giant, and cast him down;
the standard of Truth was raised above all opposition,
to the everlasting honor of the God of the just of all generations,
who gives strength to the weak, and turns the battle to the gate.
I next attended Ware South meeting, which was also large,
wherein it appeared that too many who had known better days,
were settled down at ease and the young people going into the air.
I had to sound the alarm among them, to the relief of my mind;
yet I could but look over to the young people with a heart impressed with sorrow,
to see how little help they had from those,
who ought to have been nursing fathers and mothers.
From there to Salem, where I arrived the 4th of 6th month, on seventh day,
and lodged with Enoch Page.
I attended that meeting on first day, the 5th, in the forenoon,
and Lynn in the afternoon; both were favored, satisfactory meetings.

I then went direct to Rhode Island, to attend the Yearly Meeting of New England,
which was large.
The business was conducted in harmony, and favored with the greatest degree of solemnity,
from beginning to the end, of any Yearly Meeting I ever attended,
and ended under a humbling, thankful sense of the unmerited favor of the Lord,
continued to His Church and people everywhere.
On first day, I attended a meeting on the Island, and at Tiverton, in the afternoon,
and went to Edward Wing`'s. My youngest son being on a religious visit in those parts,
without suitable company, I traveled with him a space of time.
We attended Westport, Dartmouth, Allen`'s Neck, and Smith`'s Neck meetings,
also New Bedford Monthly Meeting.
The latter was a laborious day to me; as the public service fell mostly on me.
After which, we visited New Town and Acushnet.
In these meetings my son had nearly all the public service, and was favored.

Seventh day, at night, we arrived at Obadiah Davis`', Long Plain,
and attended that meeting on first day, the 26th. Second day, we went to Rochester,
and had a meeting there; from there to Sandwich and Yarmouth.
Lindley was favored beyond my expectation, but my mind was shut up, as with a close seal;
with many painful exercises to wade through,
on account of an infidel spirit among Friends, secreted under a plain coat,
and smoothed over by an affected concern and zeal for the Truth.
From there to Nantucket Quarterly Meeting,
where there came in a number of Ministering Friends from different parts,
one of them from North Carolina.
They kept up such a stream of preaching, that I saw no way to relieve my mind,
and gave it up, concluding to stay after the Quarter, and try to get an opportunity.
As soon as that meeting closed, two Friends who had occupied much of the time,
went to appointing meetings in the town, so fast one after another,
that I found my way closed again, and I give all up,
except attending the two meetings on first day, in which I relieved my mind in a measure.
My son left on seventh day.
Second day, I was windbound, but intended to go on board the Packet;
the wind still standing ahead on third day,
I informed Friends it was on my mind to appoint a meeting
at the North meetinghouse at five in the afternoon.
It was readily agreed to.
The meeting was pretty full, and favored, to the relief of my own mind,
and the satisfaction of Friends.

There had been so much preaching, that many Friends had been burdened; so that,
although I had been silent through the Quarter,
I had concluded to go off and not burden them myself; but head wind had detained,
until I yielded to duty and accomplished it.
Then, on fourth day morning, I went on board the Packet, finding nothing in my way,
and had a pleasant passage to Yarmouth, with the enjoyment of a peaceful mind.
I got there in good season, and attended that little meeting on fifth day,
and appointed a meeting on sixth day afternoon, at the same house, which was well filled,
and it pleased the Great Head of the Church to favor with His solemnizing presence;
doctrine flowed freely, and Truth arose into dominion.
On seventh day, we went to Falmouth, and attended that meeting on first day,
where I was enabled to relieve my mind among a prudent
set of plain Friends--prudent for this world,
but too much lacking in religious weight and Gospel love.
Second day, I rode to New Bedford, and attended the Monthly Meeting,
where I had close searching service;
being dipped into a sense of a rending spirit among them.
I was enabled through Divine mercy to clear my mind,
so as to enjoy a full reward of peace,
I also attended the Preparative Meeting of Long Plain,
where Friends were in a languid state.
My mind was dipped into a feeling sense and near sympathy with them,
and I felt strengthened to minister that to them, which my Master gave me,
and found relief.

After meeting I returned to New Bedford, and attended their Preparative Meeting,
where my mind was dipped into a feeling sympathy with the suffering seed of Life,
and those who suffered patiently with it.
A little portion was given me from my Master for them, which I cheerfully handed to them;
but not feeling clear, I had to labor plainly with those,
who in a fiery zeal wanted to drive furiously.
It was painful labor, but I obtained a rich reward.
After meeting, I returned to my friend, Francis Taber`'s, where I made my home,
and after dining with his brother, I journeyed to Fall River,
and put up with S+++_______+++ Chase, the 22nd of 7th month.
The day following, I had a meeting there,
which was more comfortable than in some other places;
as Friends appeared to live peaceably with themselves and their neighbors.
Then I went to Providence on seventh day, and on first day,
attended their morning and afternoon meetings;
where there was much more correct outward acquired knowledge,
than inward vital experience of true religion.
To me it was an exercising time, but I was enabled to relieve my mind, and felt quiet.
The night following, I lodged in Friend`'s Seminary in Providence; where,
if it was not for the high exalted feeling and aim of the planters of that institution,
and something of the same disposition in the managers,
it might be a blessing to our Society.

From there I went to Lynn, and I attended their meeting on fourth day,
and fifth day at Salem.
In both I was comforted in being made sensible that there was a goodly remnant,
who were honestly laboring to be what they ought;
yet they were not all Israel who were of Israel in them.
After meeting at Salem, I attended a funeral near Marblehead,
of a young man whose mother was a Friend, but his father was not.
The young man went out of the world in great distress, both of body and mind.
It was a solemn time.
On sixth day, I went to Seabrook, and put up with my cousin Benjamin Dow,
where I was received with great kindness and affection.
I lay by on seventh day,
and had notice given of my intending to be at meeting on first day.
The meeting was a full one--a mixed people;
the doctrines of Truth went forth in its own authority,
and prevailed over all opposition; I hope to the honor of the Great Head of the Church,
who is worthy of the praise of all His works.
At five in the afternoon, I had a meeting at Amsbury,
where were a large number not of our Society--a goodly looking people.
The doctrine of the Gospel dropped as the dew, and distilled as the rain,
and appeared to settle on the people.
Blessed be the God of all grace, for the continuation of His mercy in visiting the people.
May the favor rest long upon them, as the dew upon the tender grass!

Fifth day following, I attended the Monthly Meeting at Seabrook,
and found it in a low state,
as to the pure life of the Gospel--but little more than the form--the
well concerned among them were almost ready to give up.
I labored among them, in that strength my Master furnished with,
but it seemed almost like beating the wind.
The next meeting I attended, was appointed by my son Lindley, among the Baptists;
he was much favored.
I passed the meeting in peaceful poverty.
I then went to Epping, and attended their morning and afternoon meetings.
In both of them I was enabled to clear my mind fully, to the relief of it.
Second day, I had a meeting at Lee, at five o`'clock in the afternoon, where,
after a time of deep poverty and strippedness,
the Gospel spring opened and arose in the clearness, and its doctrines flowed freely;
Truth had the victory.
Blessed be the God of Truth!

After meeting, with a pilot I drove to Dover, and third day morning,
went to Meaderborough. From there, with Ezekiel Jones for company, I went to New Durham,
where I had a meeting, and returned to Meaderboro`',
and attended their Preparative Meeting.
The day following, we had a meeting at Chestnut Hill, and drove to South Durham,
where we had a meeting on seventh day.
Most of these meetings were very small,
owing to the younger class going to other parts of the country to live;
the aged ones died off; some leaving Friends, and a lack of zeal in most of them;
so that it leaves a gloomy prospect.
Yet through the goodness of kind Providence,
I was enabled so to clear my mind in the ability given, in this part of the country,
as to enjoy a peaceful mind.
Blessed be His name forever!

We then went to Dover, and attended that meeting on first day.
It was large, and laborious for me.
In the afternoon we attended a funeral, held at Friends`' meetinghouse,
which was also large--a mixed multitude in both meetings;
so that the labor of the day was deeply exercising, and truly humbling,
as the Lord does not require any service of His servants,
until He gives them to understand what the service is;
and when obedience of faith is kept to, He richly rewards them with heavenly peace.
Thanks, honor, and praise be ascribed unto Him, and the Lamb, forevermore, says my soul!
Second day, the 15th of 8th month, I returned with Ezekiel Jones to Amsbury.
He had been with me the week past, and was pleasant company.
I next attended Salem Quarterly Meeting, held at Lynn; to me a painful,
exercising meeting; yet the Lord`'s Divine mercy was good,
as he gave ability and utterance to discharge the duty He required of me,
and richly rewarded with heavenly peace.
Then returned to New Durham, and attended that and Chestnut Hill,
Meaderborough and Lower Rochester meetings,
and returned to Dover and attended their meeting on first day,
and a funeral in the afternoon.
In both I had laborious testimonies to bear,
was favored to feel greatly relieved and comforted,
and proceeded to Berwick to attend Dover Quarterly Meeting held there.

The public service mostly fell on me, in a close plain way, which gave relief.
I then went to Kittery, where there had once been a considerable meeting of Friends,
now nearly run out.
We had a pretty full meeting; and ended much to my satisfaction.
First day, attended meeting at Berwick, where I had close searching service,
but through Divine favor was enabled to clear my mind, and felt relieved.
In the afternoon I attended an appointed meeting at the Great Falls which was large.
The service was principally allotted to my son, Lindley.
He being young it tried his feelings pretty closely, yet I believe all was right;
preachers have need to learn as well as teach.
From this I proceeded to Falmouth Quarterly Meeting.
In the meeting of Ministers and Elders, I felt a necessity to deal plainly and honestly.
I hope it will do good.
The following meeting, the service fell almost entirely on Lindley; he was much favored;
Truth reigned to the honor of the head of the Church.
Sixth day, I had a meeting at Pownell; which though not large,
was favored--the minds of some were comforted.
On first day, I attended a large meeting at Durham,
where I was not altogether satisfied with myself,
not keeping enough in the patience and simplicity.

Second day, I went twenty miles to Gardner, and put up with Noah Ferris,
and had a small meeting in the town, at five in the afternoon, to good satisfaction.
The day following, I attended the Monthly Meeting, at East Pond, where I had close,
searching service, which made some stir among Friends; yet I felt great peace.
I next attended Fairfield Monthly Meeting, where I was silent.
Three or four of the leaders from the other Monthly Meeting came, I thought, as spies.
I had nothing for them.
Then we went to Cornville, and had a meeting on the East Ridge,
having Israel Goddard and Phebe Cobb, for company.
The day following, we had a meeting at Athens Village.
On first day, at Robert Wentworth`'s. Also, one at five o`'clock at Braton Village,
both of them to good satisfaction.
From there went to Sandersfield, and had a meeting.
Then went to Sebec, and had a meeting.
From there to Sirens, and lodged at John Burton`'s, a Friend,
and had a good satisfactory meeting in the neighborhood,
which was the case in several of the last mentioned meetings,
there being great openness in the minds of the people, to hear.
The Lord favored with suitable matter and free utterance, and richly rewarded with peace.
Blessed be His high and holy name!

We then rode to St. Albans, and put up with Samuel Beals, seventh day, 24th of 9th month.
On first day we attended their meeting, which was large and much favored.
At evening, we had a large meeting at Newport, which was laborious, but well.
Second day, we rode twenty miles,
and had a meeting at evening in Friends`' meetinghouse at Brooks.
It was not large, but a favored time.
We lodged at Doctor Roberts`'. Third day, we rode to Unity.
Fourth day, attended their meeting in course.
From there to Albion, Hope and Bremans, and had a meeting in each place,
and were favored to the enjoyment of peaceful minds.
Second day, we rode to Winsof, where we stopped and had a meeting among the Methodists,
to the satisfaction of the people.
Fourth day, we attended the River meeting.
Fifth day, we attended meeting at Vassalborough, where I had close,
plain service in good authority, which made its way through all opposition.
Sixth day, we were at Sidney Meeting,
where my sufferings were unusually painful a length of time,
when way opened to clear my mind, in a plain way to its relief.
Seventh day, we had a meeting at Belgrade; Gospel life rose into dominion,
and its doctrines flowed freely.
On first day, the 9th of 10th month, we attended Winthrop meeting.
It being a very rainy day, the meeting was small;
a comely number of young people attended, to whom tender counsel flowed freely.
After meeting we went to Elijah Pope`'s; were there detained by a great fall of rain.
On fourth day, we attended Litchfield meeting.
Truth opened the way, and gave ability to clear my mind, in a close, searching testimony,
which gave relief.
Fifth day, we journeyed to New Sharon, over a very hilly country, and lodged.

Sixth day we had a trying meeting there, in the exercise of close, plain testimony.
After meeting, we drove to Wilton, and had a meeting there on seventh day,
which was troubled with an impostor who took up considerable time in preaching,
tending to the unsettlement of the meeting, so that I was fearful it would be spoiled;
yet, through Divine mercy, Truth rose in a powerful manner over all opposition.
The meeting ended under a quiet solemnity, to the satisfaction of the people.
We returned the same day to New Sharon; had a meeting there.
Passed on to Fairfield, and attended a large favored meeting on first day.
After it, we drove to John Cock`'s, about twenty miles.
Second day, we attended the Preparative Meeting of Ministers and Elders, at Unity,
where it fell to my lot, to communicate some plain truths.
The day following, attended their Monthly Meeting, which was the most solemn,
favored meeting that I have attended in this part of the land.

The next day, I attended the Monthly Meeting at Vassalborough.
It was large and favored.
In the evening attended a meeting appointed by J. J. W., at Hallowel Forks,
in a school house; a full meeting,
wherein the doctrines of truth flowed freely and
appeared to settle on the minds of the people,
as dew on the tender grass.
On 5th day, I attended Sidney Monthly Meeting.
It appeared to be a low time with Friends, owing much to the lack of true Gospel love,
and a right zeal.
Their business was managed dull; yet the Gospel spring flowed in strength,
and arose in dominion.
Sixth day, I attended Leeds Monthly Meeting held at Winthrop,
where the business was also conducted without much energy.
In both the last meetings, I enjoyed myself in peaceful silence,
and was comforted in partaking of a share of the reward of those who labored.
On seventh day, I had a meeting in the town of Hallowell, among a high feeling people,
where through unmerited mercy, strength was given to deliver the truth,
in such Gospel authority the people became settled; the meeting ended quietly.
We next went to Leeds, and attended that meeting on first day.
I was silent, and well satisfied with it.

Second day, I attended the Preparative Meeting of Ministers and Elders, at Durham.
Third day, the Monthly Meeting, a laborious time with me,
in clearing my mind to the relief of it.
Fourth day, I attended Falmouth Preparative Meeting of Ministers and Elders,
where I had to communicate some plain remarks.
Fifth day, I attended the Monthly Meeting, where I was greatly enlarged,
to the relief of my own mind, and it appeared to the satisfaction of my Friends.
Sixth day, I had a meeting on Cape Elizabeth,
where an approved minister among Friends had turned Hicksite, in consequence of which,
several were jostled in mind, and some became more slack in attending meetings,
so that the meeting, which was not large before, became very small and somewhat languid,
but through unmerited mercy, it pleased the Head of the Church to speak comfortably,
to those who remained alive among them, to hold fast that which they already had,
and let no one draw them off from the Truth.
Seventh day, in company with Samuel Hussey and wife,
I made a social visit to all the families of Friends,
and returned to Portland that night.
On first day, I attended their fore and afternoon meetings,
where the Gospel spring arose in strength, flowed freely,
and went forth in its own authority over all opposing spirits,
I hope to the glory of God.
Strength and utterance were given to hold up the standard of Truth,
and the ensign of righteousness, to the people.
Second day, I lay by in Portland, the Quarterly Meeting being near at hand.

Third day, I went to Durham,
and on fourth day attended the meeting of Ministers and Elders,
and on fifth day the Quarterly Meeting at large.
Both were favored meetings.
Under a sense thereof, many minds were humbled and contrited,
in consideration of the tender mercy of the Lord,
who does not limit His mercies to our worthiness.
Seventh day, I had a meeting at Humphrey Purinton`'s, in Bath, the forepart of the day;
in the afternoon I had another in the Village of Bath.
First day, I had a meeting at Brunswick.
Second day, I had one in Bowdoinham, and then went to John Perry`'s, at B+++_______+++,
and had a favored meeting in that neighborhood.
The next day I had a meeting in Lisbon Village, where my labors were deeply exercising,
on account of the careless, unconcerned state the minds of the people were in;
which appeared to be the general state in most of the meetings in this town.
Though my mind has been depressed for several days past,
under a sense of my own weakness, and the painful labor I had to pass through,
from day to day, yet through all, my good and heavenly Master, has been my only helper,
furnishing with matter, strength, and utterance,
which enabled me to clear my mind from day to day, and obtain comforting peace.
Blessed be His ever adorable name!

On fifth day, I rode to Lewistown, and put up with Amos Davis.
Israel Jones accompanied me, who, with his brother, Thomas,
had been agreeably with me for several days; the latter having returned home.
Seventh day, I went to Windham, I and attended that meeting on first day,
which was very large and solemn.
Through Divine help, the testimony of Truth was set forth in Gospel authority.
Second day, I rode to Poland, and had a comfortable meeting there in the afternoon.
Fourth day, I went to Norway, and had a small meeting.
A company of rude young people came to it, and kept it unsettled.
Near the close, I believed it right to address them,
and let them know my thoughts of their conduct, in relation to their own credit,
and the reproach it cast on their parents who brought them up;
as also their irreverence to their Creator.
This stilled them, and some of them looked ashamed.

On fifth day, the 6th of the month, I went to Raymond, and had a meeting there next day,
in which I was enabled to clear my mind to good satisfaction.
From there, I returned to Portland,
and attended their fore and afternoon meetings on First day,
which were painfully exercising, and I had to deal plainly,
which gave a comfortable enjoyment of sweet peace.
Second day, I returned to Raymond, and had another meeting there on third day.
I had to sound the alarm, and show the danger of being deceived by the subtle serpent,
and his transformings in the appearance of an angel of light;
and was led to set forth how he might be known and detected,
greatly to the relief and refreshment of my mind.

I returned to Windham on fourth day, and had a meeting at Gorham, which was not large,
but a suffering time.
It appeared that heartfelt sickness was among them; I cleared my mind,
and felt a peaceful quiet.
Sixth day, I attended Windham Monthly Meeting, held at Limington.
After suffering in deep poverty and strippedness of spirit,
the Gospel spring rose high and flowed freely; though much weakness was felt,
the Lord favored with a renewed visitation to the comforting of the honest-hearted,
and a solemn warning to those at ease, who choose their own ways,
and despise the cross of Christ.
Seventh day, the 26th of 11th month, I went to Parsonsfield,
and lodged with Charles Cartland, when feeling my mind clear of that part of the country,
I went to Winter Harbor, and had a small meeting there.
The snow coming on, made it difficult traveling on wheels, so I went direct to Berwick,
and put up with my children, John and Elizabeth Meader, for several weeks.
While there, I attended that meeting several times, and Dover twice,
and had a meeting on Dover Neck.
In all these meetings, my good Master was pleased to furnish with appropriate matter,
ability and utterance to relieve my mind, and obtain the reward of peace;
being mercifully supported in all the exercises, though they were painful and laborious.
A fig-leaf covering was too much resorted to by many,
which often caused mourning with the few upright-hearted among them.
May the Lord sustain these, that the ensign of righteousness may not fall in the streets!

After making these visits, feeling my mind drawn to visit Pittsfield, Weare,
and Henniker, a kind Friend, Joseph Bracket, took his sleigh,
and carried me this short tour.
We attended Pittsfield meeting on first day, but the weather being stormy,
the meeting was very small.
Not feeling clear, I proposed meeting with Friends again on second day,
which was agreed to, and notice given,
but the second meeting was very little larger than the first;
some whole families not attending.
Having done all I could, I felt clear, and had two meetings in that part of the country,
out from the settlement of Friends, much to my satisfaction.
There was more openness among them, than with nominal professors of my own Society.
We then went to Weare North Meeting on first day, at the usual time,
and at the South Meeting at three o`'clock; both were well attended.
The word of Truth went forth in its own authority
and its standard was over the heads of transgressors,
by and through the power of the mighty God of Jacob.
Blessed be His ever adorable name!

On second day, I had a meeting at Henniker,
where I passed through great depression of spirit,
under a sense of the lack of faithfulness in many professing with us, who,
instead of being lights and encouragers of others, were stumbling blocks in their way.
I was enabled faithfully to bear the testimony my good Master gave me,
to my relief and peace.
After meeting, I went to my cousin, Winthrop Dow`'s where I was on the 10th of 1st month,
1832.
I next attended Weare Monthly Meeting, wherein I had close, painful,
and exercising labor; and the day following, I went to Concord,
and had a meeting in Friends`' meetinghouse, which was large,
and favored with a renewed visitation from on high.
May the people gratefully prize the favor!

I then returned to Berwick.
Next I went to Seabrook, and attended Salem Quarterly Meeting,
where I had to preach plain, solemn truths; then returned to Berwick,
and attended that meeting on first day, and a meeting in the evening at the Great Falls,
which was well attended, and a favored time.
From there I went to Sandwich, N. H., and attended that Quarterly Meeting.
That for worship was a renewed visitation to the inhabitants thereaway.
Oh, that it may be wisely improved!
The meeting for business was very dull, taking a long time to transact a little business.
I then went again to Pittsfield, and attended their Monthly Meeting,
and was enabled to clear my mind so fully,
that I hope my Master will not send me there again,
but bless the labors already bestowed.
I then set out in a sleigh for Smithfield, but the snow going off,
I was stopped at Edward Goves`', in Seabrook.
The 4th of 2nd month, in the evening, I had a meeting with those not of our Society;
the doctrines of Truth were well received and acknowledged.
On first day, I attended Seabrook meeting, which was very small.
The life of pure religion was very low,
and were it not for a few honest-hearted ones I think that meeting would cease to be.
May the Lord strengthen the hands of the few,
to hold up the standard of righteousness to beholding enquirers,
to the honor of His own Name!

I next went to Lynn, and attended that Monthly Meeting--a suffering time to me.
I next journeyed to Providence, and attended the morning meeting in the town--a dry,
suffering time to me.
In the afternoon I attended meeting at the School, which was a favored time,
wherein I felt my mind above the depression of spirit I had waded under for days,
and was marvelously enabled, both in public and private,
to clear my mind of a concern that had arrested it, until it became a heavy burden.
He who promised to go before His sheep that He put forth, made a way for me,
beyond my expectation, and my labors were received without any apparent offense,
though they were plain and close.
I felt fully relieved, and made to rejoice with thankfulness to my Lord and Master,
for His direction and holy help, through this portion of exercising service.

I then went to South Smithfield, and attended a meeting there, which was not large,
but favored, and the minds of the people appeared open to hear the Truth.
The day following, I was at a meeting at Cumberland,
where there was not such openness as at the former, which made the labor more painful,
but my mind was strengthened to discharge my duty.
I then rode to Mendon, and attended their Preparative Meeting; it was small,
and I had good service; yet, not feeling clear,
I had a meeting appointed at three in the afternoon, which was pretty full and favored,
and the testimony of Truth rose into dominion.
The day following, I attended Smithfield North Meeting,
a large and deeply exercising one,
there being great lack of a true religious concern among the people;
although it was a laborious day, I was favored to feel a peaceful mind.
The next meeting was at Uxbridge, where we had a searching time,
and the testimony of Truth went forth in its own authority,
and reigned over all for that time.
In the evening I had a meeting in a school house near Jacob Aldrich`'s,
to my satisfaction; the testimony of Truth went forth in clearness,
accompanied with tendering Gospel authority, and closed solemnly.

On the 11th, I was at Douglas--a meeting much run down.
The 12th, I was at North Bridge, a pretty full, favored meeting.
From there to North Mendon; the meeting was considerably full.
The testimony of Truth went forth in clearness, and good authority,
to full satisfaction to my own mind.
The next was Bolton Monthly Meeting, attended by many not of our Society.
The truths of the Gospel were largely opened,
and appeared to settle with weight on the minds of the people.
I next attended Richmond, where there were more in number, than there were Friends.
I was led to show the difference between the Gospel and its effects,
and the inventions and wisdom of men, in the great cause of religion;
and to contrast them in a clear point of view.
The testimony of Truth was in dominion, and the spirit of oppression gave way.
I proceeded to Unity, where there was a pretty full gathering of Friends and others,
and much openness in the minds of the people.
Truth flowed freely, to the comfort of the honest-hearted.
I then passed on to Pittsfield again, and attended that meeting once more,
and was mercifully enabled to bear a close, searching testimony,
greatly to the relief of my troubled mind.

Having discharged my duty to some individuals, I felt clear to take my departure,
and journeyed to Gilmantown, where I had a pretty full, favored meeting,
which ended to good satisfaction.
At evening I attended a meeting appointed by Abigal Miller;
the first time that I had an opportunity to hear her, except a few words,
and to my satisfaction, found she was an able Gospel minister.
The day following, sixth day, the 10th of 3rd month, I went to Wolfsborough.

[.small-break]
'''

+++[+++No further narrative of this journey is given,
and at what time he arrived at his own home, is not certainly ascertained; yet,
it is believed not to be long after the close of his narrative at Wolfsborough,
than one hundred and fifty miles from home.
The following extracts from a letter written to his wife
and children about the middle of his last visit to New England,
will be familiar to those who have been acquainted with him in conversation;
from the manner of style and expression.]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Portland, 24th of 10th month, 1831.

[.salutation]
Beloved Wife and Children:

I take my pen once more to address you, with making this apology,
that I have put off writing in hopes I should find myself at liberty to come home.
But seeing no time for my release, I feel best, to inform that I am in good health,
and have been, by far the most of the time,
since I left home--a favor that calls for humble gratitude,
and a thankful heart to the Giver of the blessing; not only for this,
but in that He has enabled me in a marvelous manner,
to perform all that He has required of me, since I left Rhode Island.
From there I passed on, taking meetings in course, until I got to New Bedford,
where I found Satan had got into the high bench, where he sat himself as God,
and had made such a rent, as almost to destroy harmony and unity,
through one Quarterly Meeting, and to draw down several stars of magnitude,
that once shone brilliantly.

The escaped remnant lay low, almost buried under discouragement;
that this part of my travel was in a land of sorrow to me,
in beholding the breaches in the wall, and the desolation in the city.
My inner garment was that of mourning, from day to day.
From there I put on for Lynn, where I met a troop of archers,
with their bows all bent--the horse and his rider, all in battle array.
But my Master made my arm strong to handle the bow, and He directing the arrow,
it never missed so that the battle was turned to the gate,
and the prison doors were ordered open by the King,
and the captive daughter was set free, to the honor of the King`'s name, I hope.
From here I passed on, until I got to Berwick,
where I found old Satan working like fire in the roots of the trees, underground,
so as to be sure to kill all the green timber, and not be seen to blaze,
lest it should be put out.
His fire-bed got exposed and his head bruised; the people were warned to watch his moves.

From there I passed pretty smooth, until I came to Vasselborough,
where I attended their Quarterly Meeting of Ministers and Elders,
a goodly appearing band, I was pleased with the sight.
But my Master came and anointed my eyes, and bade me look with a single eye.
When I fixed my eye intent, and the light shown clear, behold I saw Satan in the midst,
dressed up in an Elder`'s suit, from head to foot.
My Master caused me to see that Satan was very busy in raising
a zeal that would tread to death every seed that He,
the Lord, had planted, if not checked, and bid me pitch battle with him,
and put a sword into my hand for that purpose.
And when I came to try it I found it was a wieldy sword, that had a sharp edge;
and every blow cut so that the enemy squirmed every way he could,
so that he exposed himself and got detected, and a mess of bars and bolts taken from him.
And it was found that he had one of my Master`'s children, summoned,
and was endeavoring to handcuff, and fetter him, and cast him into prison for life.
But the poor child was rescued, taken from him,
and it is the King`'s mind that he should be set at liberty.
I have since visited all the meetings in that Quarter.
In many of them my Master tuned my ram`'s horn,
so that many of their walls gave way before it.
In other places He gave me the pipe and harp, to cheer the heavy-hearted.
I have got through this tour, and well entered into Falmouth Quarter.
I have visited Weare and all those parts, and found our Society in a pitiful state;
of course my labors were heart-aching, and wearing every way.

My Friends take good care of me, as to all I need to keep me comfortable.
I can give no opinion about coming home, having already been disappointed,
in having double the ground to travel over, that I expected to, when I left home,
and am not yet favored to see when I may return;
though I think my stay here will be longer on Lindley`'s account.
There is as much need of my being in this part of the country on his account,
as there was at Rhode Island;
and whether I shall not have to stay until he is ready to return, is unknown to me.

I now take my pen, the 25th, to close this detail,
with giving a general view of the state of our Society, as it appears to me,
in this part of the land.
The first disorder appears to be spiritual pride, out of which grows jealousy,
and a tormenting fear that anything should rise as high as Master Pride`'s shoulders.
In order to prevent the rise,
let the seed be ever so good in its kind and the
plant grow in ever so good and beautiful order,
Master Pride fixes the more an eagle eye upon it, and in the appearance of a dove,
will coo about it, in order to set its talons under its roots and destroy them,
so that the plant must die.
If it cannot prevail this way, it will turn into a serpent,
and creep under the grass and weeds--buzzes in the ears of its own kind,
and starts their fears.
Then it is to draw in the better hearted, and raise a strong zeal.
When this is fixed, the tongue of slander blows it into a flame.

In this kind of toss and fuss, ups and downs, Satan has walked in this land,
until he has abundantly marred the beauty of our Society,
and deeply wounded the pure in heart.
I now take my pen to close this, the 4th of 11th month, at the house of Thomas Jones,
a ministering Friend, who has been at our house.
Yesterday I attended the Quarterly Meeting, which was large, and much favored;
and though much weakness appeared in their accounts,
their business was conducted in harmony.
I may now inform you, that in my hours of intermission,
I often find myself at home looking round among you, feeling anxious for you.
The language runs through my mind, '`Here I am in a strange land,
wearing out the last of my strength, often in heart aching labor;
and how is it with my Friends at home?`' A heavy-hearted feeling returns upon my spirit.
I do not write this, as having any doubt of being in my right place,
for I am abundantly confirmed that I am.
I have often thought of you, my son Nathan, when in different parts of this land.
I now draw to a close, desiring, fervently desiring your faithful standing in the Truth,
and prosperity therein.
Give my love to all my children, relatives, and enquiring Friends.
You may rest assured that I never felt greater desires
for the peaceful welfare of my own country,
than at this time.
Farewell.

[.signed-section-signature]
Joseph Hoag.

--
