== Chapter XIII

On the 21st of 11th month, 1832, having obtained the unity of my Friends,
I set out to perform a religious visit to Friends in Upper
Canada and some parts of Farmington Quarterly Meeting,
and to attend the approaching Yearly Meeting, of Philadelphia,
and visit some meetings in its vicinity.
We traveled several days before we stopped to have a meeting;
the first being at the town of Chateauguay, an assembly of bright countenanced people,
who appeared fixed in a choice of a popular religion,
so that though the doctrines of the Gospel flowed freely and lively,
it appeared to make but little entrance.
I parted, feeling much good will for them, with a relieved, peaceful mind.
We traveled two days more before getting to Friends`' settlement at Indian River,
now called New Philadelphia, where I was delayed a day,
on account of the Hicksites having possession of the house.
The meeting was held on sixth day, when Friends generally attended,
and a few of the neighbors.
I was in hopes, as there had been a heavy shaking, and a number had gone off,
to have found them in a humble quiet, encircled with Gospel love,
and bound together in the unity of the Spirit, but it was sorrowfully otherwise.
The old serpent had got among them, and sowed the seeds of jealousy,
which had taken deep root, and the fire had broken out,
to the great grief of the upright among them.

Being constrained in Gospel love to be faithful to my Lord`'s command,
though with an aching heart for the people, my labors were painful, pointed, and close;
and I was favored with the reward of sweet peace for obedience.
I have always found my good Master a rich rewarder for faithfulness,
and a sure supporter in every trial, if fully confided in.
Blessed, and forever adored be His holy name!
From this place we went to Le Ray, and broke down our carriage on the way,
which detained us on our journey to get it repaired;
but a Friend took us through in a sleigh, in time to have notice given.
The meeting was large, including a small band of lively spirited Friends,
who were helpers in the field of labor, being disposed to stay the hands from dropping,
while the rod of God was lifted up.
The battle was turned to the gate and the Truth reigned.
May the Lord bless that day of favor to the people!
After our repairs were finished, we proceeded to Oak Point, on the River St. Lawrence,
where an aged Friend and his wife lived, remote from any meeting of Friends.
We stopped and appointed a meeting the next day.
Many came in, all anxious to hear,
which caused the meeting for sometime to remain unsettled,
but sitting in solemn travail of spirit,
I felt the word of Truth to arise in Gospel authority.
In attending thereto I felt strength to increase,
and ability given to hold forth the truths of the Gospel, in a clear, plain manner,
easy to be understood, which appeared to settle upon them as the dew.
Their countenances became grave, and some of them tendered.
In this state, the meeting closed, much to my satisfaction.
I felt great tenderness for them,
remembering that though Paul might plant and Apollos water,
yet it was God only who could give the increase; here I felt easy to leave them.

The day following, we crossed the river to the British side,
and went to a small settlement of Friends in the county of Leeds,
where we arrived the 6th of 12th month.
On sixth day, 7th of 12th month we had a meeting with Friends and others;
found the state of society low; too many at ease;
were it not for a few faithful ones among them, who labor under much discouragement,
the testimony of Truth must fall.
I was enabled to relieve my mind.
Not being able to get a pilot to go forward, we lay by, seventh day, and had notice given.
The meeting on first day was large; the doctrines of the Gospel flowed freely,
and went forth in good authority.
Truth rose into dominion.
Blessed be the name of the Lord.
Second day, we started for Kingston,
and on third day we got to the widow Ferris`'. Fourth day, at evening,
we had a meeting in Kingston.
Next day, at Waterloo.
Sixth day, we passed on for Adolphus town, and were with Friends on first day,
the 16th. All three of those meetings were small;
two of them reduced by the disorganizing spirit that has prevailed.
Yet, amid all this stripping there was comfort felt in finding at every place,
there were those who stood faithfully concerned to maintain the testimonies of Truth;
and the Lord was not only pleased to sustain,
but often times to meet with them in their assemblies;
to strengthen and sweetly comfort them.
From Adolphus we went to West Lake,
and had an appointed meeting there before the Monthly Meeting came on; it was a large,
solid, favored meeting.
The day following, we had a meeting at Hilyard, where, after,
sitting in much poverty of spirit, a living spring in Gospel love was felt to arise,
and in carefully attending to it, it increased to a lively stream,
and plentifully watered the garden.

We returned and attended the Monthly Meeting at West Lake,
where it was my lot to feel my mind depressed,
and stripped of all lively feelings for awhile; but sitting in resignation to my lot,
and gathering into stillness, I was favored to feel, though very small,
the gentle arising of Gospel life, and attending thereto in deep humility and simplicity,
it became a river, not only to the ankles, but to the waist, and a river to swim in.
The service of the day appeared to settle on the assembly as the dew on the tender grass,
and distil as the rain, to the tendering of many minds.
The business was conducted pretty regularly.
From there we went to Cold Creek,
and put up at the widow Terrill`'s. The next day attended meeting in that place;
it was a suffering time until Truth arose,
and gathered the minds of the people into a solemn quiet.
The next place we stopped at was Haldimand,
where we had a meeting with the few Friends and their neighbors,
where the Gospel spring flowed lively, to the tendering of many minds.
May it rest long on them.
The meeting closed greatly to my satisfaction.
The 25th of 12th month, we went forward to Pickering,
where the meeting had been greatly shattered;
some of the few Friends who kept to our ancient principles
felt as though they had done so nicely,
that they appeared in imminent danger of settling down at ease, to their own hurt,
while others appeared pretty well concerned to keep their ranks in the Truth.
My labors in this meeting were arduous and searching.
The following day, we had a meeting at Uxbridge, where,
for lack of a true watchful concern, the life of religion was very low.
We proceeded to Whitchurch,
where there appeared to be a little band of well concerned Friends,
who were kept out of their meetinghouse by the Hicksites,
and had to meet in an old school-house;
but the Great Head of the Church was pleased to meet with us, to our comfort.

We next went to Yonge street, where we fell in company with Jacob Green,
from Ireland--a goodly Friend, and edifying Minister.
On sixth day, the 4th of 1st month, 1833, we went to Tecumseh,
a small meeting and settlement of mostly younger Friends,
with whom we had a meeting on seventh day.
It was a comforting time;
the Holy presence of the Great Head of the Church being sensibly felt among us.
Blessed be His name!
After meeting we returned to Yonge street, and attended their meeting on first day;
it was large and the forepart was dull, and a deeply suffering time;
but as resignation was kept to,
the Master of Israel`'s assemblies anointed with the influence of holy strength,
the word of Truth went forth in Gospel authority, and reigned over all,
to the tendering of many minds.
May the Lord bless the favor of the day, to the everlasting good of the people!

On second day, being fatigued, I lay by to rest.
Third day, we had a meeting at a small village called Beverly,
a larger collection than I expected.
The word of Truth flowed freely, attended with that solemn weight,
that it appeared to rest on the minds of the people, like the dew on the tender grass.
May the Lord render the favor of His visitation, a blessing to that people,
for many days yet to come!
Fourth day, we were at Asa Rogers`'. Fifth day, I attended their Preparative Meeting,
in which I was enabled to relieve my mind, and felt clear.
Sixth day, we took our departure for the Half Year`'s Meeting, near West Lake.
We stopped at Whitby,
and had a meeting with the people of that place--a suffering and laborious season,
owing to the state of ease the people were in.
I had to speak to them in a plain, close way, and though painful to me, so to do,
I felt the reward of sweet peace for being faithful.
After this, we made no other stop, except for our accommodation,
until we got to West Lake, and put up with Jonathan Clark, on sixth day,
the 18th. First day, the 20th, we attended that meeting, where Truth,
in its own authority rose into dominion, to the comfort of the upright,
and the encouragement of the sincere in heart.
From there to Thurlow, and had a meeting with the few Friends and others there.
Also two meetings in Sidney.
In all these,
the Master of Israel`'s assemblies was pleased to favor with his owning presence,
and richly favored, with suitable matter and utterance.
Blessed be His holy name!

We returned to Judah Bowerman`'s, on fifth day, and on sixth day evening,
we had a meeting at Hollowell, which was laborious.
Holy help was given to hold forth the Truth in plainness,
and it appeared to be well received by the people.
Seventh day, we lay by.
First day, the 27th, we had a crowded meeting near Little Lake, among a raw people;
many of them made no profession of religion, yet they were very attentive.
The doctrines of Truth were largely communicated;
the meeting became settled into stillness, from a restless state, and closed in quietude.
May the Lord grant that the labors of this day, be like the bread cast on the waters,
to be gathered in time yet to come.
The Half Year`'s Meeting commenced with that for Ministers and Elders,
the 29th of 1st month--a deeply suffering time to me;
being made sensible that human wisdom was too much acted in,
while transacting their business,
and Divine wisdom not even sought for by many of them so that the
poor in spirit who had no wisdom but the Truth to lean upon,
often went with their hands upon their loins,
when they saw their beloved turned out of doors, and true judgment trodden under foot.
I was enabled to clear my mind on this subject in plain dealing.
The day following, they were long and dull in doing their business,
and of course got but little done, owing to a worldly wise spirit,
that influenced many who appeared determined that
true judgment should not be brought to the line,
or righteousness to the plumb-line; and in order to carry points,
outdoor plans were laid, and practiced in meetings;
they had to adjourn to another day to finish their business,
in which some important matters were carried by misrule,
deeply wounding the feelings of their brethren.

After this meeting, we set forward for Norwich, and got to Pickering,
attending that meeting on first day, which was a favored, refreshing time.
We passed on round the head of the Lake, to Daniel Crossthwaite`'s,
where we had a meeting to our own satisfaction, and that of the people.
We continued our journey until we got to Job Peckham`'s, in Norwich,
on sixth day evening, the 8th of 2nd month, where we stayed until first day,
and attended their meeting.
Here, I found many sick, and death in the pot,
and much bitterness in the minds of some against their better brethren;
but Truth enabled me to clear my mind for that time.
After it, we had a meeting in the lower settlement,
with a little remnant who stayed with Friends,
the most of that meeting having gone of with the Hicksites.
In this meeting, we were favored with the company of the dear Redeemer,
to our comfort and encouragement.
The Monthly Meeting coming on fourth day, we stayed and attended it,
where I had to pass through deep, painful feelings, which made my heart to ache,
in seeing the discipline trodden under foot, and those who wished to have it so,
justified.
I was strengthened again to bear a faithful testimony in the plainness of Truth.

From there we went to Yarmouth, and had two meetings in that town,
and one at a place called Nova Scotia Settlement,
in all which it pleased the Head of the Church to give strength in weakness;
for it was my lot between meetings,
almost continually to pass under great poverty of spirit, and to feel great weakness.
In this way I was led about from place to place, not knowing what would come next,
until I was brought into action,
and the Master laid it upon me to hand out to the people,
and in simply attending to His directions,
I have witnessed a being raised out of great poverty and weakness,
and clothed with strength to run through a troop, and leap over the walls of opposition,
and the Truth to rise into dominion over all.
Blessed, and forever adored, be the name of the Lord, my God!
We returned to Norwich and attended the fourth day meeting,
where my good Master strung my bow and tuned my harp, and enabled me to clear my mind,
in so full and plain a manner, that I felt clear of them, whether they will hear,
or whether they will forbear.

We arrived at Pelham, on seventh day, the 23rd. First day, we attended a meeting there;
the presence of the Lord being felt among a little band who had been closely peeled,
but not forsaken.
We then proceeded to Lockport, in the State of New York,
where we had a favored meeting on fifth day.
On sixth day, the 1st of 3rd month, we had a suffering meeting at Hartland,
and put up with Benoni Sprague, where we were blocked up by a boisterous snow storm.
We next proceeded to Rochester and had a meeting in the town; then one in Macedon,
and attended Farmington meeting on first day, at the old house.
In the evening, we had a meeting in Macedon village.
On second day, we set forward for Pennsylvania, and on third day night,
we arrived among Friends at Hector, where,
finding their Monthly Meeting was the next day, we attended it.
Fifth and sixth days, drove to Friendsville, in Pennsylvania, and put up with John Hudson.
Finding there was a small meeting of Friends held in the place,
we concluded to proceed to Jehu Lord`'s, and lay by on seventh day.
On first day, the 17th, we met with Friends and others of that place--a mixed multitude,
and crowded meeting, which caused close labor;
but the Truth made its way through all opposition, and arose triumphant.

Second day, we set forward for Stroudsburg; the roads being exceedingly muddy,
it took three days, but we got through in season to attend the Monthly Meeting,
which was small, having been reduced by a number running into infidel principles;
yet they conducted the business regularly and in harmony.
In this meeting I had the indulgence to sit in peaceful silence,
which I esteemed a favor; but not feeling clear, I appointed a meeting on sixth day,
which gave an opportunity to relieve my mind considerably;
yet not feeling clear to leave, I concluded to stay over first day,
the 24th of 3rd month, at our kind friend, Daniel Stroud`'s. We attended their meeting,
where a number present appeared in a very unsettled state of mind.
I was dipped into a sense of their dark state of insensibility,
and had to warn them seriously; it was a painful, exercising meeting,
and there appeared a determination in some of them, not to receive or believe the Truth,
so that I parted with them under the impression of sorrow.
We left on second day, and arrived at Plumstead on third day evening,
and had a meeting there on fourth day,
and one at Buckingham on fifth day--both favored meetings.

Sixth day, we went to Christopher Healey`'s, where we were on seventh day.
First day, the 31st, we attended Falls Meeting;
there being a goodly number of Friends who had kept their places
through the struggle which produced the great rent in our Society.
We returned to Buckingham Monthly Meeting on second day,
which was much larger than we expected.
They conducted their business in peace and good order.
Third day, we attended Wrightstown Monthly Meeting,
the weakest that I ever remember of attending--a painful, exercising one to me.
We next attended Middleton, on fourth day; it was small,
yet they conducted their business in pretty good order,
and appeared concerned to sustain the reputation of the Monthly Meeting.
I had pretty good satisfaction with the little band of that place.
Fifth day, we attended Falls Monthly Meeting, where we met, I think,
with the largest body of Friends in a Monthly Meeting capacity
that we had fell in with since we left Canada.

The good Shepherd, who goes before His sheep, and puts them forth,
was pleased not only to furnish matter, but to give strength and utterance.
The testimony went forth in its own authority.
I felt fully clear after meeting.
On sixth day morning we rode to Middletown, and put up with David Comfort,
and stayed until seventh day, when he took us into the city of Philadelphia,
to Ellis Yarnall`'s, in season to attend all the meetings but one,
before the Yearly Meeting, and also that of Darby.
In all of them, I was enabled to clear my mind, so as to feel pretty well relieved.
The Yearly Meeting of Ministers and Elders commenced on seventh day,
and the Yearly Meeting ended on seventh day following.
I was favored to attend all the sittings,
and mercifully indulged to pass them all in silence,
with the enjoyment of peaceful poverty of spirit.

On first day morning, I attended Orange street meeting; therein my mind was enlarged;
Truth flowed free and lively--a refreshing time to me.
On second day, I went out to Byberry, and had a meeting on third day,
with the few Friends.
Notice being given, quite a number, not of our Society, attended,
so as nearly to fill the house; among whom,
were several of those who had seceded from us.
Truth went forth in its own authority,
and arose in its own power and dominion over all dark spirits.
Blessed be the name of the Lord Almighty, who gives strength in the day of battle!
On seventh day morning, the 27th, I returned to the city,
in season to attend the Monthly Meeting for the Western District.
There the Master of Israel`'s assemblies was pleased to open the well-spring of life,
and water His heritage.
Blessed and adored be His goodness, forevermore!

On fifth day, I attended Arch street meeting,
where Mildred Radcliff and another woman Friend,
were much favored in testimony to the comfort of their Friends.
Sixth day, I went to Marion, and had a meeting with the few Friends there,
much to my satisfaction, and returned to the city.
Seventh day, we crossed the Delaware River, and went to Burlington,
and attended the morning meeting, entirely closed up, without suffering.
In the afternoon, way opened in the springing of the Gospel,
to bear a short testimony to the relief of mind; I departed in peace,
and went to Springfield, where we had a favored meeting; for the Holy Shepherd of Israel,
in the clearness of Gospel light and life, furnished with matter and utterance to divide,
and apply to the several states before me; full relief was given;
peace flowed as a river.
Blessed be His holy name!

The next meeting was at Mount Holly,
where they were much stripped by the rent that had taken place;
yet I thought they were in a better state than they were,
when I was there some years before, when their meeting was large.
I think I was rightly authorized to encourage them;
if they abode faithful there would come a returning Spring,
when they would not only bud and blossom, but be nourished to bring forth good,
acceptable fruit to the Great Head of the Church.
We passed on to Rancocas, the meeting is pretty large;
there appeared to be a number of well-concerned Friends,
yet with the younger class too much of a worldly spirit prevailed.
My labors were exercising and plain, rewarded with peace.
The following meeting at Westfield was reduced by the revolt among them;
a stripped remnant appeared concerned to keep up their little meeting in faithfulness.
The presence of the good Shepherd was felt among them, to our comfort,
and their encouragement.
We then went to Newtown and Haddonfield.
In both those meetings, the testimony was deeply exercising, yet Truth rose in dominion.
From there, on first day, to Cropwell.
We attended a large, favored meeting on second day, at Moorestown,
where the Gospel spring ran freely, greatly to the relief of my mind,
and tendering of many minds in the assembly.
On third day, we had a meeting at Easton, to my satisfaction,
and the comfort of honest Friends,
who had suffered by the bearing down disposition of the seceders.

Fourth day, we attended Springfield Monthly Meeting.
It was small, being reduced, by many leaving Society; the remnant that were left,
appeared well resigned, and engaged to maintain the good order,
in support of our Society, conducting their business regularly.
After meeting, we went to Joseph Haine`'s, where we were on fifth day,
the 9th of 5th month.
Sixth day, we attended Lower Evesham Monthly Meeting.
Seventh day, at Upper Evesham Monthly Meeting--both favored meetings.
First day, we attended the Upper meeting again, greatly to the relief of my mind.
Second day, we went to Tuckertown, on Little Egg Harbor,
and had a meeting with Friends and others.
Fourth day, we attended Barnegat meeting.
Fifth day, we proceeded to Shrewsbury,
and on sixth day we had a comfortable meeting with them.
We made our home with the widow Elizabeth Williams, the 17th of the month.
The 18th, we went to Plainfield,
and had a pretty full favored meeting there the next day.

After this meeting, I felt easy to take my departure,
to attend our own Yearly Meeting at New York.
We reached the city on the 21st, and the day following, attended their mid-week meeting,
and found I was in my place, and general satisfaction I think was given.
I lay by until the Yearly Meeting came on, and attended all the sittings,
wherein business was conducted in harmony and condescension, ending in the quiet.
Sixth day, I met with my wife in the city,
and had her company through the Yearly Meeting, and up the river as far as Troy.
There she took land conveyance; I kept to the water some miles further,
and landed at Stillwater, where a carriage came for me the same day,
and took me to Schaghticoke Point.
My wife arrived there first, and had appointed a meeting there for the day following.
I stayed and attended it with her, and was well satisfied with the meeting.
She went on for home.
I had to wait for my carriage to come,
which arrived at night the day she left me in the morning.
We started for Granville and arrived in good season.
My wife had stopped on the way, and had appointed a meeting,
so that she got in but little before me;
and finding their Monthly Meeting was coming on the next day but one,
we both stayed and attended it, and felt glad that we did.
Then quietly left for home, and arrived there the forepart of

[.small-break]
'''

+++[+++From this time forward, there has been no further memoranda kept by Joseph Hoag,
of his travels, or religious exercises.
Probably occasioned by his inability to write, from advanced age, being in his 72nd year.]
