[quote.epigraph, , Rev. 14:13]
____
Blessed are the dead which die in the Lord,
from henceforth, yea, saith the Spirit,
that they may rest from their labors, and their works do follow them.
____

== Preface

Believing it to be the will of God, that the righteous should be held in remembrance,
and having ample evidence, both in Scripture testimony and the accounts left on record,
of the great benefit such remembrances have been
to individuals and to the Church of Christ at large;
it is thought best that the following accounts led by our worthy deceased Friend,
Joseph Hoag, to his children,
should be added to "`the cloud of witnesses`" that have gone before,
all testifying to the Mercy of God in Christ Jesus,
through the manifestation of His grace, to save the people from their sins.
There are many still living, up and down in this land, (for he was very generally known),
who can testify to his zeal in the Lord, and his labors of love,
in persuading his fellow creatures to "`come, taste and see, that the Lord is good.`"

He was as a sharp threshing instrument in the Lord`'s hand, in rebuking sin,
and all manner of iniquity; as will appear by the following pages: but to the humble,
contrite ones, his words often fell as the dew of Hermon on the tender plants,
which greatly endeared him to the upright in heart.
He was a man of strong mental powers--by which,
through the qualifying influence of God`'s grace abundantly bestowed,
he was prepared as a judge, and counsellor in Israel, rightly to divide the Word,
laying "`judgment to the line,
and righteousness to the plummet;`" being quick of discernment in the fear of the Lord,
and a zealous disturber of every false rest.
Having in early life been convinced of the rectitude
of the principles of the Society of Friends,
(in which he was educated), he became warmly attached thereto,
and was never known to swerve therefrom,
through the changing vicissitudes accompanying a life protracted to old age;
in which he suffered "`perils by sea, perils by land,
and perils amongst false brethren;`" for, as the Israelites of old,
were troubled with their Korahs, Dathans, and Abirams, so the Church in his day,
was afflicted at different periods, with false teachers, who have brought in heresies,
and taught doctrines,
at variance with those upon which the Society was first established.
These innovations grieved his spirit; and as a faithful watchman on the walls of Zion,
he was concerned to sound the alarm, and testify against their unsoundness;
notwithstanding which, many followed their pernicious ways,
which finally resulted in the Hicksite secession,
and many trials and difficulties attending the introduction
of the unsound views of Joseph John Gurney.
As the followers of each were numerous, and he drawing towards the close of life,
he became greatly concerned for the preservation of his writings,
lest they might fall into the hands of those who would utterly suppress, or pervert them;
knowing that they contained sentiments at variance
with the principles of both of those leaders.
He, therefore, took measures to guard against these evils,
by adopting the following course, and giving forth the subjoined testimony:

Monkton, 1st month, 5th, 1846

Having, from my younger life, felt best to keep by writing,
some account of the religious services and exercises,
that from time to time I have passed through;
but of latter times I became uneasy relative to some
circumstances which I had omitted to commit to writing;
also, about the place where my writings were,
and no way seemed to open to have it otherwise,
until my wife proposed that I should go and get Narcissa Battey to write for me.
This looked pleasant to me.
Accordingly, the past summer, I took my writings and carried them to Ezra Battey`'s,
and feeling easy about their location,
I have committed them to the care of Ezra and Hannah H. Battey,
with a request that they shall not deliver them to any other person, save myself;
and if they are permitted to remain in the hands of the said Ezra and Hannah,
or either of them at the time of my decease, I hope,
and do now request them to take especial care of them,
and not suffer them to pass into the hands of any who would destroy them,
or cause them to pass into oblivion;
as I believe some parts of them may prove of importance in a future time,
and feeling assured that some parts of my writings are in
opposition to the doctrines propagated by Elias Hicks,
and many of those written by Joseph John Gurney,
I am unwilling to have them fall into the hands of any persons who have,
or may support either of the above named persons,
or advocate either of their peculiar tenets;
and feeling confidence in the above named Ezra and Hannah, I therefore place,
and have placed them with them for the purposes above named:
And further--if by reason of death or otherwise,
it shall appear necessary that they should be placed with some other person, I request,
that those who do witness this procedure, or the survivors or survivor of them,
should place them in the hands of some sound, substantial Friend or Friends,
agreeably to the foregoing request.

Joseph Hoag

We being present, know the signer of the foregoing to do it of his own free act,
and requested us to witness the same.

Amos Battey, Ruth Battey Moses Huntington, Elizabeth Huntington Joshua F. Meader,
Joanna Worth.

Although our deceased Friend was not highly learned in the literature of the age,
and some of the expressions contained in the following journal
may not suit the nice and critical taste of some readers,
and may contain, in their view, some incidents of a trivial character; yet,
as we believe he was taught in the school of Christ,
the compilers of this work thought it would be more interesting to the general reader,
that no material change should be made in the language,
and that it should be presented to the public, very nearly in its original form.

We have endeavored in no instance, by change of language,
to alter the meaning of the Author.

The above statements relative to the disposition of Joseph Hoag`'s writings,
are corroborated by the testimony of Starksboro Monthly Meeting.
