== Chapter III

Having brought my account thus far,
I go back to the time of our becoming thoughtful of having a Preparative meeting.
This also met with strong opposition, some members openly declared against it,
that discipline always promoted contention, and did more hurt than good;
which backened the work for a while, until Friends abroad grew uneasy;
consequently the opposition ceased.
But one member told me if we obtained meetings for discipline I should never
live to see the day that Friends would live peaceably and happy together;
notwithstanding, we went forward and obtained a Preparative meeting,
and affairs went along pretty smoothly for a few years.
These same opposers came forward in our meetings for business,
and affected to be well satisfied with order,
at the same time taking much pains to ingratiate
themselves into the esteem of Friends abroad,
until they thought they had got strong enough,
then they broke out and endeavored to destroy the
influence and credit of every faithful honest friend,
who dared to oppose them.
This gave Friends abundance of trouble for about twenty years,
until the death of a member who said it should be so.
Some of his aids soon followed him, since which,
that spirit has much subsided amongst us, and we are at peace in doing church business.

I now leave this subject (as I shall in the course of the narrative have
recourse to some of the events which transpired during that time,) and
turn my attention to the labors of myself and bosom companion.
We being placed in a new country, which was filling up with people of every society,
or nearly so, in our land;
the priests not being anxious to crowd in until some more
favorable prospect of pecuniary advantages could be obtained,
the people were thus left destitute of preachers, so that there was great openness.
We often felt our minds drawn to have meetings amongst them; the Lord blessed our labors,
many became convinced and joined our Society.
A number of these are faithful members to the present day.
This increase, with young Friends moving in, soon caused meetings to be settled at Peru,
Grand Isle and Lincoln, all which soon became Preparative Meetings.

This relation may show you my children,
how the Lord blesses the labors of the faithful to their encouragement and comfort,
and to the praise of His ever adorable name.
We found it our duty when at home to be faithful in attending our meetings,
so that the two first years we used to walk over four miles, twice a week, spring,
summer and fall: In winter I used my oxen for a team, taking all our family with us.
Starting about sun-rise, we could get to meeting seasonably, and home about sunset.
When I got able to buy and keep a horse for your mother to ride, I felt rich.
Oh! dear children, I want, if any, or all of you, should arrive at easy circumstances,
that you remember whence you have risen,
and always let a thankful and humble mind be your inner garment,
that the blessing of the dew of heaven may rest upon you.
Friends got along in the main, pretty well, until we got several settled meetings,
and others began, when we thought it time to have a Monthly Meeting of our own;
we made a request, and obtained it, with Danby added.

Having lived here from about the age of twenty-eight to thirty-eight years,
and meetings thus far settled in order,
and my family as comfortably situated as the circumstances of a new country would admit,
my estate being nearly clear of debt,
I found my mind impressed from day to day with a prospect
of paying a religious visit to the inhabitants of Nova Scotia,
and the adjoining British Provinces, and to Friends with others,
generally in New England.
After considering the importance of the subject for several months,
the Lord gave me to see clearly that the time was come to inform Friends of my concern,
which I complied with at the next Monthly Meeting,
under a feeling sense of the greatness of the undertaking.
The meeting took up the subject and appointed a committee
to consider the matter and report.
Some Danby Friends being on the committee,
one of whom having much influence in his own meeting,
drew the line at once that I should not go unless
I would give up all my prospect on British ground.
This, I could not, and dared not do,
so they kept it along about one year without giving a decided report.
At length the concern left me, as though it had never been;
of this I informed the meeting.
It seemed to shock the Friends who had held back; the business dropped here.
I felt no more of it for more than a year, being quite easy;
but those Friends who held back, were much uneasy the whole time.

When I opened my prospect again, in the year 1800,
the meeting gave me a certificate expressive of full unity;
the Quarterly Meeting endorsed it, and it appears by the minutes I kept,
that I took a solemn leave of my family on the fifth of first month, 1801,
and traveled one hundred miles within the verge of our own Yearly Meeting;
having had twelve meetings during the time, mostly amongst those not of our Society,
where there appeared much openness.
When this service was accomplished, the Friend who was with me returned home,
and I went to Danby to fall in with my other company,
arriving in time to be at their first day meeting, which was an exercising one;
but through the aid of Holy help I was enabled to clear
my mind to the several states brought before me,
so as to feel well relieved.
From here we set forward for Richmond; crossing the Green Mountains,
we reached there on second-day evening, the 26th of the month,
and had a meeting there on the 27th. Here, deep suffering was my lot;
patience seemed the only stay for a while;
it appeared to be much of a barren place every way.

From here we went to Orange, a small meeting, there being notice given of our coming,
a number of their neighbors came.
In this meeting my mind was bowed,
and brought into a renewed sense of the dependent state in which the human family stood,
not able to help themselves, nor to help others without Divine aid and support;
therefore the Lord only is to be looked unto, and waited for, who was pleased,
at this meeting, to cause His holy presence to be felt amongst us,
to the tendering and encouraging of some minds.
After meeting, we rode until in the evening.
The day following, there fell a heavy rain with hail.
This made me thoughtful of my health,
but finding Uxbridge Monthly meeting to come the next day,
I felt most easy to go forward.
Though the storm was severe, I took no cold,
and arrived in season to attend that meeting, held on the thirtieth of first month,
at which I found it painful to be baptized for the dead,
who were wrapped up in a worldly spirit, and buried deep in the earth;
who called self-confidence righteousness, and have made it a bed,
or couch of ivory to stretch upon.

I had to arise under the weight of the subject,
bear a faithful testimony against such Babels,
and sound an alarm to those who were at ease in Zion.
My mind was relieved and comforted in feeling the arm of Israel`'s Shepherd,
to be underneath and strong in the time of battle; blessed be His holy name!
The meeting for business was exercising; that which glorified Israel and comforted Jacob,
appeared very low, and suffering appeared to be the bitter meat of the upright in heart.
Near the close of the business I was enabled to clear my mind so as to feel easy.

The day following we traveled to Leicester, attended their meeting on first-day,
in which painful travail and searching of heart was my lot;
blessed be the Lord whose arm was underneath!
He gave strength to bear the testimony He required, to the peace of my mind,
and I hope to the praise of His holy name.
We went next to Bolton and attended their Monthly Meeting, held the 2nd day of 2nd month.
Here the Holy One was graciously pleased to be near His people and feed His flock,
to the refreshing of His heritage; blessed be His name! may Israel now say,
for His mercy endureth forever!
On the third we lay by and rested; the fourth had a meeting at Northbridge,
and on the fifth day of the week, had one at Mendon.
This appeared to be an old meeting nearly run down.
On sixth day we were again at Uxbridge Meeting.
On seventh day we had a meeting at Douglas.
The first of the week and eighth of the month we attended a meeting at Smithfield,
called Winsocket.
At this place the gospel flowed freely; it was a good, comfortable meeting to us.

After proceeding thus far, I felt a full stop; but after several hours of serious musing,
my way opened clear to attend a Quarterly Meeting for the Province of Maine.
I informed Friends of my prospect; they soon furnished me with a companion.
The next day Nicholas Battey and I pursued our journey,
having to ride one hundred and forty miles as soon as we could well perform it.
On our way, a number of miles before we got where the Quarterly Meeting was to be held,
we came to a small settlement of Friends near night, who held a meeting.
It came into my mind that we could have a meeting there early next morning,
and reach the Quarter.
We being at the house where they held their meeting.
I opened my prospect to the man; he answered me short, and left the room,
but soon returned.
I resumed the subject, he answered as before, and left the room again.
This so affected my feelings that I went into another room and lay down.
My companion then took hold of the subject and obtained liberty for the appointment.
We got an active young man to give notice that evening.
In the morning we had a large gathering and a solid favored time, so much so,
that the Friend acknowledged the meeting to be right, and that his objection was,
he thought neither of us looked as though we could preach,
and he did not want the people to be disappointed; but he would never do so again,
so we parted.
We rode that day hard, and the next day fifteen miles, before meeting;
it being a select one, and gathered when we arrived, and my companion a private member,
I had to go in where there was not one face that I ever saw before.
There appeared the most general gravity and exact
uniformity in dress and deportment that I ever noticed.
Oh!
I exclaimed in my mind, what a fine body of solid Friends here is.

It was not long before all turned dark and painful.
I said in myself what does this mean?
It came forcibly into my mind, that when the Sons of God met together, Satan came also;
and his first work was, (as fast as he was suffered to do it),
to get them all by the ears, and quarreling,
which was the case with this fine looking people,
and that I had to tell them how they appeared.
Solemn were my feelings, and weighty the subject upon me.
After sitting one hour, feeling the wellspring of gospel life forcibly,
I rose with these words: "`Friends, I have never learned any other rule to preach,
or speak by in the assemblies, but feeling,`" and proceeded, as matter and words flowed,
without turning to the right or left.
It was a heart-aching time to me,
for I had to tell them plainly that the accusing spirit had got in,
and there were those who charged others who were innocent,
with that which they stood in themselves.
I had to go largely into the subject in an impressive way, and closed with these words:
"`Friends, you know, I do not, though I believe there is cause for this;
let the subject rest on your minds, for if it has not already appeared,
the old serpent lies at your doors; his crooked tail is at the steps of them,
and it is time for you to be on your guard.`"
Many heads hung down.
They soon proceeded to business, nothing was discovered from their accounts,
yet I felt a solemn, peaceful quiet, to cover my mind.

The meeting for worship and discipline was held the next day; it was large and favored.
The business was transacted lively and harmoniously.
There was a woman Friend in attendance, from another Quarterly Meeting,
who had a good minute, giving her liberty to visit the meetings of this Quarter,
and a number had been appointed.
There was also a man Friend of this Quarter,
who with the unity of his Friends had appointed several meetings;
one of their appointments was at the same place and time.
The man preached first, the woman followed.
Nothing appeared in their testimonies to clash; but as soon as meeting closed,
the woman arose and desired the select members to stop.
She then testified that the man Friend was a false
minister and had preached false doctrine that day.
The man being quick and nervous, it came to sharp words.
The other members ordered them to stop.
They consulted together and told them their mind was that each
of them should attend the meetings they had already appointed,
and appoint no more until after the Quarterly Meeting, which was to be in a few days.
They would then attend to it, and give their judgment on the subject.
These occurrences took place but a few days previous to the Quarterly Meeting,
and were unknown to me, until after I had attended a neighboring Quarterly Meeting.

After this Quarterly Meeting we rode several miles towards the other Quarter,
and found this woman and husband, (he being her company),
at the house where we proposed to lodge.
She was on a bed, groaning and making much ado.
The man was more sociable, asking questions about Friends and their ways in my country.
At length, it came into my mind pleasantly to remark;
there was one thing we did not approve of, which is,
one minister`'s running down another; little thinking how suitably it applied.
It stopped any further inquiries.
The next day we rode forty miles through snow banks and mud.
I attended the Select Meeting of that Quarter and found it no better.
My labors were nearly of the same nature,
so that after meeting I much doubted the possibility of my feelings being right.
My mind was bowed under the reflection,
earnestly craving that I might be preserved aright.

Next came on the meetings for worship and discipline,
where I soon felt that light and gospel life was in dominion.
I rose in the early part of the meeting, feeling my mind furnished with good matter;
strength and utterance were given; the doctrines of the Gospel flowed freely,
and went forth in the light of Gospel life.
The meeting closed under a sweet calm.
This time of favor a little revived my drooping mind; but short was the repast; for,
when business came on, such feelings arrested my mind,
and such conduct was presented to my view that I knew not what to think.
When I looked at them with my outward eyes, seeing their comely appearance, I said,
"`these things cannot be.`"
These thoughts were followed with distress.
When I looked with an inward eye it was clear and plain, as though I knew it.
I waded in this manner for some hours; and to add to my trials,
the woman who had given dissatisfaction within the other Quarter, was at this meeting,
and came into the men`'s room, walked into the gallery, and thus addressed the meeting:
"`My mind has been pained, and I felt a necessity to come in here; for,
notwithstanding what was said in the foregoing meeting, the people were not fed,
neither were the mourners comforted; I am come to comfort them,
and give the children some bread.`"

She detained the meeting sometime, but this did not take the load off my mind.
After the rise of the meeting two Elders came to me and questioned
me as to what I thought of that woman`'s visit to their meeting.
I told them I did not come there to meddle with their Ministers;
that was the Elder`'s business; but,
"`if I have said or done anything that hurt your right feelings,
I hope you will treat me as I should expect my friends to do were I at home.`"
They paused a little, and one, with a smile said,
"`we have nothing for thee on that ground, for thou hast been highly favored,
and rejoiced the hearts of thy brethren today.`"
This interview seemed a little to relieve my mind.
There being some time between this and Bedford Quarter, I visited Seabrook, Dover,
Almsberry, Turkey-Hill, Meaderborough, and returned to Seabrook Monthly Meeting,
and a meeting for discipline at Dover.
When I came into their meetings for business my former burden came renewedly upon me,
and I endeavored to clear my mind from place to place,
as I had done in the smaller meetings I visited.

Having got through these parts, looking over my labors I greatly feared I was wrong.
The enemy took the advantage, and brought a dark cloud over me,
so that I believed all was wrong; that I had done hurt, wounded the innocent,
and was bringing reproach on my Friends at home.
I concluded to tell Friends my prospect had closed up, and I felt best to go home;
for I had slept but little for two nights, the last, scarcely at all.
I got up in the morning with a resolution to leave.
I had not yet mentioned it, as I was waiting for the Friends who were with me to go away,
thinking then to get on my horse and go home.
While thus musing, in stepped Joseph Meader an Elder,
and asked me to go into another room.
He then said, "`I parted with thee not expecting to see thee again;
but after riding several miles,
my mind was weightily arrested and impressed with
a sense that thou wast sinking under discouragements,
thinking that things could not be as they appeared to thee.
Thou mayest be assured that it is all so,
thou hast not been mistaken in one instance where I have been with thee,
as I have heard of.`"
This interview so relieved my mind as to renew my courage to pursue my journey.
But entering into a solemn consideration and enquiry, why it was, if all was right,
that I was left to fall into such distress,
and was led to see in the clear light of the Lord,
that I had reasoned with flesh and blood,
and had not gone to Him for counsel and knowledge;
thereby leaving the way open for the old serpent to present
his false and deceiving representations to my mind.
It was an humbling, contriting season to me,
and I was made willing to enter into renewed covenant, let what would come,
if the Lord would be my guide and helper, I would serve Him faithfully.
Blessed be the adorable goodness of the Most High God!

After these occurrences I fell in with a Friend who told me he was at
the first Select meeting where the two Ministers were who had disagreed,
and that I brought to view the altercation that passed between them,
nearly word for word--and showed so clearly where the wrong was,
that Friends there were all satisfied.
They acquitted the man Friend, and directed the woman to go home,
but she followed me to the next Quarter to try what she could do there;
but failing of success, she went home.
I shall have cause to mention her hereafter.
In looking over the marvellous and tender care of the Most High,
in bringing about my relief in the way he did, my mind was bowed in gratitude,
thanksgiving and praise to the Great Shepherd of Israel.
I took fresh courage and pursued my prospect cheerfully.
The next meeting I attended was at Sandwich, the 18th of 3rd month.
There, being taken sick with a heavy cold, and the weather being inclement,
I lay by until first day, and attended that meeting again.
From thence, rode to Sandwich, Barnstable county, Massachusetts,
and attended their Select Preparative Meeting on the 27th,
sensibly feeling the want of true Gospel love and unity, which gave me close exercise.
But I relieved my mind amongst them, and some of them confessed after meeting,
there was just cause for my feelings.

From this place I rode to New Bedford to attend the Quarterly Meeting,
and was taken to the house of William Roach, where I was affectionately received.
Next day I attended the Select Quarter,
and found myself embodied with a number of sound-headed, solid Friends.
Notwithstanding it appeared so,
my mind was strongly impressed there was a disease amongst them,
and there were some ailing who were not sensible of it, but believed themselves well,
while the mortal disease was increasing upon them;
and that such were like those in a slow consumption, exposed to flattering hopes,
until dissolution closed the scene; then all would be over.
I was led to call their attention solemnly to this subject,
and whom to call on individually, to know what, and where the disease was,
and what would be the remedy.
After meeting, some Friends remarked, they believed there was a cause for my feelings,
and told me where they applied it.
But as it proved, those who applied it to others were the very ones to whom it applied.
In this way, the poor servant`'s labor is often handled,
much to the hurt of those to whom it applies,
by depriving themselves of the blessing of improvement, and rendering the labor lost.

The day following, the meeting for worship and discipline was held.
The presence of the Shepherd of Israel, was felt to own this meeting;
the business was conducted in harmony.
Near the close thereof my way opened clearly, to proceed to Nantucket,
but the wind not being favorable, we had to lay by on seventh day.
We attended their meeting on first day; it was large and favored.
The wind continued unfavorable until 3rd day, the 31st, when we set sail,
about seven in the morning, for Nantucket, and arrived there about one in the afternoon.
The 1st of the 4th month, I attended their Monthly Meeting for the northern district.
The 2nd of 4th month and 5th of the week, I attended the old meeting,
and lay by on sixth day.
The 4th of the month, I had an appointed meeting.
The 1st day, the 5th, attended the northern meeting in the forenoon,
and the old meeting in the afternoon.
In all these meetings, I found Holy help to bear up my mind,
in the exercises that came upon me, and ability was given to clear my mind,
so as to feel easy to leave for this time.

2nd day morning, I went on board for New Bedford, where we arrived in about seven hours,
being very sea-sick on the passage.
The 3rd day morning, the 7th of 4th month, I set forward for the Yearly Meeting;
it being some time ahead,
I employed my time in visiting the meetings in that part of the country.
I was conducted to Moses Brown`'s, in Providence.
Here I was kindly received; he and his wife went with me to the Quarterly Meeting,
and introduced me to a rich Friend`'s house; but being dressed in coarse cloth,
and making a rustic appearance, I was coolly received and coolly treated.
All this I did not mind, it being good enough for me,
but I could not get fodder and grain for my horse as he needed;
the poor creature could not speak for himself--I had to care for him.
When morning came, I took my horse and walked towards the meetinghouse.
I saw a house that looked right, and meeting a young man,
I asked him if a Friend lived there; he replied, yes.
I asked him if he would take my horse there, giving him directions how he should be fed,
and to tell the Friend, if he would do so,
that after meeting I would come to his house to dine.
The young man, with a smile, complied with my request.
When I came there, I found a good home for my horse, and a kind reception for myself,
where I made my home while in these parts.

I attended the Select Meeting at East Greenwich the 8th,
the meeting for worship and discipline the 9th. At this meeting my mind was much grieved,
and heart pained, with a lengthy testimony borne by one of their own members,
who ran into repeated repetitions, which hurt the meeting, and closed my way.
The business went on dull.
I sat nearly silent through these three meetings, but had one appointed at evening,
in the same house, which was pretty large,
and acknowledged to be a solid favored meeting.
Then I had a meeting at Wickford.
The 1st day, the 12th, attended South Kingston; the 13th, had a meeting at Richmond;
the 14th, at South Kingston, upper house; 15th, at Westerly; 16th, at Hopkinton; 17th,
at Foster; 18th, at Scituate; 19th, at Elisha Stear`'s, Smithfield; 20th,
was at the lower meeting, Smithfield; 21st, I reached Providence, and was silent; 22nd,
at Cranstone; 23rd, at Providence again; way opened to relieve my mind,
Gospel doctrines flowed freely.
24th, was at Cumberland; 25th, was at Pautuxet; 26th,
and first of the week at Providence, and silent the second time.
The 27th, being much fatigued and not well, I had no meeting.

After this I had meetings at Somerset, Rehoboth, and Taunton.
The 5th month 1st, I had a meeting at Freetown;
the 2nd and 7th of the week at Fall River, which was a large, good meeting.
The 3rd and 1st of the week, was at Tiverton, and at Fall River again, in the afternoon,
at a meeting in the Baptist meetinghouse.
Here, utterance and ability were given fully to clear my mind,
so that I felt relieved and clear of the place, and sweet peace to be the reward.
The 4th of the month and 2nd of the week, I was at Swansey Monthly Meeting,
and found myself among some solid Friends; but all things not well.
I had to labor plain amongst them.
5th, had no meeting; 6th, had a meeting at Little Compton; 7th, at Accoakset,
and in the afternoon at Centre; 8th, was at Aponaganset; 9th, at New Town; 10th,
at Freetown again, in the morning, and at Bower`'s Shore in the afternoon.

11th, I was at the house of Joseph Austin at Accushnet; 12th, I had a large,
crowded meeting at this place; the presence of Divine Power was felt to be over all.
After delivering a testimony, in which I thought I feelingly cleared my mind,
I had sat but a minute or two before it opened as clearly to my mind,
as the large plain print of a book, so that there was no doubt remaining,
and that I must deliver a message in that meeting, without delay.
I rose on my feet, I think, with these words: "`Friends, I rise on my feet,
to deliver a message,
and I want you individually to turn your attention to your own feelings, for, if you do,
doubtless the one to whom it belongs, will feel the force and evidence of it.
It has appeared as plain to my view, as a plain printed book,
so that I have neither doubt nor scruple, that there is one in this meeting,
who has lived a good moral life, been a good companion, a good parent, a good neighbor,
and an honest dealer, but has settled down at ease, thinking this was enough;
yet thou hast not made thy peace with thy God, and while this is wanting,
all that is essential is wanting; thou hast time to make thy peace with thy God,
and not a moment to spare, for thy time is very short;
thou must go hence to be seen of men no more.
O! let not sleep rest on thine eyes, nor slumber upon thine eyelids,
until this work is done; for thou shalt have no time on a languishing bed;
for when thy change comes--in the language of the apostle--it shall be in an instant,
at the twinkling of an eye; for the mouth of the Lord hath spoken it.`"
I sat down,
and was favored to feel that the power of the Almighty Jehovah reigned over all.
The meeting closed under great solemnity.

13th, I was at Long Plain; here had been a great division amongst Friends,
which appeared to be wearing off and improving, but not altogether healed.
There was need of Friends keeping humble and watchful, which I had to put them in mind of.
14th, I returned to New Bedford, thence to Sandwich on the 17th, and 1st of the week,
where I met with my intended companion for Nova Scotia, Joseph Wing, a pleasant,
agreeable man.
18th, was at Yarmouth, and 19th, at Falmouth.
At all the places I have mentioned, I had meetings;
but the state of them and my exercises in them were so similar
that I thought it would not be edifying or instructive,
to go into particulars;
yet am willing that it should be seen I did not idle away my time.

From Falmouth I went to Nantucket, attended the north meeting once,
and the old meeting twice.
Here I was led into close labor, and felt concerned to sit in some families.
I called on the Elders and opened my prospect to them.
After sitting for some time in stillness,
one of them said I had opened my prospect so plainly,
that he thought they clearly understood me, and that the business could be accommodated.
They all expressed their unity, and named a Friend of each meeting, to be my company,
who knew their own members, and the class I had pointed out.
I entered into this work in fear, and deep searching of heart,
and found Divine Wisdom and Holy help amply sufficient in every needful time.
Good is the Lord to His servants who are devoted to Him!
In five families out of thirty, I had to proclaim the near approach of death,
and to warn them to prepare for the solemn change--a humbling time to me.
I did not hear anything particular from these labors in four or five years,
when I fell in with a widow, at Hudson, who informed me she was one of the visited;
that she had a husband, three sons, and two daughters, all in good health,
about her at that time, and that in six months from that time,
she buried her husband and two sons; and that there was not one house,
where I was led in that way, but one or more died within nine months,
and some within a short time.

After clearing my mind in these parts,
I went to Rhode Island and attended their Monthly Meeting,
where I had satisfactory service to my own mind and my Friends.
On 5th day, I had a meeting at Portsmouth, and 6th day on Comment Island,
and returned to Newport, and on 1st day attended both fore and afternoon meetings.
On 2nd day I went to Hopkinton, and had a favored meeting.
From here we went over into Connecticut, had a meeting at William Browning`'s,
and next day had one at John Foster`'s,
and the day following had another at Samuel Browning`'s.
These three last places were in Stonington,
Connecticut.
I think it was in this little town, in the first meeting, there came in so few,
that I felt disappointed.
In musing upon it,
it came into my mind that Friends had not given general notice as I requested,
and there was time for another appointment in the afternoon.
This language crossed my mind, "`Tell them how thou feelest--send them out again,
and thou wilt get a meeting.`"
It appeared so singular, that I suppressed my feelings, and suffered the meeting through,
to but little satisfaction,
feeling much depressed with poverty of spirit the remainder of the day.

The next meeting I found it so again--sat the meeting through with but little service,
and at the close of it I informed Friends how it appeared to me, what my feelings were,
and desired them to go out and give notice faithfully,
for a meeting at the 4th hour at that house.
When the time came, a large body of people were gathered,
and through the tender mercies of Israel`'s God, we had a fine, favored meeting.
I felt much better, and went on cheerfully, finding my good Master`'s word to be Truth,
as I ever had done.
I came to the next meeting, and found it in the same situation.
I sat the meeting through, and had but little to hand out to them.
At the close, I informed them of my feelings,
and desired them to make a second trial for a meeting there, the 4th hour that afternoon,
When the hour came, I thought it was a larger gathering than there was the day before.
It was a solid favored time; Truth arose into dominion.
I felt comforted in having given up to the openings of Truth,
and that I had left a good lesson for them to think of.

I returned to East Greenwich, attended their meeting on 1st day, the 7th of 6th month,
and had a meeting at the meetinghouse in the town, at 4 o`'clock in the afternoon.
In both these meetings I was enabled to deal plainly,
and felt ample satisfaction in so doing.
On the 8th attended the Monthly Meeting at this place,
and though the business was conducted regularly,
the want of concern to live up to our ancient and present principles, was too prevalent,
which caused deep exercise, and painful labor--the aged buried in the earth,
the young on the wings of the air,
embracing the customs of the world in dress and address,
which was so prevalent in these parts,
that many of the young people could hardly be distinguished from the fashionable
world--so that my soul was many times clothed with mourning,
as with a mantle.
I often felt the necessity to labor plainly,
and call their attention to first principles,
showing them the consequences of their departure.
This seemed to be my general labor amongst Friends, and though my lot was painful,
yet bountifully good was the Most High, in giving confidence, strength, and utterance,
and causing me to feel His holy arm underneath in my getting along.
Blessed, forever, be His holy name!

On the 9th of the month, I had a meeting at a house owned by Friends,
where Friends lived, which was to good satisfaction.
On the 11th I had a meeting four or five miles south of this place.
From here, I went to attend Rhode Island Yearly Meeting,
and attended the several sittings of it, which were large, and in general,
favored with the presence of the Great Head of the Church, to the comfort of many.
The business was conducted with much condescension.
In the main, I was favored to feel my mind much released from public labor,
though not altogether.
At this meeting, we had the company of John Hall, a Minister from Old England,
and Stephen Grellett, his companion, a Minister from Philadelphia; also,
many of the Select members, from all the Quarters, where my mind had been so tried.
Stephen addressed them on the same subjects that I had, not only the same words,
but whole sentences as I delivered them, in their meetings at home.
His communication was strengthening, confirming, and relieving to my mind.
The Select Meeting met several times, and after Stephen had cleared his mind, John Hall,
at a subsequent sitting took up the subject at large,
and spoke in that authority and clearness, that the heads of a number fell,
and rose no more with equal confidence, through the remainder of the Yearly Meeting,
much to the joy of the upright in heart, and their admiration of the Lord`'s goodness,
in confirming His people and comforting His sorrowful ones.

After Yearly Meeting, having got somewhat acquainted with Ann Millin and Mary Gilbert,
from Philadelphia, whose company we had had, and finding my companion not ready,
and the vessel not prepared, I was invited by these women Friends to be their company,
as they were going to Nantucket.
I complied therewith, to fill up the time.
We went to Fall River,
where they appointed a meeting--they both being Ministers--which was to good satisfaction.
They had another meeting at the head of the river, with the Indians; it was a favored,
tendering time; the poor creatures appeared very grateful for the favor.
Oh! thought I, how many poor creatures there are, up and down in the earth,
who would rejoice to have the crumbs of Gospel favor, that fall from the Lord`'s table,
while they are overlooked, and despised by many of our members.
Surely, will not the Lord require it at our hands,
and justly turn off many of the children of the kingdom, who despise their favors,
and will gather from the solitary corners of the earth, to sit down with the faithful,
in the Kingdom of the Lamb.

They had a meeting at Westport,
and from there they went to Aponaganset and had a meeting, and returning to New Bedford,
made some tarry there.
Then went to Rochester, where, I am told, was once a body of faithful Friends,
and now but one family.
Their meetinghouse is occupied by a set of separatists, who went out from Friends.
Benjamin Bump was their minister,
who was disowned for justifying the payment of war taxes.
There was scarcely anything of the life of pure religion to be found among them,
and the very form of godliness was lost.
It was a laborious time.
Next day they had a a meeting at Long Plain, where the dear sisters were enlarged;
it was a favored, good meeting, which seemed to revive their spirits.

In the afternoon they had a meeting at Accushnet,
the dear women were favored with lively testimonies,
which settled like dew on the tender herbs.
O, may it rest long.
The meeting ended well.
We then attended New Bedford meeting in course.
After this, Ann, her companion, and myself;
felt drawings to appoint a public meeting at Friends`' meetinghouse there,
but the packet being ready, we all kept our feelings to ourselves.
Next morning early, we went on board, and sailed about an hour,
when the wind shifted directly ahead, and held us half a day.
At length, the captain concluded he had a Jonah on board, and he would go back.
While going back, we got each other`'s minds, and when we got to the wharf,
we three stepped off.
I turned to the captain,
and told him he might go to Nantucket--we should not go with him,
and I thought the wind would let him sail.
In about one hour the wind was fair, they hoisted sail,
and were out of sight before sunset.

We went to William Roach`'s, and opened our prospects.
They gave notice that evening.
The next day we had a pretty full meeting.
Ann and Mary had good lively testimonies to bear.
I had not much in that way; it seemed to be my lot to feel with them,
and hold up their hands, which I was enabled to do in my little measure.
That evening the other packet came in, and in the morning we went on board;
we had a fair wind, fine weather, a good passage,
and arrived in season to attend their first-day meetings.
We next attended their Quarterly Meeting, which was large.
John Hall, Stephen Grellett, and Elizabeth Coggshall, were present; several large,
weighty testimonies were borne to the everlasting Truth, to the refreshment of many,
and warning of the careless ones.
The business was conducted in a solid, harmonious manner.

My companion not yet coming to me, I had to stay some days.
Feeling the return of an opening, that had been presented to view several times,
which now came before me with weight,
to appoint a meeting for the people of color and the Indian natives on the island,
I opened it to Friends, who united with it,
and took considerable pains to get them together.
There was a fine body of people collected.
I soon felt my mind clothed with Gospel love, which flowed to that people;
utterance was given in language that was easy for them to understand;
which flowed freely, accompanied with Gospel energy,
to the tendering of many of them to tears.
A heavenly solemnity was felt to spread over the meeting, clearly evidencing,
that equal are the mercies of the Lord, to all the children of men.
The service closed with prayer and thanksgiving to the Lord,
for the continuance of His mercies to His people.

Ann and Mary wanted to pay a visit to the people on Martha`'s Vineyard,
and desired my company, with which I complied, as my companion had not yet arrived.
The first meeting was at Old-Town, a dark, hard place; Gospel communication rebounded,
like water poured upon a rock, and we were glad to make our escape from the place.
We went to Gay Head, and had a large meeting amongst the Indians.
Those precious women were favored, and the meeting was quiet, and solid, and ended so.
The poor things expressed a great deal of thankfulness for the visit.
We returned to Old-Town; there we parted; they went to Holmes`' Hole,
and as I did not feel clear, I went to the east end of the island,
and had a meeting with a small tribe of Indians;
after which I felt clear to return to Nantucket,
where I stayed till the 14th of the 7th month, when the vessel was ready to sail.

Before leaving, there came a letter from Samuel Rodman to William Macy,
informing that not long since, "`a Friend near sixty years of age,
belonging to Accushnet meeting, went to the barn near night to milk his cow,
a little earlier than usual, as it looked likely to rain.
While milking he was struck with lightning, and instantly killed.
The Friend was at the meeting when Joseph Hoag dropped that singular testimony,
and that he appeared to be such a person as Joseph described.
And now Friends are easy and satisfied in regard to Joseph.`"
The above is as near as I can remember the contents of the letter on that subject.

14th of the 7th month, we set sail for Nova Scotia; were five days on the voyage,
owing to contrary winds, fog, and poor pilot.
When we got into Beaver Harbor, on the 19th,
we had a meeting with the few Friends living there, and being first-day,
there was more of a gathering than I expected.
In the course of my testimony, I was led to speak to a single state, who felt whole,
and thought himself in good standing; who was in good health, and as to the outward,
appeared likely to live for years; who had not long to live,
and was deceived in the favorable belief of himself.
I was led to call the attention home,
to a narrow heart search, and a faithful petition to the Lord,
that He would show how it stood, between Him and the soul;
saying "`the Lord will show thee, and show mercy too;
this is the only escape from a disappointment in the end, which cannot be recovered.`"

From here, we went back into the country, to a new settlement, and had a large,
favored meeting, in a barn, to which a tribe of Indians came, and sat very soberly.
After meeting, they were asked how they liked what was said.
One of them answered, putting his hand on his breast,
"`I could not understand every word, but felt him here.
I believe, he is a very good man.`"
O! thought I,
how many of the wise and learned never think to try preaching by that standard.
We returned back to the Friend`'s house we first put up at;
we left him well but now found him sick with the pleurisy.
I had it on my mind to have another meeting there, which was readily consented to,
and the sick Friend chose to lie in the room where the meeting was.
I had to take up the subject of the woe to them who were at ease,
and trusted in the mountains of Samaria;
showing there was no greater mountain than the Gospel,
and no greater name than the Truth, for that was over all;
and when all this was professed and believed, and their peace not made with God,
it would disappoint in the end; and this was the woe under the Gospel.
After meeting the sick man was much broken down,
and acknowledged that he saw it was not with him as he expected.
We left him under great exercise.
I heard a few weeks after, he was gone; and,
that after passing through great and painful exercises,
he was favored to come to a quiet, resigned state of mind, which was joyful to bear.

Before I take leave of this place,
I feel most easy to remark that all three of these meetings were favored;
the Truth was in dominion, and the people generally acknowledged its doctrines.
One thing I mourn for, Friends did not meet together, nor sit down in their families;
they were not willing their children should go to other meeting of course; poor things,
were growing up, not only in a way that was unprofitable, but uneasy to themselves;
not informed in Friends principles, through the neglect of their parents,
I was grieved for them; faithfully cleared my mind to the parents, and left them.
O! may the Lord remember the dear children, who are so neglected,
and be a father to them, and gather them into his own enclosure.

We stayed hereabouts until 10 o`'clock on first-day, when we set sail for St. Johns.
Had a quick passage, and made a short tarry at this place;
then went up the river about 60 miles, in an open boat.
Setting out late in the day, and the wind leaving us,
we sat in the boat nearly all night; being foggy it was very uncomfortable,
and what made it more uncomfortable, had a noisy ruffian on board.
We landed near the place we intended, and hired horses of Hugh Copperthwaite.
We rode forty miles up the river,
and came amongst a people who held their meetings some like Friends.
They rejected hireling ministry,
and held that none ought to preach but those who were called upon,
and qualified by the spirit of Christ.
There were three of those meetings, about 12 miles apart.
They generally ended their meetings with a psalm or hymn.
We got amongst them the second day`'s travel, about noon,
and had a meeting with them at five in the afternoon.
There was openness with the people to hear and receive the Truth,
which flowed freely in Gospel authority.
They were much broken into tenderness, under a sense of Divine favor.
The day following we had a meeting about a mile up the river, which was very large,
and much favored; it was truly an humbling time.
Praised be the Most High God!

After meeting we were called upon to give our opinions on women`'s preaching,
being informed that they had three women, one at each meeting, who preached;
that they were the most able Ministers they had,
and all the traveling Ministers who come along before us had opposed women`'s preaching.
This opened the door for us to let them know we approved of women`'s preaching,
and had women preachers amongst us, who were able Ministers,
and to show them our reasons at large why we approved of them in that way.
This was very satisfactory and rejoicing to many of them.
We returned to Nicholas Rideouts;
in this place we stopped and had a large meeting--a
day of high and renewed favor to the people.
May they be wise and improve it to their comfort!
We went to Hugh Copperthwait`'s and delivered up his horses;
he would take nothing for their service.
We had no meeting on 7th day; but on first day two,
the first was pretty satisfactory to the people;
the latter was a large gathering of several different Societies.
I was led to show that the law and the ceremonies in our day were all of a piece;
that they could not make the comers thereunto perfect, as to the conscience,
and of course left them under the dominion of sin;
that nothing could purify the conscience but the law of the spirit
of life which made free from the law of sin and death.
This doctrine offended some, who, though they could bring nothing to confute it,
yet were disturbed by it.
Others rejoiced that the subject was so clearly opened to their understandings.

On the 2nd day of the week, twelve miles down the river,
we had a meeting at the house of one Birdsall, who went from Friends;
a number being there of that sort.
I had close, exercising, plain labor among them,
and felt much satisfaction in being honest to my Lord and good Master.
We continued down the river to New Brunswick town, and on the 14th,
had a large meeting in the Methodist house.
The people sat soberly, conducted respectfully, received our visit well,
and treated us kindly.
16th, first day, we attended two meetings; the first was satisfactory,
the last was much hurt,
by my endeavoring to evade taking hold of the subject as it opened in my mind.
After proceeding a little way it all left me and I had to sit down in confusion,
and remained so until meeting ended, and some time after,
until the Lord showed me that if I had looked to Him for counsel and strength,
He would have carried me through all He required;
but in that I leaned to my own understanding,
it was but right that He should chastise me.
It was an humbling and instructive time.

17th, we sailed for Westmoreland, but went up Maccan River to Nathan Hoag`'s,
and held a meeting there, among a thoughtful, enquiring people, mostly Welsh,
who appeared willing to hear and believe the Truth.
The day following, we had a meeting down the river apiece, which was satisfactory;
and the next day, in the Courthouse near Cumberland Fort.
There was a large company of mixed people, and it was an exercising time.
Though some of them acknowledged to the Truth, yet there were many others, who,
when their sentiments were crossed, it seemed to set them on fire;
particularly the belief that if a man once had grace, he cannot be lost;
let him do what he will, he will be brought in at last.
This idea is so pleasing to carnal nature,
that it seems almost impossible--sorrowful as it
is--to prevail with them to admit the thought,
that it is possible for them to be wrong.
This much closes the way for profitable labor in these parts.

In this part of the country I fell in with the Swedenborgians,
who tried hard to bring me over to their belief.
They kept about me for several days.
At length one of them asked me what reason I could give,
why we were not in duty bound to believe what that man of God (Swedenborg) wrote,
as much as to believe the Scriptures, for the prophets said,
"`Thus saith the Lord,`" and so did he.
I considered a little, and it came into my mind to answer,
that (Swedenborg`'s) was a revelation different from the law or the Gospel.
God chose his own way to reveal the law in a way that man could not counterfeit
by signs and miracles that were visible to the natural eye;
and when Jesus Christ came to introduce the Gospel He wrought
miracles that were as much greater than those of the law,
as the Gospel was more glorious; and that we, Quakers,
were not going to give away revelation so well proved as the Scriptures were,
for a revelation that had no better foundation than the assertion of one man.
To this they made no reply, and I got rid of them, for which I was truly glad.

After the last meeting we were invited home by Thomas Roach, a Methodist by profession.
He lent us horses to ride across the country, and a civil old man was our pilot; they,
neither of them, would have anything for their services.
We rode it in one day, dismissed the man and horses, and let him return the next day.
Here we were detained about a week, before we could cross the bay to St. John`'s Island.
It being wheat harvest, we went into the field to labor, to save spending money.
We earned our living and a dollar over.

While detained here the enemy poured his floods upon me,
insinuating that I had no business there; if I had, I should not have been disappointed,
and that was not all; I had no business to leave home, and my family to suffer;
I was deceived, and had deceived my Friends;
that to be a deceiver and a false teacher was the most wicked of sins;
and I was guilty of that sin;
for to destroy the souls of others was worse than to destroy their bodies.
In this way I was afflicted from day to day.
When I strove to get those thoughts out of my mind, I found it in vain;
and to flee from them, out of my power.
At length it was presented to me--and it came like
the voice of a lion--that if I went on as I had done,
deceiving the people, a dreadful judgment would come upon me,
for God would not be mocked.
It came so heavy that my stomach failed for food or drink, my strength failed every way,
and when I thought of stopping and going home,
the enemy would tell me that would not do,
for when I got there and told my friends how I was
deceived they would ever after disregard me,
and my wife would look coolly upon me.

Then I had better be dead than alive;
that the best way for me was to slip away and get into some
solitary place where I never should be heard from.
It was in vain for me to plead sincerity, for the Lord knew my heart,
and that to plead innocence was mocking God, for my own feelings told me better.
By this time my distress was such that I slept but little and ate little,
grew weak fast and could find no other stay to my
mind than in this appeal--"`I am before thee,
O Lord! thou knowest all things, and if things are so or not;
to run away I cannot and dishonor thy Holy Name, reproach the Truth and thy people,
and bring scandal on myself, I cannot do it;
I would rather die in this strange land and be buried among this strange people.
O Lord! if it is any offering, here is my life, my body and my soul,
in time and eternity, at thy disposal, for Thou wilt do right.
But I pray Thee to preserve me from bringing reproach on thy Holy name,
or on Thy righteous cause.`"
When my mind became stayed here, the billows rolled away, the mists passed over,
and my poor mind was admitted once more into the clear sunshine,
to rejoice and give thanks to the Lord for His wonderful
mercy and sustaining Providence in the hour of temptation.

30th, of the month and first of the week, we sailed for the Island of St. Johns.
We were about twelve hours on the water; landed at Charlotte town,
and were kindly received by John Cambridge and wife,
whose house we made our home while on the Island.
The 1st of 9th month we had a large, quiet, good meeting.
The Governor and his wife attended; he expressed his satisfaction with the communication.
Thus we see many will acknowledge and approve of
that which they are not disposed to practice.
We enquired for horses to hire; the Governor hearing of it, offered his: we accepted,
and sent for them next morning.
He had his own riding horse furnished for me, and said;
"`let the Minister ride that horse,
he will carry him well;`" he looked at the saddle and said;
"`it is so fine I don`'t know but it will hurt the Minister`'s feelings;
bring the blanket;`" had it put on and said; "`now he won`'t see how fine it is,
and it won`'t hurt his feelings.`"
I note this, as due, to show the kindness of the man,
though one of the great of the world.

2nd of 9th month we rode 25 miles through a wilderness of good land to Tryon village,
and had a comfortable meeting with a body of poor people;
thence we rode 12 miles through the woods to a settlement, mostly refugees,
and had a meeting with them.
It seemed like encompassing Jericho; their walls were strong.
But blessed be the name of the Lord,
who was pleased to give strength so to blow the Gospel ram`'s
horn that the walls gave way and Truth rose into dominion.
Not feeling clear, we stopped until first day, the 6th of the month,
and had another meeting with them, which was large and much favored;
the way appeared open, and the minds of the people much reached and tendered.
The meeting was solemn and ended well.
From here we put forward 17 miles through a thick wilderness and a poor path,
and had two rivers to swim our horses across.
In the latter, we stood a narrow chance of drowning our best horse,
owing to mud in the bottom,
but were favored happily to escape and get into Parker`'s Corner in good season.
Went to Farmer Townsend`'s (who had been formerly
a Friend,) and had a meeting at his house,
the 8th of the month.

Here we had to wade under deep sufferings; I had to deal in a plain, close,
and solemn manner,
showing the desolation it produced where there was a known departure from the truth,
and what stumbling-blocks such were to the honest seeker after righteousness;
but it seemed like pouring water on a rock.
I was informed before I left here that a number of years past,
there came several families of Friends and an approved
Minister and settled in this place,
and held a meeting under the care of Friends in England for some years.
The preacher and the next principal member took to excessive drinking,
so as often to be disguised;
the people would not meet with them and the meeting had dropped.
When I heard this I did not marvel at the sufferings we had to feel.

9th of the month, we left this place with heavy hearts,
and rode thirty miles back to Charlotte, through the wilderness, a dreary,
solitary ride to me.
The 10th, 11th and 12th, we did not travel, but rested at our former home,
and wrote to our Friends.
13th, and first of the week, we had a second meeting at this place; 14th,
we had a little meeting on the south part of the Island, five miles from the town,
among a tender, thoughtful people.
The Lord was with them to do them good, and His presence was felt amongst them;
it was a tendering, humbling time, I think not easily to be forgotten.
O, how often is there renewed cause for humble thanks,
and grateful praise to the Most High God, for the continuation of His mercies,
that endure forever.

15th and 16th, we rode to the east end of the Island; 17th,
we had a small meeting at one Coffin`'s, who was formerly from Nantucket,
and brought up a Friend.
There were several more of this description present.
It was an exercising, laborious time, which is often the case,
when we fall among people who know what the Truth is, and do not live up to it;
it is not only a loss to themselves, but often proves a hindrance to others.
In the evening, we had a meeting about three miles from this;
a number came to it who had never been to a Friend`'s meeting before.
It was a favored meeting; the minds of the people were touched and tendered,
and they seemed to want to show their gratitude.
I thought it best to retire from them as quietly as I could.
In the evening, it came into my mind, that when I departed,
I must give the mistress of the house where we lodged, a dollar.
In the morning, it came into my mind again, so that when we departed,
I left a dollar in her hand, and told her to take it, and make good use of it,
and left them.

When we got on the road,
John Cambridge told me he went out among the people after meeting,
and they were gathering money for me, until he told them I would not take it.
Then they stopped.
The husband of the woman I gave the dollar to,
was the most earnest to raise something handsome for me.
I then thought could see clearly, why my mind was impressed to leave money with them,
to show them I could give, but not receive on the principle they gave,
and to confirm John`'s testimony.
We rode back to St. Petersburg; the 20th and first of the week we had a meeting there,
where was great opposition in the minds of the people,
which caused deep searching of heart, until Truth arose, and cleared my way,
and enabled me, with gospel authority, to hold up the standard of Truth;
the people acknowledged to it, but seemed to struggle under it, which, Balaam-like,
is too often the case.
I felt well relieved and satisfied.
We stayed in the neighborhood the night following.

21st, we returned to John Cambridge`'s, and stayed there until the +++_______+++, for a passage,
when we took a solemn departure from those kind, friendly people,
and on the +++_______+++ landed at Pictou, a little Irish village,
not a house without some more or less sick with the small pox in it.
Neither of us ever had it.
We had to stay several hours, to hire horses to ride across the country.
We were at a place where, when we sat down, we could look through the loose partition,
and see them on their couches, apparently at the point of death,
all having the disorder the natural way, yet we neither of us took it;
a great proof of Divine Providence,
the remembrance of which was truly humbling to my mind,
and awakens and calls for grateful thanks.
We started the same day for Halifax, one hundred and forty miles distant.
Got there the +++_______+++ very much fatigued.
We stopped a few minutes at a Friend`'s house,
who asked me if we intended a meeting in the city.
I answered, that I had heard it said, that when sailors came in from sea,
they must first get a good entry into harbor,
before they could tell much about their clearing out; and thus the subject dropped.
We soon crossed the river and put up with Seth Coleman, and kept close for several days.
