== Chapter V

I now return to the time of my setting out on my journey
to New England and the British Provinces in 1801,
at which time we had two candid, faithful overseers,
their standing faithful with a few other Friends,
for the support of order and discipline,
and being opposed by others often made hard getting along; the latter,
who complained of discipline doing hurt would oppose in nearly every case,
taking up or calling to an account any of our members for evil conduct.
One of these overseers took a piece of work to do for two men,
(zealous members of the Methodist Society), to the amount of sixty dollars.
They acknowledged the work was done to their full satisfaction,
but when the Friend called for his money they utterly refused to pay him.
The Friend urged his claim, upon which they went to the Friends who opposed discipline.
The latter went to the Friend,
(two of them being Elders who had been brought over to the libertine sentiment),
and ordered him to give up his demand.
He asked, for what?
They said the men would not pay it; and if he contended for it,
it would make a great noise, and that would be a scandal to society.
He let them know he should venture that.

They then told him if he did not comply with their orders, be peaceable,
and say no more about it, they would carry a complaint against him for being contentious,
and refusing the advice of Friends; and accordingly did so,
but could not make their matters work, till they charged the Friend with disunity.
In this plausible way they got him and his associate dismissed from being overseers,
and had two appointed of their own choosing who presented
a complaint that was never supported,
and got it into the meeting, and a committee appointed.
By this time the Monthly Meeting was about equally divided and all in an uproar,
The committee was as equally divided, being two on each side,
and so it was continued until my return, the Friend still insisting on having a hearing,
and his evidence heard, as his witnesses were credible persons,
stating he could prove the charges false.

Two of the committee absolutely insisted that there should be no proof heard,
neither should they be suffered to speak against what the Elders had stated.
The other two were as absolute on the other side, as to the Friend having his rights.
But in order to carry their point,
they got a Baptist man to take up the business as his own, who in truth, was not present,
and knew nothing of the bargain, only what the Methodists told him,
and then brought them in for witnesses,
so by false witness they so placed the business that the Friend could not recover.
He brought forward one witness who stated the truth,
and told Friends and others concerned,
that he had another which he should produce before the business ended.
They wanted to know who that witness was, but the Friend would not tell them.
(I being the other witness and absent from home on Truth`'s service,
was the reason of his declining to tell them who his other witness was,
thinking it might unprofitably embarrass me if I was written to on the subject,
and he chose to wait for my return.)

The next day, I think, after I got home,
one of the Elders came to my house and stated to me that the Friend was a wonderful liar,
and it was proved by the two Methodists he had called on for payment,
but the Baptist man had the business, and the Friend had to look to him for it.
I asked the Elder how he knew that?
He said it was all proved by the two Methodists.
I asked if they had no other evidence?
He answered, No. I asked what they stated, and he told me.
I then asked what the Friend stated; he told me.
I asked if the Friend had no evidence?
He said, yes, one, and said he had another, but does not produce him, or tell who he is,
and by such kind of equivocation and lying, he deceives many Friends,
and we cannot disown him.
I am glad thou hast got home.
I hope thou wilt help us.

By this time I felt poorly.
I began to see how the situation of affairs stood.
I then looked on the Elder, and remarked,
that the Baptist had no more business with it than he, or any other man;
that the Friend had stated the truth, and his witness had stated the truth,
and that those men had falsely sworn money into their own pockets,
for they were the men who employed the Friend, and the money was due from them;
for I was the other witness, and there were no others by, when the agreement was made,
but myself and the other witness, excepting the parties.
The Elder looked at me with a stern countenance, and with a strong voice, said, "`Joseph,
do thou never tell this again, for thou art now in unity with Friends,
and if thou tell this, thou wilt lose thy unity with Friends and never travel any more.`"
I replied,
what didst thou ever see in me to make thee think that the fear of man
could induce me to withhold the truth in a case of suffering innocence.
No, Friend, if I am called on in this case I shall tell the truth before any tribunal.
At this answer he seemed offended and left me;
but when I came to the Monthly Meeting I found it
in such a state as I never saw a meeting in before.

When this subject came before the meeting, I requested to have it lie over one month,
that I might have an opportunity to see the committee,
and those who had acted in the case, together with the Friend,
which was strongly objected to by the Elder, and several others, and he,
in a taunting manner held up,
that public Friends had no business to meddle with discipline,
neither with contention between members in any case, and gave me a severe reprimand.
This grated my feelings, and I returned a warm reply,
which silenced him and his abettors, but this did not do the meeting or me any good.
I had to suffer for it, but the meeting laid the business over.
Yet I was not allowed the opportunity I requested.
This so tried my feelings that a little before the next Monthly Meeting,
I took my horse and went away, to be absent at that time,
but I there being so many dissatisfied, the meeting put it over again.

This brought them to, and when I came to open all I knew,
and give the business a fair statement, and show them what could be supported,
a number of them who had been drawn into a party, backed out,
which so far started them that they proposed a trial for settlement.
I advised the Friend to ease away all he could consistently, and after several hours,
it was brought to a settlement, all persons excepting one member,
agreed that they would be satisfied;
although the Friend did not obtain his right as he ought.
But when the monthly meeting came, the committee would not report,
though they were present at the settlement, and all agreed to it but one.
In this way it was continued for several months.
The meeting grew uneasy, took the business up,
and appointed a second committee to call on the first,
and find their reasons for not complying with the meeting`'s directions;
also to search into the business and report.
The latter committee attended strictly to directions, and reported,
(two of the former committee uniting with them),
that they were satisfied with what the Friend had done.
The other two reported they had visited him to no satisfaction;
but the meeting chose to receive the report of the second committee,
and put an end to the business.
This so vexed them, that they pursued him and others,
who were disposed to maintain discipline, as it ought to be, that they kept murmuring,
and complaining against discipline,
and would spiritualize it into any meaning they wanted,
and in this way they disordered our meeting at times for twenty years.

At length there was a difficulty between two Friends, in a neighboring meeting.
The case came to the Quarterly Meeting, where a committee of seven was appointed,
of which I was one.
We agreed to pay no attention to reports,
or parties but to go into the merits of the case by proof,
and we kept to it with a steady eye, to close the business with truth and justice,
and let each party make the best defense they could by proof.
The Friend who had been harrassed so much in our Monthly Meeting,
was the first who was brought on for a witness in this case.
His testimony appeared clear and correct, but was denied by one,
until it was confirmed by several of the first characters; then he gave it up,
and owned that the testimony was truth.
Of course, judgment went against him.
This offended some of his party so much,
that they advised their fellow to refuse compliance, and accordingly he did so.

There being a committee appointed by the Yearly Meeting, to visit the Monthly Meetings,
and labor for the support of discipline,
they came while things were in this unsettled state.
They did not go into the merits of the difficulty,
but insisted that all should be dropped where it was, and be at peace.
I told them that would not do, for there was a company that always had been contentious,
and sought to hurt those who were concerned to support discipline;
but they would not believe me, and quashed the business until they got out of sight.
It was but a short time before the person, failing in all his attacks,
got another member to join with him.
They persuaded a Methodist to enter a complaint for
perjury against the first witness in the above case,
and that they would support it.
They prevailed with him and attested enough to obtain an indictment.
It went into the Court, and was not decided for more than two years, and there,
in the Supreme Court, the Friend brought on his witnesses, and I being one of them,
gave good attention.

I heard these two members whose testimonies obtained the indictment, and one more member,
come forward and give in testimony to support the indictment,
under affirmation as false as false could be.
Then there were five other members called up, who felt it our duty to tell the truth.
This led to expose the whole business, before a great body of people.
The Friend was cleared by public proclamation.
There were others standing by who could witness what the five testified,
but the Judge would have no more witnesses, and exclaimed,
"`You cannot criminate the prisoner at the bar, and why will you try?
Here are five witnesses of the first character, and we know them, and they agree;
they tell one thing, and neither two of you agree;`" then exclaimed,
"`Monstrous! there is a monstrous mistake made by some of you.`"
I have given the particulars,
finding some of that class had reported that the indictment was never fairly tried,
which is entirely false,
except that the Friend indicted was stopped from bringing all his witnesses,
and they brought all they had.
This decision very much put a stop to the libertine class,
and we had much more peaceable times.

I shall now relate some of the conduct and events that followed
the two overseers who carried in the complaint against the Friend.
They both were men in good circumstances as to a living, and one a thriving man;
but soon after they took their stand they began to go down,
and in a few years became very poor, and every way they seemed to be blasted,
and at last were both disowned.
Their families are gone from Friends also,
and parents and children are gone from good living, and good credit, to poverty and want,
and have taken their rank amongst the libertine rabble of the world.
I note these events, my children, for your instruction, knowing them to be true,
in hopes they will be precepts to guard you from being drawn into a fixed belief,
by hearing one side, either against, or in favor of a person, or cause,
until you know the truth to the bottom, and see what justice and truth are; then,
abide by that standard, without fearing man;
then you will always have the Lord on your side, who will uphold the innocent,
and rebuke the guilty; as I have seen in this case, in several instances.

The two before mentioned Methodists, were men of handsome property,
and of good credit in the world; now one of them is as poor, as he well can be,
having become a drunkard, and acknowledges that a blast and a curse,
has followed him ever since, for his conduct to the Friend.
The other who was not so spiteful, but who went hand-in-hand to defraud the Friend,
has run down, and is brought into straitened circumstances;
and things seem continually going against him.
He has confessed that he always knew, that the Friend was wronged.
The Baptist was a man of heavy property, but in a few years was so run,
as to be confined in jail for debt for several years, and died a prisoner,
leaving the most of his family very poor, and his estate deeply in debt.
The libertine class, by out-door complaining, and telling pitiful tales,
affecting grief with sanctimonious countenances, drew in many honest-hearted Friends,
to their own hurt.

This they did at home and abroad,
while the upright felt bound not to tattle or speak evil of any;
and it appeared the libertines thought they had a great advantage;
and they made use of it; but it all failed them.
The truth at last had the victory.
Those who were drawn in, fared with the rest.
There was one who had a fine gift in the ministry, very acceptable to his friends;
but when he sallied off with the contentious, his gift dwindled away, and ceased to be;
and he became a poor, sleepy, thing, appearing like the heath in the desert.
So we may see that being deceived will not excuse us; for the God of all grace,
gives a sufficient measure of Light and Truth, which if kept to, with a single eye,
will preserve us from all deception, and enable to see it, and through it,
and will bind the mind to the law, and testimony, of the Spirit of Life;
where He sustaineth those who put their whole trust in him,
even when the mighty billows pass over the head, can my soul truly say.

Here I close this disagreeable account, having lived to see the rise,
progress and fall of those who arose against truth and order.
I now have to acknowledge, that it was of the Lord`'s mercies,
who upheld and sustained His little ones, through all this fiery trial.
Blessed be His holy name, and exalted be His power and goodness over all forevermore.

In the year 1804 I felt drawings of Gospel love,
to visit the scattered Friends and others,
in the eastern parts of my own Quarterly Meeting.
I obtained the unity of my Friends, and attended the Quarterly Meeting in the 11th month,
at Danby; went from there to Easton, and attended their Monthly Meeting;
the day following I was at Saratoga Monthly Meeting, where I had to bear a close,
searching testimony,
found things much out of order and a great want of love and good will among them.
The next first-day I was at Galway Meeting.
It was large and favored with the over-shadowings of good.

On second-day I attended their Monthly Meeting where
I found it my place to be a silent preacher.
This sometimes is better for the people than words.
Third-day, I had an appointed meeting at Upper Greenfield,
where I had to exhort the people in moving language,
to be faithful to the knowledge already received,
as the only way to grow in grace and in the saving knowledge of the Lord.
That evening I had a meeting at the house of Israel Kelsey, a few miles from Friends;
a crowded meeting and favored time.
The next, I was at Queensbury, and fell in with Asa Smith, on the same route.
After making our visit here, we went to Chester; where there are a few Friends,
and had a meeting with them, also two,
among a company of rigid Baptists in that part of the country.
It was heavy getting along with them.
We took our departure, and went to Granville, by the way of Queensbury;
were at Granville Preparative Meeting, where I saw no room to preach to them,
neither did Asa communicate much; it seemed a closed up, suffering time.

From here we went to Danby, were at their Monthly Meeting.
Here we were nearly united in close, plain labor, with a people much like some formerly,
who believed they were rich and lacked nothing; wise and able to judge those,
who were of the synagogue of Satan, when in truth,
they were so in the spirit of the world, and pursuit of its riches,
that they knew not how they were blinded, or how naked they appeared,
in the sight of the Searcher of all hearts;
or that they had fallen from their first love; therefore,
they were not willing to part with their possessions,
to buy soft raiment or gold tried in the furnace, that they might be rich.
Though the exercise and labor were painful, and deep sorrow was our lot;
yet good was the Lord, who gave strength to labor, so as to feel clear of them,
and the evidence of "`well done`" was felt.

First day, the 2nd of 12th month, we had a meeting near the Creek;
many came to it not of our Society, and many young people.
The Lord had compassion on them; He brake the bread, and fed them to the full.
Oh, that they would gather up the fragments, and let nothing be lost.
On second day, we rode to Mount Holly, and third day,
visited the families of that little meeting.
On fourth day we attended the meeting there, the well-springs of life were low,
and sorrow was our bitter meat at this place, on the account of unfaithfulness;
we were grieved, as it was a stumbling block to others.
Here our labors together closed, Asa feeling easy to go home,
we parted in mutual friendship on the sixth of the 12th month.
I went for Weston, and got there in the evening;
stopped and had a small meeting at Land Grove, and another at Weston;
in both ability was given to do the work of the day.

9th and first of the week, we had a meeting in Derry, at the house of Samuel Arnold,
who was a well-behaved man, and entertained us kindly.
The meeting was large--the people sat soberly--gave good attention,
and appeared to be well satisfied.
The evening following, I had a meeting near Andover,
amongst a people who sought to get to heaven an easier way than by the Cross of Christ;
preferring ease, to faithfulness to known duty.
I had to proclaim the notable day of the Lord, which would shake all false rests,
and search out all false coverings.
The next, we went to Ludlow,
and had a meeting at the house of a family by the name of Havens.
It was not large, yet it was a favored meeting, and much rejoiced some tender,
seeking minds.
The Friend, who had been with me several days, left me,
and Anthony Nichols took his place.
I was glad of his company.
We went to Hanover and got to John Williams`' on the 12th. 13th,
we had a large meeting in the neighborhood; the people were civil,
and the Lord gave strength for the day, and utterance for the time.
I was enabled to bear a clear, faithful testimony, to and for the Truth,
amongst a mixed multitude.
The meeting ended quietly, and the people retired with a sober countenance.
The 14th we rode to Stafford, and went to Alexander Presson`'s. 15th,
we had a meeting in that neighborhood.

On first day, the 16th, we had a meeting at Timothy Blake`'s. In both the above meetings,
close, plain labor, was my lot,
amongst a people who had known better days than they now enjoy.
In the evening we had a meeting at Preserved Taft`'s. It was full and richly
favored with a renewed and tendering visitation to the people of that place.
Oh! may it not be like the early dew, that soon passes away.
17th, we had a meeting at Matthew Herrinton`'s. More people came in than I expected,
it being a windy day, and the snow flew much.
This was a season of mourning.
There had once been a Friend`'s Meeting kept in these parts, in a hopeful state;
but they not being enough on their guard, got into contention, and their meeting dropped.
The old fire had not yet gone out.
I had to labor close and plain with them; cleared my mind and felt well relieved.
18th, parted with Anthony Nichols, in good unity, he wanting to go home.
19th, I started with Timothy Blake, for Charleston, in New Hampshire,
to answer a request of George Churchman,
and with one day`'s search found all that could be found, of what he wanted,
and sent it to him.
21st, we returned to John Williams`', in Hanover.

22nd we had a meeting near the College, at the house of Ezekiel Baldwin.
To it came a number who were high in their feelings, and full of high notions.
This brought deep exercise over my mind,
until the Lord of Hosts was pleased to send forth his word with power,
and his Truth in clearness, which made its way and prevailed.
Their partition walls gave way; their high feelings came down, and Truth reigned,
to the praise of the name of the Most High.
First day, the 23rd, I had a meeting in the East part of Hanover,
and a number of seeking people came to it.
I felt the Gospel to flow to them, and it settled on them as the dew,
to the tendering of many minds.
May the Lord bless the favor of the day to them,
and hold them as in the hollow of His hand.

24th, we returned to Timothy Blake`'s. 25th, had a meeting at Benjamin Folsom`'s,
in Tunbridge, where, after having a favored, solid meeting, and closed the same,
they being what is called New Lights, went into their manner of worship,
for several hours.
They soon destroyed all the precious life that had been felt in the meeting before.
It being evening, I had nowhere else to go, and had to stay, see and hear it all.
They kept the noise agoing until they wearied themselves.
They then went off by one and two, and tapered of until there were none left.
I had some discourse with Folsom on the subject, but he insisted it was perfectly right.
I had a wearisome night, and was glad when morning came.
I pitied them, and left them.
26th, I rode to Ezra Sleeper`'s, in Corinth, and had a large,
favored meeting at his house.
The power of the Lord was felt to be over all.
27th, had another meeting in Corinth.
It was also large, and a favored, humbling time.
28th, I had a meeting at Chelsea, and had the company of the high and gay.
I had to come to close, plain work, and was strengthened through Divine Mercy,
to perform the service of the day, to the relief and peace of my mind.
29th, I rode to Montpelier.
First day, the 13th, attended that meeting, in which I had close labor,
and felt well satisfied.
31st, I had another small meeting in Montpelier;
after that I felt clear to look towards home, where I arrived the 2nd of 1st month, 1805,
and found my family well, to my comfort.

In the year 1806, a prospect opened with weight on my mind,
to visit the meetings of Friends in the south and east parts of our Yearly Meeting.
I opened it in the Monthly Meeting, and had their consent.
The 7th of the 2nd month, I left home, with Nicholas Battey for a companion,
and went to Danby, and on first day, the 9th, sat through the meeting in deep suffering,
with sealed lips.
We had an appointed meeting in the afternoon, in the Valley,
where way opened to get relief.
The comforting presence of the Lord was felt to crown the meeting.
10th, we rode to Easton.
11th, I attended our Select Quarter,
where we had the company of Mary Newbold and Elizabeth Coleman,
two goodly ministers from Burlington, New Jersey.
We had a favored Quarterly Meeting, and from it I went to White Creek,
and on the 14th had a laborious meeting there, having to encounter ease,
and a worldly spirit I was mercifully helped to relieve my mind,
so as to feel satisfied.

On the 15th, we rode to Adams.
16th, we attended their first day meeting, where,
after sitting some length of time under deep exercise, and much strippedness of spirit,
a way opened in Gospel light and life,
to deliver a testimony which much relieved my mind,
and was a comfort and satisfaction to my friends.
We then went to Hancock, where were a few Friends, and on the 17th,
appointed a meeting there, which though not large,
was favored with the owning presence of Israel`'s King.
After it, we went to John Gorton`'s for the night, and found a large family of children,
several grown up.
In the evening, we had a solemn, tendering opportunity in the family,
much to the satisfaction of the parents, and sweet peace of my mind.
18th, we passed on to New Britain, having John Gorton for our pilot.
This was a large meeting.
19th, we had a meeting at Clinakiln, which was also large.
In both these meetings, I had painful labor,
there being much of a worldly spirit and self-confidence
among Friends--states hard to touch.
I passed from them with a heavy heart.

21st, we had a meeting in Hudson, which was a large gathering,
and a deeply exercising time,
it being the place where Hannah Barnard had sown much of her infidel seed,
so that there was great coolness in the minds of many;
yet they would come to meetings when strangers passed along.
Through Divine Goodness, ability was given to bear a faithful testimony,
which gave me full relief.
On the 22nd, we traveled to Little Nine Partners.
First day, the 23rd, we attended that meeting.
24th, we had a meeting at Stanford.
25th, we had a meeting at the Creek--my native place, 26th, had a meeting at Crumb Elbow.
From there we went to Poughkeepsie, and had a satisfactory meeting in the town.
In the above meetings heart searching exercise was much my lot,
for a worldly spirit and a state of ease had got so much the ascendency in many minds,
that it was trying to my feelings to be faithful to the openings of my gift;
but in faithfulness, I found great peace.
I had now and then to drop the language of encouragement, to the honest and upright;
this was pleasant.
We had a meeting in Pleasant Valley, a comfortable time, the meeting ended sweetly.
The 1st of 3rd month, we had a meeting at the West Branch, Oswego.
First day, the 2nd, we attended Nine Partners meeting,
where I had to come to plain work amongst the great ones, and had peace in obedience.
On 2nd day, we had a meeting at Old Oswego, and the day following at Apoquague.
Here I had to see the ways of Zion mourn, and to mourn with her,
in seeing her walls trodden down,
by some who ought to have been repairers of her breaches.

We were next at the Ridge meeting.
From there we went to the Little meeting, West Branch, Oblong,
and proceeded to West Hartford, Connecticut, and attended their meeting.
We found them in a tried situation, on account of some who had dissented from them,
and were disposed for clamour.
Not feeling easy to leave, we stayed until after their Monthly Meeting,
and then passed on to New Milford,
got there on the 13th and had a meeting with them on the
14th. There were many present who were not of our society.
It was a time of favor; many minds were tendered,
and brought to remember "`the rock from whence they were hewn,
and the hole of the pit from whence they were digged,`" and to acknowledge to the Truth;
may it prove a time of profitable planting to that people.

15th, we rode to Middlesex, and the 16th, the first of the week, notice being given,
there came in a number of sober countenanced people,
for whom I nearly felt--it being a day of favor--for the inhabitants
of that part of the country are so infested with hireling priests,
that if a little light break forth amongst the people,
they bestir themselves to cast a veil over it, so that it seemed mournful,
and I pitied the people.
17th, we crossed the East River, at Rye Ferry, and went to Stephen Titus`',
and being much unwell, I stopped until after their Monthly Meeting at Westbury,
on the 19th, where, not finding any commission to preach,
I passed the meeting in silence.
20th, we attended Jericho Monthly Meeting, where I had a short, close testimony,
and was well rewarded by my Good Master.
21st, we had a meeting at Matinicock.
Here, having a clear, extensive opening, on a deep subject, I mused on it and put it off,
until I lost the right time and best strength,
and thereby wounded myself and hurt the meeting, and had to suffer deeply for it.

The next meeting was at Cow Neck, and having learned by the things I had suffered,
I endeavored to mind my Master`'s business more attentively,
and was favored to get through the service of the
day to good satisfaction to myself and Friends.
23rd, first day, we were at Flushing,
where it pleased the Master of Israel`'s assemblies to lift up the light of His countenance,
and raise the standard of Truth, and set its dominion over all.
After this meeting, I felt arrested to go into New York City,
and appoint a meeting for second day evening the 24th, at Pearl street meetinghouse.
This brought close exercise, as I never had appointed a meeting in the city;
but seeing no way to turn to the right or left hand, I gave up, went to the city,
and opened my prospect to Friends.
They struggled under it for awhile, and proposed several alterations.
I let them know I could not turn to the right hand or left.
I could give it up and go along, but to alter, I could not.
They did not choose to take the burden off me, so complied with my prospect,
and informed the people.
It was thought that more than two thousand people collected,
and He who required the appointment, furnished with matter,
and gave ability and utterance sufficient for the day; favoring with His holy solemnity,
which covered and crowned the meeting, to the joy of many hearts,
and the satisfaction of Friends in general.
The meeting closed with thanksgiving and praise, to the Most High God,
for His present and past favors,
with an humble prayer for a continuation of His mercies that endure forever.

Third day, the 25th, we rode to Westchester, and stopped with Thomas Walker and wife,
where we found kind reception.
Next day, attended that meeting, and though a stormy day, it was pretty full,
and a favored, satisfactory meeting; after which, we rode to New Rochelle,
and lodged with Joseph Bowne, when we were kindly treated.
27th, we were at Mamaroneck meeting.
Here, finding my mind led into different subjects,
I was thoughtful to close in good season; but after sitting down,
I did not feel that clear quiet which I commonly feel when I time it right;
but being unwilling to rise again,
or kneel--for my mind was arrested with both--I sat until it wore off,
and then broke the meeting.
After I got out, an Elder came and took me by the hand and said, "`Joseph,
thou hast been preaching to others to be faithful to their gifts;
hast thou been faithful to thine?
I confess I did not expect the meeting to end so,`" and turned away.
Though I did not expect to be found out in that way,
I was glad to meet with such honesty from the Friend.

We went on to Harrison`'s Purchase, where we stopped until first day;
we attended that meeting, according to prospect,
and had another in the evening at North Castle.
In both these meetings ability and utterance were given to bear
a faithful testimony against the unlawful love of the world,
the love of ease and carnal security, and I felt comforted in the quiet I enjoyed.
The next meeting was at Shapaqua.
Here I had to put on my mourning garment, and call on the Ministers of the Lord,
to weep between the porch and the altar.
The day following, we were at Croton Valley.
Here we had a comfortable meeting, with a little company of well concerned Friends.
We passed from this to Amawalk, where we had a serious, good meeting,
and then went to Cortland`'s Manor, near the mouth of Croton,
and had a meeting there to good satisfaction.
We passed on to Peekskill, and had a meeting in the evening,
where I remembered the apostle, who felt a necessity to labor in weakness and fear.
After this, we went to West Point, and crossed the river and mountains to Cornwall,
to see my aged friend, David Sands,
who had lately returned from a long religious visit in Europe.
We found him cheerful, enjoying the rich sheaves of a well gathered harvest.

While here, I felt arrested to have a meeting at Newburgh.
It kept with me with weight, and I saw no better way than to open it to Friends,
who seemed not opposed to it.
It was agreed on; we set out with a young friend to pilot and assist us.
After we got into the road, it was shown me, in great clearness,
that the offering was accepted--the will was fully taken for the
deed--and I was at liberty to go home--a joyful release.
We dismissed the young man and went forward for home, and made no stop except for rest,
etc., until we got to Troy,
where we stopped to their first day meeting--to me a refreshing time,
the living presence of the Lamb of God was felt to be in the midst,
sweetly giving strength for every good word and work.
I being unwell, and the weather unfavorable, we got no farther than Granville by 4th day.
We stopped and attended that meeting.
In it I had satisfactory service.
This was the last meeting we attended in this journey.

From here we went direct home; got there the 18th of the 4th month,
and found my family well, and glad to see me return.
On the 7th of 5th month, 1807, I set out to perform a visit to Friends of Upper Canada,
and Farmington Quarter, in company with Valentine Meader, (my son-in-law),
and Nathaniel Austin.
We went to Peru on seventh day, and attended that meeting on first day, the 8th. 9th,
we had a meeting in the town of Jay, about twenty miles up the river Au Sable.
10th, we had a meeting on the west branch of said river; both of them small meetings,
amongst a careless, easy people, who cared very little about religion;
so that it seemed like beating the wind, to preach to them.
11th, we had a meeting in Chesterfield, to good satisfaction; the people were attentive,
open and tender.
12th, we attended meeting at Peru again, where I had extensive labor,
and was much relieved in mind.
In the afternoon, we had a favored, satisfactory meeting,
two or three miles north of Friend`'s meetinghouse.

On the 13th we set forward for Upper Canada,
traveled seventy miles through a wilderness almost without inhabitants,
the road new and miry, so that it took us two days and a half to gain Salmon River,
where there is a newish settlement, mostly Scotch,
and finding no way to cross the river St. Lawrence until second day, the 16th,
we lay at one Comon`'s, who went with us across the river,
and landed us in Charlottebury.
We rode eight miles and took dinner in Camwell,
and on the 17th and 18th traveled to Elizabethtown,
stayed with Matthew Howard for the night, and were kindly entertained.
We had a meeting in this settlement.
The people were civil and quite attentive, and appeared well satisfied;
thence to Gershom Wing`'s, (a Friend), twelve miles ride, where we had another meeting.
It was a favored, tendering time.
May the hand of the Lord be over that people for good!

After this we journeyed through a long wilderness for Kingston; the weather being rainy,
and the roads new, we, and the horses were much fatigued,
but were favored to get through in good season on the 21st,
and went to the Widow Brewer`'s, in Kingston, where we were kindly received.
First day, 22nd, we attended the little meeting there, which was painful,
on account of the want of true zeal and faithful obedience
to the knowledge already received by some of their members.
I had to come to plain work, and found peace in being faithful.
Not feeling clear, I appointed another meeting at the 4th hour in the afternoon,
at the same place, which was trying to an hair`'s breadth.
The people being uneasy and restless, it seemed hard getting into the quiet,
or a suitable preparation either for worship or service.
Thus tried, I sighed to the Lord, and breathed in the groanings of spirit,
that He would arise for the help of the needy, and order the battle of the day.
He was pleased to still the bustle in a marvelous manner,
and open the spring of life in the needful time,
so that the testimony of Truth went forth in clearness and living authority,
to the breaking down of the strongholds of opposition for that time.
Blessed be the mighty power of the Lord forevermore!

23rd, we rode to Adolphus town,
and went to John Dorlan`'s--an old friend of my father`'s--where we were cordially received.
24th, had a meeting with Friends there.
Next day, we attended their usual meeting, with them,
and in the afternoon had a meeting with those not of our Society.
We next had a meeting across the Point, in the Courthouse.
In both those meetings the people were sober and attentive,
and parted with us respectfully.
From here, we crossed the Bay to a settlement of Friends at Ameliasburg,
where we had a large, favored meeting, for the place, and I passed on cheerfully.
Seventh day, we rode to Westlake, and put up at a Friend`'s house.
There soon came in a number of people.
I felt that I could not stay in the house in peace.
The sun was all of two hours high when I walked into the woods,
and did not return until after dark, when I found the house clear of the company.

The next day, at their meeting,
I was led in the course of my testimony to take up the subject
of high professors taking advantage of the necessities of the poor,
to screw them down, and grind the face of the needy.
I was led to make some close remarks on the subject; but not feeling clear of the place,
we appointed a meeting in the afternoon, and to it abundance of people came.
I had to take up the subject at large,
and show that the rich had it in their power to wipe the tear from the widow`'s eye,
and make the fatherless rejoice, and their hearts bless them;
that the honest and industrious poor ought to be helped.
This would be acting as Ministers of the Lord to the poor.
But when the rich took the advantage of the poor,
to increase their boards of shining ore, they made the poor to sigh, the widow to weep,
and the fatherless to cry for want; thus adding grief to sorrow,
and vexation to those already in trouble; so that in vain is the profession of such.
The Lord will have no respect to your offering,
until you can stretch out your hands to the poor, to relieve the agonies of woe.
The word of Truth went forth in that authority, that all opposition fell before it;
the meeting became very much broken into tenderness of heart,
and many to weeping--a solemn, humbling time.
May the Lord bless it to the people, to the praise of His own name!

After we left there, I was informed by my company,
that those who gathered at the house where we first went,
came there on account of an arbitration between a rich Friend and a poor man.
They sat by and heard the investigation,
and it was made to appear that the Friend had taken unjust advantage of him several ways,
and screwed him down unmercifully; that when the award was brought in,
the Friend refused compliance, and went off offended.
This took place while I was in the woods.
Both parties were at the meetings,
and they heard the Friend came forward the next day pliably, and was willing to settle:
I had reason to hope that some good was done, and I had in humility,
to admire the tender care of the Lord, in leading me into the forest, solitary and alone,
so that I heard nothing of it until I got clear from them.
I have often found it good to adhere to impressions felt,
though at the time I knew not for why or what.

30th, second day, we set forward to Yonge street,
rode about forty miles through woods and mire, and weary enough when night came.
We put up with Joseph Keeler, a friendly man--his wife a member.
Here we had a meeting in the afternoon, which was to our comfort,
so that we were glad we were here.
We passed from here to Whitby, forty miles, and reached Russel Hoag`'s, a kinsman of mine.
He was educated a Friend, and his wife a Baptist;
each closely attached to their education, so that it made hard work in their family,
they having a number of children.
They both earnestly endeavored to get as many as they could to go with each of them,
so that I pitied the children.
The parents brought this dilemma upon themselves,
and it was but just that they should feel the rod of their own choosing.
The 3rd of 6th month, we had a meeting at his house,
amongst a people settled at ease on couches of their own choosing,
off of which they seemed determined not to be moved.
To preach to them seemed to make no more entry to many minds than water poured on a rock.
I parted with my kinsman with a heavy heart, who feels the weight of his situation,
and none in that place to unbosom his grief to, so that his trials are deep,
and afflictions great; but it is the reward of his own conduct.

From here, we went to Timothy Roger`'s, at Duffin`'s Creek, eight miles,
who seemed rejoiced to see us.
A few years before this, he had moved from my neighborhood.
We tarried with him one night, and I was glad to see him so comfortably settled.
We took a solid parting opportunity with the family, and went on to Asa Randall`'s,
at Whitchurch, the 4th. First day, 5th, we attended Friends`' meeting in that town,
and appointed another in the afternoon at the same house, which was large,
and the minds of the people were open to receive what the Great Master had for them;
and the Lord was pleased to favor with a plentiful
shower that softened and tendered the soil,
and revived the tender plants.
Second day, we rode to Yonge street, and went to Jacob Winn`'s, another Friend,
who had moved from my country.
He and family seemed much joyed to see us.
Third day, we went to Ephraim Dunham`'s, (my brother-in-law), in Queen street settlement,
where we had a large, favored meeting.

The Truth went forth like a sword, that divided between the precious and the vile,
and reigned over all wrong that day to the honor of the cause of Truth,
and I hope to the praise of the Most High God.
8th, we attended the Preparative meeting, at Yonge street.
Notice being given, the meeting was large.
I was led into a close, searching line of testimony.
I felt the Truth to prevail, and its authority to rise in dominion over all opposition,
to the great joy of my heart, and the comfort of many honest minds.
Magnified be the name of the Lord,
who abundantly giveth strength sufficient for the day! 10th, we rode to Uxbridge,
a long stretch through the woods, and had a meeting with a few Friends there.
It was a tendering, comfortable opportunity.
11th, we returned to Yonge street.
First day, the 12th, we attended Whitchurch meeting.
Here I was led into a painful exercise, being deeply distressed,
and saw no way to get relief but to tell Friends how I felt,
and how it appeared to me it was with them, and how it came to be so,
and what they had to do to get into a better state, though it was much in the cross.
I was finally relieved, and after meeting, felt my cup to overflow with peace, as a river.
I was told by a Friend of that meeting, that I had twitted them of facts,
and that it was so; for they had been in a sad quarrel,
and he hoped it would do them good.

Second day, the 13th, we attended an appointed meeting, at Queen street for Sarah Pope,
of Jersey, and Gulielma Widdifield, of Philadelphia--a good meeting.
14th, we had a meeting in the south part of Uxbridge, it was small.
Being election day, many of the men were gone.
We had a fine company of women, and a favored, tendering time.
The meeting closed under a sweet solemnity.
15th and 16th, attended Yonge street Monthly Meeting; abundance of people came to it.
After sitting awhile in this meeting, under a close, lively exercise,
I felt a clear opening, and lively motion to rise on my feet,
and when I had opened my subject, it was all taken from me.
I stood a little, then sat down,
and felt great peace in being resigned to the Lord`'s will.
The people were much disappointed; but the women had good service.
In the last meeting my bow was well strung,
and I returned from the field of labor well rewarded.

17th, we rode to Humber, where I met with my wife`'s sister, Elizabeth,
who I had not seen for nine years.
Here being taken sick, I stopped one day.
First day, 19th, I parted with the family, with an exceeding heavy heart,
and rode forty-three miles.
The roads were generally muddy; the country being new,
we had deep mud holes to plunge through.
We arrived at the Government house at the head of Lake Ontario, where we stayed all night.
20th, we got into Pelham; 21st, this morning, parted with our southern friends,
and next day attended meeting there.
It was a crowded one, and much of mixed multitude.
Here, my son-in-law bore the most able testimony, I thought,
that I had ever heard from him.
I had to follow on, and the Lord was good,
and clothed with strength sufficient for the day,
furnished with matter and utterance equal to the occasion,
and raised the Truth in dominion,
and exalted the standard of righteousness to our great joy,
and to the honor of His holy and ever adorable name.

23rd, we attended a little meeting at William Showell`'s. Here I was shut up in silence.
At the close of the meeting I thought I felt it best to remark, that it was they,
and they only, who waited on the Lord, that renewed their strength;
and it appeared to me,
that if the people then gathered had waited as intently
on the Lord as they had on an inferior object,
no doubt we should have had a fine, precious meeting.
I felt well satisfied in making the remark.
After meeting I felt easy to go on to attend an appointment in Cowland,
where a number of sober looking people came together.
Here the well-springs of the Gospel were opened, and its waters ran freely, forcibly,
and made its way in the dry and parched, as well as other kind of soil,
and abundantly refreshed the tender plants--a day of favor to the people.
May it be remembered with thanksgiving and wisely improved!
Seventh day, we visited Niagara Falls, a great curiosity of nature.
From this, we went to Black Creek, attended that meeting on first day,
the 26th. It was large, and a renewed visitation of the Lord witnessed.
Oh! that the people would improve their favors.

27th, we crossed the Niagara river at Black Rock, into the States,
and traveled through Buffalo Indian settlement--a
beautiful tract of land--the Indians were very kind.
Finding their crooked paths puzzled us,
they sent one to pilot us to the few Friends who had settled a few miles from them.
With these Friends, the 28th, we had a favored, and to us a refreshing meeting.
29th, we rode thirty miles, mostly in a wilderness, through good land.
30th, we continued our wilderness travel twenty-eight miles.
The 1st of 7th month, we came to Abraham Lapham`'s;
we got a little refreshment and went to Caleb Macomber`'s
where we stopped and got some rest,
for we and our horses were much fatigued.
2nd of the month we had a meeting at Asa Aldrich`'s, in Palmyra--a laborious,
exercising meeting.
I was led to show that one fault-mender was worth many fault-finders,
as none could mend a fault, but those who committed the fault,
and while people were looking up others faults, they certainly neglected their own.

I had to come to plain work, and felt quite comfortable after it.
First day, 3rd, we attended Farmington meeting; this was also a tribulating time to me.
I was led to address the backsliders, who wanted to be esteemed, and like Adam,
were hidden under a fig-leaf covering; showing them, that would not do,
as also the eagle-eyed,
to spy out others faults for an excuse for the neglect of their own duties,
showing them the neglect of duty was wrong, and doing wrong was the neglect of duty;
and while they were condemning others, they were acting like them,
and ranking themselves in range with those they despised.
This was not wise.
I was enabled to open these points close and plain, to the relief of my mind.
Near the close of this meeting, I felt drawings towards the youth,
and appointed a meeting the 4th hour, the same afternoon.
Many came to it, and He that declared Himself to be the true Shepherd,
was pleased to be in the midst,
and to break and bless the little with an abundant increase,
so that there was enough and to spare.
And Oh! that the dear youth would gather up the fragments, and let nothing be lost.
4th, being rainy, we lay by; 5th, had a meeting in Bristol, among the Baptists,
who come so armed, that it caused a long silence.
At length my son-in-law felt authorized to tell them that we had not come for battle,
nor to preach any other doctrine, than the grace of our Lord Jesus Christ,
which appeared to all men, by which we are to be saved, if we are saved, and that,
through faith in the gift, and the Giver of it.
This so settled the people that they laid down their arms,
and the way opened for gospel communication, and it flowed freely.
A solemnity came over the meeting, and it ended pleasantly.

From this, we returned to Farmington,
and attended their mid-week meeting on the 7th. To me it was a solemn parting,
feeling my mind drawn into tender sympathy with the honest-hearted of that place.
May the Lord be their helper in every needful time!
In the afternoon we had a meeting at Palmyra,
among a people that was so much in the outward, that it was heavy wading to get along.
The next meeting was at Junius, on the 9th. Here was a small settlement of Friends,
some of them under a good exercise, to whom the language of encouragement flowed freely.
After the meeting, we rode twenty-two miles, to Scipio, and on first day, the 10th,
attended that meeting.
In it I hurt my testimony by making an apology to soften the matter,
and soon discovered I had weakened my hands.
After the meeting an Elder--after making a long apology--remarked to me,
that the Truth did not need an apology,
and he thought a great porch and a little house did not look well;
and if I saw anything in him, he was as willing to receive as to give.
I told him I had nothing, only he had chastised me for an apology in a good work,
and I thought he was in as good a work, and had made as long an apology,
which I thought did not come out right,
for there was no more need in one case than the other.
So we parted, and I hope we both learned a good lesson.
We had another meeting in the afternoon, in which I had close work,
but I took care not to make an apology.
11th, had a meeting at Calvin Tupper`'s, a favored time.

Truth broke in on some minds, like the breaking in of mighty waters.
After it, we rode to Sempronius,
and had a meeting there on the 12th. The people were mostly not Friends.
I sat a long time in this meeting, under such a dark cloud of distress,
that it seemed almost insupportable.
I cried in my agony, "`O Lord! what have I done amiss?
show it to me and purify me,
until I am acceptable in thy sight;`" and in deep prostration of spirit I lay low.
In this condition, a language saluted the ear of my soul, remarkably clear and forcible;
"`How shall the dead be raised--or thou be qualified to
speak feelingly and effectually to their conditions,
if thou art not baptized for the dead, and feel the weight of distress that is on them?
Or how canst thou pray for them fervently,
without feeling their distress and their wants?`"
This was a good, profitable, and instructive time to me.
After passing through this, I felt a lively motion to rise on my feet,
and set forth in a clear, lively manner the tender mercies of the Lord,
in often calling upon, and long waiting upon the children of men,
for their return to Him; also the nature of spiritual worship,
and what qualified therefor,
and the great loss sustained by all who do not believe the Truth and neglect these things.
It was a memorable time to me, and may the Lord be pleased to make it so to the people,
to the everlasting praise of His own name!

13th, we rode to De Ruyter, and had a meeting there on the 14th, to good satisfaction.
15th, we rode to Brothertown, and went to John Dean`'s, an old acquaintance of mine;
we were glad to meet once more.
Friends living very scattered, it was thought best to lay by on the 16th. First day,
17th, we attended their meeting.
It was large for that place.
Several of them came sixteen and eighteen miles to meeting.
It was pleasant being with them,
on account of their lively concern for the testimony of Truth.
We had another meeting in the latter part of the day, with the Indian natives;
we found a very open, cordial reception among them.
18th, we went to Weston,
and had a meeting there on the 19th. Here I was led
to feel much for those who were disposed to halt,
and question the way of Truth, instead of coming up in the pointings of duty,
which they already know, and so avoid the cross of Christ;
and thus deprive themselves of a growth in experience
and knowledge of the mystery of Truth,
and the comfort arising therefrom; thus endangering the loss of the crown.
A sense of these things gave me pain and sorrow of heart, and I felt pity for them.

20th, rode all day.
21st, we got among Friends in Mayfield, and had a meeting with them.
22nd, had another meeting at Abraham Wood`'s. 23rd, was at Northampton,
and had a meeting there.
Not feeling clear of Mayfield, we stopped to their first day meeting, the 24th. Here,
my good Master opened the door of utterance, furnished with matter,
and gave ability fully to clear my mind, so that I felt relieved,
and clear of this part of the country,
where I had to wade under deep exercise from meeting to meeting, with much ardent labor.
To me it was a joyful release, and an humbling, tendering time to the upright in heart.
At 5 o`'clock we had a precious, good meeting at Providence.
25th, we had a meeting at Galway.
Here, I had to call on those who were at ease in Zion,
and couched on their beds of ivory, and to blow the trumpet of alarm amongst them.

From here we went to Ballston,
and all our little company felt very much distressed in coming into the place,
which continued with us.
Third day, we attended that meeting.
General notice being given, there came in many who were not Friends.
We sat silent the usual time of holding a meeting, when I informed the people,
we had requested their attention, and were glad of their company;
that their solid deportment was grateful to our feelings;
but as the Lord had not given anything to communicate,
we felt it not safe to undertake to preach, without His help and direction;
lest we run when we are not sent, and that would not profit the people.
Therefore, we believed it best to be resigned to the Lord`'s will,
who always knows what is best for us, and He would do right.
I then informed the people that I wanted an interview with my Friends,
and if they were willing to retire, it would be grateful to my feelings.
They rose up with pleasant countenances and went out very quietly.
I afterwards heard they were well satisfied.

We had not sat long by ourselves, before I had to address them in this language:
"`In the foregoing meeting, this was presented, and it still remains with me:
'`There is death in the pot, and bitter gourds put therein,
by those whose business it was to provide wholesome food for the needy and sickly;
having no Elisha among you to direct what to do,
nor meal to put into the pot to take away the bitter, neither had it been sought for;
therefore death remains in the pot.`'`" After clearing my mind,
I got away as soon as I could, but felt great satisfaction in being faithful.
A while after, I was informed that there could be nothing more appropriate,
and at that time there was an Elder in that meeting who had so conducted,
as to get the meeting into an unsettled and divided state,
so that their neighbors would not meet with them; and they could do nothing with him,
short of dismissing him from his station, and disowning him from Society.
Then the confusion settled away, and things returned to their former quiet channel.

From here we went to Troy, and attended their fore and afternoon meetings on First-day,
31st. In both, we had good service, and were well accepted by our Friends.
After the last meeting, my master took off the harness,
and showed me that I might go home.
Accordingly, we set out early on second-day morning,
and rode several miles without much discourse.
Observing that Nathaniel and Valentine rode with their heads down,
it came lively into my mind to ride up to Nathaniel
and relate a fable that I had fallen in with;
so I said to Nathaniel, I have concluded to go home like the old jay-bird.
He said, "`What does thee mean?`"
I then remarked, that among the fables,
it was stated that the jay-bird took a feather from every bird,
and plumed herself with them.
Then she was the finest bird in the woods.
At length the birds discovered how it I was; each came, claimed, and took its own feather.
She looked on herself and exclaimed, "`I am the poor old jay-bird.`"
I said, "`I am going home, the old jaybird.
The good Master has harnessed, and plumed us in this journey, and has now taken it off;
therefore it was best for He and I to be contented with it, and go home,
the old jay-bird.
For the Master had a right to do it, being the rightful owner of the plumage,
and now it is best for us to go home and do as well as we can.`"
He replied, "`This will do.
I have thought a good many times since we have been out, feeling what I have,
and seeing so many clear proofs of its being right that we are out in this work,
that I have concluded, if I live to get home, I will live as I ought,
and do better than I ever have done.
But since leaving Troy, I have felt so poor and stripped, I did not know what to think.`"
I then remarked,
that "`Mordecai did not give out after riding the
king`'s horse because the royal robe was taken off,
but quietly went and put on his sackcloth, and waited at the king`'s gate;
and by that means was found worthy to be promoted to greater honor.
And so it might be with him and me, if we did right.`"
The discourse ended, with his concluding to do right; but,
poor man! he has fallen further into the dark than he was before.
We continued on our way homeward, and when arrived there, found all our families well,
to our mutual joy.

After returning home from my long Eastern journey,
I remained about home most of the time for several years,
being often confined with sickness;
yet I made several visits within my own and neighboring Quarterly Meetings.
Of these visits I find no correct minutes.
I have lost the date of the year, and considerable of the minutes of one long journey;
so that I can do no better than relate, what clearly occurs to my memory.
I set out late in the Fall of the year; went to Queensbury, took that meeting, Saratoga,
Milton, Greenfield, Galway, and several other meetings.
From this part I went to Cherry Valley, with having, I think,
one or two meetings on the way.
From Cherry Valley, we commenced having meetings for the most part,
as often as one a day, for, I think, two months;
and having got into the edge of Pennsylvania, and almost beyond civilization,
I felt easy to turn about.
In this part of the visit, we met with great openness, and kind reception with the people.

On our return to the older settlements,
we stopped at a tavern where two men had just entered
into a warm dispute relative to the Indians.
They ran so high in argument, that one asserted they were savages,
and ought to be cut off from the face of the earth; that they were worse than the beasts,
and had no souls.
The other argued that they were of the human family,
possessing all the feelings of sensibility that we have,
and that they were as capable of being improved as we were.
When they had tired themselves, they turned to a plain, genteel looking man,
and asked his opinion on the subject, who answered thus:
"`There has lately been a missionary out on a visit to a tribe of Indians,
that never had been visited by a Christian minister before,
who preached to them four times.
At length, he took up the subject of the conception, birth, life, miracles, ministry,
crucifixion, resurrection, and ascension of our Savior, in one sermon.
He stated that all his other sermons were well received; but,
after this meeting--as is their universal custom when they
hear preaching they do not understand or believe,
they call a council, and agree what answer to give the minister,
and if they do not approve, they hear him no more--they called a council,
but could not altogether agree in belief;
so they put it on one of their chief speakers to give the minister an answer.

The Indian said, '`Well, then me go into the woods,`' and retired about four hours.
When he returned, the Indians gathered about him, and said, '`Well,
what you think?`' He replied, '`O, minister preach true, certain.`' One exclaimed,
'`Minister no preach true; a man hang up till he is dead, a great hole cut in his side,
all the blood, all the water run out; he no live certain.`' Then the chief speaker began.
Now you hear me; me tell you.
The Great Spirit speak all things; He make all the people; they all His children;
He love them all; He tell them to love one another, and do good to one another.
But some of His children, by and by, grow bad; they quarrel; they cheat; they tell lies;
they make some of the rest of his children do bad.
The Great Spirit see it; He sorry; He speak to them; they no mind Him;
He speak to them again; they no mind Him.
He see they grow very wicked; He much sorry; then Great Spirit think, think, think.
He say, '`Well, Me send my son; they mind Him.`' He know his son must have body,
or they no see Him.
He look all over among the women; He see one very good woman, purer than all the rest.
Now you hear; you mark and remember; the Great Spirit speak a body in that woman.
When that body came into the world, and grow big enough,
He fill that body full of He-self.
That His son.
Now you hear, mark well, remember.
You know the Great Spirit speak all things; He speak cold weather;
that may come great deal snow, great deal ice.
No snow, no ice in warm weather; all water then.
So Great Spirit speak warm weather again; and that make all the snow,
all the ice back to water again.
Now, you remember that me tell you, the Great Spirit send His son; He came;
He do much good; cure the sick; He make blind folks see; He make lame folks walk;
and He make some dead folks live.
His good children much glad, they mind Him; His bad children no mind Him.
He speak to them; He tell them they no mind Him.
He then speak strong, very strong.
That make them very mad.
They get together; they catch Him; they kill Him.
The Great Spirit see it.
The Great Spirit much sorry to see His children so wicked.
Now, you remember; the Great Spirit speak that body; He no lose that body;
He speak that body to life again; He call His son home.
That body, spirit before He came into the world; that body spirit now.
The minister preach true, certain.`'`" Here, he stopped, with this observation: "`Now,
gentlemen, you may judge for yourselves,`" got up and went off.
I was sorry that I had not detained him a little, to know who, and what he was;
but my mind was in such a muse on the subject,
that I did not re-collect myself until he was gone; and I can say no more,
than that he appeared to be a sensible candid man--and was very likely a Methodist Missionary.

From this western travel, we put forward to Brothertown, where we found a few Friends;
some living with the Indians, and had several meetings thereabouts, to good satisfaction.
Then, passed on,
taking all the settlements of Friends on the west
side of the North River as we traveled southward;
having many meetings among those not of our society,
where we met with open doors and kind reception.

In Unadilla, I was attacked by a Presbyterian deacon,
almost as quick as I sat down after speaking, who tried hard to get into an argument.
Thinking there was not much good to be got by it,
I endeavored to bring the business to short, plain work.
After altercating the matter a little, I brought him to agree,
that what could not be proved by Scripture, should be rejected.
He strove to open the subject of unconditional election; but I thought it not best,
as we had had a favored meeting, and the minds of the people appeared sober.
I asked him, "`By what are we to be saved; by works?`"
He answered, "`No.`" I then asked him, "`Are we to be saved by faith alone?`"
He answered, "`No.`" I then asked him, "`By what are we to be saved;
is it by grace through faith, and that not of ourselves?`"
He answered, "`Yes.`"
I then replied, "`The Grace of God that bringeth salvation, the Apostle tells us,
hath appeared unto all men; and remarked, that there are no more in number than all;
therefore there were none overlooked,
and that His grace did not appear as an outward object to the natural eye,
but in man in its own power of manifestation.`"
To this he agreed.
I then replied, "`If it appeared in man, it was certainly put within his reach,
and he could lay hold of it; and thou wilt not deny that the grace of God,
is over all the power of the devil.`"
He answered, "`It is.`"
I then remarked, "`If this is so, as thou acknowledges,
were all mankind to lay hold of this grace, and believe in it,
it would teach them the same thing--to deny all ungodliness, the world`'s lusts,
to live soberly, and to do right in all things.
So thou seest we should all be engaged in the one concern; eyeing the same thing,
and walking by the same rule.
Now, what room would there be for division among the people, or occasion for disputes?`"

This so confused the deacon, that he stood some time silent.
The people all sat quiet, till the subject was brought to a close,
when several spoke to this effect: The stranger reasons fairly; it is good,
sound doctrine, and you ought not to crowd upon him.
Here it ended, and I was truly glad to get through,
without having the people`'s minds jostled,
or drawn from under the solemnity that was over the meeting,
which was the object aimed at, and through mercy, attained.
It is not desirable after a solid meeting,
to get into a discussion upon what has been said,
but many artful sectarians will seek to do it, I have thought,
purposely to divert the attention of the people from what they have heard and felt.

We passed on, having meetings where way opened for it, until we got to Otego;
there was a settlement of Friends.
We had several meetings thereabouts.
At one of them, were people of different persuasions; amongst the rest, a deacon;
and in our company, we had a young woman a preacher, who,
in the early part of the meeting gave us a short, lively discourse.
The deacon arose quickly, and reproved us for suffering a woman to preach.
When he was through, I asked him to be quiet until the meeting ended,
and then we would answer to that.
He remained quiet until near the close of the meeting, when the woman Friend kneeled.
After the prayer ended--in which she was favored--the deacon arose and
tantalized her for presuming to pray when there was a man Minister by,
whose duty it was to do that service.
He laid women very low.
By this time I felt my mind well harnessed for the occasion.
I took up the subject in a calm, pleasant way, beginning with the promises,
and went through the Prophets, Christ being born of a woman,
Christ sending women to preach His resurrection,
Paul`'s recommending Phebe and other women, as fellow-laborers in the Gospel, and lastly,
Paul`'s teaching women how they should behave when they prayed or prophesied.
When the subject was closed,
the people appeared more solid than in any other part of the meeting,
and acknowledged their satisfaction with the reasons and meeting;
so that the Lord disappointed the device of the crafty,
and turned their folly on their own heads.

I think, from here, we passed on to Oakhill, taking meetings on our way.
Thereabouts I felt drawings to have some meetings with those not Friends.
At one of these, their Priest came.
I was led to show, that God, by, and through Jesus Christ,
had provided means in the gift of grace,
and pouring out of His spirit upon the children of men, and to show,
if they believed in it, and walked in it, and through the Spirit,
mortified the deeds of the flesh,
that this Spirit and grace of God would enable them to live without sinning, in word,
thought, or deed; and that this was the perfection we believed in,
and sought to go on to, quoting many of Paul`'s sayings in confirmation;
and I was led to show that Paul, in walking by this rule, overcame the world,
fought the good fight, kept the faith,
and obtained an evidence that there was a crown laid up for him in heaven,
and not for him only, but for all those who love the appearance of the Lord Jesus Christ:
with this I closed.

Their Minister rose quickly, and with a warm tone of voice exclaimed,
that he had labored among them, by night, and by day,
and had gone with his life in his hand, to gather a little flock; and now,
when the wolf came he thought it his duty to come and guard his flock,
and that what they had heard was false, for there never was a man,
who lived a day without committing sin enough to damn him; forgetting,
that by such assertions, he made God unjust.
He carried the matter so far,
as to assert that Paul lived a sinner all his days and died a sinner,
excepting only his hope in the mercy of Christ.
With this assertion he sat down, and I made a few short,
plain remarks on the several points to which he had objected.
I then turned to the people,
and reminded them that I had not come there to invite them to be Quakers,
but to call them to Christ, and to the word of His grace,
which the Apostle said would build us up in the most holy faith,
and give an inheritance among the sanctified; and the people could judge,
if to preach Christ, and to recommend to the word of His grace, was false doctrine;
seeing I had the Apostle with me in sentiment and practice,
and as to the Apostle`'s living and dying a sinner, they might judge; querying,
which knew best--Paul, who had left his experience on record,
or this man who had come into being almost two thousand years afterwards--seeing
there was a flat contradiction between them.
I then sat down and waited a little;
no reply being made I acknowledged the civility of the people, and closed the meeting;
but the hearts of the people were moved; they reprobated their priest`'s conduct,
and urged me to stop and preach for them again;
but I was glad to get away from them as easily as I could,
and could but rejoice that the Lord returned the priest`'s venom on his own head,
and caused it to work more to the settling of the
people in the belief of what they had heard,
than otherwise would have been, had he been peaceable.

I went on, taking Friend`'s meetings,
and had a number with other people on the west side of the Hudson river to New York,
and attended the Yearly Meeting through.
After it I went to West Chester, and, having spent all my pocketmoney,
I concluded I must go home with my prospect unfinished.
At evening a Friend came in where I was, who took me by the hand,
and left a ten dollar bill with me, saying, "`Take it,
thou hast need of it,`" and went out.
I knew I had not told any one my situation, and all excuse being out of the way,
I had to give up, and finish my visit.
After attending West Chester meeting, I went into Connecticut,
and visited all the meetings of Friends in that State, west of the Connecticut river,
and had a number with the Presbyterians and Baptists,
where I found laborious getting along.
They were very much afraid of having their old castle shaken,
but my good Master favored with strength and utterance,
so that when I got through I felt well relieved.
Returning to Nine Partners, I visited several meetings thereabouts,
and took some on my way home, where I arrived after an absence of more than seven months,
found my family and friends generally well,
and felt my mind richly rewarded with the enjoyment of peace.

I have but a part of the account of my next journey, the date being lost,^
footnote:[It appears by the records of his Monthly Meeting,
that he was liberated to perform this visit in the 9th month, 1809.]
and my recollection not retaining the particulars with correctness,
until I was in and about New York, where I met with kind reception.

When on Long Island, after having several meetings with Friends,
I felt forcibly arrested to have several meetings with those not of our society.
This prospect was not favored by the Hickses; though they did not forbid it,
they held back, so that I could get no company or assistance.
I concluded that it was in vain to run against wind and tide,
so turned my attention for home, and rode to Danby, more than two hundred miles,
and there was taken very sick, confined I think, nearly three days,
and thought of calling on a doctor, but my Master told me,
if I would go back through Connecticut and pay up the arrearage of the other visit there,
and go on Long Island, and do His will, He would cure me without a doctor.
I thought of it awhile and promised my Master if He would go with me,
and show me plainly what He wanted, I would go, if it was through fire and water.
In a few hours I was well and able to ride, and turning about rode to Nine Partners,
and took a Friend, a bold man, and went into Connecticut.
Had a meeting or two on the way to West Hartford,
where I called on Thomas Rotch and wife,
and told them I had come back to give up that concern to them to look to.
I had intended when there before, to have a meeting in Hartford town,
but they were so loath I should appoint a meeting there,
that I gave it up and it had remained with me ever since;
now I resigned it to them and Friends of that place.
They would not take it from me, but chose to appoint a meeting.
Thomas and his wife attended it.
After meeting, Friends let me know that if I wanted any more meetings in the town,
the way was open for them.
I informed them I desired not to do anything more than my Master bid me,
nor to run without His command.
I then went to New Milford, and attended Friends`' meeting.
There I parted with my companion, took another Friend,
attended a little meeting in the southwest part of the state,
and taking a Friend from there, went on the Island among those not Friends.
I did not go near Friends until I had got through
all the meetings I wanted with other people.
My great and good Master favored and helped me through all in a wonderful manner.
Honored and adored, forever, be His holy name!

There is one event I think best to note.
The second meeting I appointed, after getting on the Island, was among the Presbyterians,
near their meetinghouse,
in a school house that we obtained liberty to have for the purpose.
Shortly after the people were notified of the appointment,
the priest of that place came to the Inn where I was, and about ten or twelve with him,
and attacked me.
We soon got on the subject of election and reprobation;
he being very full of talk would give but little chance to hear,
and if I attempted to speak, he would break upon me with this assertion,
"`I came to convince you, I can convince you,
and I will convince you,`" and if I mentioned any text of Scripture, he would reply,
"`you could not pick a better text for me,`" and
would go on and put his own construction upon it,
going his round over again, so that I saw it was in vain to attempt to reason with him,
as he was determined to have all the talk.
I sat silent until he had somewhat emptied his fund, and then said,
"`Wilt thou answer me a few plain, simple questions, right to the point?`"
He said, "`I will.`"
I then queried, "`Art thou sound and unshaken in thy own principles?`"
He answered, "`Yes.`"
I then asked if he believed that everything that took place to the smallest iota,
was fore-ordained?
He answered, "`Yes.`"
I then remarked, "`If thou wilt hear me a few minutes,
we will decide this dispute on thy own ground.
If all this is so,
I was fore-ordained to be a Quaker many thousand years before I was born,
and to be just such an one as I am, and to have the disposition I have,
which is to make thy principles look ragged, and I am doing the will of God,
and can do no otherwise,
and thou dost not know but that I am one of the elect for happiness; and this is not all,
if these things are so,
it was fore-ordained that I should come here and appoint a meeting in this place,
and that thou shouldst not like it, but shouldst come here to convince me,
saying thou couldst do it and wouldst;
also that it was fore-ordained that thou shouldst not convince me, for if anything,
I feel stronger in my principles than before,
and of course it was fore-ordained that thou shouldst labor in vain.`"
I then said, "`Is it not just so?`"
He sat mute for awhile.
I again queried, "`Is it not just so?`"
now answer me to the point.
He answered, "`I suppose it is.`"
When this came, his company went out at the door like a flock of sheep,
and he followed them.
Thus I was released, and felt bound gratefully to acknowledge the goodness of the Lord,
in opening a short, plain way to confound their false doctrine,
and silence the boasting tongue.

After getting through this meeting with others to my satisfaction,
I went to Fry Willis`' and released the Friend who had been with me,
as he was desirous to go home.
I rested awhile, then visited the rest of the meetings, and felt at liberty to go home,
not having met with any opposition now, though I went among the Hickses;
they were very smooth to me, so I parted with them, and set forward for home,
after spending near five months away from my family; one month and a half longer,
I think, than I need to have done, if I had not been interrupted.
