== Chapter VI

In the year 1812,
having for a long time had a prospect of a religious visit to Philadelphia Yearly Meeting,
and to the settlements of Friends in the Southern States generally,
and now feeling the concern weightily to increase upon my mind,
I laid it before my friends, and obtained their unity and certificate.

I set out 30th of 10th month, having Weston Macomber for a companion.
Had a meeting at Waybridge, and went to the Quarterly Meeting at Danby;
after the Quarter had a meeting in Dorset, amongst the Presbyterians,
much more favorable than I expected.
First-day, 8th of 11th month, attended meeting at Granville,
which was large and much favored; went next to Easton Quarter, and attended that meeting,
where I had good service; next to Saratoga, and had a large good meeting;
then to Queensbury, and attended that meeting, first-day 15th; from thence to Greenfield,
Milton and Galway, where we attended a Monthly Meeting on the 18th. 19th,
started for Duanesburgh; 20th had a meeting there; 21st, had one at Berne,
and went next to Stanton Hill, and attended a meeting there.
We then set forward and drove seventy-two miles in two days,
and reached Tristam Russell`'s, in Newburg Valley,
and attended their Monthly Meeting next day.

The day following traveled sixteen miles and attended Cornwall Monthly Meeting;
after this, we stopped at Smith`'s Clove, and had a meeting; from thence to Hardwick,
Sussex County, New Jersey, fifty-three miles, arrived on seventh-day evening,
and attended that meeting on first-day, 29th. 30th, we had a meeting at the same house.
Finding my mind clear of that place, 1st of 12th month, we rode to Kingwood; 2nd,
to Buckingham, in Pennsylvania,
and arrived just before their Preparative Meeting broke up.
3rd of the month, we reached Philadelphia, and made our home with Thomas Scattergood.
Having met with an accident by a hurricane, which rent our carriage top to pieces,
we had to stop here to get it repaired, and were detained till first-day.
This crossed my inclination, as I did not want to stop in the city until I returned;
but I had to submit.
When first-day came, I dreaded to go to meeting in Philadelphia, with such great folks;
but my Master soon showed me they were all of the human family,
and were as much dependent on Him, for their life and being, as I was.

This soon calmed my mind, and I had a short, clear testimony to bear,
which was well received by Friends.
This was at the Northern District Meeting.
In the afternoon I attended Arch Street Meeting,
where I had to take up a copious subject, and go through with it.
Thomas Scattergood followed, and united with my testimony.
Thus I found much encouragement, that if I only kept to my Lord and Master`'s direction,
I was safe among every people.
Second-day, having Stephen Mackfield, and John Paul, for our pilots,
we rode thirty-six miles, and lodged with John Pine, in Chester County.
8th, we rode to Columbia on the Susquehanna forty miles.
9th, had a meeting in that town;
after meeting we crossed the river and rode ten miles to Little York.
10th, we had a satisfactory meeting there.
11th, we rode to Gunpowder, and had a meeting there on the 12th; pretty exercising,
on account of many being settled down at ease.
After this meeting we rode to Baltimore, sixteen miles,
and made our home with John +++_______+++, where we were kindly provided for.

Here we had occasion to lay by till fourth-day, when we attended the West Meeting,
and had a meeting, with the youth of that part of the city,
the largest that I ever saw of the kind.
17th, we attended the Old Meeting, in the east part of the city,
and had a meeting with the youth there in the evening; both comfortable, and favored.
This seemed to make up for some of the hard, painful meetings I had passed through,
and renewed my courage.
I noticed at all the meetings in this city, that the people of all descriptions,
even down to little children, sat very still; more so,
than I remember to have observed in all my travels; an evident mark of a good education,
and a wise, prudent care in parents, overseers, and other leading characters of meetings.
My mind becoming settled that it was best to attend to my prospect,
and visit the poor-house, and the state prison, I opened it to Friends,
who made way for it by taking considerable pains.
19th, we had a solid, satisfactory meeting with the invalids;
after meeting we stopped a little, and seeing some without feet, others without hands,
some with parts of limbs gone, and many with scarified faces, I enquired the cause.
I was told that nearly all of it came from their intemperance.
I exclaimed, in my heart, what a spectacle of warning to the rest of mankind,
to take care and not become dupes, and miserable slaves to that unmerciful tyrant,
ardent spirits; truly heart-aching to behold its effects.

20th, first of the week we attended the West Meeting.
In the afternoon we visited the State Prison, and had a meeting with them.
There is a great contrast between this, and the Poor House, many of these,
of bright countenance, and possessed of active minds, capable of being useful,
and doing much good in their generation, confined for their wicked, outrageous conduct,
which rendered them a pest to the human family;
many of these brought to this by attending balls, horse-racing and gambling-houses,
whereby they get stripped of all they have then flee to the tyrant, ardent spirits,
for comfort, which soon dupes them to thieving, forgery, and all manner of evil conduct,
and then to the State Prison.
The consideration of these things bore heavily on my spirits,
but through the tender mercies of the most high God,
I was enabled to clear my mind amongst them in a way that was well received,
though plain to the point.
21st, we had a meeting at evening at the West House, with the people of color;
it was large; they behaved very quietly, as became Christians.
I think they were evidently owned by the Shepherd of Israel; it was a serious,
tendering time, a renewed visitation to that people;
may the Lord make it a blessing to them.

22nd, we went to Elk Ridge, and attended that meeting in course.
There being a marriage it was pretty full, and sometime unsettled,
not at all to my satisfaction, they not giving opportunity to me to clear my mind.
After meeting we drove to the head of South river. 25th, to William Ward`'s;
not far from this stood an old meetinghouse,
once occupied by a large society of Friends, and now left destitute.
I enquired if they had moved away?
I was answered, "`No; the old stock owned abundance of slaves,
and the young ones had fallen off; when the parents died,
there were none to keep the meeting up.`"
This answer was so full, I thought well to notice it,
for although their parents left them rich in this kind of property, their offspring, now,
are generally poor, proud and lazy; a sad entailment--clear evidence that a little,
earned by honest industry, is better than much, otherwise obtained;
in that the latter is blest, and the other blasted, every way.
I could but mourn for their offspring; their countenances looked sour towards Friends.
26th, we rode to the Cliffs, where once was a large body of Friends, and the first,
or nearly the first Yearly Meeting that was held on the Continent,
which was large for many years.
But Friends running much into slavery, and raising their children in idleness,
they have gone from the society,
and many of them now are some of the most cruel slaveholders in that country,
and Friends have ceased to be, over a tract of country that is very beautiful.

In a space of country one hundred and fifty miles in length, and several wide,
much of which was formerly owned by Friends,
there is now but one meeting pretended to be kept up, and that by an old man,
whose children will go to the meetinghouse with him sometimes.
Some of their descendants seem to have a regard for Friends, and mourned their situation.
We had a meeting at the Cliffs, which was heavy,
and heart-aching on account of the two or three Friends
who could not be reconciled to leave the country.
We parted with them, and returned ten miles on our way back.
29th, rode ten miles and attended an appointed meeting in a village called Friendship,
where there was a good sized meetinghouse owned by Friends;
but not a Friend in that part of the country to come to it,
and the inhabitants had filled it with tobacco;
on that account the Methodists offered us their house which was large and accommodating.
To this meeting came abundance of people;
the arm of the Lord was felt to be strong this day.
I had to go into a large field and show the abuse of slavery on the human family,
the pernicious effects on the offspring of slaveholders,
and its open violation of all right in a gospel point of view.

I had not witnessed the power of gospel authority so to
rise in dominion over all opposition for many days.
It was the Lord`'s doing, and the glory is all His.
From this we went to attend an appointed meeting, the 30th, near West River,
where Friends once held their Yearly Meeting for Maryland.
We found it a desolate spot, the meetinghouse almost rotted down,
the graveyard lying common, and briars and bushes growing over the bones of the dead,
and many of the graves rooted down with swine, so that mournful were my feelings,
and heavy was my heart.
I could but exclaim, "`how the earth mourns with a dreary face,
and refuses to smile upon the dead, who marred her beauty by oppression!`"
We had a little meeting there and departed.
31st, we attended Indian Spring Meeting.
1st of 1st month, 1813, we rode to Sandy Spring; 2nd,
we had a meeting with Friends there, wherein my mind was comfortable,
feeling the presence of the Lord was near to uphold
and sustain all those who put their trust in Him.
After this meeting we rode sixteen miles toward Washington,
and lodged with Issachar Schofield.

First-day, the 3rd, we attended the little meeting of Friends in Washington City.
4th, rode to Alexandria, and had a large meeting with Friends and others.
5th, we returned to Washington, in the evening we had a meeting in Georgetown.
6th, we attended the Preparative Meeting in Washington, and after it rode to Alexandria.
7th, attended their mid-week meeting.
8th, we rode to Nathaniel Elicot`'s, at Occoquan, where we had a meeting in the evening,
which was favored;
and holy help was felt to give ability to discharge my duty from day to day,
and to feel sufficient satisfaction therefor.
9th, we traveled thirty-eight miles to Fredericksburgh.
10th, forty miles to Caroline.
11th, we had a meeting in that place; the prospect is, that meeting will run down;
it was small, and but little true gospel life felt amongst them.
12th, we went to Cedar Creek 13th, attended that meeting,
where I had to come to close work, which made my heart ache.

From thence to Jenito, and had a meeting; then returned to Cedar Creek.
15th and 16th, we lay by except visiting the sick and afflicted.
17th, first of the week, we attended Cedar Creek meeting again,
where I had to show the evil effects of those who Lorded over God`'s heritage,
and oppressed the Babe Immortal, in their brethren, Christ`'s little ones;
a solemn day to me.
I felt richly rewarded for being faithful, yet could but mourn for the self-righteous,
important feeling in that land which would not enter the kingdom themselves,
nor suffer others who wanted to enter.
I had to leave them to the Lord.
21st, rode to Wayne Oak.
22nd, we had a meeting there.
23rd, we rode to +++_______+++. 24th, first of the week, we attended that little meeting.
25th, rode back to Wayne Oak, and attended meeting there on the 26th. 27th,
rode to Burleigh, and crossed James River. 28th, we had a meeting with Friends there,
and rode after meeting eight miles to William Hunicot`'s. 29th,
we had a meeting at his house.
30th, we rode ten miles to Petersburg, and had a meeting there the same day,
where my heart was pained to see the droves of human beings driven about like cattle,
and used much worse.

After meeting, we drove to Gravelly Run.
Here was a pretty large, lively meeting, there being a number of well established Friends.
31st, first-day, we attended that meeting to good satisfaction.
1st of 2nd month, we went to Stanton.
2nd, we laid by to give opportunity of notice for future meetings.
3rd, we had a meeting there; after it we rode twelve miles to Samuel Jones`',
and had six miles to ride in the morning.
We had sent a written information of our appointment
to a Friend that was recommended to us,
to be relied upon, but instead of answering our request,
he kept still until the morning that the meeting was to be, at 11 o`'clock;
he then sent it to a poor man who had no horse, who gave what information he could.
When we got there, there were five or six friends, and two or three neighbors,
and the Friend who had neglected our request.
It came so clear before me how it was, that I rose on my feet and stated,
it appeared to me that the Friend who was requested to give notice of the meeting,
had neglected it, and put it on another, who was not in circumstances to do it,
and at so late a period that it was out of his power
to notify the people according to my request;
and I thought it hard after giving up to come so far as I had,
that I could not have the opportunity of seeing the people I wanted to;
but having done my duty, must leave it on the Friend, who had neglected his, to look to,
and sat down, and soon broke the meeting.
Friends called on the Friend, who acknowledged he had given no information,
but had sent the paper to a poor Friend that morning.
I was told, they asked him why he did so?
He answered, "`He did not know of any Friends in Vermont,
and thought it better to get acquainted with the man,
and to know whether he could preach first; if I had come from Philadelphia,
he should have felt safe in informing the people.`"

After this, we drove eighteen miles, to Benjamin Jordan`'s, near Vix Meeting,
at whose house we found kind usage, and on the 5th had a large, crowded meeting,
at that place.
At this meeting, the High and Holy One was pleased richly to furnish me with matter,
strength, and utterance, so that the power of Truth came over all,
and a solidity sat on the countenances of the people.
6th, we went to Somerton.
7th, first of the week, we were at that meeting.
From thence to Johnston.
8th, we had a meeting with the inhabitants thereabouts.
9th, rode to Secock, and attended an appointed meeting; it being rainy,
we tarried with John Watkins, the night.
10th, went to Black Water, and attended the Quarterly Meeting of Ministers and Elders.
While sitting there, it was shown me, as clear as the beams of light,
that there was in that meeting, one who defrauded the free blacks out of their wages,
after they had well earned them,
and that was the reason the Lord`'s presence was not to be found in the meeting.
It was also shown me, who it was that was guilty; but they all looked so smooth,
and answered the queries so whole, that I reasoned until the subject died away,
to the wounding and burdening my mind for many days.
And before I left the country, I was told that it was actually the case,
and who the man was, (the very person that was brought to my view);
when this was told me, I had not so much as hinted my feelings to any mortal.
This reinforced the burden on my mind.

I leave this for a warning to others.
11th, came on the meeting for worship and discipline.
It was painfully exercising, the continual moving of the young people,
and running in and out of the rabble.
At the meeting for business, they set the windows and doors open,
and the rabble would come and put their heads in at the windows and listen;
others almost continually running in and out;
and many sat in the meeting who were not members, nor even moral people,
and no endeavors were used to have it otherwise.
I was glad when the meeting ended.
We appointed a meeting there the next day, the 12th,
where I cleared my mind as well as I could,
and left them with a grieved heart and pained mind.
After meeting, we drove to the Western Branch twenty miles.
13th, we had a favored meeting with a few Friends there; a tendering,
contriting season to some minds.
14th, first of the week, had an appointed meeting at Suffolk.
15th, we rode to the Widow Winslow`'s, in North Carolina.
16th, had a meeting at Piney Woods, and another at Beach Springs on the 18th. 19th,
we had one at Goose Creek; at this, my mind was singularly led,
and having suffered deeply for suppressing my feelings before, I gave up,
to walk up to the mark faithfully.
The saying of the prophet arrested my mind: "`Thy Maker is thy husband;
the Lord of Hosts is His name; thy Redeemer, the Holy one of Israel;
the God of the whole earth shall He be called.`"

I was led to show that this would apply to the Church, and to individuals;
and that the way the Church became the Lamb`'s wife, was by entering into promises:
the Bride had to make promises as well as the Groom,
and these promises were not to be broken without guilt,
and the reward of guilt was condemnation always;
and in like manner it would apply to individuals.
Here I felt a full stop, but shortly the language flowed forcibly, "`What aileth thee,
O wife!
Has thy husband withdrawn his affections from thee,
or doth he neglect to provide for thee, or hast thou let out thy affections to another,
and played the truant thyself; and now, to hide thy shame, and to secrete thy wickedness,
art accusing thy husband of being guilty of thy own conduct?
This is cruel.`"
Then I was led to show how such a disposition would affect grief,
and use a private influence to get a strong party on their side;
and that such would pretend a broken heart, to carry their points,
while suffering innocence could say but little more than "`I am clear, I am innocent,
I never did so.`"
I then was led to show the agonizing pain it must
give to an innocent mind to meet with such treatment,
and that from one in whom they had put the greatest confidence.

When I felt clear of this part of the subject,
way opened to show the inseparable unity between Christ and his Church;
and that it was by covenant, and that compared to the wedlock covenant;
and when both parties kept the covenant inviolate,
then each partook of every solace that could promote joy and happiness;
but to those that broke covenant, sorrow, anguish, and woe, were certain.
I was, to my own mind, marvelously strengthened to go through the service of the day,
to my own peace, and the satisfaction of Friends.
I was shortly after informed there had been such a case with them,
which run to that length, that it brought the Monthly Meeting into confusion,
but that now all parties were satisfied.
The woman was disowned, and all things returned to a quiet course,
to the exaltation of the standard of Truth and Righteousness;
and I hope to the everlasting praise of the true God.
We went on to Simons`' Creek to attend their Monthly Meeting on the 20th,
but such a rain came on that only enough came to adjourn the meeting to another time.

On first day, 21st, we attended the meeting at Newbegun Creek.
22nd, had a meeting at Pasquotank, and returned to Aaron Morris`'. 23rd,
we rode to Nathan Morris`'. 24th, we had a meeting at Sutton.
25th, attended the adjourned Monthly Meeting at Simons`' Creek.
26th, attended the Quarterly Meeting for Ministers and Elders at Little River. 27th,
Quarterly Meeting for worship and discipline.
First day, 28th, we attended the burial of Mary White, daughter of Aaron Morris;
a large and solemn gathering.
1st of 3rd month, had a meeting at Pasquotank Narrows.
2nd, a meeting at Little River. 3rd, had another meeting at Sutton`'s Creek.
4th, we had another meeting at Simons`' Creek.
5th, we had a meeting at Nixonton.
All through this low country I felt much for Friends;
many of their brethren who had freed their slaves,
had left them unprotected and unprovided for;
and they themselves had gone into another country,
leaving their blacks a burden on their friends who stayed behind;
for they were liable to be taken up and sold again, unless protected by Friends,
so that it was a grievous burden.
I thought it right to encourage Friends to do what
they could for this oppressed and much injured people,
for whom I had much labor laid upon me, to plead their cause,
and bear a faithful testimony against the wicked practice of holding slaves.

The 6th of the month, we attended Piney Woods Monthly Meeting.
First day, 7th, we attended Wells meeting;
and at three o`'clock another appointed for us at Beach Springs.
8th, we rode to Eli Copeland`'s, thirty-eight miles.
9th, rode to Richsquare.
10th, attended Richsquare Meeting.
11th, we rode to Jack Swamp.
12th, had a meeting in that place.
18th, we had a meeting at M+++_______+++. First day, 14th, we attended Richsquare meeting again.
15th, we drove forty miles, to Tarburgh, and had to cross the great Waynoak river; here,
to our grief, we saw abundance of slaves, who were hardly used.
We put up with Henry Austin.
16th, we had a meeting in that town; after it, we drove to Contentney.
17th, attended meeting there.
18th, attended meeting at Turner`'s Swamp.

19th, attended Holly Spring meeting.
20th, visited Nahanty meeting.
First day, 21st attended Contentney meeting again, after which we rode to Cane Creek.
22nd, had a meeting with the inhabitants of that place.
23rd, set out for Core Sound, and continued traveling the 24th and 25th,
and arrived at Josiah Burden`'s 26th, in that neighborhood.
27th, attended Core Sound Monthly Meeting.
First day, 28th, attended Core Sound meeting.
29th, we had a meeting in Beaufort Village, by the Seaside.
From here we went back to J. Burden`'s. 31st, we drove to Newberne.
1st of 4th month, reached Washington, a little town on Bear River;
part of the roads were pole and log cross-ways, for miles together;
the most tedious of any I ever met with.
2nd of the month, rode to Pungo river.

3rd, we drove to Mattimuskeet.
4th, and first of the week, we attended that little meeting.
After this, we appointed a meeting at the lower end of Musketo Lake,
and attended it on the 5th of the month, and returned to Mattimuskeet.
The 6th, returned to Pungo river. 7th, arrived at Washington.
8th, had a large meeting there.
Here were abundance of slaves, and it being in the time of the war with England,
it was thought dangerous to say much against war or slavery.
I was led to show that the gospel, if complied with,
led every true follower of Jesus Christ to endure every burden, break every yoke,
and let the oppressed go free; and those who did not comply therewith,
were not true christians, but deceivers of themselves and others, and therefore,
anti-christians.
From this I was led to the subject of war.
But when I mentioned that, a number straitened themselves up,
and stared me full in the face,
with all the defiance of confident countenance they could; so much so, that I stopped,
and thought to sit down, and give up any further attempt to preach to them.
As I went to set down, the ear of my soul heard a clear voice,
saying "`stand still and wait for the Lord, and He will help thee.`"
So I stood like a stock to be stared at, awhile.
Then the voice spoke again,
saying "`speak to the people and state to them where thou livest,
and the situation of the country and people.`"

I then proceeded, and stated that I lived, when at home,
within sixty miles of the British lines; the nation that we are now at war with.
It is a land line two hundred miles; one hundred through a country of rich, fertile soil,
and both thickly settled, not only with farms, but towns, villages and meeting houses;
and that I had traveled in nearly all of the British American Provinces,
and found Episcopalians, Presbyterians, Baptists, Quakers, Methodists, Restorationists,
and Roman Catholics, and large societies of each, and many of them own brothers,
children of the same mother, and communicants at the same table.
When I had proceeded thus far, Gospel life arose, with authority, in this manner: now,
is it possible, for any one who has rational sense and power of reflection,
to make himself believe that Jesus Christ, the Prince of peace,
who came not to destroy men`'s lives, but save them,
should command any of His dear children of the same communion, who,
in commemoration of His agonized sufferings for them, in hopes that through His merit,
atonement and the gift of His grace, they may obtain eternal salvation,
(and this is the belief of all these societies),
should command any of them to draw the martial sword,
to open the veins of life of their brethren,
and deprive them of the remainder of their days.

And this is now the case in our land, with all those societies except the Quakers.
Who can believe all this should be?
I cannot, though I am well aware that the monarchs of the earth,
command obedience from their subjects, on the plea of being subject to the higher power;
seeming to forget that all power in heaven and earth, was given to Jesus Christ,
and that they have their power by his permission,
and are bound in duty not to counteract His command,
and are as accountable to Him as their subjects, and have no right to control conscience;
and Jesus commands to do good for evil; and He, in the Father,
is the highest power of all.
When this came, every head had dropped, and every countenance had fallen, except one;
he struggled awhile longer.
I felt the power of Truth to arise mightily over them all,
and the spring of the Gospel to flow as a mighty stream,
so that I had to keep on my guard to speak distinct and clear.
The last head came down; many of them wept much.
Thus, the Lord was pleased to make bare his arm, and show his mighty power,
and exalt the truths of the Gospel, amongst a full, hardy people,
to the honor of His own ever adorable name! and richly rewarded the poor servant,
for the obedience of faith this day.
Blessed forever be His goodness, and honored be His name.

After this, we journeyed to Greenville.
9th, to Contentney.
10th, we attended their Monthly Meeting, and put up with Silas Hallowell,
and rested one day.
12th, we visited Holly Spring Meeting.
13th, attended Nahante Meeting.
14th, we attended Bear Creek meeting.
15th, I attended the Quarterly Meeting for Ministers and Elders, at Contentney;
afterward we attended the Quarterly Meeting for discipline.

First-day, the 18th, was a general parting meeting, which was large, solemn and favored.
All the meetings in this quarter are small, many having moved away,
and meetings going down, which seemed gloomy and discouraging.
There seemed hardly strength to support discipline.
Many of their children marrying into slave families,
taking their wives`' portion in slaves; then ends all fellowship with Friends.
They become the hardest people that I fell in with.
While I mourned for the slaves,
I could but doubly mourn for the dwindling state of our Society in these slave countries.
My heart was many times so filled with grief, that had not the Lord sustained me,
I should have fainted in the field.
19th, we had a meeting at Neuse, eighteen miles from Contentney.
20th, set out for Eno; arrived there 23rd,
and had a meeting with the few Friends of that place.
After meeting, drove twenty miles, and crossed the river Saxapahaw,
to attend Spring Monthly Meeting, 24th of the month.
First day, 25th, attended that meeting again.
26th, had a meeting at South Fork, and rode to Cane Creek.
27th, had a meeting there.
In this part of the country, I found things much out of order,
and much discord amongst Friends.

My Master led me from day to day, and from meeting to meeting,
into a clear sense of the state of meetings and individuals,
and laid His command on me to speak His word faithfully, from which I durst not deviate,
so that my fears of missing the right mark were almost continual:
being in almost every meeting, for quite a number of days,
led into a sense of the wrongs that were among them, and had to deal plainly with them,
which was very painful to me, and deeply under the cross;
so that it wore upon my constitution to that degree,
that I sometimes thought I should lay my bones among them.
And had not the Lord borne me up, I should have fainted in the field.
28th, we were at Rocky River and made our home with David Vestal, one of their worthies,
an Israelite indeed, and attended that Preparative Meeting, and went to the Ridge,
twelve miles.
29th, had a meeting there.
From thence, we went to Holly Spring once more; much in the cross.
Was at that meeting the 30th of the month.
After it we returned to David Vestal`'s.

The 1st of 5th month, were at Cane Creek Monthly Meeting.
First day, 2nd of the month, we had a meeting at John Long`'s,
seven miles from Cane Creek.
3rd of the month, had a meeting at Providence.
The 4th, at Salem.
5th, at Centre.
6th, at Marlborough.
At this meeting, painful was the travail of my mind,
on the account of discord amongst brethren;
and I had to leave some close remarks in some families.
I was told after leaving that place, there were two brothers,
both members of Society in that meeting, who had not spoken to each other in five years,
and that I had dined at one of their houses,
and that I need not think strange of the remarks that I had to make in the family.
7th, I attended the Quarterly Meeting of Ministers and Elders, at Black Creek,
where I was led into the closest communication, and was, I think,
constrained to express the sharpest language that I ever
had in charge from my Master in a meeting of that kind,
and was told after meeting there was a cause for it.
The 8th, was their meeting for business,
somewhat exercising on account of an opposing spirit,
but by Friends keeping in the quiet and patiently waiting at Wisdom`'s gate,
Truth bore the victory.

The business was conducted regularly and consistently, to the comfort of many minds.
First day, the 9th, was the concluding meeting for the Quarter.
10th, we had a meeting at Uwavie.
After this meeting we drove twelve miles, and the 11th traveled forty-five miles,
to Rockingham.
12th, got to Pedee, about 8 o`'clock in the morning, and attended their mid-week meeting,
and appointed a meeting for the next day, at the same house,
and another in the afternoon, on the other side of Pedee river,
at a place called Little Creek.
Both these meetings were satisfactory.
14th, we set forward for Piney Grove, in South Carolina.
15th, we attended Piney Grove Monthly Meeting.
Here, Friends labor under great discouragements,
a number having removed to other countries, and they, surrounded with slaveholders,
so that they seemed to be in an unsettled state.
They conducted the business in much condescension and humility.
There appeared nothing austere amongst Friends of this place.
I had the best satisfaction with Friends here,
of any meeting for business I had attended for a long time.
16th, and first of the week, we attended meeting there again.
17th, we affectionately parted with Friends of this place,
and turned our course for New Garden, in North Carolina.

We went to Rockingham.
The 18th, we had a meeting with the inhabitants of Rockingham,
and rode to Archibald Morman`'s. There,
we had a meeting the 19th. After this meeting we rode thirty miles, and the 20th,
we rode twenty-five miles.
The 21st, we got to John Winslow`'s. The 22nd, we rode to Nathan Hunt`'s, in Springfield.
The 23rd, and first of the week, we attended Springfield meeting.
The 24th, I had to lay by and doctor, having taken a great cold.
25th, I went to Matthew Coffin`'s. About this time,
my companion becoming very uneasy and discontented, left me, in a distant land,
among strangers, where I was often plunged into deep sufferings.
26th, I attended Springfield mid-week meeting.
27th, had a meeting at Piney Woods.
28th, had a meeting at Kennet.
29th, rode twelve miles to attend Back Creek Monthly Meeting at Heworry.
In this little tour I had Matthew Coffin for a companion.
First day, the 30th, I was at Heworry Meeting, and returned to Phineas Nixon`'s,
where I was kindly cared for.
31st, I had another meeting appointed at Back Creek.
This seemed almost like giving up my life, to have to go back to a place,
where I had been so many times, and been plunged into such deep exercise;
it seemed like the mighty waters that rolled over the head.
But I found peace in giving up to my Master`'s requirings.
He was pleased to bear me company, and strengthened with ability and utterance,
so to do His work that I felt well relieved, and richly rewarded.

The 1st of the 6th month,
we returned to Springfield and attended their Preparative Meeting.
2nd of the month, again visited Piney Woods Meeting.
The 4th, at Kennett; 5th, attended Springfield Monthly Meeting,
where I had to go into close, searching labor.
After they commenced doing the business,
I felt my mind impressively drawn to make a visit to the women`'s meeting.
I opened it to the men and had their consent, and a Friend was named to go in with me,
and soon after I got there,
it was opened to me that there was one in the meeting who was accused of stealing,
who was as innocent of such a crime as a child unborn.
I sat under the exercise until my Master showed me how,
and in what manner to take hold of the subject.
I then rose with these words: Had I in the men`'s meeting met with what I have here,
I should not have been surprised;
for men who have to go ahead in the business of the world,
will sometimes run across each others`' track and spat each other;
but to find amongst the fair sex, to whom we look for the finest feelings of sympathy,
those who are accusing an innocent sister of taking property, not her own,
and keeping it for her own use, who is as innocent of any such crime as a child unborn;
and not only accusing,
but whispering and spreading it abroad to the great injury of the credit of the innocent;
and what is still worse, for those who sit in Moses`' seat,
and those in the station of Elders to sanction these reports, is cruel;
and to be found among the fair sex, is surprising.

But rest assured, the Lord will overturn all this,
and the day will come that it will be known who is innocent--for
the Lord will plead the cause of suffering innocence.
And if thou who art the sufferer, keep in the quiet, and abide in patience,
the day shall come when this shall be carried over the heads of thy accusers.
I passed on, and no one said anything to me on the subject.
I heard nothing of it for years.
But when I did, it was said that a Friend and his wife and children,
had accused a daughter-in-law, a widow, of taking several hundred dollars in money,
that was not her own, and had secreted it.
Several years passed; at length the man who had the money,
came forward and let it be known that the widow`'s husband
had paid the money over to him a few days before he died,
for land which he gave a deed for, and the deed was found,
and I agreed with the man`'s testimony.

Thus, I was credibly informed, the widow was cleared.
I leave this, in hopes that it may be a caution to others, how they accuse on suspicion,
and give pain to suffering innocence.
The 6th of the month, and first of the week, I was at Deep River Meeting; the 7th,
I attended Deep River Monthly Meeting; 8th, at Muddy Creek Meeting; the 9th,
at Blue Creek Meeting; the 10th, I attended Dover Meeting; the 11th,
attended New Garden Quarterly Meeting for Ministers and Elders; the 12th,
the meeting for business.
First day, the 13th, attended their closing meeting held for worship--it was a solid,
favored meeting; 14th, visited Hopewell Meeting; here I had Jesse Towel for a companion;
15th, we had a meeting at Newberry; 16th, at a meeting at Sandy Springs; 18th,
we were at Centre Monthly Meeting;
it was a trying day on account of a division amongst Friends, and a noisy man,
they were about to disown, at length left the meeting,
after which the business was conducted pretty harmoniously; 20th, first day,
we attended Centre Meeting in the forenoon and had
an appointed meeting at Providence in the afternoon;
21st, went to Jesse Towel`'s, where we put up for the night; 22nd,
we rode to Joseph Thompson`'s; 23rd, we had a meeting at Hillsborough; 24th,
we attended Eno Preparative Meeting, and returned to Jesse Towel`'s, twenty-six miles;
25th, I laid by and wrote letters; 26th, we attended Spring Monthly Meeting; 27th,
we were at Rocky river Meeting, and took dinner with our worthy, aged Friend,
David Vestal; 28th and 29th,
we traveled sixty-eight miles and reached Archibald Morman`'s for the second time; 30th,
we had a meeting at Samuel Chauncey`'s, and tarried with him the following night.

The 1st of 7th month, we had a second meeting at Rockingham; 2nd, we reached Piney grove,
in South Carolina, and made our home with John Thomas.
4th, first day, we attended Piney grove meeting, which was large and favored; a tender,
humbling time; 5th, 6th and 7th, we spent in visiting the families of that meeting; 8th,
we attended their mid-week meeting, which was a solemn, parting opportunity,
and proved a final parting with several of us,
who had become much bound together in spirit; 9th, set out for Bush river; 10th,
we got to Camden, seventy miles on our way, and had a meeting there on first day,
the 11th, which was large and favored.
We made our home with Samuel Mathers, a Methodist preacher,
who treated us with Christian kindness,
and was very helpful in getting a house for the meeting, and notifying the people.

We had another meeting in the evening, in the same house, to good satisfaction.
Here, I was shown the ground where Friends held their Quarterly Meeting for sixty years,
and was told that Friends once had a large, good house there;
but the ground then lay commons.
I asked what had become of Friends, and was told they all moved off in a body,
except a few who had since died, and one old man.
The Quakers told us for several years,
that if we did not use our slaves better they would quit the country,
for they could not endure to see it; but we did not believe them until we saw them go,
and sorry enough we are that they are gone, for they were good inhabitants.
This gave me a fair opportunity to reason with them on the subject,
and show how inconsistent it was with good policy or humanity,
and repugnant to the very nature of all the Divine attributes,
and entirely incompatible with every precept of the Gospel.
They acknowledged it was wrong, but complained they had got them;
their fathers had left them on their hands, and they did not know what to do with them;
their fathers had done them a great evil.
Here they chose to stop, and curl down on their fathers`' sins,
making that a couch of security.
They seemed to have no disposition to ease their slaves`' burdens,
or mitigate their distress, nor yet to look forward for their enlargement;
but the plea was, we have got them, and must keep them, and keep a strict hand over them,
or they will be saucy and rebel.
So I said, no blindness so great as willful blindness;
no sin so hardening to heart and searing to the conscience,
as the sin against light and knowledge.

The 12th, resumed our journey for Bush River, over a hilly, rough country.
We lodged at a small village called Winnsborough.
Here, we thought best to stop and propose a meeting with the people,
which was readily complied with.
It was held on the 13th; the people were civil, and appeared well satisfied,
and I felt much relieved.
Our landlord`'s name was Hugh Barclay.
14th, we started, expecting our next night`'s lodging would be at Bush River.
It was a heavy day`'s travel, over a hilly, dry country; the water was very poor,
which is not common in a hilly country.
I was taken sick on the road, vomiting heavily several times, but continued our travel,
and arrived at the widow Hannah Kelly`'s, where we put up for the night.
15th, continuing sick, we moved to Isaac Kirks, an able man,
who had a good open heart to take us in, and do all he could for me.
When we got there they were just going to meeting, but I was not able to go with them.
My sickness proved to be the billious colic, and I was confined here among sympathizing,
kind Friends, till first day, the 18th,
by which time I had so recruited as to be able to attend their meeting;
and notice having spread of our being in the place, the meeting was large.
The Master of Israels`' assemblies was pleased renewedly to visit that people,
and cause the water of His love to be plentifully showered on His heritage,
to the tendering of many precious minds.
May it be productive of fruitfulness unto holiness!

The 19th, we had a meeting in Newberry Courthouse, which was large,
and the people very attentive and quiet.
20th, we appointed a meeting at New Chapel, it was large.
In both these meetings my mind was enlarged in the love of the Gospel,
and the doctrines thereof, flowed freely to the people.
21st, we had a meeting with Friends by themselves--a humbling, parting opportunity,
not easy to be forgotten by me.
22nd, we set out for North Carolina, and rode thirty-one miles through a hilly,
stony country, James Galbreth being our pilot.
23rd, pursued our journey through that hilly country, and drove forty-four miles; 24th,
we drove to Statesville, forty-two miles.
25th, first day, by driving twenty-three miles, we got to Hunting Creek Meeting;
though late, I was glad to find myself among my Friends once more.
Not feeling clear, I proposed a meeting there the next day,
which was readily complied with.
It was large and favored, much to the relief of my drooping mind.
The 27th, we had a meeting at Swan Creek; this was also to good satisfaction.
After which, we rode to Deep Creek,
and had an appointed meeting there on the 28th. The spring of gospel life ran freely;
29th, we went to Westfield twenty-five miles.
I was taken sick on the road,
and was not able to travel or attend meeting till first day, the 1st of 8th month,
when I got out to Westfield meeting.
Here I parted with my agreeable companion, Jesse Towel,
who had been with me through this southern tour.

2nd of the month we set forward to cross the Blue Ridge, to go to Fruit Hill,
thirty-five miles;
I think the worst road of the length that I ever drove a carriage over. 3rd,
attended Fruit Hill Meeting; I had Nathan Coles for companion,
at whose house I had been confined at Westfield, where I was kindly nursed.
4th, we were at Mount Pleasant Meeting.
It was small.
We lodged with John McLane.
From here I had to ride on horse back fifteen miles, to Chestnuts.
Previous to my arrival, I had to stop for refreshment; the fare was poor,
but the people were kind.
We got to meeting in season; it was small; the country was hard, and Friends poor.
After meeting we set forward on our return to Mount Pleasant, but failing,
I did not get in until near one o`'clock next day, 6th. On the 7th,
by the doctor`'s direction, I took an emetic, which operated so violently,
that it nearly overcame nature, and I lay about six hours nearly as cold as a corpse,
until they boiled a large vessel of water with a quantity of bitter herbs.
They put me in this warm bath, and rubbed me faithfully with the boiled herbs;
this promoted a warmth, and restored nature to action.
The emetic turned down, operated powerfully, and I revived;
but it broke the fever which had been hanging about me for several months.
I sweat profusely for about twelve hours, which reduced me very low.
I think I never was brought so near the grave, in my life, before.
I was taken to John McLane`'s, on account of his wife being a good nurse,
and I had never before fallen into the hands of one,
equal to her in skill and motherly affection, so that when I think of her,
my heart glows with gratitude, much desiring, and fully believing,
that the Lord will richly reward her for her kindness to me,
a stranger in a strange land.

I was confined from traveling until the 20th,
except to attend Westfield Quarterly Meeting,
and in the latter part of the time I sat with Friends
twice in their little meeting at Mount Pleasant.
After attending the Quarter, I visited Fruit Hill and Pine Creek meetings;
returned to Mount Pleasant, and attended their Preparative Meeting the 27th,
and their Monthly Meeting, the 28th; both of them were small and weak.
29th, first day, was at Chestnut Creek meeting again, after which,
I returned to Mount Pleasant,
where I met my intended companion for Tennessee--Caleb Carson.
On the 30th, we set out for Tennessee.
We had to cross the Blue Ridge.
The first day we traveled twenty-eight miles, the 2nd day, thirty-eight miles.
The 1st of 9th month we traveled thirty miles; the 2nd, not more than twenty miles.
We turned over our carriage, damaging it considerably,
so that we had much difficulty in getting amongst Friends.
The first Friend`'s house we came to was Isaac Hammer`'s, where we put up for the night.
From here, we went to Isaac Beal`'s, and mended our carriage.
The day following, we had a comfortable meeting.
The next meeting was at New Hope,
and the day following at the little meeting at Tick Creek.

In all the above meetings I was led much in the line of doctrine.
Friends here generally lived comfortably, but none of them rich;
they seemed to be pleasant company for one another,
no distinctions to feed jealousy or promote pride,
so that it was much easier getting along here than in many other places.
We had a large meeting at Canada Spring,
(about the time the Methodists were holding their Camp Meeting, not far distant),
to which many of the Methodists came.
I was led to show that the work of religion was a
work carried on between God and the soul of man.
I was also led to show that while the soul kept its attention on the spirit of the Lord,
which began the work of reformation in and upon it, every advance in the growth of grace,
from stature to stature,
was known in the communion that was held between the spirit of the Lord and the soul;
and when the spirit of the Lord was believed in and obeyed,
it dictated all our duties to God, our fellow creatures, and ourselves;
and the duties so done were always acceptable with the Lord,
while all man-contrived devotion and will-worship, is rejected by Him.
They took offense at my remarks, and after I was gone,
they charged me with false doctrine.
I give a little sketch of this meeting as an introduction
to what will come in course before I leave the country.

After meeting we rode to Lost Creek, fifteen miles.
9th, we had a large, favored, satisfactory meeting with Friends and others of that place.
10th, we had a small meeting at the Valley.
11th, we had a little meeting at Grassy Run.
A number of these little meetings were once larger, many having moved away,
to get out of a slave country, and led a few scattering ones in each place,
who do not seem willing to give up holding their meetings,
though some of them were but little more than ceremony.
They seemed in an uneasy and unhappy situation,
so that I thought these had better follow their brethren; yet I think,
that had Friends of that part of the country kept together,
and been faithful to their principles, and stood their ground,
they might have done much good to, and for the oppressed black people,
who have but few to plead their cause;
and I think they would have done much better than moving away.
In that part of the country there are many not Friends, who are very uneasy with slavery;
so that I think, where Truth shakes the foundation of iniquity,
Friends had better keep the ground and hold up the
standard of light and Truth to the people.

The 12th, we went to Newberry, twenty-five miles.
13th, we lay by to give opportunity for the notice of the meeting,
Friends living scattered.
14th, we had a large, good meeting at that place.
15th, we started to return, but not feeling clear, we turned back,
and had a meeting about five miles southward of Friends`' Meetinghouse, on the 16th,
and then returned to Friends.
17th, we visited families.
18th, we started for Lost Creek.
We stopped on our way, at Knoxville, to take breakfast.
The Indians having made an invasion on the frontiers of the white inhabitants,
it was a time of general alarm while I was there.
Being taken into the room where the General was with his officers;
the sergeants made their returns to the General,
that they had warned every man that the law required to do military duty,
Quakers and all, and there had not one Quaker appeared on the ground.
In the meantime the General looked sharply at me, as I was walking the room, and said,
"`Well, we have lost a number of our frontier inhabitants, and some of our soldiers,
and a people who would not defend the frontier inhabitants,
when the savages were destroying and scalping them,
could not be considered friends to their country, and should have no favor from him.`"

He then said, "`How do you like this doctrine, stranger?`"
I answered, "`It is no doctrine for me; I have little or no opinion of it.`"
He asked, "`Why?`"
I said, "`The people with whom I commune, who are sound in their principles,
are all King`'s men to a man, and are remarkably attached to their King,
and our King told Pontius Pilate, that His kingdom was not of this world, for if it was,
then would His servants fight that He should not be delivered to the Jews;
that His kingdom was not from hence, and that His kingdom was our kingdom;
that He had nothing to fight for in this world, neither have we;
and you warriors are fighting for the riches, honor, and glory of this world,
and when you have got them, you cannot stay with them.
We choose to lay up our riches, and have our treasures, where the rust cannot mar them,
nor thieves nor warriors get them from us.`"
The General sat down, but soon rose with these words,
"`I am not going to give up the argument so; I see by the look of your eye,
that you are no coward; you are a soldier;
and if an Indian was to come into your house to kill your wife and children,
you would fight.`"
I answered, "`As for cowardice,
I ever despised it,`" but pointing toward the guns
standing in the house with bayonets on them,
"`General,
it would take twelve such men as thou art--and then you
would not do it--to make me take hold of a gun or pistol,
to take the life of a fellow creature,`" and looked him full in the face.
He said, "`I see you do not deny the sword.`"
I replied, "`No; I profess to be a swordsman,
that is the weapon go into the field with--a sword that
never was beaten in the field nor foiled in battle.`"

He turned and sat down, but not long, and said, "`I will bring you to the point.
If an Indian was to come into your house, with his knife and tomahawk,
and you knew he would kill you, your wife, and children,
and you knew you could kill him and save all your lives, you would kill him;
if you did not, you would be guilty of the death of the whole.`"
I thought it time to look for a close, and proposed a standard to bring the argument to,
that should decide it, but he declined.
I then asked him if he professed to be a Christian, a Jew, or a Mahometan?
He declined awhile.
I then added, if he were a Jew, he was not prepared to fight;
his men were not circumcised, he had not burnt a sin offering, nor a peace offering.
He exclaimed, "`I profess to be a Christian; I am not a Jew or a Turk.`"
I asked him if he believed Jesus Christ was the author of the Christian dispensation.
He said, "`Yes.`"
I asked him, if he believed Him sufficiently equal to the work as God himself,
as he received all the works of God to do.
He said, "`He did.`"
I then told him, I should keep him to the Christian platform or creed,
laid down by Jesus Christ;
and that he would not deny that a Christian was fit to live or die--I meant a true Christian.
He said a true Christian was fit to live or die.
I then told him I would give the subject a fair statement, and he might judge.
I proceeded thus: "`I shall state, that myself and wife are true Christians,
and our children are in the minority--and thou knowest it is natural for
children to believe what their parents teach them--and therefore we are
all true Christians as far as our several capacities enable us to be;
and now the question lies here;
which is most like the precepts and example of our King--the
author of the Christian religion--to lay down our lives,
and all go to heaven together; or kill that wicked Indian, and send him to hell;
for he must be in as wicked a state as he can be,
to kill a family that would not hurt him.
General, it is a serious thing to send wicked folks to hell;
they have no chance to come back and mend their ways; and thou dost not know,
but that if that wicked Indian was spared he might feel remorse enough to make him repent,
so as to find forgiveness, and go to heaven.

I really believe,
I should feel much better to see him come there than to send him to hell;
and that is not all, General; when I killed that wicked Indian, and sent him to hell,
I imbrued my hands in human blood; before, they were clean;
but now they are stained deep in the crimson gore.
Canst thou make thyself believe, that I stand as good a chance to get to heaven,
as to die when my hands were clean, and I innocent of human blood?
And besides, our King who was Lord of all,
had disciples and many women who looked up to Him for protection,
as much as a wife to a husband, or children to their father.
Did He, when the wicked Jews came out with staves to take Him,
cut off those wicked creatures, and send them to hell,
when he could have the command of twelve legions of angels?
He did not act without reason, He knew if He cut them off they must go to hell;
and He knew if He laid down His life, He was going to heaven;
and neither thou nor I knows, but some of the poor creatures repented of their conduct,
and found forgiveness, and are now in heaven, glorifying His name for sparing them.
Now General, was He guilty of suicide?
Thou wilt answer, He came into the world for this purpose.
I reply that we are brought into the world to obey his commands,
and to follow his example, and do likewise if called on; and, General,
we find He had one soldier among His followers,
who drew his sword and fought like a valiant for his Lord.
But what then said his Lord?
Did He say, thou art a good fellow, I will promote thee for this?
Or, did He not say, put up thy sword into its sheath,
for they that use the sword shall perish with the sword.
General, thou will do well to remember that saying; it is the word of a King.

The General made no answer, but sat and hung his head for some time.
One of the company at length replied, "`Well, stranger,
if all the world was of your mind, I would turn and follow after.`"
I replied, "`so then thou hast a mind to be the last man in the world to be good.
I have a mind to be one of the first, and set the rest the example.`"
This made the General smile.
He got up and went out at the door,
and ordered his officers to let me go where I pleased, and not to interfere;
then turned and came in.
I was then walking the door, and after a little discourse, the General said, "`well,
stranger, there are a great many of your sort of people in this State.`"
I answered, "`yes, and I hope thou finds them an honest, industrious, peaceable people;
good inhabitants to populate and clear up a new country, and make it valuable.`"
He said, "`yes, they are an industrious, harmless people.`"
We were both on our feet.
I turned, and looked him full in the face, and spoke with some emphasis.
"`General, canst thou say that an honest, industrious people, who will harm nobody,
are enemies to their country?`"
He paused awhile, and said, "`No, and they shall have my protection,
and you have the word of a General for it.`"
I then felt easy that all was done that could be done.
I had the same man`'s word who had said,
"`No favor should be shown the Quakers,`" now pledge his honor to protect them.
After some more conversation, we parted very pleasantly.
We refreshed and went on; and after getting alone and looking it all over,
I said in my heart, "`Lord, what hast Thou done,
for Thou wast near me and I perceived it not; Thou carried me through, and I knew it not.
The honor and the praise is all Thine; Thou hast magnified Thy own honor,
and exalted the cause of righteousness in the eyes of gainsayers,
and caused the tongue of the lofty to change,
and hast caused the mighty to feel Thy power to be over them all,
to the praise of Thy ever blessed name!`"

The 19th, we attended Lost Creek Preparative Meeting.
20th, we attended Grassy Valley Preparative Meeting.
In both of these I had relieving service to my mind, and good satisfaction;
but not feeling clear of Knoxville, we returned to it, whilst the army lay there.
21st, we had a meeting with the officers, soldiers,
and inhabitants--a great concourse--having a place that would accommodate thousands.
Here, the Lord, my good Master, gave strength sufficient for the day,
and took all the fear of man from me,
and furnished me with ability to hold forth the beauties
of the peaceable kingdom of the Messiah,
the Lamb of God; and to bring into view the reward in time,
in the enjoyment of social society in love, whose law is kindness;
that love which worketh no ill to its neighbor, but promoteth peace,
and spreadeth joy in the human family.
Thus, I was led to hold up the warrior`'s weapons in their terrific hues,
and show the agonies they caused, in making widows, and fatherless children,
with the other evils attendant, and had to contrast the subjects,
so they would look me in the face, look down on their swords,
turn pale and hang their heads, and some of them shed tears.

Truth arose mightily in dominion over them all.
The power of the Lord and the Lamb, reigned that day, to the honor of the Godhead,
to whom all honor belongeth.
After meeting, I thought to get away soon,
but before I could start a man came to me with a number of silver pieces in his hand,
to reward me for my service, and urged me to take them,
and to stay three-quarters of an hour, and they would raise something handsome for me,
for that was not half enough; the people wanted to do it, and I ought to receive it,
for I well deserved it.
So that I was obliged to take up the subject at large,
and give them my reasons why I could not take even one piece of the money.
They gathered around, and looked on me like people amazed, until I had done,
and then the man who held the money looked on me and said,
"`I believe you are sincere and conscientious in it,
but I think you are a little bigoted, and we are sorry,
for we think you ought to take the money.`"
I acknowledged their respect, and was glad to get away so well,
and returned to Lost Creek.

The 22nd, we attended that Monthly Meeting.
23rd, first day, we were at Canada Creek Meeting.
Notice being given of our being there, a number of Methodists came in.
This was the place where the Methodists accused me of false doctrine when here before,
but now I had to take up the subject of silent worship at large,
and show from many scripture texts,
that silence was an ordinance of heaven--as preparatory to all right devotion.
I was led to bring into view the silence in heaven for the space of half an hour,
and what transpired after it; also Elijah being silent in the cave`'s mouth,
when the wind, the fire, and the earthquake passed by, and the Lord was in none of them,
and was led to show what transpired after it,
in continuation that silent worship was acceptable with God,
and a necessary preparation for all other devotion; then sat down.
I had not sat long before I found my mind drawn to take up the subject of prayer,
and call to remembrance the Lord`'s instruction how to behave in prayer;
that Christians were not to make long prayers as the heathen did,
thinking they should be heard for their much speaking;
nor to blow the trumpet to call people to hear them pray;
nor to stand in corners of the streets to be heard or seen of men;
but to pray to their Father, who was in secret, and who would reward them openly.

When we returned to John Kennedy`'s, after meeting, the aged Friend, remarked that,
he did not know but that his prayer was answered;
for the Methodists had said so much about my false doctrine,
that he had craved that I might come back and have another meeting with them,
and clear the way.
He thought I had been enabled to answer every objection and every cavil,
as plainly as though I had heard them; and that, too, in the hearing of the objectors,
in such a manner, that he saw no way but they must be still and quiet now.
He could but marvel at the goodness of Providence to his people.
Then remarked, thy last testimony crowned all the rest;
for in their Camp Meeting they blow the trumpet to apprise the people,
and when they thought they had time to wash and prepare themselves,
they blow the trumpet to call them to prayers.
And when they had time to breakfast, they blew the trumpet to call them into the camp.
So that when thou came over the blowing of the trumpet, and the manner of parade,
it so fitly applied, that the Minister who sat before thee,
dropped his head that had held up before,
and he did not raise it again until thou sat down.
So that I think it is evident that the Truth arose in dominion over all opposition;
a favor that we ought to be thankful for.
And truly the account was humbling to my soul.
24th, we drove about ten miles on our way, stopped and had a meeting; after which,
we drove ten miles and put up with Jacob Killpatrick.
25th, we drove but twenty-four miles; it being very rainy,
we stopped with Friends at Lick Creek.
26th, we had a satisfactory meeting with them.
After meeting we drove to Newhope, and had a meeting with them on fifth day.
After meeting, we drove to the widow Elizabeth Powel`'s, in Limestone Settlement,
and had a meeting with them on 6th day of the week.
In these last meetings the way was opened, and I was favored so with utterance,
that I felt fully relieved, and at liberty to bid farewell to Friends, and that country,
for that time.

The 2nd of 10th month, we set forward for Westfield, in North Carolina,
and arrived there the 10th of the month.
We attended but one meeting in the time,
and traveled three hundred miles across the most hilly, mountainous country,
that I had ever traveled.
11th, I attended Westfield Monthly Meeting, and was glad to get amongst Friends again.
12th, first-day, I attended that meeting again, to my own,
and Friend`'s satisfaction and comfort.
13th, I left Deep Creek, and reached there about the middle of the next day, 15th,
I had a second meeting there.
16th, had a satisfactory meeting at Hunting Creek,
and took dinner after it with Daniel Burnsides.
17th, I went to Swan Creek, and had a good meeting there on the 18th. 19th,
I returned to Deep Creek, and was with Friends of that place, on first day, 20th. 21st,
in company with John Jackson, I had a meeting at a town called Rockford,
on the east side of the Yadkin River.

From there we returned to Westfield, and lay by on the 22nd, waiting for company,
being bound for the Yearly Meeting of North Carolina, to be held at New Garden.
23rd, we crossed Surrytown mountains, and put up at night with Latham Folger.
24th, we drove to Barnabas Coffin`'s, Deep River. 26th,
I attended the Yearly Meeting for Ministers and Elders.
27th, first day, attended meeting at the same house.
At this meeting I hurt my testimony by speaking fast,
fearing I should be in the way of others.
28th, the Yearly Meeting for business commenced, and held by adjournment several days.
Much deep exercise was witnessed on account of the many deficiencies,
which through declension, had crept into our Society;
so that there was much disorder in the Yearly Meeting, by young people going in and out,
who were not members, accompanied by young Friends;
so much so that I proposed to appoint doorkeepers to prevent the disorder,
which the meeting did; yet a member of Friends were highly offended with it,
so that I had much arduous, and painful labor through this Yearly Meeting,
on account of the many wrongs not done away.
There were many colored children amongst them,
who were in no way for obtaining learning to fit them for business;
and when I talked with some Friends on the subject, they replied,
that if they gave them learning, it would make them saucy,
and they would feel themselves as good as white folks.
There were others who felt concerned for them, and wished them to have learning;
but there were few who were willing to put forth the hand;
so that I felt a necessity laid heavy upon me, to labor honestly, faithfully,
and plainly with Friends on that, and several other accounts, which lay heavy on me.
But it did not suit them in general, and only a few would receive it.
But my good Master strengthened me so from day to day,
to bear the testimony which he gave me, that when the meeting closed I felt easy, clear,
and richly rewarded with the returns of that peace, which no man could take from me.

After this meeting, my way being shut up as to any further gospel labors in this land.
I set out for home and traveled fourteen days,
without any stop except what nature called for, until I got to Stroudsburgh,
in Pennsylvania.
There I stopped a week and rested my horses, got my clothes washed,
and then started again, and reached home in about ten days;
found my family and Friends generally in good health,
after an absence of thirteen months, having passed through many deep wadings,
and witnessed the arm of the Lord to carry my soul through heights and depths.
It is all of His power and mercy which hath sustained me hitherto.
Honored, worshiped, and adored be His goodness, and His holy name forevermore,
saith my soul!

Several years have passed,
in which I had to make several short religious visits
in different parts of my own Yearly Meeting.
Not having regularly dated minutes, I pass by them,
and take up the following account to close my first visit in North Carolina.
After getting through South Carolina, I expected from there to go home,
but after getting from Chestnuts, among the mountains, I was taken very sick,
and was confined most of the time for several weeks, at Mt. Pleasant,
and at one time so low, they thought I was dying, and I thought so myself.
At this time I was seriously looking over, to find if all was well to leave the world,
and the Lord showed me that I was not to die yet.
I had got to attend North Carolina Yearly Meeting and several others, and there,
in every place, deliver what He gave me,
and see that I did not turn to the right hand nor to the left.
Shortly after, I was able to get into my carriage and close my visit in Tennessee,
and return to North Carolina.
I visited one Quarterly Meeting,
and two Monthly Meetings before the Yearly Meeting came on, and found close,
searching labor in all of them, much more so than is common for me in such meetings.

When the accounts were presented to the Yearly Meeting from the different Quarters,
there appeared much disorder and weakness among them;
I found my mind arrested to labor much, plain and clear; among the rest,
my mind was arrested with weight, for a length of time, which I sat under,
until I was not able to attend to their business
sufficiently to know how it was going on.
I then informed them there was a subject on my mind,
and continued with me so heavy that I saw no other way but to leave it where I found it.
The subject is this--it is not good for Ministers and Elders to mount
their horses and ride round the country to electioneer to get a slaveholder
for an assembly-man--it is not consistent with our principles.
I was led to show that while we were bearing a testimony against slavery,
to ride round and endeavor to get in an assembly-man who was determined to support slavery,
was not consistent, and was led to treat the subject very plain, and clear,
to show the encouragement it gave for other Friends to do so likewise;
that it was not good; Friends had better keep out of the mixture.
I sat down, feeling great peace of mind,
and had but little more service through the meeting.

When the meeting closed, my certificate was not given me;
when one-third were out of the house,
I found the clerks crouched down behind the door writing on the back of it.
I took it and walked into the yard and saw what was put (written) upon it,
that the Yearly Meeting knew nothing about as a Yearly Meeting;
written in the name of the Yearly Meeting, and signed by its clerk.

I soon fell in with N+++_______+++ H+++_______+++,
the assistant clerk, and asked him what it meant.
With a good deal of emphasis, he said, oh, thy conduct has ruined the Yearly Meeting.
I queried with him wherein; he did not let me know,
but insisted that I had wounded a great many Friends`' feelings,
and ruined the Yearly Meeting, and that I had no business here;
I had ought to have gone home.
I let him know that I knew better,
and gave him a short account how I knew that I had done my Master`'s work faithfully,
and got my reward--a good reward, so that they could not help it;
which seemed to check him a little.
We soon parted.
Being yet feeble, I thought it best to leave as soon as I could.
There was one D+++_______+++ Q+++_______+++ of my own Yearly Meeting
that came home and reported that I was sent home,
which was altogether false, as there was never such a word or hint given me;
for what was put on my certificate was not an act of the Yearly Meeting,
but was left so no one could tell what was meant.

I returned home and had it to muse upon for five years, before I knew what it meant.
When I visited that country a second time, I fell in with M+++_______+++ C+++_______+++,
an Elder of the same place,
who asked me if I knew what it was that offended N+++_______+++ H+++_______+++ and his brother,
(who were clerks of the Yearly Meeting when I was there before), I replied, no.
He then said, N+++_______+++ H+++_______+++,
persuaded me to ride with him to electioneer for such a man.
I rode with him one day and a half, and told him I could not ride any more,
as I did not feel right, left him, and he rode alone.
This influence got the man in; after he was in, he made sport of it,
saying the Quakers were such fools as to think he would favor them.
He proved the hardest man against Friends they had in a great while,
and afterwards was detected in Pennsylvania in kidnapping, suffered imprisonment,
and had to pay a heavy fine.
When I heard all this, I was amazed, for the Lord knew, and does to this day,
that He laid it upon me to deliver it there in the meeting,
as I never had a thought that N+++_______+++ H+++_______+++, or any in his station,
would go into such business, until I had to deliver it.
When I look it over, to this day, it gives me a gloomy feeling,
for he fought against the living truth, and his tantalizing was hard to bear.
