== Chapter VIII

Some time having passed, during which I kept much at home,
except attending neighboring meetings, and a few short visits not far distant,
of which I kept no account,
in which time I had to pass through many deep and sorrowful trials,
which I sometimes thought would take my life;
there having risen up a company in the Quarterly Meeting to which I belonged,
some of whom were active members in each Monthly Meeting,
who seemed determined to lay waste all order in the Society,
making great pretension of the Spirit and revelation;
pleading that they must go by the Spirit, and not by the letter;
that the discipline did abundance more hurt than good.
They disordered and troubled our meetings for several years, until the Lord was pleased,
in tender mercy to His people, to shake and expose their foundation and principles,
and put them much to silence.
When their principles were discovered, they were found to be Deistical,
and their aim seemed to be, to lay waste the Society, root and branch;
and in order to do this, their endeavors were to run down every faithful member,
by slander and censure, and by this means, to stir up discord among brethren;
thus bringing much trouble and grief to Friends, and reproach on the Truth.

After this storm had a little passed over, I felt my mind drawn in Gospel love,
to visit Friends and others, in the southern and western parts of my own Yearly Meeting.
I laid my concern before Friends, and obtained their unity fully expressed.
I proceeded to Queensbury, where I perceived Friends were almost alarmed,
as they had heard slanderous reports about me,
having no idea of seeing me there again in that way,
as some of these reports--though utterly false--were
carried by Ministers who had been in our country,
professedly in Truth`'s service; which gave the reports credit abroad.
I remark this, with a hope it may prove a caution to others,
how they carry reports which they do not know to be true.
It made hard work for me for some time; but good was the Lord, His strong arm underneath,
supported, and His Spirit sustained me, and in many instances,
He caused the walls of prejudice to fall before me, as dust is blown before the wind.
Blessed be His name.

After having a solid, satisfactory meeting at Queensbury, I passed on to Greenfield,
Providence and Galway, visiting all the meetings in that part of the country,
in which I had much labor, greatly to my satisfaction,
and the full acceptance of my Friends.
Thence we went through Saratoga, visiting all the meetings thereaway,
being enabled to clear my mind nearly to universal satisfaction,
and passed on to Duanesburgh Quarter, there attending two meetings.
The third meeting I attended, was at a place where Friends had disowned a number,
but keeping entirely still, (which was right in them),
these circumstances were unknown to me.
I afterwards learned it was on account of denying the Divinity of Jesus Christ,
and holding the doctrine of annihilation of the wicked.
Soon after taking my seat, from impressions felt,
I soon became satisfied there was a strong and very wicked spirit in that meeting,
and sitting under the weight of it,
I felt a clear and forcible motion to rise on my feet, and attending to it,
I was led to take hold of the subject, showing that Truth led into knowledge,
whilst the spirit of the old serpent, led into imaginations.

The Truth leads to gather in love, and to encourage and build up in the holy faith;
whilst the spirit of the devil urged people with high pretentious,
and much apparent zeal, to lay waste and destroy the heritage of God,
if they were suffered to do it.
Thus, I was led to show how it would work,
and in such a manner that it excited them--a number
of them being present--so that after meeting,
those of other societies exclaimed, "`now we know who is right,
for here has come an old Quaker, from another part of the country,
who knew nothing about them, and he has laid waste their doctrines and proved them false,
and the doctrines of the Gospel to be true,
and its foundation to be as sure and durable as God;
the Quakers have done right in disowning them.`"
This seemed to aggravate their feelings, for they had made much noise among the people,
asserting that Friends had disowned them for their religion; calling it persecution.
But the righteous Lord Almighty, was pleased for His Holy name`'s sake,
and in tender mercy to His suffering people, to turn the battle to the gate,
in favor of the everlasting Gospel of our Lord and Savior Jesus Christ;
forever and ever adored, be His Holy name!

After meeting, I rode five miles before I stopped to dine;
but a number of those Ranters followed me, and brought their champion with them.
I was favored to keep much in the quiet, and let them run on awhile; then,
as it opened clear and lively in my mind,
I called their attention to a few binding points,
which I requested them to remove out of the way, by proof and sound reason,
or their doctrines must fall, as I should not admit bold assertions only,
to destroy proof.
This brought them to a stand, and soon to silence,
and I embraced the opportunity to tell them what I thought of their principles,
and what they were doing for themselves, and trying to do to the Society they had left;
and I felt to admonish them, which I did faithfully, and found peace in so doing.
They seemed quite willing to get off as easy as they could, and glad was I,
feeling there was renewed cause to give thanks to my good
Master for helping me through so easily.

I passed on, taking meetings until I came to Staunton Hill.
While thereabout, I had a meeting where a meeting had once been held,
but was now laid down, there being so many Ranters among them,
who created great disorder--which Friends kept from me.
As my concern was general, a meeting was appointed there;
a number of that class came to it, I think, as many as half the meeting.
I had not sat long, before I was made sensible, that I was amongst a dark people,
who were carried away with wild and strange imaginations, as much so,
as ever I had fallen in with.
I had to address them in these words:
"`The consequence of imbibing pernicious principles is very dangerous,`"
and was led to show what conduct and disorder it would bring forth.
The word of Truth went forth with that authority, that before I sat down,
they settled down and hung their heads, and some of them wept.
Truth rose into dominion, and reigned that day.
They let me pass quietly off,
and Friends who went with me expressed their joy that they kept still,
informing me that I could not have described their conduct and conversation,
and the censure they cast upon Friends, more correctly, if I had lived among them.

This made my way in that part of the country,
so that I went through the rest of the meetings of that Quarter,
and found pretty open doors with Friends, having much arduous labor amongst them;
but the Lord being my Leader and helper in every needful time,
way was made for me many times, where there appeared to be no way.
Blessed be His Holy name!
From this, I went into Cornwall Quarterly Meeting, attending Rosendale first,
where I had painful labor; things being much out of order;
and next at Little Esopus Monthly Meeting,
where I think I was never more sensible of disease extending
from the crown of the head to the sole of the foot;
they being full of wounds and bruises, and putrefying sores.
With the help of my good Master, I cleared my mind amongst them, in a plain, coarse way,
and passed on.
I had not attended more than one or two meetings, before I had to go back to Rosendale,
and have a second meeting, which was no less painful than the former.
I turned, and took another course, but had only a few meetings,
before I had to go to Rosendale again, and had the third meeting with them,
and endeavored to clear my mind faithfully amongst them; but after getting away,
I told Friends, it seemed to me,
there was something very deathly and wounding in that meeting;
and notwithstanding all that had been done, I thought the cause was not removed,
but I felt that I had cleared my mind as to any further public labor with them.
They then told me that there was a difficulty in that meeting, of five years standing,
that had set the members of the meeting and families at variance;
that the Monthly Meeting had made several trials to settle it, but had not succeeded,
and that members of Society had got into the law.
This account blocked my way from going forward.
After musing upon it several hours,
it came into my mind to take two Friends--whose names were presented
to my view--and go back to Rosendale as privately as we could,
and if we took hold of the business right, we should settle the difficulty.
I slept quiet, after taking this view of the subject.

The morning following, I called on the two Friends, and opened my prospect to them.
They said they would go, but seemed very doubtful of success.
I told them I was willing to lay by that day, to give them time to consider of it,
and accordingly did.
The day following we went, and when we told our business, it alarmed the parties.
I had told the two Friends that they must go forward and take the laboring oar,
but they might make use of my name when they could to good advantage.
They proceeded accordingly, and it was thought it did much better for me to set and hear,
and once in a while make a serious remark, than to have gone into it otherwise.
I think it took us two days and a half to bring the business to a final settlement.
But when we came to go into the business,
it appeared that one of the contending Friends had committed the crime,
in a poor part of the country, of getting richer than any of his brethren,
and not by speculation, but by good economy and prudent industry.
And now it was to keep him down and not let him get proud.
It seemed this Friend and his wife were desirous to have the business settled,
and were brought to an agreement, at a considerable loss of property.
The business was agreed to by all parties; but in a few hours the other side flew off,
and did so three times,
and seemed not to regard their promise until the suit was
like to turn to their discredit and disadvantage.
They then complied, and signed in article of settlement.
We could have given no countenance to the loss the Friend sustained,
had he not given way to improper resentment,
and made some wrong moves in his own defense, and had given advantage,
which the others were disposed to hold on to.
So that we thought it best to advise him to comply.

After getting through this siege,
I passed through the remainder of this Quarter pretty smoothly,
and crossed the Hudson river into Nine Partners Quarterly Meeting,
and had meetings at Poughkeepsie, Pleasant Valley, and Oswego; at the latter place,
I attended a Monthly Meeting.
Hereabout was another set of Ranters, whom Friends had disowned;
but I had not fallen in with them before, in this part of the country, that I knew of.
To this meeting, two of their champion preachers came.
Here, I felt my mind arrested with a question that was so singular,
I did not know for a long time, what to think or make of it; at length,
I became persuaded it was best to let the meeting have it, and arose on my feet, I think,
with these words: "`I have been thinking, whether there is any person in this meeting,
who has ever read in any history that may be relied on, or found in the Scriptures,
that God ever created such a creature, as all mouth and no ears.`"
Here, I made a pause, and then proceeded: "`if God never made such a creature,
and if there were such creatures in mutability,
then it must be that the devil had a hand in making them such creatures.`"
I then proceeded as I felt ability and utterance given,
and was led to show that such a creature was out of all proper shape,
and could not be in the order of the Great Creator, and must be a monster,
and therefore could only work in its own element, to destroy harmony, lay waste order,
which was God`'s creation, and spread confusion amongst the inhabitants of the earth;
and it would be wise for the children of men to be on guard and beware of them.
I was led largely, plainly, and fully into the subject, and enabled to clear my mind,
so as to feel well satisfied.

Soon after the close of my testimony, the meeting proceeded quietly to business,
but these men were so disturbed, that the champion of the two,
stayed near by until the meeting was over.
I went direct to a Friend`'s house to take dinner; he came there,
and walked to and fro by the door, sending in word several times,
that he wanted to talk with me.
So, as soon as I had done eating, I went to him.
We talked, I think, for an hour; he poured out heavy censures on me and Friends,
for awhile, I thought best to keep much in the quiet, until he had emptied his store.
I then asked, what his principles were, that he and Friends could not agree?
He then stated, that he believed mankind came into the world as all other animals did,
without any other souls than the beasts had;
their souls went down to the earth when they died, and so it was with mankind,
until they were quickened by Grace, and Grace, if they were faithful to it,
immortalized the soul.
I asked him, what became of children before Grace came on them?
He answered, "`they died as beasts did; their souls went down into the earth,
and ceased to be.`"
I asked, what became of the man who embraced Grace, and ran well for a season,
and then made shipwreck of faith and a good conscience, and died in that state?
He answered, "`the Grace returned to its own fountain,
and the man I dropped into the condition of the beast, and when he died,
was like the beast; he ceased to be.`"
I asked him, if he preached such doctrine in our meetings?
He said, "`Yes.`"
I replied, "`I think Friends have done well to disown thee,
for these are not our principles, and never were, and thou knowest it;
and what dost thou want to be a member for?`"
He said, "`to spread the Truth among the rising generation,
for the old ones would not be moved, and his being disowned,
deprived him of the privilege of doing his duty;`" and then exclaimed, "`that old,
superstitious book, the discipline, will tear you all to pieces yet.`"
I answered, "`Thou art mistaken, for it has proved a wall around our Society,
for almost two centuries, which always has enabled them,
when giddy headed men rose up and propagated false principles--and
would not desist--to put them out of Society,
and prevent their spreading discord among the brethren,
and drawing the youth into wild notions;
and thou wilt find it will answer the same purpose now, if kept to.`"

This stopped him on that point.
I embraced the opportunity to ask him, how he came by these principles?
He said, "`by revelation.`"
I thought it now time to bring him to the binding points,
which had stopped the mouths of all his brethren I had fallen in with; so I asked,
"`what proof they gave of their revelation?`"
He said,
"`the same as the prophets did--'`thus saith the
Lord`'--and those who did not receive them,
were punished, and so they would be now.`"
I then remarked, "`your revelation contradicts abundance of the Scripture;
and seeing that God chose His own way,
when He introduced the bible into the world by the hand of Moses;
He sent him with a message,
'`Thus saith the Lord God;`' and then endued him
with power to work marvellous signs and wonders,
such as had never been seen or heard of,
and in the presence of unbelievers as well as believers, in proof of his revelation.
And it did not end here; it continued with Joshua,
and several of the prophets at different ages; and this is not all;
when Jesus Christ came into the world to introduce the Gospel to the people,
He did not ask the people to receive Him as Christ, until He had worked many miracles,
such as had never been seen or heard of before, and far to exceed Moses;
for Moses`' miracles were punishments, and the display of the power of God on the wicked.
But Jesus Christ`'s miracles were benevolence,
and mercy to enduring humanity--the full revelation
of His love and tender mercies to all people.
Yet, He did not call on them to believe Him, but for the work`'s sake; for, said He,
'`No man hath done the works ye see me do.`' And now, friend, thou hast told me,
that your revelation has carried you beyond all the old prophets,
beyond the apostles and all our ancient Friends, into the vision of light;
beyond what any of these ever saw, and that it has carried you beyond the Scriptures;
and in that, your revelation contradicts the revelation of the Scriptures.
For the power of working miracles did not end with the outward Ministry of Jesus Christ,
but rested on His apostles, His successors, long after His ascension.

Now, friend, we look back as well as forward, and when we reflect seriously,
on the mighty, and long continued evidence of both the former dispensations,
we think that He is the same God He ever was, and changes not;
and that His love and long forbearance, is as much toward the people, as it ever was;
and we think, that if God was about to reveal a new dispensation,
which would be more glorious than either of the others,
that you would give an evidence answerable to the magnitude of the revelation;
seeing He has always taken that way.
So, that there are too many sound heads in our Society,
to be drawn of of this ancient foundation,
and well proved doctrine of the Gospel and Divine revelation,
by nothing better than the bold, empty assertion of a few confident men; and that,
in contradiction to all well proved revelation.`"
To all this, he made no answer; but mused awhile, and then exclaimed, "`I always heard,
that thee was a tender-spirited, charitable man, but I am disappointed,
for I now see that thou art as much laced up in that old buckram superstition,
as any of them.`"
And so we parted.

Previous to this, I had a number of meetings laid out,
and notice of the appointments timely given; so that when I came to Crum Elbow,
Little Nine Partners, and the Creek, I had full and satisfactory meetings;
but when I came to Stanford, though Friends had received the notice,
they had made no appointment for the meeting, so I passed on to the Plains,
thence to Nine Partners; then turned about, and attended the Creek Monthly Meeting.
Here, I observed that two Friends mostly dictated the business,
and when any one opposed them, they bore heavily upon such; and if they said nothing,
they urged them to unite: the effect was, that they had nearly all the speaking to do,
and the business went heavily.
After the business was through, I told them what effect such conduct had on the meeting,
and felt good satisfaction in telling them my mind.
There was a complaint brought against a member for drunkenness,
and was under the care of a committee, and no favorable report;
but these two Friends strove hard to throw it out,
and have no further notice taken of it; yet, they did not effect their purpose that day.

The next day, I attended Stanford Monthly Meeting, held at Little Nine Partners,
where I had satisfactory service to myself and Friends.
After meeting, I set forward for home, and thought I saw my way clear,
expecting to be at Hudson meeting the next day.
I had a borrowed horse; for when I was in the Otego country, my beast was taken sick,
so that she could not travel, and a kind Friend, Aaron Wing, lent me a noble young horse,
a fine traveller, to go the rest of the journey.
All the time I had him, he never lost his course for home,
and whenever he saw a road that turned that way, he would pull hard for it.
But on this afternoon, when I started, and thought to make good headway,
as the horse would travel freely towards home, after a few miles drive,
I came to a road that turned from his home, and the horse, for the first time,
pressed hard to take it; but I urged him by, and though a lively horse,
he afterwards traveled slowly and dull, so that I had to urge him on.
A heavy feeling came over me; I could not see for what,
but it increased as I went forward, and I concluded, if I came to another road,
and the horse made a choice, he should go where he would.

I soon came to a road that turned the same way the other did; the horse crowded for it,
so I let him go; he then pressed ahead, and traveled fast.
My mind became easy, and I went on until I came in sight of the stage road,
concluding to let the horse go where he pleased; when we came to it,
the horse turned again from home, and went ahead fast, until near night,
before he slackened his speed.
I then enquired if any Friends lived on that road, and was answered,
that some distance beyond, a half Quaker lived, and his wife was a whole one.
I passed on, and enquired again; was answered as before.
A man standing by, said he was his neighbor, and if I would let him ride,
he would show me his house.
When I got there, I found him so drunk that he could but just totter about,
and not able to talk plain.
When morning came, I cleared my mind, and left him, and went on to Crum Elbow;
being first day, we had a large, solemn, favored meeting,
so that I was satisfied I was in my right place, though a horse was my pilot.

After meeting, I informed Friends, with whom I lodged, and how I found him.
They then told me, he was the man the complaint stood against,
that the two Friends strove to throw out, as being taken up on a trifling affair;
and that he had been in the practice of drinking strong liquors, to intoxication,
for years, and it was much known round the country, among every sort of people.
I said in my heart,
"`alas! if these are the principles of those who sit at the head of government,
an Elder and a Minister, who will rise up and endeavor to suppress discipline,
and prevent the testimony of Truth from going forth against such filthy evils,
it is no marvel that it is felt,
that the Spirit of the Lamb of God groaneth under crucifying sufferings;
and that the spirits of the upright mourn in sackcloth and ashes,
to see the wall about the Church broken down,
by those who ought to stand as faithful watchman,
to keep it in good repair and good order.
Where there is such unsoundness in the head, the faintness is such,
that when they attempt to do the business of the Church,
it drags like Pharaoh`'s chariot wheels.`"

From Crum Elbow, I felt drawings in my mind to attend my own Yearly Meeting.
After considering it, I became satisfied it was best.
I took Amawalk, and Shappaqua on my way; I was led into close, painful labor,
there being much of a worldly spirit, self-security,
and worldly wisdom in these meetings, so that it was painful;
being made sensible that the true spirit of the Gospel
was much oppressed in the minds of many,
but not in all, I think.
I attended the Yearly Meeting, which was deeply exercising,
in the several sittings thereof;
yet the business was conducted in a good degree of condescension, and ended quietly.
After the close of the Yearly Meeting,
I felt my mind arrested to be at Shappaqua meeting, on first day.
When I got there, my Master showed me a monster, and his name was Great I,
and my Master constrained me to describe him to the people,
that they might know he was a monster, and not a disciple of Jesus Christ.

It was a solemn day to me.
At four in the afternoon, I had a meeting at Croton where my testimony did not suit all.
I was led to preach up the doctrines and acknowledge the Divinity of Jesus Christ;
and after meeting, was treated with great coolness.
From here, I went pretty directly on to return my borrowed horse; and when I got there,
my little mare was dead, and I had to borrow the horse the second time, to get home,
where I arrived in the 6th month, after an absence of five months or more,
in which time I had many sore conflicts to pass through.
But such was the goodness of the Lord, that He supported me,
feeling His strong arm underneath, to bear up in every trial,
and His power to give strength in every battle,
with wisdom and utterance in in every needful time.
Thus the Lord marvelously led me along,
in such a way that I had the opportunity of clearing my mind to good satisfaction,
and to silence those wicked, false reports, which were sent over the country; so much so,
I was credibly told, that one of the Friends who gave the reports credit,
wrote to his correspondents and connections,
informing them that I had been in his country,
and had visited nearly all the meetings in those parts,
and that my conduct and labors in the ministry had
been to good satisfaction wherever I had been,
and that he had heard me; that he never had better unity with me in any part of my life.
This got to them before I got home, and stopped their clamor;
so that through the mercy of the Most High God, in his interposition,
all was still without, when I got home, and my mind richly filled with peace.
Blessed, worshipped and adored, be the Lord, my Redeemer, forevermore!
