== Chapter X

The first time I attended our Yearly Meeting, after my return from my western journey,
(from which I had been absent for several years,
owing to my being in other parts of the country on religious service),
I found the minds of Friends like the troubled waters,
as two of our Quarterly Meetings brought up proposals in strong terms,
to make an alteration in the discipline in the appointment of Elders;
to drop the practice of appointing them as always had been
the practice ever since Friends had been a people,
and to appoint them only for four years.
This aroused Friends, and led to the enquiry as to what was the cause of this.
It was soon discovered to be Elias Hick`'s followers, pretty generally,
who had already made a heavy attack on several of our sound,
faithful Ministers and Elders, in Philadelphia Yearly Meeting.
They had disowned several for opposing Elias Hick`'s false doctrine,
and infidel principles, but they were all restored by appeal.
This aroused the Hicksites in that Yearly Meeting,
and the same plan was urged in our own Yearly Meeting.
Several of the first members of the Yearly Meeting, living on Long Island,
were under dealing, and the charge of a committee,
for opposing Elias Hick`'s false and pernicious doctrines,
which conduct much aroused the sound part of Society.
Yet, the Hicksites crowded their plan so hard,
that they got a large committee appointed to consider the subject.
When the committee sat on the subject,
there was so much weight in favor of the sound part of Society,
that the Hicksites could not make headway; so the committee concluded to report,
that they could not agree to propose any alteration in the discipline on the subject.

This made a stir in the meeting for sometime,
and the Hicksites crowded hard to keep the subject in the meeting.
At length, to get rid of it for that time, it was submitted to,
and put over until the next year.
This move so fully spread the subject in every part of the Yearly Meeting,
that when the year came about, Friends seemed settled, and prepared to meet it;
but when it came before the meeting,
the Hicksites would not give up without the appointment of a committee.
When the committee came to go on to the ground,
the Hick`'s party found themselves weaker than they were the year before,
and were induced to comply with a similar report.
When it was read in the meeting, the Hicksite party showed a good deal of agitation;
but Friends kept much in the calm, keeping close and steady to the point.
This seemed to increase the heat with Elias Hick`'s party,
when they saw they were not going to carry the business as they intended; so much so,
that the Friends who favored the committee`'s report, were censured, and reflected on,
and frequently with abusive language.

Friends kept steady, and deliberate, but at length the heat ran so high,
that when a Friend sat down after speaking, though he spoke ever so calmly,
by the time he was on his seat, and sometimes before,
several of Elias`' followers would be up at a time, all speaking at once.
This, I think, continued an hour--though Friends several times called for order,
but had little or no attention paid to them.
At length, Elias Hicks called for order, and his followers quieted,
so that the meeting became tolerably still.
Elias then stated,
"`We cannot give the matter up without seeing if the meeting could not
decide it,`" and then stated the majority was the weight of the meeting,
and that every member in the house had an equal right to his sentiment,
calling pressingly for all to come forward and give their sentiment,
and the young men in particular,
asserting they had as good right to give their sentiment as any.

When he sat down, they went on rapidly uniting with the proposed alteration;
some times several up at once, and several were seen to rise and unite twice,
and others three times.
After awhile they came to a stop, when Elias arose quickly and proclaimed,
"`All of three fourths majority; we have got the judgment of the meeting.`"
A Friend arose quickly and observed,
"`The other side has not had the opportunity of giving their sentiment;
and the subject will not be given up,
until they have a chance to speak their minds;`" and then advised to proceed orderly.
They did so, and in the course of half an hour,
Elias Hicks had the opportunity of seeing a large majority,
come forward in favor of the old institution;
yet he was so far from acting up to his own declared sentiments in favor of majorities,
when he saw how it turned, he quickly arose,
and declared that the meeting was so divided that it could not decide upon it,
but must be again referred another year, and not allowed to be taken from the minutes.
This was submitted to, but through the remainder of the meeting, business dragged heavily.

Much enquiry continued to be made out of meeting, as to the cause of all this,
and much agitation prevailed amongst Friends of all classes;
many believing there was something the matter, but that it was kept out of sight; which,
at that time, was the case--as E. Hicks`' principles were not then generally known,
though they had been preached up in a blind way for many years,
to the great exercise of discerning Friends.
Much tender advice had been bestowed upon him from time to time,
to save him from running out, not only to nothing, but much worse than nothing,
but all to no good purpose.
All this time,
he was in the plausible appearance of great love and concern for the cause of Truth,
and the welfare of the Church; and in this way,
he was diffusing--in private--his deistical sentiments; and by letters,
he spread his principles far and wide, before Friends were generally aware of it.
About nine years before the division took place in our Society,
in consequence of the doctrines promulgated by Elias Hicks,
he came into our country with credentials to perform a religious visit.^
footnote:[It appears from a record that has been kept,
that Elias Hicks was here in the 2nd month, 1819.]
I was in Ferrisburg on temporal concerns, and was told while there,
that Elias Hicks was in the neighborhood,
and would have an appointed meeting there that day,
and that it would be largely attended, for everybody that could would come.

I had no thought of attending it myself,
but intended to return home as soon as I had finished my business.
When that was accomplished, it pressed upon my mind with such weight,
that I believed it right to stay and attend the meeting, which I did.
It was a great gathering of people.
Elias rose very early in the meeting, and stated that,
"`In the beginning God created the heavens and the earth, as we read in Scripture.
He also made man in his own likeness, as we read in Scripture;
and prepared a garden in Eden, in which He placed the man and his wife;
and also the tree of life, and the tree of the knowledge of good and evil,
in the midst of the garden, as we read in Scripture.`"
He made a full stop,
then took up the tree of knowledge of good and evil--a
distinct subject--and occupied a full half hour,
to make it appear that there was no other evil in space;
and three times asserted positively, that it was not possible to be otherwise;
yet he brought no proof only his own statement.
By the way, to polish his discourse, he recommended a good deal of moral conduct.
He then took up the tree of life, and treated upon it separately,
for about another half hour, and three times stated without reserve,
that the tree of life was God Almighty himself, and it could not possibly be otherwise;
but offered no proof except his own assertion; and as before,
dressed it with the beauty and happiness of good moral conduct;
and had much to say on the right and liberty of choice.
He made a full stop, stood a little while, and then stated,
"`We have a right to choose good or evil, just as we please; and take that right from me,
and I would not value my being worth having!`"
For about half an hour,
he appeared to labor with much earnestness to substantiate his statements,
and then stopped, and soon closed the meeting.

I walked into the yard with a heavy heart, and a grieved mind,
intending to get my horse and go immediately home, without speaking to any one;
but hearing some one following me, with a quick step, I halted a little,
and a voice said, "`Stop, I want to get thee by the hand.`"
I turned round, and one of our head elders said, "`Joseph,
dost thou know that it is contrary to discipline,
to show restlessness during the preaching of a minister, while in unity with the body?`"
I said, "`Yes, and I have good unity with that discipline.`"
"`Well, thou showed it today three times.`"
I said, "`Did I?`" He said, "`Yes, and the young people noticed it.`"
"`Didst thou see it?`"
"`I did.`"
I replied, "`Then I will not dispute it.`"
He said, "`Thou hadst not unity with him today.`"
I replied, "`I had not.`"
He said, "`What is the matter?`"
I answered, "`He preached false doctrine, and I can prove it,
if you allow the Scriptures for a test,
and thou may take me before any tribunal thou choosest.`"
We then parted.
I returned home, and told my wife the discourse, and my feelings,
and that I would follow him through the Quarterly Meeting,
and attend every meeting which he did,
in order to have an opportunity of conversing with him.

I perceived that the Elder intended to have a company;
but I thought it best to take him alone, according to Gospel order,
and then was willing to meet him before whomsoever he pleased,
but could not get an opportunity.
The next day, he was at the meeting to which I belong,
where he gave us a similar discourse, but not so bare-faced.
After meeting, I asked him to go to my house; he answered, "`No,
I am going to another Friend`'s house.`"
I went home, took dinner, and went to that house immediately.
When I arrived, he was rising from dinner.
I beckoned to him, and went into another room; he followed, and I shut the door.
I soon said to him, "`I wish to have some talk with thee,
with the privilege of speaking freely, openly, and plainly; without thy taking offense,
and thou shalt have the same liberty with me;
for we are both men who know how to treat each other properly,
and he that refuses this treatment,
shall forfeit his right of having any further attention paid to him.`"
To this he cheerfully agreed, and gave me his hand.
I then informed him, that I was dissatisfied with his preaching; to which he replied,
"`Well, wherein?`"
I then proceeded to repeat his text, word for word, and said,
"`This gave the people to believe thou wast going to treat
upon the text agreeably to the tenor of it.
Thou acknowledged that God planted the tree in the midst of the garden,
as the Scripture said;
and then for full half an hour labored to make us
believe that that was the only evil in space,
instead of explaining it according to Scripture;
and three times thou asserted it was not possible to be otherwise.
I cannot take up with thy bare assertion; I must have better proof than that;
for thy idea makes the Almighty the author of all evil; for he planted the tree.`"

He said, "`What other evil is there then?`"
I replied, "`The Bible tells of a serpent.`"
"`What!`" said he, "`a snake?`"
I replied, "`No, I think thou knowest better than that; no, an evil spirit,
inimical to all good; and if thou dost not know of such a devil out of thee,
thou art not fit to preach.
Thou and I have been such fellows when young, and we would try what we could do;
and when we have been in our high career in company, something has met us,
so clear in its manifestations, so powerful in its convictions,
and so convincing in its evidences,
that we have had to acknowledge that we had done wrong, in thus going into loose company;
and thou hast felt it so severe, thou hast concluded to refrain from such courses;
and as thou didst so, thou hast felt quiet and peace,
and as thou continued in well doing, thy peace has increased.
All this thou knowest, yet by unwatchfulness, there has something from somewhere,
(for it was not in thee, when that which brought peace was,
for they cannot both abide in the same person at the same time,
we both know,) that suggested to thy mind, that the serious thoughts were all a notion;
that thou didst not make thyself, but was created by the Almighty;
and that He gave thee thy dispositions, and created objects of delight,
and placed them before thee, that thou mightest enjoy them; but when thou hast listened,
and put forth thy hand, and embraced the temptation,
thou hast always felt thy peace stung to death, and thy conscience sorely smitten.
I want thee to tell me what these two are that will not agree; the one urging to right,
promising peace, and always performing, when we obey; the other enticing to do wrong,
and promising increase of happiness, but always disappointing us.
If that tree is the only evil in space, what is that which thus follows us,
which we both know?`"

He said.
"`I do not mean to discard the idea that there is an evil spirit which tempts us.`"
I said, "`What then dost thou mean to deny?
Thou certainly denied it in thy preaching.`"
He said, "`I mean to deny that there is a great mawking devil,
with one ox foot and one man foot and fire eyes,
which appears to the people to scare them.`"
I said, "`I am disappointed in Elias Hicks.
I always thought him to be a man of talents.
I did not expect to hear such words come out of his mouth.
I have no belief that there is a child in our country, twelve years old,
who has learning enough to read, that believes such an idea.
Matter does not inhabit the world of Spirits.`"
He remarked, that "`many of our Quaker Ministers believed it.`"
I requested him to stop, and remarked,
that "`the Bible tells us that our Savior cast seven
devils out of Mary Magdalene,`" adding,
"`thou may see how short thy ideas are.`"
I then took up the tree of life,
and his statement of God`'s planting it is the midst of the garden,
according to Scripture; and his statement of its being God Almighty Himself,
and could not possibly be otherwise--and requested him to reconcile these two statements,
and make good, sound doctrine, or even good sense, which he declined attempting to do,
though I pressed him closely.

I then endeavored to show him, how confusedly he handled the Scriptures,
in treating the fall of our first parents,
and endeavoring to make it appear that there was no other evil in space,
but the tree of knowledge; as it plainly appeared that there were three criminals,
and three punishments stated as facts that took place,
and wished him to reconcile this with his discourse--in which he had crossed
himself--and I let him know that these were points I must have cleared up.
He made no reply, though I urged him.
I then dropped that point, and took up his assertion of our right of doing as we pleased,
and put sundry questions; whether light and darkness could be blended together,
and be one thing?
He answered, "`it is not possible.`"
I proposed to him, that "`good and evil, right and wrong, we knew, were in the world,
and that they were opposite, we knew.
Is there any such thing, as bringing these together, and making but one thing of them?`"
He answered, "`it is not possible.`"
I replied, "`each must have its spring of action, and place of existence;
now I want thee to show whether all good must not emanate from the fountain of good,
and evil from the fountain of evil; and as thou hast acknowledged that right and wrong,
good and evil cannot be brought together,
show where thou gettest thy right to choose evil, for thou didst not make thyself,
and thy rights are limited.
Where didst thou obtain liberty to do right if thou pleased, and wrong if thou pleased,
which thou prizest so highly,
that thou wouldst not value thy existence worth having without it?
Here, Elias, I wish thee to clear this up with Scripture proof, and sound reason.`"

He sat awhile, and replied; "`we are free agents.`"
My answer was, "`free agency I don`'t deny; moral agency I don`'t deny;
but we were created agents, we were not our own creators.
Free agency belongs to the Almighty; He is His own agent, His own being,
His own vast dwelling place; we receive all our power, which is agency, from Him;
we are limited creatures.
Now show me wherein we are not accountable for those
powers and faculties which are given us,
and if accountable, where is the unlimited freedom?
I deny that Adam was brought into existence, a free agent;
for he was God`'s representative--His image--and placed lord of these lower regions,
free from guilt and shame.
His free agency given him, therefore,
stood in freedom of fellowship and communion with his God.
I can see claim to free agency in no other point of view.`"
"`But where was he after the fall?
A great alteration took place; for he was put under punishment all the rest of his life.
Was he free while under bonds, and these never to cease but with life;
and the same with his wife, for the same length of time?
Were they then, or ever after, free agents?
But there was an agency renewed to them; they were to have dominion over the earth,
to multiply and replenish it, and to till the ground; this I call moral agency.
But that which they lost and never regained,
they never could bestow upon their offspring,
and this shows the reason why the human family needed a Mediator.`"

He sat some time, entirely silent, and then said, "`Free agency I will not give up.`"
But he offered no defence in favor of it.
I replied, "`when a man will not give up a point which he doesn`'t attempt to defend,
I think it is because he has not wherewith to support his argument; therefore,
I shall urge it no longer.`"
I then said, "`I have traveled after thee in New England a number of weeks;
in Maryland and Pennsylvania, I was two weeks behind thee,
for more than two hundred miles;
in all which places I heard many remarks upon thy preaching,
and some upon thy private conversation.
I was frequently interrogated, whether I was acquainted with Elias Hicks,
and had unity with his doctrines.
I had one way of escape, and was glad of it.
'`I have not heard Elias Hicks preach within five
years.`' They would then state what he preached,
and wished to know my sentiments.
I let them know they were not my sentiments nor doctrines.
I queried with them, whether they had been honest and let him know their dissatisfaction.
Some said they sought such opportunities, but could not obtain them; others,
that he appeared so great that they were afraid.
I replied, '`I should have talked with him; and if ever I see him,
I intend to tell him how you talk about him.`'
They said, '`thou mayest tell him the whole,
for he will never make Quakers by his preaching, but he will make infidels.`'

"`I agree with them; and I have no more unity with thy preaching and sentiments,
than I have with a Presbyterian Priest, who preaches unconditional election.
But as we have discoursed calmly, and are now going to part,
I cannot in conscience give thee my hand in fellowship;
but if thou wilt receive it as a token of civility, and let me reserve the fellowship,
I will give it upon that principle.`"
And I reached forth my hand.
He took it, and we parted.
He stayed hereaway some time; held meetings, and made social visits,
until he had enlisted every Elder in our Monthly Meeting,
and several influential members; and went off and left me in as hot a furnace,
as he could prepare for me.

When the Hicksites thought they had become strong enough,
they made strong efforts in many places, to displace all the sound Clerks,
and place others in their stead, in order to hold the books and records.
They made a resolute attempt to displace the clerks of our Yearly Meeting,
who had served several years, to the satisfaction of Friends;
but failing in their attempt, they manifested much uneasiness,
and some of them cast unhandsome reflections on the clerks.
The great struggle was with the Ministers and Elders.
In their meeting it was proposed (by a woman Friend from England),
to appoint a solid committee to go into a judicious investigation of the subject,
which Elias violently opposed;
and when any attempt was made to bring the dispute to a settlement, he,
with a few others, would oppose it with violence,
making long replies to every one who spoke;
their replies being often full of harsh and bitter reflections.
In this way, they produced such confusion in the meeting,
that the business could not be done in order, and this continued,
until Friends gave up the attempt, and passed through the Yearly Meeting, (1827),
as well as they could.
When a knowledge of the cause of contention became more spread,
the Hicksites saw their former mask would not hide them any longer.
They came out more open and bold in their principles,
laboring in every part of the Yearly Meeting where they could,
to make strong their bands in preparation for a large sweep the next Yearly Meeting,
(1828).

Elias, and one of his confederates, in the spring of that year, went to Philadelphia,
and joined a body that were of his principles, who had already separated from Friends,
and held what they called a Yearly Meeting, with which, he fully identified himself.
A great number of these seceders from Philadelphia Yearly Meeting,
many of whom were disowned, or under dealing for their out-goings, came to New York.
Several of these imposed themselves upon us at the
opening of the Meeting of Ministers and Elders,
on seventh day.
Friends bore long with them without casting any reflections,
yet stood firm in the maintenance of our ancient
order--not to transact the business of the Society,
before those who are not members of it--and in return for their calmness,
received little but harsh reflections and censures,
which are beyond the power of my pen to describe.
In this way we passed two long sittings,
and adjourned until after the opening of the Yearly Meeting at large, on second day,
when several hundred of these intruders poured in upon us,
and proceeded as they had done in the other meetings.
Friends objected to proceeding to business, until the meeting was select.

The Hicksites insisted that the regular clerk should not act for the meeting at all,
and in their contending, used abundance of censures; but Friends kept calm,
and close to the point in hand,
until the meeting got into such a general uproar
that no business could be done in decent order.
At this juncture,
a Hicksite proclaimed that the representatives had
agreed to propose such a Friend for clerk,
which was not strictly true;
for it was ascertained that a large number of them knew nothing of the agreement.
This was objected to by Friends, and united with by a few Hicksites,
and quickly a cry was made by a number speaking at once, "`Clerk,
go to the table!`" which he did,
and a part of the way by passing over the heads of Friends,
by stepping from the back of one seat to another.
The regular clerks were crowded away, and he was placed in their stead.

At the time the cry was made for their clerk to go to the table,
I think there were not less than forty or fifty on their feet speaking,
some of them very loud; many were drumming with their feet, others with their canes,
and many others with their hands, on the backs of the seats,
while others were laughing and hissing, and acting many kinds of gestures,
indicating extreme bitterness.
The like I had never seen before, though I had traveled all over this continent,
where there was known to be any body of Friends,
and had then passed the 66th year of my age, had seen much,
but nothing that would compare with this horrid scene;
neither had it entered my heart to believe that there was any set of men,
professing the peaceable principles of a Quaker, who would act so void of all truth,
justice, and honor, as they did, as though they feared not God, neither regarded man,
and believed there was no devil, or future punishment.

When the din had so abated that a voice could be heard,
a Friend audibly proposed for all thou who believed in our ancient principles,
and wished to adhere to and maintain the ancient order of our Society,
to withdraw to the basement story, to hold the Yearly Meeting.
Accordingly, we arose, and went out in a body;
but when we got to the door of the apartment, we found it locked and guarded,
and we were told, in a taunting manner, that if we attempted to open the door,
the law would be put in force against us.
Friends replied, that they should use no violence,
but wished to enjoy their rights peaceably.
When we found we could not be permitted to enter,
we retired to a Medical College in the city, where we transacted our business in unity,
harmony, and a peaceful quiet.
A new field of labor now opened,
in expectation that the Hicksites would assume to be the Yearly Meeting,
in which Friends were not deceived; therefore,
in order that sound Friends should not be drawn away by them, an epistle,
setting forth the cause of the division, and the treatment Friends endured, was drawn up,
and a large committee appointed to accompany that and the extracts,
down to the Preparative, Monthly, and Quarterly Meetings, as promptly as way might open.

The Hicksite Yearly Meeting closed one day before ours, at the close of which,
I returned home, being aware that the two eldest and most influential men, Elders,
had for many years adhered to those separate doctrines, and having become strong therein,
endeavored to spread them;
yet I had opposed those principles in every part of the Quarterly Meeting,
wherever I found them, showing that it was rotten infidelity,
wrapped up under the plausible pretext of a more profound, religions knowledge,
than Friends had ever attained to before.
My opposing it steadily, which was mostly among the younger class,
soon got to the Elders, and I was called on by them, and inquired of,
if I opposed such sentiments.
I let them know that I did, and gave them my mind, letting them understand plainly,
that if such sentiments prevailed amongst Friends,
the time would come when it would make the greatest division that ever was,
since Friends were a people; as their principles were not those of Friends;
being deistical sentiments, which seemed to offend them.

I was told in reply, that they were Elias Hick`'s sentiments, and that he was no deist,
but the greatest man in the world; and one of them said,
"`I believe he knows more than George Fox did.`"
I replied, "`I do not go to Elias Hicks or any other man for my religion.`"
I was replied to, in a short way,
that he was not afraid to trust himself upon Elias Hicks`' knowledge.
Thus, all our friendship closed, as they continued, both in public and private,
whenever they thought it would be borne,
to pour out censure upon me to destroy my credit as a Minister
and my influence in the discipline and amongst Friends;
having others to back them openly.
Not knowing how far their pernicious principles were diffused, it seemed at times,
as though there were but a few steps between me and death.

Before we left New York,
I told Friends of my own Quarter who were appointed
with me on the Yearly Meeting`'s Committee,
that I thought it would be best for us to furnish ourselves with epistles and extracts;
giving them my reasons, with which they united;
yet when we got home the Hicksite epistles and extracts
were circulating from hand to hand,
very currently.
The minds of Friends seemed agitated, and things looked gloomy;
yet they were favored to keep steady and calm,
so that when the documents from our Yearly Meeting were offered
to the Preparative Meetings of Starksboro Monthly Meeting,
at which time there were four, they all received and acknowledged them,
without a dissenting voice.
Two of the Preparative Meetings at Ferrisburg Monthly Meeting,
received them without any hesitation; the others refused.
The Preparative Meetings of Peru Monthly Meeting refused
to pay any attention to the Yearly Meeting`'s committee.
When Monthly Meeting came, the committee presented our epistle and extracts,
which were violently opposed by a few,
and the committee was treated with very unhandsome language.

At length, a Friend proposed to allow more time,
as he thought they were not enough informed to come
to a judgment on so weighty and important a subject;
adding, he had seen the epistle and extracts on one side,
and that he wanted to see them on the other,
before he could form a judgment to his satisfaction,
and thought it was the case with others.
This was satisfactory, and the subject was laid over for one month.
At Ferrisburg Monthly Meeting,
the two Elders censured us for attempting to come there and offer an epistle
from that company who had gone off from the great body of Friends.
The committee calmly showed them,
that our Yearly Meeting was in full unity with the Yearly Meetings in Europe,
and nearly all on this Continent, and that theirs was disowned;
which somewhat checked their boasting.
After enduring many reflections,
a proposition was made to let it rest one month for consideration,
which appeared to be the mind of several; and the committee uniting, informed,
that all who wished for information, would have the epistle and extracts handed them,
at the close of the meeting.

Nearly all came forward and were furnished; and here it rested for one month.
Starksboro Monthly Meeting received, and cordially united with the epistles and extracts,
without a dissenting voice.
When the month came round, we attended Peru again,
and renewed the offer of the extracts and epistles;
which met with a resolute opposition from a few; but Friends being now well informed,
a number desired to have them read.
The debate continued two hours; during this time,
the Hicksites often threw out heavy and harsh censure upon the committee,
one of them prophesying with affected solemnity, that we were in a delusion,
and should run out to nothing; yet Friends were favored to keep patient,
until the Hicksites had much exhausted their funds,
in a way that was not convincing in their favor.
At length it was proposed by a Friend,
that he thought it would be right for those who had spoken so much, to give it up,
and let the meeting decide, as they were not likely, by continuing the dispute,
to bring the business to a close; and seeing the meeting so fully united, they gave up.
The documents were then read and accepted; and the women`'s meeting did the same.

When we came again to Ferrisburg Monthly Meeting, and offered the extracts,
the Elders arose in vehement opposition, casting on us and the Yearly Meeting,
heavy censure;
calling the committee separatists--deluded imposers on Friends--pressing
us not to stand against the great,
and weighty body of Friends,
of which they were members--that such attempts have never prospered, and never would.
In this way,
they kept bearing down on the committee whenever they offered anything to the meeting,
until it was in such confusion,
that there would be five or six up and speaking at one time.
Several moves of this kind were made when any Friend arose to speak.
They seemed determined to run us down,
and the clerk--being a Hicksite--would have nothing to do with our business.
A Friend proposed for Friends to withdraw,
when a Hicksite arose quickly and said there was no need
of dividing,--he knew of nothing to divide for.
When he stopped, another arose and requested to be heard, and spoke lengthy.
The substance was, keep together a little longer.
Through the whole, Friends were favored to keep much in the patience.

When the last set down, I soon arose and proposed,
that all who believe in and are satisfied with the ancient principles of Friends,
propagated and maintained by George Fox and his contemporaries,
and wished to maintain our discipline and ancient order,
which was established by our forefathers,
which has proved a blessing to our society to the present day,
to withdraw as still as they could.--Then I went out to the school-house,
and found it fastened.
I had not expected more than one quarter of the meeting would withdraw.
But when I turned about and saw such a body standing,
and little lads from ten to fifteen years of age, looking as sober as old men;
and some of them with tears in their eyes, it so came over me, that for a short time,
I had enough to do to command the man.
After a short pause and recollection,
I thought we had nothing but the open canopy to hold our meeting under.
But looking around, I saw at the east end of the horse shed, there was a space,
where we went.
And by taking the seats out of Friends`' carriages, and picking up a few boards,
we seated more than forty pretty comfortably;
leaving only eleven men and three lads in the house,
although they had boasted of their great majority.
Shortly after we were seated, a pleasant calm came over the meeting,
which brought us into a tender and near unity, one with another,
which encouraged our drooping minds, to go forward in this sharp trial.
We appointed clerks, and having the minutes of two of our Preparative Meetings,
after a suitable introductory minute to organize the meeting,
we transacted the business in much harmony, and adjourned to Monkton.
The women kept the house for the day, but the Hicksites refused to act with them.
They also adjourned to Monkton, where we hold our meetings to the present time,
without interruption.

At the ensuing Quarterly Meeting, which came in course at Peru,
we had the company of several of the Yearly Meetings committee,
from New York and thereabouts;
and all three of the Monthly Meetings having fully
acknowledged the authority of the Yearly Meeting,
there was but little struggle in the Quarter,
and we went through with our business comfortably.
Yet, at the next Quarter, held at Ferrisburg,
there came a company of Hicksites from New York, Long Island, Saratoga, and Pittstown,
who got into the house early, and filled the seat at the clerk`'s table;
and when the clerk drew near, an individual from Peru, gave him a push to keep him off;
and when he, by direction, arose to open the meeting, the Hicksites opposed him,
and ordered their own clerk to proceed; Friends opposed this in moderation,
and civil language, and with composed firmness asserted their rights,
and gave their reasons.
This so heated them, that they fell to their usual practice of censuring,
a number speaking at the same time, until the meeting was in great confusion;
They withal let us know, that their meeting they would hold,
and that we should not do our business first, if we sat all day.
I looked it all over; it being the fall Quarter, the roads were muddy,
and it was four miles to the nearest meetinghouse; the probability was,
that if we attempted to withdraw at that time,
as the weather was not favorable for being out of doors,
that these circumstances might induce some to stay with them, and others might go home,
rather than undertake the toil, as it would bring meeting very late.

Under these views, I proposed to Friends to stop disputing and sit quietly,
and let them do their business, hoping that when they were done,
they would treat us with a little civility.
Friends readily agreed to the proposal, and the Hicksites proceeded,
and might have finished in a short time,
for their business appeared to be nearly all written down;
but their clerk appeared disposed to prolong the time all he could;
and when they were informed that the business was completed,
several of them wanted to clear their minds; so we had to sit,
I think near an hour to hear them, which was calculated to wear our patience,
and grind our feelings.
After they had all got through, no reply being made, we sat quietly a little time,
then modestly asked the Hicksite clerk, to let our clerk come to the table.
He did not, however, and was asked the second time; but he did not move,
until one of his own side said, that as we had sat so long quietly,
and had not disturbed them,
he thought now we ought to have the privilege of doing our business.
Their clerk then, with apparent reluctance, left the table,
and our clerk came forward and opened the meeting.

The Hicksites withdrew, leaving us to transact our business,
which was accomplished in harmony, and greatly to our comfort.
We adjourned the meeting for worship the next day to Monkton, where we had a large,
crowded meeting, many of our neighbors coming in,
some of whom had left our meetings on account of the doctrines
they heard preached by travellers that came amongst us,
not knowing but that Friends approved of such views.
But now, seeing the separation had taken place, said,
"`We will come to your meetings again, where we can hear the old fashioned preaching;
for you believe in Jesus Christ,
as we do--the other side does not;`"--an evidence that those of other
Societies saw clearly what error was promulgated--calling it infidelity.
This division in the Quarter, proved favorable for Peru;
for there the Hicksites would not divide, but kept harrassing Friends;
but now they went out with the rest,
which gave us the opportunity of knowing who they were,
and relieved Friends of a grievous burden.
Now we can meet, worship, and transact our business without interruption,
to our great joy.

A short time before our Quarterly Meeting,
there came a letter from Friends of Danby Monthly Meeting,
informing that the Hicksite extracts were presented to their last meeting,
and that a considerable majority chose to accept and identify themselves with them;
in consequence whereof a number withdrew to a Friend`'s house,
and adjourned the meeting to be held the next month at Granville,
earnestly desiring those of the Yearly Meeting`'s
committee belonging to Ferrisburg Quarter,
to meet with them,
as they had no prospect that any of the committee from the south would attend.
Agreeably to their request, four of us attended,
and found them laboring under great discouragement;
yet there appeared a sufficient number of well qualified members,
to sustain a Monthly Meeting to the honor of Truth.
We met at the meetinghouse--the Hicksites also attending--and
at the opening of the meeting for business,
we offered the extracts from our Yearly Meeting,
and requested the privilege of attending to the business according to the order,
and in subordination to the Yearly Meeting,
under which the Monthly Meeting had always acted;
The Hicksites rejected this with abusive language, especially one of their number,
who made use, I think, of the most insulting language we met with; but by being guarded,
Friends were preserved from running into rambling disputes,
which were sought for by the dissenting party.

When we had accomplished our duty agreeably to our appointment,
we withdrew to a convenient dwelling, owned by a Friend, who kindly offered it,
where we sat down like two little flocks of kids, feeling stripped, peeled,
and borne down.
In this state, it pleased the God of all our sure mercies, to compassionate us,
and favoring with the overshadowing of His heavenly presence,
to the reviving of our drooping spirits,
and strengthening our confidence in His never-failing arm.
The members were brought into unity and sympathy one with another,
and we passed through the business to our mutual satisfaction, and I believe,
to our thankful joy in the Lord,
who had wonderfully made a way for our escape from the scourge of the cruel tongue,
and had enabled us to hold our meetings in the ancient quiet.
The minds of the committee were brought into serious consideration of the propriety
of encouraging Friends to try to sustain Easton Quarterly Meeting,
All being united therein,
it appeared necessary for that Monthly Meeting to appoint a committee to visit
East Hoosick Monthly Meeting to inform them of what had taken place,
and of the proposition for them to meet with us.
After a time of consideration, the meeting appointed a committee,
who found that most of the Friends in East Hoosick were sound in principle,
and rejoiced in the steps that had been taken.

When the time came, we found a larger collection than we had expected;
for we had several from Easton and Troy Monthly Meeting,
whose remaining with Friends we knew not of.
We also had several of the Yearly Meeting`'s committee from the Southern Quarters,
who approved of the steps taken.
The several sittings were favored, contriting seasons,
tending to strengthen our confidence in the unslumbering Shepherd of Israel.
The meeting was adjourned to the same place the next quarter.
It was considerably larger, and owned by the great Head of the Church.
Our business was conducted with solemnity and near unity and brotherly condescension,
and adjourned to be at Adams, the next Quarter, formerly called East Hoosick.
This ends the account for the year 1828.
