== Chapter XIV

The following, is nearly verbatim what was delivered by our aged Friend, Joseph Hoag,
at the meeting referred to below,
and has been corroborated by the testimony of Starksboro Monthly Meeting,
and other reliable witnesses.

[quote]
____
In the Fall of the year, 1837, at Starksboro Monthly Meeting, held at Lincoln, Vermont,
Joseph Hoag, in a solemn and impressive way, spoke at considerable length,
of the severe trials that Friends had passed through in many places,
within several Yearly Meetings,
whilst this Monthly Meeting had been preserved from the Hicksite ravages.
He then adverted to the doctrines, practices,
self-denying and cross-bearing life of our fore-fathers in the Truth;
to whom their peculiar testimonies were as life to them,
and brought them together to be one people in religious fellowship.
Far is this from that state of delusion, brought painfully to view at this time,
when professors of our name, let loose the restraints of Gospel truths,
and peaceable practices that bound them together at first, and instead thereof, be found,
little by little to shun the cross, mingle more and more with the world,
in its ways of glitter, pride, wealth, and supposed refinement,
from primitive principles of a self-denying, cross-bearing life,
to one more in the will and wisdom of the creatures, which seeks to change its own views,
holding to great pretentious of firmness and zeal and to former name and action,
to screen them from shame.
From these, and causes growing therefrom,
this society will be brought into greater trials than they have
heretofore witnessed beginning at the heads of the tribes,
who have gone into spiritual pride, from high stations down to the rear ranks,
and Friends will be tried to a hairs-breadth, brayed as in a Mortar,
and sided from sieve to sieve; yet a remnant will be preserved through these trials.
I may not live to see it,
but there are those who are in this house that will--adding--"`Friends,
you may pen it down if you please, as it will cause a greater split,
than that we have passed through.`"
The solemnity attendant at that memorable time, is still lively,
in the remembrance of many then present.
____

The following account of the travels and religious meetings attended
by Joseph Hoag in Ohio and Indiana Yearly Meetings in 1840-41,
was kept by his kind Friend and companion, Job S. Collins, of Utica.

[quote]
____
They left Utica, the 6th of 7th month, 1840, in a boat bound for Buffalo,
and arrived safe at Lockport, the 10th;
dined at Jesse P. Haine`'s. From thence to Mead Atwater`'s, put up there,
stayed over first day, and attended their meeting held at Lockport.
From thence to Buffalo, where we took the steamboat for Huron, in Ohio,
and landed there on the 15th. From thence to Joseph Healy`'s, in Greenwich,
twenty-eight miles, where we arrived about noon.
17th, attended an appointed meeting there;
that meeting having been laid down in consequence of improper management therein.
After meeting we returned to J. Healy`'s. 18th,
Willis B. Smith took us in his carriage thirty-two miles.
We stayed one night at A. Carey`'s. 19th,
had an appointed meeting two miles out of the village, called Sandusky Meeting,
after which, we stayed the night at Benjamin Carey`'s. Thence to Samuel Peasley`'s,
and stayed the night.
21st, attended Gilead Monthly Meeting.
22nd, attended an appointed meeting at Westland.
23rd, attended Allum Creek Monthly Meeting, and put up at William Benedict`'s. 24th,
in company with Samuel Peasley, we started for Lewisburg, forty miles distant.

25th, had an appointed meeting there, and rode eight miles to Goshen;
stayed at Martin Normon`'s. 26th, attended their mid-week meeting.
27th, attended Westland meeting held in the woods,
the house not being large enough to hold the people.
After meeting, returned to Thomas Pearson`'s, and stayed at his house.
Samuel Peasley then returned home.

28th, we started for Camel, ten miles; put up at Thomas Cowgill`'s. 9th,
attended Carmel Meeting.
30th, in company with Henry Pickerill, we started for Centre Quarterly Meeting,
Warren county, Ohio, fifty miles distant, and arrived at Nathaniel Carpenter`'s,
where Joseph was taken sick and was not able to attend the Quarterly Meeting.
He remained sick about five weeks,
his life being often despaired of by his nurse and physician;
yet he recovered his health so far as to be able to ride out.
He then gave out appointments for four meetings near each other,
occasioning seventeen miles travel The last one being held at Wilmington,
near John M+++_______+++, where Joseph again lay sick two weeks.
When recovered, we went on to Turtle Creek Meeting.
From thence to Springfield Monthly Meeting, held 15th of 9th month, 1840.
It was an interesting meeting;
the young people whose countenances bespoke innocence and integrity of heart,
were an ornament to their parents, and an encouraging prospect to the society of Friends.
16th, we proceeded down the Creek five or six miles, and attended a small meeting,
held in a brick Meetinghouse.
17th, we traveled to Harveysburg, and attended their mid-week meeting; dined at Doct.
Harvey`'s. From thence we went 12 miles to Jonathan Johnson`'s, in Wainsville.
18th, had an appointed meeting there; thence 12 miles to Springborough;
on account of Joseph being sick, we remained two weeks at Solomon Miller`'s,
and were kindly entertained by him and his wife,
who arranged to accommodate with their horse and carriage
to attend several meetings at Sugar Creek and Springborough.
In attending those meetings we traveled fifteen miles.
The 11th of 10th month, Jacob Taylor took us to Cincinnati, to Ephraim Morgan`'s,
where we fell in company with Enos T. Robinson, from England, and John Scott,
from Maryland.
15th, we attended Cincinnati Monthly Meeting.
16th, we started in a steamboat for Beaver Falls, 500 miles up the river,
where we landed the 21st, about one o`'clock at night.
22nd, we took coach for New Brighton, where I left Joseph at his son`'s,
and returned home.

Fourth month, 8th, 1841,
I left home in order to accompany Joseph Hoag through the remaining
part of his religious visit to Ohio and Indiana Yearly Meetings.
I arrived at Joseph D. Hoag`'s, at Brighton, Beaver county, Pennsylvania, the 15th,
where I found my aged Friend in tolerable health for traveling.
18th, we took steamboat, for Pittsburg.
19th, took the boat for Redstone, 60 miles; arrived there the 20th. 21st,
attended their Preparative Meeting.
22nd, (the first day of our aged traveler`'s eightieth year,) rode 11 miles to Pike Run,
had a meeting there,
and stayed the night at Amos Griffith`'s. Next day after meeting rode six miles to Westland,
and stayed at George Smith`'s. 24th, we had an appointed meeting there,
after which we dined at Mildred Radcliffe.
26th, returned to Eli Haine`'s, at Redstone.
28th, attended their Select Monthly Meeting.
29th, attended the Monthly Meeting.
30th, went to Providence, and attended the Quarterly Meeting.
5th month, 2nd, attended Centre Meeting and stayed the night after, at John Lippincot`'s,
returned to Providence, and put up at Samuel Cope`'s. Third we arrived at Sewickley.
4th, had an appointed meeting there.
5th, we went to Youghiogeny River; thence by boat to Pittsburg, 28 miles.
Next morning took steamboat for Wheeling, and arrived there that evening.
8th, took coach for St. Clairsville.
9th, attended an appointed meeting there, and went to Benjamin Vail`'s, at Plainfield.
10th, attended meeting there.
After which, John Vail went with us to Stillwater; we put up at our kind Friend,
Benjamin Hoyle`'s. 11th, attended their Meeting.
After which, our kind Friend, Jacob Crew took us to his house, and on the 12th,
took us to the Ridge Meeting.

13th, attended Sommerton Meeting.
Thence attended meeting at Sunbury, Richland, Goshen,
and the Select Meeting at Stillwater.
23rd, attended meeting at Stillwater.
24th, attended Ridge Monthly Meeting.
Thence returned to Stillwater; 30th, attended Pennsville meeting;
thence to Chesterfield Meeting, which was large; thence to Plymouth,
and had a meeting there on the 3rd, and arrived at Cincinnati, 5th of 6th month,
and attended meeting there the 6th. Then had an appointed meeting at Elk.
Thence to New Hope, and attended meeting there.
10th, at Westfield Select Quarterly Meeting, held at Salem.
11th, attended with the African Committee.
12th, attended Westfield Quarterly Meeting, where Joseph was highly favored.
13th, attended their meeting, and an appointed meeting at 3 o`'clock, at Silver Creek.
Thence to Millborough--Joseph was favored at both the last meetings.
On second day, we attended meeting, at Poplar Ridge, which was favored.

15th, had an appointed meeting at Orange.
Thence to Woodbury, and attended an appointed meeting at Chester.
19th, at Dover; then to Concord, and New Garden, on the 20th. 21st, at Newport.
22nd, at Arby meeting.
23rd, Cherry Grove.
24th, at Lynn.
25th, at Jericho.
26th at White River. 27th, at Duck Creek, then to Sparrow Creek, L+++_______+++ Creek,
Popple Run, West River, Springfield, Nettle Creek, and attended Westbury meeting,
the 4th of 7th month, first day; then to Flat Rock, Clear Spring,
and the mid-week meeting at Spiceland, on the 7th; thence to Duck Creek, and Elm Grove,
which was fully attended 10th, at Raysville, then to Carthage, Walnut Ridge,
Little Blue River, Sandy Creek, In Driftwood, Blue River, Beech Grove, Lick Creek,
and Blue River Quarterly Meeting, on the 25th and 26th. 30th,
had an appointed meeting at Hopewell.
31st, at Bethel, in Wayne county, Indiana.
8th month, 1st, at Milford meeting; then to West Grove, Fairfield, West Branch,
Mill Creek, Concord, Randolph and Mill Creek again.
Then returned to Randolph.
18th, Joseph attended Waynesville Select Meeting.
14th and 15th, at Miami Quarterly Meeting.
17th, attended Mill Creek Monthly Meeting, then to Union.
19th, at West Branch Monthly Meeting.
20th, Joseph attended the Select Quarterly Meeting.
21st, we attended the Quarterly Meeting at Branch, and on first day following,
the public meeting.
25th, attended Monthly Meeting at Richmond.
Then to New Garden Select Meeting and Quarterly Meeting.
Next day attended the public meeting.
Thence to Somerton, Beech Creek, Oak Ridge, Deer Creek, Missineway, New Hope,
and Centre meeting.
Then moved forward for Allum Creek Quarterly Meeting,
and on the way attended Carmel Preparative Meeting, Westland meeting,
also a Select Preparative Meeting, and Goshen Monthly Meeting.
On the 23rd of 9th month, attended Allum Creek Quarterly Meeting,
and after it we went to William Gidley`'s. We then attended Allum Creek, Gilead,
and Owl Creek meetings.
Then accompanied by our kind Friend, Birthday Cone, we passed on to Joseph Healey`'s,
in Greenwich, and attended that meeting.

We arrived at Huron, the 2nd of 10th month.
Thence by steamboat to Buffalo,
where we arrived on the 3rd. We then proceeded to Lockport and
attended an appointed meeting there on the 5th. The 7th,
we attended Farmington Quarterly Meeting for worship, and were at Rochester,
on first day, the 10th, arriving safely at Utica, on the 15th.
____

[.offset]
The following account is given by Benjamin Taber,
who took Joseph Hoag from Utica to his own home:

[quote]
____
On the 21st of 10th month we rode thirty-two miles,
part of the way through deep mirey roads.
22nd, we traveled to Galway and lodged at Caleb Palmer`'s. Seventh day, 23rd,
we rode thirtytwo miles to Isaac Mosher`'s in Queensbury,
and attended that meeting on first day, the 24th, and lodged with Caleb Dean.
Second day we went to Luzerne;
Uncle Joseph appointed a meeting there for the next day at eleven o`'clock;
after it we returned to Queensbury, and attended their mid-week meeting on fourth day.
We then attended four appointed meetings as follows: Glenn`'s Falls, Nider,
Gurney Settlement, and Kingsbury; the latter a crowded meeting in a school-house;
all of which were seasons of favor, and spiritual refreshment;
especially the last one among the Baptists, where the outward, shadowy,
figurative law was brought to view,
and contrasted with the inward and spiritual law of the spirit of life;
showing that as the former was but as the shadow, or figure of the substance,
it must decrease and give place,
when the substance was brought experimentally and feelingly to the heart.
Then as the former decreased,
the latter would increase--as it was practically
abode in--to that of perfection in holiness,
in accordance with the measure of the gift of the grace of God.
It was a season of favor to the people, and one to be remembered.

One of their deacons was so far convinced that he left the Baptists,
and has been a pretty steady attender of Friends meetings ever since.
First day, the 31st, we were at Queensbury meeting.
Truth owned the testimonies delivered,
and we were enabled to leave them with peaceful enjoyment,
which seemed to render our journey pleasant to our homes.
We traveled that afternoon fourteen miles to Isaac Osborne`'s. Next day rode to Cornwell,
forty-three miles.
Third day morning the 2nd of 11th month, we started very early,
and rode twenty-four miles in season to take refreshment
before attending Ferrisburgh Select Preparative Meeting;
thence to Uncle`'s home.
____

As our beloved Friend Joseph Hoag,
did not keep any account of the preceding journey himself,
probably owing to his advanced age and infirmities,
the following will no doubt be interesting to Friends generally.
It appears by the records of Ferrisburg Monthly Meeting, Vermont,
that he obtained a minute of concurrence,
to perform a religious visit to some parts of Ohio,
and nearly all the meetings in Indiana Yearly Meeting, which was dated 4th month, 29th,
1840, which he returned the 3rd of 11th month, 1841,
with returning minutes from West Branch, Red Stone, and several other Quarterly Meetings,
with a large number from different Monthly Meetings,
all expressive of his company and gospel labors being satisfactory; except one,
which expressed that his company and deportment were satisfactory.

After his return home in the 11th month, 1841,
he attended the Yearly Meeting in New York, in 1842,
and nearly all the meetings in Ferrisburg Quarter.
Having obtained a minute of concurrence from Ferrisburg Monthly and Quarterly Meetings,
the former dated the 3rd of 8th month, 1842,
to perform a religious visit to the meetings of Friends
within the limits of Indiana Yearly Meeting,
he left home, in company with Samuel Peasley and wife, and Johanna Worth,
in the 9th month, 1842.
He afterwards visited most of the meetings within Indiana Yearly Meeting,
extending as far west as Iowa, where he spent a considerable portion of one winter,
with his son Joseph D. who had recently removed there.
He returned back to Willis and Ann Smith`'s, at Greenwich, Ohio,
from whom the following account has been received.

[quote]
____
We think it was in the latter part of 7th month, 1844,
that Joseph Hoag came to our house, being desirous to go to Lake Erie to embark for home.
He mentioned, that though he was preparing to return, there was a cloud before him,
and that he could not see his way clear; yet said,
we might prepare a carriage for him to start the next morning, He got up in the morning,
and went to the door to go out and wash (not suffering water to be brought to him),
and fell from the door on the ground.
He was raised on his feet, and still persisted in the attempt to wash his face and head,
but growing faint, was helped into the house.
We attempted to lay him on the bed, but it gave him so much pain,
he was placed in an easy chair, in which he remained,
(though sometimes raised upon his feet) for more than two weeks,
without a murmur or a groan that we ever heard.
After he was able to converse,
he said that he now saw the cause of the cloud that was placed before him;
that his Master required it of him to go to a Monthly Meeting, which he named,
to assist a remnant of that meeting, who were borne down by the other part, and said,
that if his Master raised him up, he should return; which he did on his recovery,
to his satisfaction, as he expressed when he came back to our place.
And also said, now he thought his work was nearly done,
that his Master would send him of no more errands; and appeared cheerful.

During his confinement at our house,
he frequently expressed his concern for the Society of Friends; also,
that he believed there was coming a more trying time to Friends than they had ever known,
because the old dragon was about, and had already in some places,
turned himself into the appearance of an angel of light, and would draw many stars,
yea many who had been bright stars, to the earth,
by his fine speeches--but that he believed there would be a remnant,
that would be preserved, though in the furnace of affliction,
and that this remnant would grow, and eventually fill the earth; Many, very many,
were the times he expressed a concern for some of his own family,
who were in high standing, and had known the time when they spoke tremblingly;
then they were on good ground, but now he feared for them.
Often would he exclaim, "`O, poor +++_______+++, thou thinkest thou art rich and strong;
but if thou only knew thy nakedness, thou wouldst sit in sack cloth and ashes.`"
We could fill many sheets with his expressions whilst confined,
but perhaps this may suffice.
We know that some here and at other places say, he was childish, but we believe,
he was a strong man in the Lord.
____

It appears from the records of Ferrisburg Monthly Meeting,
that he returned the forementioned minute the 28th of 8th month, 1844,
with returning minutes from Indiana Yearly Meeting, from Western, Blue River,
and White Lick Quarterly Meetings, with a large number from different Monthly Meetings,
expressive of his company and gospel labors while among them, being satisfactory.

The following was taken down in his own words, by his daughter, the late Hannah H. Battey:

[quote]
____
I attended the Yearly Meeting in New York, in 1845, which to me was a painful,
distressing time, especially some of the sittings;
though unable to hear one word that was spoken in meetings,
I believe I was not void of a true sense of the present situation of our Society.
I was in company with +++_______+++, and +++_______+++, they carried high heads and lofty looks,
and appeared in high spirits.
There was a great deal of conversation; I could not hear it, but I felt it,
and it distressed me.
I found by inquiry that I was not mistaken as to the subjects conversed upon.
I mused often upon my present as well as former feelings,
respecting the situation of the Society in New England Yearly Meeting,
particularly their treatment of John Wilbur.
Sometimes I would say to myself am I deceived, or am I not!
They do not tell me much about it,
but I cannot get rid of the impression that he has been, not only a sufferer,
but a deeply injured man, and that by false brethren.
If so, will not one be raised up to plead his cause, or defend him in this day of trial?
____

[.offset]
The following information is obtained from the records of Ferrisburg Monthly Meeting.

[.embedded-content-document.testimony]
--

On the 28th of 2nd month, 1845, our aged Friend Joseph Hoag,
obtained a minute to perform a religious visit to Friends and others,
in the western and northern parts of Ferrisburg Quarterly Meeting;
which he accomplished in the 6th and 7th months following.

He also obtained a minute on the 1st of 10th month, 1845,
to pay a religious visit in some places in the compass of Saratoga Quarterly Meeting;
which it appears he was enabled mostly to perform.

These appear to be his last religious visits with minutes.
He attended New York Yearly Meeting, in 1846.

[.signed-section-context-open]
"`9th month, 5th, 1846.

"`It is with painful feelings that I believe it is encumbent on me to cause to be placed
on paper a pretty full and explicit account of some conversation of mine,
which took place at New York, in the time of our last Yearly Meeting,
in consequence of reports getting into extensive circulation,
very different from my understanding, or my intention to convey;
I have therefore requested Amos Battey, to act as scribe for me.
I put up at Mahlon Day`'s, where +++_______+++,
an aged Friend--who had long been in good standing as a member of our Society,
but had latterly taken a decided stand with the larger body in New England--also put up,
who showed great respect for me.
Conversation by different persons was often started, as I thought,
to get my sentiments in regard to the present existing troubles in our Society;
and when pressed pretty close, I generally answered in this way:
I think I see an unhallowed fire on both sides, and it all comes out of one focus.
By this unhallowed fire,
I meant the heat I discovered in different individuals on both sides, in conversing on,
the subjects.
And I said, if you will quarrel and divide, I do not see but I shall be left alone,
for I have no unity with these fires that all come out of one focus;
for I did not come here to be busied about the concerns of another country,
and another Yearly Meeting, out of doors, where they cannot decide or settle anything,
but get into a heat, and sometimes censure; if this is not a strange fire,
I do not know what to call it.
I said this to show them my views, for I am not a party man,
but one who wishes to stand firm to the ancient principles, as held by our early Friends.

"`But to proceed.
I was much noticed by +++_______+++. I had considerable conversation,
in which I brought to view a number of events,
which had taken place since the first gathering of our Society,
in which there had been a defect,
not only in regard to the right and faithful support of the discipline,
but also in regard to doctrine.
I told +++_______+++, I had never altered my sentiments that I was sensible of,
one hair`'s breadth, through all the Hicksite concern, nor in this;
for when I was fully convinced of our ancient principles,
I was as fully convinced of the propriety and right of our discipline,
and Church government of our forefathers.
+++_______+++ with a smile, answered, "`I never thought thou had.`"
By this time, all, were gone out of the room but +++_______+++, and myself,
and I supposed out of hearing.
We both sat silent awhile.
It was in my mind, to tell him what I saw in the meeting on second day afternoon.
I sat and mused, until much of its lively feeling was lost.
This made me think more seriously, and it returned with equal clearness.
I still mused, until it seemed to me like the blaze of a candle nearly gone out,
and I felt not as I wanted to.
I began to think I almost wished I had let +++_______+++ have it,
but it came again with increased clearness.
I turned to him and said, "`I have a mind to tell thee,
what appeared to me as I sat in meeting.`"
He said, "`I am willing to hear it.`"
I then said, "`It opened to me in the clearness, that many of the leaders of our Society,
(meaning our Yearly Meeting as then being held) were in danger of running into ranterism,
and not know it; and it would be in this way; in speaking to business,
which every concerned member has a right to do, and to give their reasons therefor,
if need requires; but there is a class that will do all this,
and then take up more time in preaching in favor of their sentiments,
and sometimes double the time.
The Ministry is a pure gift, and ought not to be mixed with other matters.
Elias Hicks practiced in that way for many years, and see what he came to;
and several others in my day have very much run down, and some entirely out.
After informing him that I told him this for him to remember,
for I thought I should not live to see the effects that would follow,
in consequence of that spirit spreading, but thought he would;
here the discourse stopped for that time.

"`In the course of the next day I was sitting alone; +++_______+++ came and sat by me,
and in the appearance of much solidity, said, he had thought much of our conversation,
that we had the day previous.
He proposed for me to read and sign a paper, which he had written on the subject.
I declined, as I could not well read strange hand-writing, and my hand trembled so,
that I had not pretended to write in some time.
He then read it to me.
He had got a long preface to it, so that I concluded I should not put my hand to it.
I made no remark to him, but I thought he seemed unwilling to give it up;
yet all the time he carried the idea that the subject had
so impressed his mind that he felt most easy to write it,
to lay by and keep, as a testimony, to have recourse to in a future day.
I had no thought that he had any other object in view,
and I consented for him to put my name to what I had said,
which he had asked the privilege of; but in looking it over,
I grew uneasy and took +++_______+++ aside, and told him in substance,
that if he kept that paper, he must draft it off; and the preface that he had written,
put at the head of the sheet,
and strike a black mark across the sheet and put his own name to it as the author;
then under it thou mayest write what I said on the subject,
but put it in the same words as near as thou possibly canst,
and to that thou mayest put my name, and under my name I want thee to put a note,
that I also observed, that there is a class that would be careful, neither to meddle,
nor move, only as they see in the clear light of the Lord, was required by Him;
and when they had done their duty, leave it all to the Lord,
keeping their eye single to Him, and no where else.
These will be preserved to the end, for He always had a people and always will;
and it is this class only that the Lord always owned and kept, and always will,
while He remains to be an unchangeable God.
After this I turned to +++_______+++, and told him, "`I see my mental faculties are failing,
and should I be drawn off from the Truth, as Hugh Judge was,
and thus bring a reproach upon the Truth, then let this all be put in oblivion,
that it never be known that such a writing ever was;`"
which he appeared to assent to cheerfully.`"

[.signed-section-signature]
Joseph Hoag.

[.postscript]
====

Neither had he assented to any writing understandingly,
which might carry a different meaning to the foregoing.
And as he wished us to be witnesses, we have hereunto set our hands.

====

[.signed-section-signature]
Ruth Battey, William C. Battey, Lydia Worth, Louisa Battey, Nicholas Battey,
Thankful Battey.

--

+++[+++As the subjects alluded to in the following vision, are of general interest,
and much expression having been given in favor of its being appended to this journal,
it is concluded to do so:]

[.embedded-content-document.paper]
--

In the year 1803, probably in the eighth or ninth month,
I was one day alone in the fields, and observed that the sun shone clear,
but that a mist eclipsed the brightness of its shining.
As I reflected upon the singularity of the event, my mind was struck into a silence,
the most solemn I ever remember to have witnessed,
for it seemed as if all my faculties were laid low,
and unusually brought into deep silence.
I said to myself, "`what can all this mean?
I do not recollect ever before to have been sensible of
such feelings.`" And I heard a voice from heaven say,
"`This that thou seest, which dims the brightness of the sun,
is a sign of the present and coming times.
I took the forefathers of this country from a land of oppression;
I planted them here among the people of the forest.
I sustained them, and while they were humble, I blessed them and fed them,
and they became a numerous people: but they have now become proud and lifted up,
and have forgotten Me, who nourished and protected them in the wilderness,
and are running into every abomination and evil practice
of which the old countries are guilty;
and I have taken quietude from the land,
and suffered a dividing spirit to come among them.
Lift up thine eyes and behold.`" And I saw them dividing in great heat.
This division began in the Church upon points of doctrine.
It commenced in the Presbyterian Society,
and went through the various religious denominations, and in its progress and close,
the effect was nearly the same; those who dissented,
went off with high heads and taunting language;
and those who kept to their organized sentiments, appeared exercised and sorrowful.
And when this dividing spirit entered the Society of Friends,
it raged in as high a degree as any I had before discovered, and as before,
those who separated, went with lofty looks and taunting, censoring language;
those who kept to their ancient principles, retired by themselves.

It next appeared in the Lodges of the Free Masons,
and it broke out in appearance like a volcano,
inasmuch as it set the country in an uproar for a length of time.
Then it entered politics throughout the United States, and did not stop,
until it produced a civil war,
and an abundance of human blood was shed in the course of the combat.
The Southern States lost their power, and Slavery was annihilated from their borders.
Then a Monarchical power arose-took the Government
of the States--established a national religion,
and made all Societies tributary to support its expenses.
I saw them take property from Friends to a large amount.
I was amazed at beholding all this, and heard a voice proclaim,
"`this Power shall not always stand,
but with this Power I will chastise my Church until
they return to the faithfulness of their forefathers.
Thou seest what is coming on thy native land for their iniquity, and the blood of Africa;
the remembrance of which has come up before me.
This vision is yet for many days.`"
I had no idea of writing it down for many years, until it became such a burden,
that for my own relief I have written it.

[.signed-section-signature]
Joseph Hoag

--

[.embedded-content-document.testimony]
--

[.letter-heading]
A Testimony of Starksboro Monthly Meeting of Friends, Concerning our Beloved Friend,
Joseph Hoag, Deceased

The subject of this memoir was the eldest child of Elijah and Phoebe Hoag,
and was born the 22nd of 4th month, 1762.
He very early in life manifested an inclination to sobriety,
and the steady attendance of religious meetings;
often feeling his mind tendered and his understanding enlarged,
he became desirous of living an upright and holy life;
yet being of a quick and unstable disposition,
he often fell short of the fulfillment of those good resolutions,
and the convictions he felt for these, his shortcomings, at times caused him to weep,
and promise amendment of life; thus several of his juvenile years were passed.

At intervals he was in an uncommon degree permitted
to partake of the incomes of heavenly intelligence,
which unfolded to his mind things of a deep spiritual nature.
It was an early period when he witnessed a clear evidence
that he should be called to the work of the ministry,
and was shown the regions of misery and woe, with people traveling thither;
the awfulness of this view caused him for a time to refrain from wrong habits;
he was also permitted to have a view of the heavenly host, with a warning to repent,
yet after these clear openings,
when the time arrived for him to engage in the service pointed out by his Divine Master,
he was unfaithful and disobedient;
soon the tendering influences of heavenly goodness became much effaced,
his mind alienated from the source of all good,
and by listening to the insinuations of the enemy of man`'s happiness,
he was left to doubt the truths of the Gospel, and embrace infidelity;
while thus wandering from the fold of Christ, it pleased his Heavenly Father,
in mercy to send a faithful servant,
who was enabled to open unto him his condition and the doubts of his mind,
closing his testimony in this moving language: "`That Jesus whom thou hast denied,
hath opened unto me thy state and condition.`"
This so wrought upon his mind that he became penitent even unto tears.

The enemy then endeavored to make him believe that
he never should arrive at a state of acceptance,
tempting him to give up all hope.
His afflictions under these besetments were great for some time,
when the same minister was qualified to show him
that this also was the work of the enemy,
with more of a comforting nature.
Being thus again encouraged,
he resigned himself to the disposal of the Great Head of the Church,
and came forward in his first appearance in the ministry
not far from his eighteenth year,
to the peace of his hitherto oppressed and afflicted soul.
For this change in his manner of life,
he had much to endure from his former associates in folly,
and found it necessary for him to withdraw from their company.

The enemy still continued to follow him with his insinuations,
endeavoring to make him believe that the continued calls to come
forward in the ministry were not from the right source;
in this season of conflict and trial, he covenanted with the Lord,
if he would send a servant unacquainted with his condition,
to tell him he was rightly called, he would endeavor to be faithful.
The Lord condescended to answer his desire,
delegating one of his servants to inform him that his call was right,
and to speak comfortably to him, encouraging him to faithfulness.
Yet after having his request thus granted, he still hesitated,
greatly abhorring a false ministry,
and desired that his life might be taken as an acceptable sacrifice in lieu of the service.
The Lord showed him that no other sacrifice except
that of His own appointment would be acceptable,
and that he had not kept his covenant after the desired confirmation had been granted.
Being sensible of his disobedience, he once more resolved to serve the Lord faithfully,
and henceforward his appearances in the ministry were more often;
this was near his nineteenth year.

In the fall of 1782 he was married to Huldah Case (who had also acceptably
appeared in the ministry.) Although their circumstances were rather limited,
he gave up to apprehended duty,
visiting in the love of the Gospel the neighboring meetings,
and at times some more remote; these little services were acceptable to his friends,
and they officially approved of his ministry about five years from his first appearance.
In 1789 or 90, with the approbation of his friends,
he removed with his family from his native place (Dutchess County,
N+++.+++ Y.,) and settled in Charlotte, Vermont, then a new country,
where there were but few Friends, and they remotely situated.
Here he continued to reside the rest of his days.
In his new location he felt drawn forth in the work of the ministry,
holding religious meetings in many places;
thus was he made an instrument in the Lord`'s hand in gathering people to the Truth,
so that in process of time, with the increase of Friends from other places,
several meetings were established in those parts, in which he continued to labor,
under the pointings of Truth, as a faithful watchman, through his long and useful life,
to the edification of many.
Neither were his labors in Truth`'s service confined to these,
but several times he traveled more extensively, and on the 5th of 1st month, 1801,
left his own habitation to perform a religious visit through New England Yearly Meeting,
extending it to Nova Scotia and other British Provinces;
having to travel some parts of this lengthy journey two or three times over,
it occupied upward of one and a half years in the prime of life.

For several years after his return, being often out of health, he traveled but little,
and that within his own Yearly Meeting,
although it appears he spent considerable time in
labors of love between that time and the year 1812;
and again in 1816, he visited nearly all the meetings of Friends in Pennsylvania,
Maryland, Virginia, North and South Carolina, and some parts of Tennessee,
appointing some meetings amongst those not of our Society.
In the two last visits he spent about twenty-eight months;
many and deep were his baptisms,
increased in consequence of that system of oppression which
prevails in the southern portion of these United States.
Yet endeavoring to follow the pointings of his Heavenly Leader,
he experienced many preservations, and the incomes of sweet peace to his mind.
After this he performed a visit of five months within his own Yearly Meeting,
and on the 6th of 11th month, 1823,
he left home to visit the northern and western part of New York, Ohio, Indiana,
and some parts of North Carolina, Yearly Meetings.
In this, as in several previous similar engagements,
he felt constrained to travel some parts over the second time.
Humbling as these requirements were, they afforded the reward of peace;
7,600 miles were traveled in a few days short of 21 months.
Previous to the separation which took place in 1828,
his spirit was often brought into deep religious exercise,
in beholding the introduction of a spirit of disbelief and misrule,
and the inroads that were being made in the Society,
through the influence of an unsound ministry.
He as a faithful watchman upon the walls of Zion, gave warning of the approaching danger,
and took an early opportunity with the principal leader in the defection,
pointing out to him the unsoundness of his ministry,
and the tendency of his course to spread disaffection in the Society;
nor did he rest satisfied without extending his labors to others,
boldly maintaining the testimonies of Truth.
For his faithful adherence to the ancient principles and order of Society,
he endured much contumely and scorn.
Being one of the committee to assist subordinate
meetings in their tried situation after the separation,
his time was much taken up in that service the remainder of the year.
The following year he performed a general visit through
the southern part of the Yearly Meeting,
and has since acknowledged that he had not at any time of life
witnessed more of the overshadowing influence of heavenly help.

In his 70th year he felt drawn to make a general visit through New England Yearly Meeting,
and left home for that purpose in 5th month, 1831, returning in about ten months.
It appears that this journey was attended with many deep baptisms of spirit;
being shown the situation of society in those parts as he traveled from place to place,
he discovered writings in circulation containing sentiments at
variance with the established doctrines of our religious Society.
After leaving the southern part of that Yearly Meeting he believed it
required of him to return to Providence and labor with one in high standing,
who was endeavoring to produce a change in the manner
of doing much of the business of that meeting,
insinuating that it could be better done by a committee
empowered with authority than by the meeting itself.
"`I labored faithfully,`" says he, "`with the individual,
to convince him of the bad consequences of such a course,
and that it would eventually scatter and divide Society.`"
He also labored in public and private to convince Friends of the
impropriety of suffering those unsound to be spread amongst them,
expressing that if they were circulated within the
compass of that meeting they would produce a schism.
Thus we find this servant of the Lord at an early period,
contending against those doctrinal innovations,
which have since those days extended through most places in Society,
laying waste its principles and changing its order.

After this he was favored, to the satisfaction of his Friends,
and we doubt not to the peace of his own mind, to perform quite lengthy visits,
one in 1832, and one in 1840 and `'41; and again in 9th month, 1842, in his 81st year,
under the infirmities of age, he left home,
visiting most of the meetings in Indiana Yearly Meeting, extending his visit to Iowa.
Whilst out on religious visits, especially in his advanced age,
he was several times reduced to so low a state of
health that doubts were entertained of his recovery,
and in the last visit, having returned to Greenwich, Ohio,
(in the summer of 1843) thinking to embark for his own residence,
although he expressed to the Friends where he was staying,
that there was a cloud before him, he was suddenly taken ill and confined for some time,
not able to rest on a bed for more than two weeks.
Upon his recovery, he found it required of him to return,
and assist an oppressed remnant in a certain Monthly Meeting;
this service being performed, he returned to the same Friend`'s house,
and appeared cheerful, expressing his belief that his work was nearly done.
He performed but few, and these but short, visits after his return.
During the aforesaid confinement in Ohio, he manifested deep anxiety,
not only for some of his own family, then in high standing, but for the Society at large,
under the conviction that there was a more trying
time coming than Friends had before known,
expressing his belief that many stars--yea, many that had been bright stars,
would be drawn to the earth, through the transformings of the evil one,
yet he was decided in the belief that a remnant would be preserved.

Inasmuch as we have oft-times been favored with the pleasant company,
the cheerful conversation, and the deep searching ministry of our worthy Friend,
we are concerned to give forth this testimony respecting him,
although he was not a member of this meeting.

Being a man of good understanding, and having a retentive memory,
and a mind seasoned with grace, his conversation was truly instructive,
and his services for the maintenance of good order in the Society, were very useful.
As an experienced father in the Church,
he was tender and affectionate to the young and inexperienced,
watching over them for their good,
with desires that they might be gathered into the fold of Christ,
and under the teachings of His Spirit come to a full understanding of that which
pertains to their growth in grace and the saving knowledge of Jesus Christ.
But to those who were disposed to slight the counsel of their Friends,
reject the witness for truth in their own breasts,
and to set at naught or trample under foot the order of society,
he was clothed with the spirit of judgment, and authority to place it upon them.

But perhaps of all the qualifications with which a wise Providence had endowed him,
he appeared most conspicuous in the gift of the ministry and the spirit of prophecy.
Often was he qualified to enter with great clearness
into the state of individuals and meetings.
We are able to call to memory certain occasions, when,
in obedience to his Heavenly Leader, he came amongst us,
and in the authority of the Gospel disclosed things known to but very few;
and divers are the occurrences, when in the vision of light,
he was led to announce the near approach of death,
in some instances that it would be sudden--no time given on a bed of languishing.

Many among us can recur to testimonies delivered by him, wherein he was permitted to see,
yea, rather was shown and was authorized to depict with much clearness,
what would take place in the Society.
At one time (about the year 1838) he expressed that a separation
on account of doctrine would take place in that meeting,
(Ferrisburg Quarter) and feeling full confidence in the opening,
in the authority of Truth, remarked, "`Friends, you may pencil it down if you please.`"
The fulfillment of these predictions is an evidence
that his authority was from Him who knoweth all things,
and can see the end from the beginning.
Neither did he expect that these troubles in Society would be confined to a small place,
for he as a faithful shepherd had watched with sorrow the diffusion of sentiments,
inimical to the principles of Friends,
the effect of which would be to produce discord and
disruption in many parts of the Society.
He attended the Yearly Meeting in 1845, and again in 1846,
both of which were to his experienced mind seasons of deep exercise,
under the belief that things were carried in a wrong channel,
although unable to hear what was said.
Truly his spiritual vision was yet clear, and that ear,
long acquainted with the voice of the True Shepherd, was open to His teachings.

He believed it right to keep, by writing,
some account of the religious services and exercises that
he from time to time had passed through in his pilgrimage,
but from negligence or the infirmities of age,
it was with great difficulty he could use the pen; and he had omitted, for some years,
to continue the account.

Feeling uneasy in regard to these omissions, he, at the suggestion of his wife,
in the summer of 1845, brought his writings within the limits of this meeting,
for assistance in taking down additional accounts
and the regulation of some partially done,
and feeling easy with their present location, he placed them the following winter,
by writing, in the hands of two of our members with instructions not to suffer them,
after his decease,
to fall into the hands of any who would destroy or cause them to pass into oblivion,
or into the hands of any persons who have supported,
or who may support either Elias Hicks or Joseph John Gurney,
or advocate either of their peculiar tenets,
feeling an assurance that some parts of them are in opposition
to the doctrines propogated by the former,
and many of those written by the latter.
He further requested that if it became necessary, by reason of death or otherwise,
to place them with some other person,
that those who witnessed "`this procedure`" the survivor or survivors of them,
should place them in the hands of some sound, substantial Friend or Friends.

His remained to be a tribulated path;
he was censured for his faithful opposition to those unsound views,
and the misrule in support of them which were agitating Society on the one hand,
and on the other frequent were the reports that he had changed his views respecting them;
on being informed of the latter, he requested that when such statements were made,
they might be contradicted on his behalf;
at one time when informed of these reports being much spread abroad,
he showed deep regret that such efforts should be
used to make him appear different from what he was,
and wept at the injustice done him.

The last time he attended this meeting was about the 1st of 9th month, 1846.
Having endeavored to place on paper some statements to leave as
a testimony in refutation of the many incorrect reports relative
to a change in his views in regard to what was transpiring in Society,
he came amongst us to obtain some assistance,
that they might appear more legible than he could make them.
This being accomplished, he expressed that he now felt satisfied with his writings,
and easy to leave them, and soon returned to his own habitation,
and finished his course on the 21st of 11th month following, in his 85th year.
During his last illness, of about five weeks continuance, he conversed but little,
though at times observations dropped from his lips deeply instructive.
A few days before his close,
he took an affectionate leave of his wife and other relatives present.

From the knowledge we have of this dear Friend and the course he pursued,
we feel safe in asserting that through the different changes and
trials which have befallen our religious Society in his time,
he adhered to its ancient doctrines,
and was opposed to all and every innovation upon them.
Truly it may be said, he "`fought the good fight,
he kept the faith,`" and having finished his course,
has doubtless received a crown of glory that fadeth not away.

Signed on behalf of Starksboro Monthly Meeting, held the 4th of 3rd mon 1853.

[.signed-section-signature]
James Harkness, Susannah Hoag, Clerks.

[.postscript]
====

The foregoing Memorial, from Starksboro Monthly Meeting, concerning our beloved Friend,
Joseph Hoag, deceased, was read in this meeting,
and after mature deliberation was approved and directed to the Meeting for Sufferings,
having the women`'s concurrence therein.

Signed by direction of Ferrisburg Quarterly Meeting of Friends,
held at Starksboro the 5th of 5th month, 1853, by

====

[.signed-section-signature]
Amos Battey, Clerk.

--
